### PR TITLE
memory and ret in simd

### PR DESCRIPTION
**Pull request by ohad-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/44)

### CODE REVIEW

**Comment by ohad-starkware** [comment]
* **#44** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/44?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ohad-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 11 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/44)* status: 11 of 16 files reviewed, 7 unresolved discussions (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/src/components/memory/component.rs` line 57 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/44#-O3m4f5XBPQ0UTJcZJJ_:-O3m4f5XBPQ0UTJcZJJa:b-f3q8qi) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e971c94231d8518bd619b3ae0501ff652cabe035/stwo_cairo_prover/src/components/memory/component.rs#L57)):*
> ```XML
>             std::array::from_fn(|_| eval.next_trace_mask());
>         let multiplicity = eval.next_trace_mask();
>         logup.push_lookup(
> ```

Add TODO to push range check lookup as well.
___
*[`stwo_cairo_prover/src/components/memory/mod.rs` line 8 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/44#-O3m6H2xE7r6IRePENa1:-O3m6H2xE7r6IRePENa2:b-ahhat4) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e971c94231d8518bd619b3ae0501ff652cabe035/stwo_cairo_prover/src/components/memory/mod.rs#L8)):*
> ```XML
> pub mod prover;
> 
> pub type MemoryLookupElements = LookupElements<N_MEMORY_COLUMNS>;
> ```

This includes the multiplicity.



_Suggestion:_
```XML
N_MEMORY_COLUMNS - 1
```
___
*[`stwo_cairo_prover/src/components/memory/prover.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/44#-O3m731uBEYLzB2fU6y8:-O3m731uBEYLzB2fU6y9:b-oor3zt) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e971c94231d8518bd619b3ae0501ff652cabe035/stwo_cairo_prover/src/components/memory/prover.rs#L20)):*
> ```XML
> use crate::prover_types::PackedUInt32;
> 
> pub const LOG_SIMD_MEMORY_ADDRESS_BOUND: u32 = LOG_MEMORY_ADDRESS_BOUND + LOG_N_LANES;
> ```

Shouldn't this be minus?



_Suggestion:_
```XML
LOG_MEMORY_ADDRESS_BOUND - LOG_N_LANES
```
___
*[`stwo_cairo_prover/src/components/memory/prover.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/44#-O3m8Bf22jICxsChCQ4i:-O3m8Bf22jICxsChCQ4j:bw85c36) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e971c94231d8518bd619b3ae0501ff652cabe035/stwo_cairo_prover/src/components/memory/prover.rs#L38)):*
> ```XML
>             })
>             .collect();
>         let multiplicities = vec![PackedUInt32::broadcast(0); SIMD_MEMORY_ADDRESS_BOUND / N_LANES];
> ```

Continuing the previous comment.



_Suggestion:_
```XML
        let values = (0..MEMORY_ADDRESS_BOUND)
            .map(|i| M31::from_u32_unchecked(i as u32))
            .array_chunks::<N_LANES>()
            .map(|c| {
                let value = PackedM31::from_array(c);
                [value; N_M31_IN_FELT252]
            })
            .collect();
        let multiplicities = vec![PackedUInt32::broadcast(0); SIMD_MEMORY_ADDRESS_BOUND];
```
___
*[`stwo_cairo_prover/src/components/memory/prover.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/44#-O3m8Qs48iqFc6rOjFwx:-O3m8Qs48iqFc6rOjFwy:b-gdt6d3) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e971c94231d8518bd619b3ae0501ff652cabe035/stwo_cairo_prover/src/components/memory/prover.rs#L45)):*
> ```XML
>     }
> 
>     pub fn from_info(info: MemoryValues) -> Self {
> ```

Is this just for testing?



_Code quote:_
```XML
pub fn from_info(info: MemoryValues) -> Self {
```
___
*[`stwo_cairo_prover/src/components/memory/prover.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/44#-O3m9ZQY2mdgbJehtmaK:-O3m9ZQZCX9D8EsIRLaj:b-qa10ow) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e971c94231d8518bd619b3ae0501ff652cabe035/stwo_cairo_prover/src/components/memory/prover.rs#L54)):*
> ```XML
>     }
> 
>     pub fn deduce_output(&self, input: PackedM31) -> [PackedM31; N_M31_IN_FELT252] {
> ```

When qureying the memory do we want to get one value of one adress or packed address/values like it is here?
___
*[`stwo_cairo_prover/src/components/memory/prover.rs` line 96 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/44#-O3mBt_QE7IMSapOC--t:-O3mBt_RBriujhnzVUe5:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e971c94231d8518bd619b3ae0501ff652cabe035/stwo_cairo_prover/src/components/memory/prover.rs#L96)):*
> ```XML
> 
>         // Lookup data.
>         let adresses_and_values = std::array::from_fn(|i| trace[i].data.clone());
> ```





_Suggestion:_
```XML
addresses_and_values
```

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/44)* status: 11 of 16 files reviewed, 6 unresolved discussions (waiting on @alonh5)

___
*[`stwo_cairo_prover/src/components/memory/component.rs` line 57 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/44#-O3m4f5XBPQ0UTJcZJJ_:-O3mLJLm6T442QBnBITR:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e971c94231d8518bd619b3ae0501ff652cabe035/stwo_cairo_prover/src/components/memory/component.rs#L57)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Add TODO to push range check lookup as well.
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/src/components/memory/mod.rs` line 8 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/44#-O3m6H2xE7r6IRePENa1:-O3mLHr00S8rfuHIHJjW:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e971c94231d8518bd619b3ae0501ff652cabe035/stwo_cairo_prover/src/components/memory/mod.rs#L8)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

This includes the multiplicity.
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/src/components/memory/prover.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/44#-O3m731uBEYLzB2fU6y8:-O3mGzaE12C5C8OIQ1zD:bn0f3zx) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e971c94231d8518bd619b3ae0501ff652cabe035/stwo_cairo_prover/src/components/memory/prover.rs#L20)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Shouldn't this be minus?
</blockquote></details>

this shouldnt be called simd, but its like that because the CPU one was too small.
___
*[`stwo_cairo_prover/src/components/memory/prover.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/44#-O3m8Bf22jICxsChCQ4i:-O3mHCaQ-nLV2EtV0XT1:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e971c94231d8518bd619b3ae0501ff652cabe035/stwo_cairo_prover/src/components/memory/prover.rs#L38)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Continuing the previous comment.
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/src/components/memory/prover.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/44#-O3m8Qs48iqFc6rOjFwx:-O3mKD3z3uGUh7zLhXbb:b-3jiwjt) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e971c94231d8518bd619b3ae0501ff652cabe035/stwo_cairo_prover/src/components/memory/prover.rs#L45)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Is this just for testing?
</blockquote></details>

yes, I removed it for now
___
*[`stwo_cairo_prover/src/components/memory/prover.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/44#-O3m9ZQY2mdgbJehtmaK:-O3mKNNW6igc_dw5LYJb:bz4e705) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e971c94231d8518bd619b3ae0501ff652cabe035/stwo_cairo_prover/src/components/memory/prover.rs#L54)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

When qureying the memory do we want to get one value of one adress or packed address/values like it is here?
</blockquote></details>

we usually have packed inputs and we want packed outputs,
see write_trace_row in ret/prover.rs

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/44)* status: 9 of 16 files reviewed, 3 unresolved discussions (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/src/components/memory/prover.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/44#-O3m731uBEYLzB2fU6y8:-O4-N3JH7Czep-zWAPe6:b-u1wswp) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e971c94231d8518bd619b3ae0501ff652cabe035/stwo_cairo_prover/src/components/memory/prover.rs#L20)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

this shouldnt be called simd, but its like that because the CPU one was too small.
</blockquote></details>

From what I understand this constant should be log the number of packed elements in the memory. So if we have `LOG_MEMORY_ADDRESS_BOUND` elements ther should be `LOG_MEMORY_ADDRESS_BOUND - LOG_N_LANES` packed elements, no?
___
*[`stwo_cairo_prover/src/components/memory/prover.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/44#-O3m8Bf22jICxsChCQ4i:-O4-NqRW6fV3IbK2ScCW:b-vr4p06) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e971c94231d8518bd619b3ae0501ff652cabe035/stwo_cairo_prover/src/components/memory/prover.rs#L38)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see it.
___
*[`stwo_cairo_prover/src/components/memory/prover.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/44#-O3m9ZQY2mdgbJehtmaK:-O4-Mlyu2sR0O0KwEsCa:brlafpj) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e971c94231d8518bd619b3ae0501ff652cabe035/stwo_cairo_prover/src/components/memory/prover.rs#L54)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

we usually have packed inputs and we want packed outputs,
see write_trace_row in ret/prover.rs
</blockquote></details>

Why is it this way? Don't we need only a single value (at pc for example)?

**Review by alonh5 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/44)* status: 9 of 16 files reviewed, 4 unresolved discussions (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/src/components/memory/prover.rs` line 87 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/44#-O40E30P4hrqRxilm25r:-O40E30QBHtBfeDHiYoY:b-vm23ok) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3c45a3ecd82bc2d5fd0690ebbf1575b9a1fbcaae/stwo_cairo_prover/src/components/memory/prover.rs#L87)):*
> ```XML
> 
>         // Lookup data.
>         let adsresses_and_values = std::array::from_fn(|i| trace[i].data.clone());
> ```

Almost :)



_Suggestion:_
```XML
addresses_and_values
```

**Review by alonh5 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/44)* status: 9 of 16 files reviewed, 5 unresolved discussions (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/src/components/memory/prover.rs` line 14 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/44#-O40EFLk6ZWSv8EwwfkD:-O40EFLl7-JWfyPjbQ9X:bhbcipy) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3c45a3ecd82bc2d5fd0690ebbf1575b9a1fbcaae/stwo_cairo_prover/src/components/memory/prover.rs#L14)):*
> ```XML
> 
> use super::component::{
>     MemoryClaim, MemoryInteractionClaim, LOG_MEMORY_ADDRESS_BOUND_D, MULTIPLICITY_COLUMN_OFFSET,
> ```

Mistake?



_Suggestion:_
```XML
LOG_MEMORY_ADDRESS_BOUND
```

**Review by alonh5 — COMMENTED** [review]
> Reviewed 2 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/44)* status: 11 of 16 files reviewed, 5 unresolved discussions (waiting on @ohad-starkware)

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 16 files at r1, 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/44)* status: 15 of 16 files reviewed, 11 unresolved discussions (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/src/components/memory/prover.rs` line 55 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/44#-O40_V1w8hs2_CbAWY9n:-O40_V1w8hs2_CbAWY9o:b-anbm0k) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3c45a3ecd82bc2d5fd0690ebbf1575b9a1fbcaae/stwo_cairo_prover/src/components/memory/prover.rs#L55)):*
> ```XML
>     }
> 
>     pub fn add_inputs(&mut self, inputs: &PackedM31) {
> ```

Do we need this separately from `deduce_output()`?



_Code quote:_
```XML
add_inputs
```
___
*[`stwo_cairo_prover/src/components/ret_opcode/component.rs` line 53 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/44#-O40XO1QB0ew24M1U-iO:-O40XO1QB0ew24M1U-iP:beek019) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3c45a3ecd82bc2d5fd0690ebbf1575b9a1fbcaae/stwo_cairo_prover/src/components/ret_opcode/component.rs#L53)):*
> ```XML
>         logup.push_lookup(&mut eval, E::EF::one(), &values, &self.lookup_elements);
> 
>         // No constraint on AP (YET).
> ```

Turn this into a TODO.



_Code quote:_
```XML
// No constraint on AP (YET).
```
___
*[`stwo_cairo_prover/src/components/ret_opcode/component.rs` line 100 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/44#-O40Hv35B5VQZ1Vae2Oa:-O40Hv35B5VQZ1Vae2Ob:bp0b9j1) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3c45a3ecd82bc2d5fd0690ebbf1575b9a1fbcaae/stwo_cairo_prover/src/components/ret_opcode/component.rs#L100)):*
> ```XML
>     // pub ret_claimed_sum: SecureField,
>     pub log_size: u32,
>     pub memory_claimed_sum: SecureField,
> ```

In this case the only lookup is to the memory but in other components it could be one claimed sum for many lookups, right?



_Code quote:_
```XML
pub memory_claimed_sum: SecureField,
```
___
*[`stwo_cairo_prover/src/components/ret_opcode/prover.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/44#-O40gzygAQAQbrJNL50d:-O40gzygAQAQbrJNL50e:b-kg78c5) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3c45a3ecd82bc2d5fd0690ebbf1575b9a1fbcaae/stwo_cairo_prover/src/components/ret_opcode/prover.rs#L20)):*
> ```XML
> use crate::components::memory::MemoryLookupElements;
> 
> pub type RetInput = [PackedM31; 3];
> ```

Create constant.



_Code quote:_
```XML
3
```
___
*[`stwo_cairo_prover/src/components/ret_opcode/prover.rs` line 114 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/44#-O40ilbv-ug7fmrrow44:-O40ilbv-ug7fmrrow45:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3c45a3ecd82bc2d5fd0690ebbf1575b9a1fbcaae/stwo_cairo_prover/src/components/ret_opcode/prover.rs#L114)):*
> ```XML
>         .collect_vec();
>     let mut sub_components_inputs = RetOpcodeInteractionProver::with_capacity(inputs.len());
>     inputs.iter().enumerate().for_each(|(i, secret)| {
> ```





_Suggestion:_
```XML
 input
```
___
*[`stwo_cairo_prover/src/components/ret_opcode/prover.rs` line 163 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/44#-O40kCMC43wXRTXSkKND:-O40kCMC43wXRTXSkKNE:b-qsew77) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3c45a3ecd82bc2d5fd0690ebbf1575b9a1fbcaae/stwo_cairo_prover/src/components/ret_opcode/prover.rs#L163)):*
> ```XML
>     dst[2].data[row_index] = col2;
>     lookup_data.memory_inputs[0].push(col0);
>     // TODO(Ohad): implement and uncomment.
> ```

What is this reffering to? 



_Code quote:_
```XML
// TODO(Ohad): implement and uncomment.
```

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/44)* status: 8 of 17 files reviewed, 11 unresolved discussions (waiting on @alonh5)

___
*[`stwo_cairo_prover/src/components/memory/prover.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/44#-O3m731uBEYLzB2fU6y8:-O44F_zd8ajhr_3DkUm7:b-vsbzqi) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e971c94231d8518bd619b3ae0501ff652cabe035/stwo_cairo_prover/src/components/memory/prover.rs#L20)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

From what I understand this constant should be log the number of packed elements in the memory. So if we have `LOG_MEMORY_ADDRESS_BOUND` elements ther should be `LOG_MEMORY_ADDRESS_BOUND - LOG_N_LANES` packed elements, no?
</blockquote></details>

its simply the number of rows,
I just added another one to not conflict with the current (which was bad for simd tests)
removed the old value and renamed.
___
*[`stwo_cairo_prover/src/components/memory/prover.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/44#-O3m8Bf22jICxsChCQ4i:-O44FmuGAZ-BKuIRmp4H:b-q94kyk) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e971c94231d8518bd619b3ae0501ff652cabe035/stwo_cairo_prover/src/components/memory/prover.rs#L38)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

I don't see it.
</blockquote></details>

Done. sorry
___
*[`stwo_cairo_prover/src/components/memory/prover.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/44#-O3m9ZQY2mdgbJehtmaK:-O44Bdd_B9_prA6CAk-H:brxgpup) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e971c94231d8518bd619b3ae0501ff652cabe035/stwo_cairo_prover/src/components/memory/prover.rs#L54)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Why is it this way? Don't we need only a single value (at pc for example)?
</blockquote></details>

consider a trace of packedM31 rather then plain M31
The vectorization is vertical, so the horizontal computation is optimal
in that case, when we perform a step of trace computation, we do that on PackedM31 (16 rows of M31's). Specifically a step that writes a memory value in the trace would have PackedM31 as target addresses(input) and PackedType as the output.
  
___
*[`stwo_cairo_prover/src/components/memory/prover.rs` line 14 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/44#-O40EFLk6ZWSv8EwwfkD:-O44HljT7yuKIj6NPaC8:b2nign6) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3c45a3ecd82bc2d5fd0690ebbf1575b9a1fbcaae/stwo_cairo_prover/src/components/memory/prover.rs#L14)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Mistake?
</blockquote></details>

yes
___
*[`stwo_cairo_prover/src/components/memory/prover.rs` line 55 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/44#-O40_V1w8hs2_CbAWY9n:-O44CXqX1u5oz0-8Uf4w:b-ht5pag) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3c45a3ecd82bc2d5fd0690ebbf1575b9a1fbcaae/stwo_cairo_prover/src/components/memory/prover.rs#L55)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Do we need this separately from `deduce_output()`?
</blockquote></details>

yes, deduce will be called on every trace cell, while aggregating the inputs.
eventually after the specific trace computation is done, add_inputs will be called on the aggregated inputs.
this is to optimize multithreading. 
___
*[`stwo_cairo_prover/src/components/memory/prover.rs` line 87 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/44#-O40E30P4hrqRxilm25r:-O44Fr6a652vT60uc1Hs:bb7m3jc) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3c45a3ecd82bc2d5fd0690ebbf1575b9a1fbcaae/stwo_cairo_prover/src/components/memory/prover.rs#L87)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Almost :)
</blockquote></details>

oops
___
*[`stwo_cairo_prover/src/components/ret_opcode/component.rs` line 53 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/44#-O40XO1QB0ew24M1U-iO:-O44G8UT7c7CuI2MPY5i:b-7rl0jd) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3c45a3ecd82bc2d5fd0690ebbf1575b9a1fbcaae/stwo_cairo_prover/src/components/ret_opcode/component.rs#L53)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Turn this into a TODO.
</blockquote></details>

done.
___
*[`stwo_cairo_prover/src/components/ret_opcode/component.rs` line 100 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/44#-O40Hv35B5VQZ1Vae2Oa:-O44GqPP3YKDhYF_lNof:bhtxgai) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3c45a3ecd82bc2d5fd0690ebbf1575b9a1fbcaae/stwo_cairo_prover/src/components/ret_opcode/component.rs#L100)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

In this case the only lookup is to the memory but in other components it could be one claimed sum for many lookups, right?
</blockquote></details>

right, every interaction claim will hold claimed sums for specific lookups, and one for itself.
the verifier will gather memory_claimed sums from all the components, sum them together with the one from the memory, and assert it is 0.
___
*[`stwo_cairo_prover/src/components/ret_opcode/prover.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/44#-O40gzygAQAQbrJNL50d:-O44HPkp5WvjId15arJ8:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3c45a3ecd82bc2d5fd0690ebbf1575b9a1fbcaae/stwo_cairo_prover/src/components/ret_opcode/prover.rs#L20)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Create constant.
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/src/components/ret_opcode/prover.rs` line 114 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/44#-O40ilbv-ug7fmrrow44:-O44HSB72J-HN0KKvL5X:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3c45a3ecd82bc2d5fd0690ebbf1575b9a1fbcaae/stwo_cairo_prover/src/components/ret_opcode/prover.rs#L114)):*
> ```XML
>         .collect_vec();
>     let mut sub_components_inputs = RetOpcodeInteractionProver::with_capacity(inputs.len());
>     inputs.iter().enumerate().for_each(|(i, secret)| {
> ```

Done.
___
*[`stwo_cairo_prover/src/components/ret_opcode/prover.rs` line 163 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/44#-O40kCMC43wXRTXSkKND:-O44HVVMCdjztYBR0_V8:b-a0w60) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3c45a3ecd82bc2d5fd0690ebbf1575b9a1fbcaae/stwo_cairo_prover/src/components/ret_opcode/prover.rs#L163)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

What is this reffering to?
</blockquote></details>

nothing

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 16 files at r1, 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/44)* status: all files reviewed, 4 unresolved discussions (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/src/components/memory/component.rs` line 15 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/44#-O44SKac1-2UKpzBIMlE:-O44SKac1-2UKpzBIMlF:b-24ddqf) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/aef072fac6f7bc938a606a331d7f0f8431e3dde3/stwo_cairo_prover/src/components/memory/component.rs#L15)):*
> ```XML
> pub const N_MEMORY_COLUMNS: usize = N_M31_IN_FELT252 + 2;
> pub const LOG_MEMORY_ADDRESS_BOUND: u32 = 7;
> pub const MEMORY_ADDRESS_BOUND: usize = 1 << LOG_MEMORY_ADDRESS_BOUND;
> ```

Add blank line below.
___
*[`stwo_cairo_prover/src/components/ret_opcode/component.rs` line 100 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/44#-O44ZcFiDNzx_Tfu2Tzz:-O44ZcFiDNzx_Tfu2U--:bhu6038) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e971c94231d8518bd619b3ae0501ff652cabe035/stwo_cairo_prover/src/components/ret_opcode/component.rs#L100)):*
> ```XML
>     // pub ret_claimed_sum: SecureField,
>     pub log_size: u32,
>     pub memory_claimed_sum: SecureField,
> ```

Continuing our talk offline.



_Suggestion:_
```XML
    pub log_size: u32,
    pub claimed_sum: SecureField,
```
___
*[`stwo_cairo_prover/src/components/ret_opcode/prover.rs` line 47 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/44#-O44S1byBFu9IQQIyKTz:-O44S1bzBk4tyvvywiAU:bmhth8n) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/aef072fac6f7bc938a606a331d7f0f8431e3dde3/stwo_cairo_prover/src/components/ret_opcode/prover.rs#L47)):*
> ```XML
> 
> pub struct RetOpcodeInteractionProver {
>     pub memory_inputs: [Vec<PackedM31>; 3],
> ```

Use constant here and anywhere relevant.



_Code quote:_
```XML
3
```
___
*[`stwo_cairo_prover/src/prover_types/mod.rs` line 61 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/44#-O44_ikg0xd3vs3nl4ez:-O44_ikg0xd3vs3nl4f-:ba3dfmt) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/aef072fac6f7bc938a606a331d7f0f8431e3dde3/stwo_cairo_prover/src/prover_types/mod.rs#L61)):*
> ```XML
>     let simd = Simd::splat(N_LANES as u32);
>     unsafe { PackedM31::from_simd_unchecked(simd) }
> }
> ```

Remove.



_Code quote:_
```XML
pub fn packed_m31_increment() -> PackedM31 {
    let simd = Simd::splat(N_LANES as u32);
    unsafe { PackedM31::from_simd_unchecked(simd) }
}
```

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/44)* status: 13 of 17 files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`stwo_cairo_prover/src/components/ret_opcode/prover.rs` line 47 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/44#-O44S1byBFu9IQQIyKTz:-O44aK0f5tbXRKNvrOcW:b-vdky6w) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/aef072fac6f7bc938a606a331d7f0f8431e3dde3/stwo_cairo_prover/src/components/ret_opcode/prover.rs#L47)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Use constant here and anywhere relevant.
</blockquote></details>

it's a different 3,
added another constant

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/44#-:-O44fZVj7dkumjEVqO_r:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/src/components/ret_opcode/prover.rs` line 81 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/44#-O44fJOK4TQ0PKR4qDuq:-O44fJOK4TQ0PKR4qDur:b-k31jta) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/7cd199ddeca587fcccb33e93a64c827bf510dcf3/stwo_cairo_prover/src/components/ret_opcode/prover.rs#L81)):*
> ```XML
>         let log_size = self.memory_inputs[0].len().ilog2() + LOG_N_LANES;
>         let mut logup_gen = LogupTraceGenerator::new(log_size);
>         for col_index in 0..3 {
> ```

Here also



_Code quote:_
```XML
3
```

**Review by alonh5 — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/44)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ohad-starkware)

**Comment by ohad-starkware** [comment]
### Merge activity

* **Aug 12, 5:54 AM EDT**: @ohad-starkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/44).

**Pull request merged**
