### PR TITLE
Batch Inverse in logup_sum

### PR DESCRIPTION
**Pull request by Gali-StarkWare**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/275)

### CODE REVIEW

**Comment by Gali-StarkWare** [comment]
* **#275** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/275?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/275?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by ohad-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/275)* status: all files reviewed, 1 unresolved discussion (waiting on @Gali-StarkWare and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/air.rs` line 113 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/275#-OEoAEQd8kxFoMky5Y4V:-OEoAEQd8kxFoMky5Y4W:bg66f82) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c521d03185ca5a3958a17bf58fd5f612a6acbc21/stwo_cairo_prover/crates/prover/src/cairo_air/air.rs#L113)):*
> ```XML
> impl PublicData {
>     pub fn logup_sum(&self, lookup_elements: &CairoInteractionElements) -> QM31 {
>         let mut logup_data = Vec::new();
> ```

?
or something else
idk what logup_data is



_Suggestion:_
```XML
let mut values_to_inverse = vec![];
```

**Review by Gali-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/275)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ohad-starkware and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/air.rs` line 113 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/275#-OEoAEQd8kxFoMky5Y4V:-OEoBlFP41i802wlnm_-:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c521d03185ca5a3958a17bf58fd5f612a6acbc21/stwo_cairo_prover/crates/prover/src/cairo_air/air.rs#L113)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

?
or something else
idk what logup_data is
</blockquote></details>

Done.

**Review by ohad-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/275#-:-OEoDOkhCjgK_LgjzgId:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/275)* status: all files reviewed, 4 unresolved discussions (waiting on @Gali-StarkWare)

___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/air.rs` line 112 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/275#-OEs23yA38EB7vez5UOn:-OEs23yA38EB7vez5UOo:b-wgr7pi) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/98a158af62046389cda9310ff59805e3a49af247/stwo_cairo_prover/crates/prover/src/cairo_air/air.rs#L112)):*
> ```XML
> }
> impl PublicData {
>     pub fn logup_sum(&self, lookup_elements: &CairoInteractionElements) -> QM31 {
> ```

Document this function



_Code quote:_
```XML
pub fn logup_sum(&self, lookup_elements: &CairoInteractionElements) -> QM31 {
```
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/air.rs` line 115 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/275#-OEs2O5x7sIYKzEBWUe0:-OEs2O5x7sIYKzEBWUe1:b5cyrh7) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/98a158af62046389cda9310ff59805e3a49af247/stwo_cairo_prover/crates/prover/src/cairo_air/air.rs#L115)):*
> ```XML
>         let mut values_to_inverse = vec![];
> 
>         self.public_memory.iter().for_each(|(addr, id, val)| {
> ```

Add comment



_Suggestion:_
```XML
// Use public memory in the memory relations.
self.public_memory.iter().for_each(|(addr, id, val)| {
```
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/air.rs` line 137 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/275#-OEs2-Y1B7eodKqTLR2M:-OEs2-Y1B7eodKqTLR2N:bh3o6fy) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/98a158af62046389cda9310ff59805e3a49af247/stwo_cairo_prover/crates/prover/src/cairo_air/air.rs#L137)):*
> ```XML
>             &self.final_state.values(),
>         ));
> ```

remove empty line
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/air.rs` line 143 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/275#-OEs2FNy5fgZC5sdUWp3:-OEs2FNy5fgZC5sdUWp4:brnoa5c) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/98a158af62046389cda9310ff59805e3a49af247/stwo_cairo_prover/crates/prover/src/cairo_air/air.rs#L143)):*
> ```XML
>         ));
> 
>         let mut inverted_values = vec![QM31::zero(); values_to_inverse.len()];
> ```

Do we need to initialize the values here? I'm not sure



_Code quote:_
```XML
let mut inverted_values = vec![QM31::zero(); values_to_inverse.len()];
```

**Review by Gali-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/275)* status: 0 of 78 files reviewed, 4 unresolved discussions (waiting on @Gali-StarkWare and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/air.rs` line 112 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/275#-OEs23yA38EB7vez5UOn:-OEs5yod6bLXAj6_YFPm:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/98a158af62046389cda9310ff59805e3a49af247/stwo_cairo_prover/crates/prover/src/cairo_air/air.rs#L112)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Document this function
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/air.rs` line 115 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/275#-OEs2O5x7sIYKzEBWUe0:-OEs45V4-JSwXWSRZxiY:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/98a158af62046389cda9310ff59805e3a49af247/stwo_cairo_prover/crates/prover/src/cairo_air/air.rs#L115)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Add comment
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/air.rs` line 137 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/275#-OEs2-Y1B7eodKqTLR2M:-OEs4Dp-1ZVMZhEa6kAX:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/98a158af62046389cda9310ff59805e3a49af247/stwo_cairo_prover/crates/prover/src/cairo_air/air.rs#L137)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

remove empty line
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/air.rs` line 143 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/275#-OEs2FNy5fgZC5sdUWp3:-OEs4EYP4EFvm6CGBieH:b-1ahm7l) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/98a158af62046389cda9310ff59805e3a49af247/stwo_cairo_prover/crates/prover/src/cairo_air/air.rs#L143)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Do we need to initialize the values here? I'm not sure
</blockquote></details>

We need to send to the function dst with len >= src.len, so I have to do the allocation before calling the function. I can use Vec::with_capacity() but the length will be 0.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/275#-:-OEs9jpy4bW5DhuhyStY:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @Gali-StarkWare)

___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/air.rs` line 112 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/275#-OEs23yA38EB7vez5UOn:-OEs937r5_2UCsSCAzDx:b-kze0ml) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ebcfd590fd1cdb699dc93ed8ae8a16b9659a7a8b/stwo_cairo_prover/crates/prover/src/cairo_air/air.rs#L112)):*
<details><summary><i>Previously, Gali-StarkWare wrote…</i></summary><blockquote>

Done.
</blockquote></details>

/// Sums the logup of the public data.
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/air.rs` line 143 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/275#-OEs2FNy5fgZC5sdUWp3:-OEs9Zo48Pf-MKBKdwI0:b-f3hsfu) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ebcfd590fd1cdb699dc93ed8ae8a16b9659a7a8b/stwo_cairo_prover/crates/prover/src/cairo_air/air.rs#L143)):*
<details><summary><i>Previously, Gali-StarkWare wrote…</i></summary><blockquote>

We need to send to the function dst with len >= src.len, so I have to do the allocation before calling the function. I can use Vec::with_capacity() but the length will be 0.
</blockquote></details>

you could do
unsafe { vec.set_len(length); }

but I don't think we should do that.
Retracting

**Review by Gali-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/275)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/air.rs` line 112 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/275#-OEs23yA38EB7vez5UOn:-OEsRZNe3ZQfHoJrzCYm:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ebcfd590fd1cdb699dc93ed8ae8a16b9659a7a8b/stwo_cairo_prover/crates/prover/src/cairo_air/air.rs#L112)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

/// Sums the logup of the public data.
</blockquote></details>

Done.

**Review by shaharsamocha7 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/275)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Gali-StarkWare)

**Pull request merged**
