### PR TITLE
pack for casm

### PR DESCRIPTION
**Pull request by ohad-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/160)

### CODE REVIEW

**Comment by ohad-starkware** [comment]
* **#160** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/160?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ohad-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by ilyalesokhin-starkware** [comment]
*[`stwo_cairo_prover/crates/prover_types/src/simd.rs` line 392 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/160#-OBZnr7H-6mrbH8pecgw:-OBZnr7H-6mrbH8pecgx:bxy2abk) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/eb4150df736b85bc7a5ba7a903093c514c5e25a7/stwo_cairo_prover/crates/prover_types/src/simd.rs#L392)):*
> ```XML
>     fn unpack(self) -> [Self::CpuType; N_LANES] {
>         std::array::from_fn(|i| CasmState {
>             pc: self.pc.to_array()[i],
> ```

Is it cheap? Maybe we want to do that outside of the lamda?



_Code quote:_
```XML
self.pc.to_array()
```

**Comment by ilyalesokhin-starkware** [comment]
*[`stwo_cairo_prover/crates/prover_types/src/simd.rs` line 375 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/160#-OBZnymHEVs-2taeQTwi:-OBZnymHEVs-2taeQTwj:b45h) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/eb4150df736b85bc7a5ba7a903093c514c5e25a7/stwo_cairo_prover/crates/prover_types/src/simd.rs#L375)):*
> ```XML
> // TODO(Ohad): When there are more structs, write a proc-macro in stwo.
> // TODO(Ohad): Optimize copies.
> impl Pack for CasmState {
> ```





_Suggestion:_
```XML
VMState
```

**Comment by ilyalesokhin-starkware** [comment]
*[`stwo_cairo_prover/crates/prover_types/src/simd.rs` line 375 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/160#-OBZnymHEVs-2taeQTwi:-OBZor975T82g63iTjoI:b-xajlh) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/eb4150df736b85bc7a5ba7a903093c514c5e25a7/stwo_cairo_prover/crates/prover_types/src/simd.rs#L375)):*
> ```XML
> // TODO(Ohad): When there are more structs, write a proc-macro in stwo.
> // TODO(Ohad): Optimize copies.
> impl Pack for CasmState {
> ```

or
CpuState

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/160)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`stwo_cairo_prover/crates/prover_types/src/simd.rs` line 375 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/160#-OBZnymHEVs-2taeQTwi:-OB_1JGL4PEqJvhmoKbo:b-hraic) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/eb4150df736b85bc7a5ba7a903093c514c5e25a7/stwo_cairo_prover/crates/prover_types/src/simd.rs#L375)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

or
CpuState
</blockquote></details>

IMO VMstate
this should be coordinated with the air team as they defined it
___
*[`stwo_cairo_prover/crates/prover_types/src/simd.rs` line 392 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/160#-OBZnr7H-6mrbH8pecgw:-OB_1Hxk2KLS8fED6wQn:b-7rl0jd) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/eb4150df736b85bc7a5ba7a903093c514c5e25a7/stwo_cairo_prover/crates/prover_types/src/simd.rs#L392)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Is it cheap? Maybe we want to do that outside of the lamda?
</blockquote></details>

done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/160#-:-OB_J8pz9ox7SqN-RUeq:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @ohad-starkware)

**Pull request merged**
