### PR TITLE
jump

### PR DESCRIPTION
**Pull request by ohad-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/221)

### CODE REVIEW

**Comment by ohad-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/221?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#221** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/221?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/221?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#220** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/220?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#219** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/219?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#218** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/218?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#217** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/217?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#216** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/216?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#215** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/215?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#214** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/214?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#209** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/209?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#208** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/208?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#207** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/207?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#206** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/206?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/221)* status: 0 of 15 files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo-cairo/221#-ODLq3pc2-g8kruQbkYF:-ODLr6C5E1jEZP2tid69:bs7wup8) (no related file):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Rename the jumps to 
jump_x_y_z   (x,y,z \in {f,t})
</blockquote></details>

Done.s
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/opcodes_air.rs` line 48 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/221#-ODLppsJ1kpp81HBSlmw:-ODLr4g3EIf_V2PFxz6R:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/8afd63dff8ed4ae3258438b186832612d2ca3ac2/stwo_cairo_prover/crates/prover/src/cairo_air/opcodes_air.rs#L48)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Rename to jump_fft :)
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/opcodes_air.rs` line 74 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/221#-ODLpIBDBzFP70x9aad3:-ODLr4ErEcHyjRahU0Gl:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/8afd63dff8ed4ae3258438b186832612d2ca3ac2/stwo_cairo_prover/crates/prover/src/cairo_air/opcodes_air.rs#L74)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

You missed one
</blockquote></details>

Done.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/221)* status: 0 of 15 files reviewed, 2 unresolved discussions (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/opcodes_air.rs` line 154 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/221#-ODLuPTJEbdyYfCKcMDr:-ODLuPTJEbdyYfCKcMDs:b-thik2e) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/9376e467a71fcfb8223902cb96e7f4e7653c47dc/stwo_cairo_prover/crates/prover/src/cairo_air/opcodes_air.rs#L154)):*
> ```XML
>         let mut jump_f_t = vec![];
>         let mut jump_t_f = vec![];
>         let mut jump_t_t = vec![];
> ```

also here
and anywhere



_Code quote:_
```XML
        let mut jump_f_f = vec![];
        let mut jump_f_t = vec![];
        let mut jump_t_f = vec![];
        let mut jump_t_t = vec![];
```

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/221)* status: 0 of 15 files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/opcodes_air.rs` line 154 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/221#-ODLuPTJEbdyYfCKcMDr:-ODM38IyB_69wHSxTjbL:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/9376e467a71fcfb8223902cb96e7f4e7653c47dc/stwo_cairo_prover/crates/prover/src/cairo_air/opcodes_air.rs#L154)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

also here
and anywhere
</blockquote></details>

Done.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 12 of 15 files at r1, 1 of 3 files at r4, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/221)* status: all files reviewed, 2 unresolved discussions (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/opcodes_air.rs` line 1184 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/221#-ODM6Ob3-mYSmf13Ki2d:-ODM6Ob3-mYSmf13Ki2e:b32vhv) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/709af91ae2ff16d5a1e0849f8cc3b67d3d327c69/stwo_cairo_prover/crates/prover/src/cairo_air/opcodes_air.rs#L1184)):*
> ```XML
>             })
>             .collect();
>         let jump_f_f_interaction_claims = self
> ```

:(



_Suggestion:_
```XML
let jump_f_f_f_interaction_claims = self
```
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/opcodes_air.rs` line 1693 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/221#-ODM6UH56ayFx5fgUWZ3:-ODM6UH56ayFx5fgUWZ4:b-8fzawp) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/709af91ae2ff16d5a1e0849f8cc3b67d3d327c69/stwo_cairo_prover/crates/prover/src/cairo_air/opcodes_air.rs#L1693)):*
> ```XML
>             })
>             .collect_vec();
>         let jump_f_f_components = claim
> ```

:( x2



_Suggestion:_
```XML
 let jump_f_f_f_components = claim
```

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/221#-:-ODMBIGM3j17Yp2YkPVK:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ohad-starkware)

**Comment by ohad-starkware** [comment]
### Merge activity

* **Dec 5, 10:57 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/221).

**Pull request merged**
