### PR TITLE
handle no inputs

### PR DESCRIPTION
**Pull request by ohad-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/179)

### CODE REVIEW

**Comment by ohad-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/179?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#179** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/179?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/179?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#177** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/177?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#178** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/178?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/179)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ohad-starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo-cairo/179#-OC41dKh-BOkNbiHjHZh:-OC41dKh-BOkNbiHjHZi:b-jagnja) (no related file):*
I think that filtering trace generators with n_calls=0 
should be at the AIR level
I.e. before you call write_trace.

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/179)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ohad-starkware and @shaharsamocha7)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo-cairo/179#-OC41dKh-BOkNbiHjHZh:-OC7WGVI9mpsqnyg6Rzw:br4uark) (no related file):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I think that filtering trace generators with n_calls=0 
should be at the AIR level
I.e. before you call write_trace.
</blockquote></details>

pr changed to asserting write_trace is not called with 0 inputs
handling no inputs outside will be handled seperatly

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/179#-:-OC7dUj32a5bVrcY5X3L:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ohad-starkware)

**Pull request merged**
