### PR TITLE
delete the function from_biguint256

### PR DESCRIPTION
**Pull request by ohad-nir-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/183)

### CODE REVIEW

**Review by ohad-starkware — COMMENTED** [review]
Not sure why shahar and I are reviewers

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/183#-:-OC8IgWi1RYfxXtJmjUQ:bycugkg)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @anatgstarkware and @shaharsamocha7)

**Comment by anatgstarkware** [comment]
Ohad added you because I asked him to. I prefer that we (builtins) won't change stwo-cairo without Shahar knowing, and I thought you need to know what to support in the packed types. (now it's just deleting a function, next we are adding a new one).

**Review by anatgstarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/183#-:-OCY0i2h9ul3_86N8Vk3:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @az-starkware, @DavidLevitGurevich, and @shaharsamocha7)

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/183#-:-OCYXPq17WDczCiUtXa8:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @az-starkware and @DavidLevitGurevich)

**Pull request merged**
