### PR TITLE
Implement MultiplicitiesColumn in range_check_vector

### PR DESCRIPTION
**Pull request by Gali-StarkWare**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/272)

### CODE REVIEW

**Review by ohad-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/272)* status: all files reviewed, 1 unresolved discussion (waiting on @Gali-StarkWare and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_vector/component_prover.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/272#-OEoAlUvCURLbqQ63aTA:-OEoAlUvCURLbqQ63aTB:b-cksehb) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/2778e317b9ac42d3108b06d9f76fe990ba70c017/stwo_cairo_prover/crates/prover/src/components/range_check_vector/component_prover.rs#L35)):*
> ```XML
>                 #[allow(clippy::new_without_default)]
>                 pub fn new() -> Self {
>                     let multiplicities = MultiplicityColumn::new( 1 << (RANGES.iter().sum::<u32>()));
> ```

formatter doesnt run on quoted code, but we should still try to stay under 100 column
maybe :



_Suggestion:_
```XML
                pub fn new() -> Self {
                    let length = 1 << self.log_size();
                    let multiplicities = MultiplicityColumn::new(length));
```

**Review by Gali-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/272)* status: all files reviewed, 1 unresolved discussion (waiting on @ohad-starkware and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_vector/component_prover.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/272#-OEoAlUvCURLbqQ63aTA:-OEoDlvF8AnrpJv77fWP:biuicm0) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/2778e317b9ac42d3108b06d9f76fe990ba70c017/stwo_cairo_prover/crates/prover/src/components/range_check_vector/component_prover.rs#L35)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

formatter doesnt run on quoted code, but we should still try to stay under 100 column
maybe :
</blockquote></details>

Done. Not using self because it doesn't exist yet

**Review by ohad-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/272)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Gali-StarkWare)

___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_vector/component_prover.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/272#-OEoAlUvCURLbqQ63aTA:-OErUtTn87hxG2MRm8ma:bcvb9un) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/2778e317b9ac42d3108b06d9f76fe990ba70c017/stwo_cairo_prover/crates/prover/src/components/range_check_vector/component_prover.rs#L35)):*
<details><summary><i>Previously, Gali-StarkWare wrote…</i></summary><blockquote>

Done. Not using self because it doesn't exist yet
</blockquote></details>

this is still 102 columns

**Comment by Gali-StarkWare** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/272?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#272** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/272?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/272?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#271** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/271?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by Gali-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/272)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_vector/component_prover.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/272#-OEoAlUvCURLbqQ63aTA:-OErkKvA1h0ysAdjw2PX:bitx5ex) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/2778e317b9ac42d3108b06d9f76fe990ba70c017/stwo_cairo_prover/crates/prover/src/components/range_check_vector/component_prover.rs#L35)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

this is still 102 columns
</blockquote></details>

My bad, forgot to commit

**Review by ohad-starkware — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/272#-:-OEsDiELBtIBhIejumWQ:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @Gali-StarkWare)

**Review by shaharsamocha7 — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/272)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Gali-StarkWare)

**Comment by Gali-StarkWare** [comment]
### Merge activity

* **Dec 24, 10:16 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/272).

**Pull request merged**
