### PR TITLE
add the trait Invertible to externalise the invert function for M31 and Felt252

### PR DESCRIPTION
**Pull request by ohad-nir-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/278)

### CODE REVIEW

**Review by dancarmoz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/278)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @anatgstarkware, @ohad-nir-starkware, and @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover_types/src/cpu.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/278#-OEyLcBt3ViLSoa_Bs90:-OEyLcBt3ViLSoa_Bs91:b-yjevc5) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c5e369bd7f2a60c82fe5a7243026048066ae9d98/stwo_cairo_prover/crates/prover_types/src/cpu.rs#L20)):*
> ```XML
> 
> pub trait Invertible {
>     fn invert(&self) -> Self;
> ```

Why pass by reference (`&`)? None of the other arirthmetic functions do that.
___
*[`stwo_cairo_prover/crates/prover_types/src/cpu.rs` line 552 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/278#-OEyJy_jDdggDoBz7060:-OEyJy_jDdggDoBz7061:b-fb3mwh) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c5e369bd7f2a60c82fe5a7243026048066ae9d98/stwo_cairo_prover/crates/prover_types/src/cpu.rs#L552)):*
> ```XML
> }
> 
> const FELT252_MONT_INV_FACTOR: FieldElement =
> ```

Add documentation as for previous constants:

```The Montgomery inversion adds a factor of 2**512 to the inverse of `self`, so to get the true inverse we should multiply with 2**-256 % P (the Montgomery form of 2**-512).```

**Review by ohad-nir-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/278)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @anatgstarkware, @dancarmoz, and @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover_types/src/cpu.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/278#-OEyLcBt3ViLSoa_Bs90:-OEyRwtN1tosSbdjmm-X:b5dkmfe) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c5e369bd7f2a60c82fe5a7243026048066ae9d98/stwo_cairo_prover/crates/prover_types/src/cpu.rs#L20)):*
<details><summary><i>Previously, dancarmoz (Dan Carmon) wrote…</i></summary><blockquote>

Why pass by reference (`&`)? None of the other arirthmetic functions do that.
</blockquote></details>

@anatgstarkware
___
*[`stwo_cairo_prover/crates/prover_types/src/cpu.rs` line 552 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/278#-OEyJy_jDdggDoBz7060:-OEyRMtpAwvKuksf5wgX:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c5e369bd7f2a60c82fe5a7243026048066ae9d98/stwo_cairo_prover/crates/prover_types/src/cpu.rs#L552)):*
<details><summary><i>Previously, dancarmoz (Dan Carmon) wrote…</i></summary><blockquote>

Add documentation as for previous constants:

```The Montgomery inversion adds a factor of 2**512 to the inverse of `self`, so to get the true inverse we should multiply with 2**-256 % P (the Montgomery form of 2**-512).```
</blockquote></details>

Done.

**Review by ohad-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/278)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @anatgstarkware and @dancarmoz)

___
*[`stwo_cairo_prover/crates/prover_types/src/cpu.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/278#-OEyLcBt3ViLSoa_Bs90:-OEylte9-C54UBnbcYco:bj7msnt) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c5e369bd7f2a60c82fe5a7243026048066ae9d98/stwo_cairo_prover/crates/prover_types/src/cpu.rs#L20)):*
<details><summary><i>Previously, ohad-nir-starkware (Ohad Nir) wrote…</i></summary><blockquote>

@anatgstarkware
</blockquote></details>

why is this a trait? 
also do pass by reference, otherwise youll get clones everywhere

**Comment by anatgstarkware** [comment]
*[`stwo_cairo_prover/crates/prover_types/src/cpu.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/278#-OEyLcBt3ViLSoa_Bs90:-OF1gc4p90j-KApz3Jyl:b-uuue4e) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c5e369bd7f2a60c82fe5a7243026048066ae9d98/stwo_cairo_prover/crates/prover_types/src/cpu.rs#L20)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

why is this a trait? 
also do pass by reference, otherwise youll get clones everywhere
</blockquote></details>

it's a trait because we don't want air-infra to depend on stwo-prover (like all other M31 operations exported from this file)

Let's use a reference here, as the inverse function for M31 implemented in stwo-prover gets a reference, unlike other operations

**Comment by anatgstarkware** [comment]
*[`stwo_cairo_prover/crates/prover_types/src/simd.rs` line 462 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/278#-OF1qqu83s369Wz760EH:-OF1qqu98WKl4tiaw9Iz:b-d740zg) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/5aecf1647b7c621d27b18719242866366667b388/stwo_cairo_prover/crates/prover_types/src/simd.rs#L462)):*
> ```XML
> }
> 
> pub trait InverseExtend {
> ```

Why do we need to add a trait here? please remove

**Review by ohad-nir-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/278)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @anatgstarkware and @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover_types/src/cpu.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/278#-OEyLcBt3ViLSoa_Bs90:-OF2gBhrErb6I1Dq1qfq:b5zlrji) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c5e369bd7f2a60c82fe5a7243026048066ae9d98/stwo_cairo_prover/crates/prover_types/src/cpu.rs#L20)):*
<details><summary><i>Previously, anatgstarkware (anatg) wrote…</i></summary><blockquote>

it's a trait because we don't want air-infra to depend on stwo-prover (like all other M31 operations exported from this file)

Let's use a reference here, as the inverse function for M31 implemented in stwo-prover gets a reference, unlike other operations
</blockquote></details>

there is an issue with trace generation: we currently have the ability to generate x.func(y) or func(x) but not func(&x).
___
*[`stwo_cairo_prover/crates/prover_types/src/simd.rs` line 462 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/278#-OF1qqu83s369Wz760EH:-OF2gAiJCySugR_PypNE:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/5aecf1647b7c621d27b18719242866366667b388/stwo_cairo_prover/crates/prover_types/src/simd.rs#L462)):*
<details><summary><i>Previously, anatgstarkware (anatg) wrote…</i></summary><blockquote>

Why do we need to add a trait here? please remove
</blockquote></details>

Done.

**Comment by ohad-starkware** [comment]
*[`stwo_cairo_prover/crates/prover_types/src/cpu.rs` line 53 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/278#-OF2vd9S6DteaJFbPWvs:-OF2vd9S6DteaJFbPWvt:b45h) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/07d393f068a891b636ecded8cda9b954e5c713b7/stwo_cairo_prover/crates/prover_types/src/cpu.rs#L53)):*
> ```XML
> impl Inverse for M31 {
>     fn inverse(self) -> Self {
>         FieldExpOps::inverse(&self)
> ```





_Suggestion:_
```XML
self.inverse()
```

**Review by ohad-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/278)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @anatgstarkware, @dancarmoz, and @ohad-nir-starkware)

___
*[`stwo_cairo_prover/crates/prover_types/src/cpu.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/278#-OEyLcBt3ViLSoa_Bs90:-OF2vNjb4G9fYUNltpV4:b-cawsc0) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c5e369bd7f2a60c82fe5a7243026048066ae9d98/stwo_cairo_prover/crates/prover_types/src/cpu.rs#L20)):*
<details><summary><i>Previously, ohad-nir-starkware (Ohad Nir) wrote…</i></summary><blockquote>

there is an issue with trace generation: we currently have the ability to generate x.func(y) or func(x) but not func(&x).
</blockquote></details>

you are exposing x.func() here
Also I don't agree with adding a trait for that reason, what happens when you need more stuff from stwo? re export everything?
are you sure there is not a better solution?

**Review by ohad-nir-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/278)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @anatgstarkware, @dancarmoz, and @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover_types/src/cpu.rs` line 53 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/278#-OF2vd9S6DteaJFbPWvs:-OFGxnr8BoDbJoRMyVeg:b-ugxz45) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/07d393f068a891b636ecded8cda9b954e5c713b7/stwo_cairo_prover/crates/prover_types/src/cpu.rs#L53)):*
> ```XML
> impl Inverse for M31 {
>     fn inverse(self) -> Self {
>         FieldExpOps::inverse(&self)
> ```

the compiler sees that as a recursion

**Review by ohad-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/278)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @anatgstarkware, @dancarmoz, and @ohad-nir-starkware)

___
*[`stwo_cairo_prover/crates/prover_types/src/cpu.rs` line 53 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/278#-OF2vd9S6DteaJFbPWvs:-OFHHJShDsaqApzPTD_9:bnez1ak) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/07d393f068a891b636ecded8cda9b954e5c713b7/stwo_cairo_prover/crates/prover_types/src/cpu.rs#L53)):*
<details><summary><i>Previously, ohad-nir-starkware (Ohad Nir) wrote…</i></summary><blockquote>

the compiler sees that as a recursion
</blockquote></details>

inverse does not need to be a trait

**Pull request closed without merging**
