### PR TITLE
rangecheck vector trace, interaction and constraints

### PR DESCRIPTION
**Pull request by ohad-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/125)

### CODE REVIEW

**Comment by ohad-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/125?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#125** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/125?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#124** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/124?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ohad-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by andrewmilson — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/125)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @ohad-starkware and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_vector/component.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/125#-O9hNAjC4TVC5Ij96c1o:-O9hNAjC4TVC5Ij96c1p:b-qpfa80) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/340f259f687daf8a505e9ffcfe409914ab062f91/stwo_cairo_prover/crates/prover/src/components/range_check_vector/component.rs#L46)):*
> ```XML
> pub struct RangeCheckClaim<const N: usize> {
>     pub log_ranges: [u32; N],
> }
> ```

Why do we support so many ranges. Don't we just need 16 bit range check?



_Code quote:_
```XML
#[derive(Clone)]
pub struct RangeCheckClaim<const N: usize> {
    pub log_ranges: [u32; N],
}
```

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/125)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @andrewmilson and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_vector/component.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/125#-O9hNAjC4TVC5Ij96c1o:-O9hiDcfCBr8k_O_Av8I:b-r14o43) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/340f259f687daf8a505e9ffcfe409914ab062f91/stwo_cairo_prover/crates/prover/src/components/range_check_vector/component.rs#L46)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Why do we support so many ranges. Don't we just need 16 bit range check?
</blockquote></details>

so you could range-check multiple items with one lookup.
Theortically we do need 16 bit rangechecks only, but since we are getting 9 bit values from the memory, a composition needs to happen.
specifically, offset2 of instructions is passed in 3 cells, - 4 lsbs, 9 mids, 3 msbs (I'm assuming its not just the two because they push other stuff with the high/low bits).
so you get the 9bit range check for free, but you do need to assert the 3,4 bit rangecheck. a 2^(3+4) table in that case would not be too tall and reduce the number of interaction columns

**Review by andrewmilson — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/125)* status: 0 of 5 files reviewed, 8 unresolved discussions (waiting on @ohad-starkware and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_vector/component.rs` line 10 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/125#-O9m69w_69O3o7PM6tmT:-O9m69wa2dGffY7LELUo:b45h) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e974182ae1978e060e6474b659575df9cbcf8c83/stwo_cairo_prover/crates/prover/src/components/range_check_vector/component.rs#L10)):*
> ```XML
> 
> use super::RangeCheckVectorElements;
> const N_MULTIPLICITY_COLUMNS: usize = 1;
> ```





_Suggestion:_
```XML
use super::RangeCheckVectorElements;

const N_MULTIPLICITY_COLUMNS: usize = 1;
```
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_vector/component_prover.rs` line 16 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/125#-O9lict400jKDgPKjfTU:-O9lict400jKDgPKjfTV:b5vr8mh) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e974182ae1978e060e6474b659575df9cbcf8c83/stwo_cairo_prover/crates/prover/src/components/range_check_vector/component_prover.rs#L16)):*
> ```XML
>     exclusive_suffix_sum, generate_sparse_enumeration, packed_sparse_representation, simd_masks,
> };
> use crate::prover_types::PackedUInt32;
> ```

Why is this type needed? Why not just a `Simd<u32, N_LANES>` type alias.  
It seems like a wrapper that doesn't have any added function beyond what's available by the Simd or PackedM31 type.
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_vector/component_prover.rs` line 19 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/125#-O9m4ageDa5B7AcWohQu:-O9m4ageDa5B7AcWohQv:bl2wxfd) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e974182ae1978e060e6474b659575df9cbcf8c83/stwo_cairo_prover/crates/prover/src/components/range_check_vector/component_prover.rs#L19)):*
> ```XML
> 
> // TODO(Ohad): rustdoc.
> pub struct RangeCheckClaimProver<const N: usize> {
> ```

Is this a prover? Or an accumulator/pool.
I think Shahar used accumulator terminology for something similar with Xor.
Perhaps SplitRangeCheckAccumulator with docs?



_Code quote:_
```XML
Prover
```
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_vector/component_prover.rs` line 21 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/125#-O9m8DZY96Hpguvsnz8e:-O9m8DZY96Hpguvsnz8f:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e974182ae1978e060e6474b659575df9cbcf8c83/stwo_cairo_prover/crates/prover/src/components/range_check_vector/component_prover.rs#L21)):*
> ```XML
> pub struct RangeCheckClaimProver<const N: usize> {
>     log_ranges: [u32; N],
>     trailing_sums: [u32; N],
> ```





_Suggestion:_
```XML
log_ranges_suffix_sum
```
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_vector/component_prover.rs` line 54 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/125#-O9m8kAXB-XYutdADfgE:-O9m8kAXB-XYutdADfgF:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e974182ae1978e060e6474b659575df9cbcf8c83/stwo_cairo_prover/crates/prover/src/components/range_check_vector/component_prover.rs#L54)):*
> ```XML
>     pub fn add_packed_m31(&mut self, input: &[PackedM31; N]) {
>         for i in 0..N_LANES {
>             self.add_m31(std::array::from_fn(|j| input[j].to_array()[i]));
> ```





_Suggestion:_
```XML
self.add_m31(std::array::from_fn(|j| input[j].simd[i]));
```
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_vector/component_prover.rs` line 106 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/125#-O9m4RnG7a1_Ek9jPaSV:-O9m4RnG7a1_Ek9jPaSW:bv5cwj8) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e974182ae1978e060e6474b659575df9cbcf8c83/stwo_cairo_prover/crates/prover/src/components/range_check_vector/component_prover.rs#L106)):*
> ```XML
> 
> #[derive(Debug)]
> pub struct RangeCheckInteractionClaimProver<const N: usize> {
> ```

Is this a prover? Would it be better to replace with a function to generate the interaction trace. Something like `generate_interaction_trace`?



_Code quote:_
```XML
Prover
```
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_vector/mod.rs` line 6 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/125#-O9m5naED0GUouK2D_ab:-O9m5naED0GUouK2D_ac:b-48m7q3) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e974182ae1978e060e6474b659575df9cbcf8c83/stwo_cairo_prover/crates/prover/src/components/range_check_vector/mod.rs#L6)):*
> ```XML
> 
> // TODO(Ohad): figure out n_alpha_powers.
> pub type RangeCheckVectorElements = LookupElements<3>;
> ```

Maybe more indicative?



_Suggestion:_
```XML
RangeCheckLookupElements
```

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/125)* status: 0 of 5 files reviewed, 8 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_vector/component.rs` line 10 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/125#-O9m69w_69O3o7PM6tmT:-O9mvEM6CNonGcBw2Vxs:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e974182ae1978e060e6474b659575df9cbcf8c83/stwo_cairo_prover/crates/prover/src/components/range_check_vector/component.rs#L10)):*
> ```XML
> 
> use super::RangeCheckVectorElements;
> const N_MULTIPLICITY_COLUMNS: usize = 1;
> ```

Done.
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_vector/component_prover.rs` line 16 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/125#-O9lict400jKDgPKjfTU:-O9mfJk_-k4ZwyVVPeCx:bstd815) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e974182ae1978e060e6474b659575df9cbcf8c83/stwo_cairo_prover/crates/prover/src/components/range_check_vector/component_prover.rs#L16)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Why is this type needed? Why not just a `Simd<u32, N_LANES>` type alias.  
It seems like a wrapper that doesn't have any added function beyond what's available by the Simd or PackedM31 type.
</blockquote></details>

not needed here because it's manully written, but in general - 
we need to have simd complements for the types defined here https://github.com/starkware-industries/stwo-air-infra/blob/51faa86fe9b4b787ee7a358919aa9458ea58def8/crates/compiled_casm_air/src/prover_types.rs

it is yet to be implemented, but I am assuming a 'Packed{type}' exists in the auto gen.

in any case, done.
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_vector/component_prover.rs` line 19 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/125#-O9m4ageDa5B7AcWohQu:-O9mrfpl2Ox_2ZQr39F9:bbk8oag) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e974182ae1978e060e6474b659575df9cbcf8c83/stwo_cairo_prover/crates/prover/src/components/range_check_vector/component_prover.rs#L19)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Is this a prover? Or an accumulator/pool.
I think Shahar used accumulator terminology for something similar with Xor.
Perhaps SplitRangeCheckAccumulator with docs?
</blockquote></details>

this is the naming scheme we agreed upon when building the dummy cairo air, tal range_check_builtin/prover.rs or the memory one
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_vector/component_prover.rs` line 21 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/125#-O9m8DZY96Hpguvsnz8e:-O9ms6Pv4V5iaWMxG-BQ:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e974182ae1978e060e6474b659575df9cbcf8c83/stwo_cairo_prover/crates/prover/src/components/range_check_vector/component_prover.rs#L21)):*
> ```XML
> pub struct RangeCheckClaimProver<const N: usize> {
>     log_ranges: [u32; N],
>     trailing_sums: [u32; N],
> ```

Done.
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_vector/component_prover.rs` line 54 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/125#-O9m8kAXB-XYutdADfgE:-O9muNmd9Xa8DlWPMIQt:bgob2i1) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e974182ae1978e060e6474b659575df9cbcf8c83/stwo_cairo_prover/crates/prover/src/components/range_check_vector/component_prover.rs#L54)):*
> ```XML
>     pub fn add_packed_m31(&mut self, input: &[PackedM31; N]) {
>         for i in 0..N_LANES {
>             self.add_m31(std::array::from_fn(|j| input[j].to_array()[i]));
> ```

it's not pub in stwo, 
also I do want the reduce that to_array() invokes.
better now?
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_vector/component_prover.rs` line 106 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/125#-O9m4RnG7a1_Ek9jPaSV:-O9msUC89hnrEuhJeQYQ:bb7od0r) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e974182ae1978e060e6474b659575df9cbcf8c83/stwo_cairo_prover/crates/prover/src/components/range_check_vector/component_prover.rs#L106)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Is this a prover? Would it be better to replace with a function to generate the interaction trace. Something like `generate_interaction_trace`?
</blockquote></details>

same
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_vector/mod.rs` line 6 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/125#-O9m5naED0GUouK2D_ab:-O9mrLsm0_-STP3rXI4y:b-6ku1qo) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e974182ae1978e060e6474b659575df9cbcf8c83/stwo_cairo_prover/crates/prover/src/components/range_check_vector/mod.rs#L6)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Maybe more indicative?
</blockquote></details>

yes, Im worried about conflicting with range_check_unit, but it will soon be removed so ok.

**Review by andrewmilson — APPROVED** [review]
:lgtm: with comment

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/125#-:-OALM0qjCC14has3gyy5:b10c0l0)* status: 0 of 5 files reviewed, 10 unresolved discussions (waiting on @ohad-starkware and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/lib.rs` line 1 at r7](https://reviewable.io/reviews/starkware-libs/stwo-cairo/125#-OALLORU3f69h3K1rQAu:-OALLORV6y19h4GAJq_F:b-9aok8w) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/4732caecc931e743d3595dc622b121fa77c16a12/stwo_cairo_prover/crates/prover/src/lib.rs#L1)):*
> ```XML
> #![feature(array_methods, portable_simd, iter_array_chunks, const_for)]
> ```

Can this be removed? I don't see where it's needed
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_vector/component_prover.rs` line 16 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/125#-O9lict400jKDgPKjfTU:-O9ri39r97E0t6zxwaGL:be9dwum) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e974182ae1978e060e6474b659575df9cbcf8c83/stwo_cairo_prover/crates/prover/src/components/range_check_vector/component_prover.rs#L16)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

not needed here because it's manully written, but in general - 
we need to have simd complements for the types defined here https://github.com/starkware-industries/stwo-air-infra/blob/51faa86fe9b4b787ee7a358919aa9458ea58def8/crates/compiled_casm_air/src/prover_types.rs

it is yet to be implemented, but I am assuming a 'Packed{type}' exists in the auto gen.

in any case, done.
</blockquote></details>

Ahh I see. Thanks for the context. 
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_vector/component_prover.rs` line 26 at r7](https://reviewable.io/reviews/starkware-libs/stwo-cairo/125#-OALLwOT9SF2ziqk0yY2:-OALLwOT9SF2ziqk0yY3:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/4732caecc931e743d3595dc622b121fa77c16a12/stwo_cairo_prover/crates/prover/src/components/range_check_vector/component_prover.rs#L26)):*
> ```XML
>     pub multiplicities: Vec<Simd<u32, N_LANES>>,
> }
> impl<const N: usize> RangeCheckClaimProver<N> {
> ```





_Suggestion:_
```XML
}

impl<const N: usize> RangeCheckClaimProver<N> {
```

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/125)* status: 0 of 5 files reviewed, 10 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/lib.rs` line 1 at r7](https://reviewable.io/reviews/starkware-libs/stwo-cairo/125#-OALLORU3f69h3K1rQAu:-OAM566vE2ub1UXxTv_M:bb7s9zz) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/4732caecc931e743d3595dc622b121fa77c16a12/stwo_cairo_prover/crates/prover/src/lib.rs#L1)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Can this be removed? I don't see where it's needed
</blockquote></details>

yes!
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_vector/component_prover.rs` line 16 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/125#-O9lict400jKDgPKjfTU:-OAM58rw59p-8CHl9Utn:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e974182ae1978e060e6474b659575df9cbcf8c83/stwo_cairo_prover/crates/prover/src/components/range_check_vector/component_prover.rs#L16)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Ahh I see. Thanks for the context.
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_vector/component_prover.rs` line 26 at r7](https://reviewable.io/reviews/starkware-libs/stwo-cairo/125#-OALLwOT9SF2ziqk0yY2:-OAM5XRT0EcNjYmdbR7Z:bsk0yx8) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/4732caecc931e743d3595dc622b121fa77c16a12/stwo_cairo_prover/crates/prover/src/components/range_check_vector/component_prover.rs#L26)):*
> ```XML
>     pub multiplicities: Vec<Simd<u32, N_LANES>>,
> }
> impl<const N: usize> RangeCheckClaimProver<N> {
> ```

on purpose, impl below definition

**Pull request merged**
