### PR TITLE
Add coset

### PR DESCRIPTION
**Pull request by ajgara**
This PR implements the coset as needed for the Fri verifier.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/28)

### CODE REVIEW

**Review by schouhy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/28)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @ajgara and @shaharsamocha7)

___
*[`stwo_cairo_verifier/src/utils.cairo` line 84 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/28#-O2PRByr-3tGcNaL7Qfo:-O2Qfya_CAoFPU-xS4kq:b-6dql9) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f435ed68160804a2f7b4424f26d31a1e53f00677/stwo_cairo_verifier/src/utils.cairo#L84)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Please put under #[cfg(tests)] until you use that in non-test code
</blockquote></details>

Ah, it is used in `circle.cairo` in the `new` and `size` methods.  We put the `pow` function in `utils.cairo` since it will be needed in multiple files later on.

**Comment by schouhy** [comment]
*[`stwo_cairo_verifier/src/circle.cairo` line 62 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/28#-O2PPGvrEXS--IbLqwTU:-O2Qh6ua8rA5enZyYJgF:b92zzqv) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f435ed68160804a2f7b4424f26d31a1e53f00677/stwo_cairo_verifier/src/circle.cairo#L62)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Consider only doing computation on the low word of u32_wide_mul and using wrapping_add
(the high word \equiv 0 mod 2**32)
</blockquote></details>

Ok! Let me know if there's a better way to downcast from u64 to u32.

**Review by shaharsamocha7 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/28)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ajgara)

**Comment by schouhy** [comment]
Hi! I'm not sure if there are more changes requested in this PR. Can't find anything in Reviewable, but maybe I'm missing something. Please let me know if this is waiting on our end to make any further changes.  Same with PR 26.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/28#-:-O2s8xIaDs-jgLG1Augh:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ajgara)

**Pull request merged**
