### PR TITLE
Range check memory values in id_to_f252 trace generator

### PR DESCRIPTION
**Pull request by shaharsamocha7**
Range check memory values from memory trace generator
Remove range check from MemoryBuilder

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/148)

### CODE REVIEW

**Comment by shaharsamocha7** [comment]
* **#148** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/148?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @shaharsamocha7 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/148)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @ohad-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo-cairo/148#-OAWaDvn8f-Th1XnfKo3:-OAWaDvo1l45q6nE6jmT:bg7rjhn) (no related file):*
I think the `test_basic_cairo_air` become a bit slow.
Wonder if that could be related to my changes @ohad-starkware 

___

**Review by ohad-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/148)* status: 2 of 9 files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7)

*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo-cairo/148#-OAWaDvn8f-Th1XnfKo3:-OAWcdLv49wNLd2yBCK0:bww9pf8) (no related file):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I think the `test_basic_cairo_air` become a bit slow.
Wonder if that could be related to my changes @ohad-starkware
</blockquote></details>

discussed in dm, it's because of rangecheck 9_9

___
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/id_to_f252/prover.rs` line 85 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/148#-OAWcVSB0MdApSbi8JOT:-OAWcVSCDD1gOrEF_spD:b-qczgmo) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/5f747975d5f0592a1a2712096a16d7d4a09875c9/stwo_cairo_prover/crates/prover/src/components/memory/id_to_f252/prover.rs#L85)):*
> ```XML
>         &mut self,
>         tree_builder: &mut TreeBuilder<'_, '_, SimdBackend, Blake2sMerkleChannel>,
>         range_check_9_9_trace_generator: &mut RangeCheckClaimGenerator<2>,
> ```

this will be fixed if you rebase 



_Code quote:_
```XML
t RangeCheckClaimGenerator<2>
```
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/id_to_f252/prover.rs` line 126 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/148#-OAWcD2-9fl9RElM1UzM:-OAWcD2-9fl9RElM1UzN:b45h) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/5f747975d5f0592a1a2712096a16d7d4a09875c9/stwo_cairo_prover/crates/prover/src/components/memory/id_to_f252/prover.rs#L126)):*
> ```XML
>                 range_check_9_9_trace_generator.add_packed_m31(&[*val0, *val1]);
>             }
>         }
> ```





_Suggestion:_
```XML
        for (col0, col1) in ids_and_values[MEMORY_ID_SIZE..].iter().tuples() {
            for (val0, val1) in zip_eq(col0, col1) {
                range_check_9_9_trace_generator.add_packed_m31(&[*val0, *val1]);
            }
        }
```

**Review by ohad-starkware — APPROVED** [review]
:lgtm:

> Reviewed 7 of 9 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/148#-:-OAWi3V18Wo6tO_1do0V:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Pull request merged**
