### PR TITLE
Added vm-runner, wrapping cairo-vm and Stwo-adapter

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/91)

### CODE REVIEW

**Review by Alon-Ti — CHANGES_REQUESTED** [review]
> Reviewed 2 of 9 files at r1, 5 of 7 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/91)* status: all files reviewed, 5 unresolved discussions (waiting on @yuvalsw)

___
*[`stwo_cairo_prover/Cargo.toml` line 19 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/91#-O8WaE87-nd2PALXcnLF:-O8WaE87-nd2PALXcnLG:b-4jwpiq) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/d7cf3fa15735d57b2f2b078076dd0dfebf1c8a8b/stwo_cairo_prover/Cargo.toml#L19)):*
> ```TOML
> lto = true
> 
> # TODO(yg): remove, this is used for local debugging.
> ```

I guess you don't really want to push this, right? I think I remember Gilad had a solution for toggling and automatically fetching a dependent repository to a known location if you want something less temporary.
___
*[`stwo_cairo_prover/crates/prover/Cargo.toml` line 10 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/91#-O8Waekv0rgioO4gqMGG:-O8Waekv0rgioO4gqMGH:b-x9o3wk) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/d7cf3fa15735d57b2f2b078076dd0dfebf1c8a8b/stwo_cairo_prover/crates/prover/Cargo.toml#L10)):*
> ```TOML
> cairo-lang-casm = "2.7.1"
> cairo-vm.workspace = true
> chrono.workspace = "0.4.38"
> ```

Why `workspace`? (Or alternatively, why not `workspace = true` and version set above like the rest of them?)
___
*[`stwo_cairo_prover/crates/prover/src/input/plain.rs` line 55 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/91#-O8Wb4kTEwlYLDxHXi_m:-O8Wb4kTEwlYLDxHXi_n:b-r3lysf) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/d7cf3fa15735d57b2f2b078076dd0dfebf1c8a8b/stwo_cairo_prover/crates/prover/src/input/plain.rs#L55)):*
> ```XML
> pub fn print_now(description: &str) {
>     let now: DateTime<Local> = SystemTime::now().into();
>     println!("yg time {description}: {}", now.format("%d/%m/%Y %T"));
> ```

Use proper logging.
___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 81 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/91#-O8WdgZ_3hk4USaw0rUW:-O8WdgZ_3hk4USaw0rUX:b-awcokp) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/d7cf3fa15735d57b2f2b078076dd0dfebf1c8a8b/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L81)):*
> ```XML
> }
> 
> impl From<cairo_vm::vm::trace::trace_entry::RelocatedTraceEntry> for TraceEntry {
> ```

Import `RelocatedEntry` above so you don't have to repeat the long path.
___
*[`stwo_cairo_prover/crates/vm_runner/Cargo.toml` line 17 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/91#-O8WeCwu-J0JiiFLRG7g:-O8WeCwu-J0JiiFLRG7h:btacx5g) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/d7cf3fa15735d57b2f2b078076dd0dfebf1c8a8b/stwo_cairo_prover/crates/vm_runner/Cargo.toml#L17)):*
> ```TOML
> # Pin wasm-bindgen version to the version pinned by lambdaclass/cairo-vm/vm
> # TODO(yuval): remove the pin once the pinning in lambdaclass/cairo-vm/vm is removed.
> wasm-bindgen = { version = "= 0.2.92" }
> ```

Maybe you should have someone who actually knows Rust well look at this and see if there's a way to inherit the pinning in some less verbose way.

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/91)* status: all files reviewed, 5 unresolved discussions (waiting on @Alon-Ti)

___
*[`stwo_cairo_prover/Cargo.toml` line 19 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/91#-O8WaE87-nd2PALXcnLF:-O8Wmm3828fyezxpfN83:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/d7cf3fa15735d57b2f2b078076dd0dfebf1c8a8b/stwo_cairo_prover/Cargo.toml#L19)):*
<details><summary><i>Previously, Alon-Ti wrote…</i></summary><blockquote>

I guess you don't really want to push this, right? I think I remember Gilad had a solution for toggling and automatically fetching a dependent repository to a known location if you want something less temporary.
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/Cargo.toml` line 10 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/91#-O8Waekv0rgioO4gqMGG:-O8Wmz5DCj7HZl3Ph1LG:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/d7cf3fa15735d57b2f2b078076dd0dfebf1c8a8b/stwo_cairo_prover/crates/prover/Cargo.toml#L10)):*
<details><summary><i>Previously, Alon-Ti wrote…</i></summary><blockquote>

Why `workspace`? (Or alternatively, why not `workspace = true` and version set above like the rest of them?)
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/input/plain.rs` line 55 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/91#-O8Wb4kTEwlYLDxHXi_m:-O8Wn-7DE2laKbdecgAw:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/d7cf3fa15735d57b2f2b078076dd0dfebf1c8a8b/stwo_cairo_prover/crates/prover/src/input/plain.rs#L55)):*
<details><summary><i>Previously, Alon-Ti wrote…</i></summary><blockquote>

Use proper logging.
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 81 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/91#-O8WdgZ_3hk4USaw0rUW:-O8WoHx9CucdzznR3SEX:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/d7cf3fa15735d57b2f2b078076dd0dfebf1c8a8b/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L81)):*
<details><summary><i>Previously, Alon-Ti wrote…</i></summary><blockquote>

Import `RelocatedEntry` above so you don't have to repeat the long path.
</blockquote></details>

Done.

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/91)* status: 2 of 9 files reviewed, 5 unresolved discussions (waiting on @Alon-Ti)

___
*[`stwo_cairo_prover/crates/vm_runner/Cargo.toml` line 17 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/91#-O8WeCwu-J0JiiFLRG7g:-O8Wovax-JOqRkniibaF:bkxkghr) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/d7cf3fa15735d57b2f2b078076dd0dfebf1c8a8b/stwo_cairo_prover/crates/vm_runner/Cargo.toml#L17)):*
<details><summary><i>Previously, Alon-Ti wrote…</i></summary><blockquote>

Maybe you should have someone who actually knows Rust well look at this and see if there's a way to inherit the pinning in some less verbose way.
</blockquote></details>

I am ok with leaving as is for now, hoping we won't have to maintain it too much

**Review by Alon-Ti — COMMENTED** [review]
:lgtm:

> Reviewed 7 of 7 files at r4, 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/91#-:-O8XAFFpDkpX9gah8zjO:bnfp4nl)* status: 5 of 9 files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by Alon-Ti — APPROVED** [review]
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/91)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
