### PR TITLE
mem squish

### PR DESCRIPTION
**Pull request by ohad-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/241)

### CODE REVIEW

**Comment by ohad-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/241?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#241** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/241?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/241?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#237** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/237?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/241)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/component.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/241#-ODjuDEc-rDJaVzpOHPw:-ODjuDEc-rDJaVzpOHPx:bz74yys) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/114c97854e9ca27daa64a33530f0884f2be30dcc/stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/component.rs#L19)):*
> ```XML
> // during The merkle commitment and FRI, as this component is usually the tallest in the Cairo AIR.
> // TODO(Ohad): Change split to 8 after seq is implemented. NOTE: it is possible to split further
> // with an expansion trick similar to the one used in XOR. Investigate if it is worth it.
> ```

I don't like those changes as we probably need to change everything here again.
I think the correct approach is to use the EXPAND_BITS as we have in XOR.



_Code quote:_
```XML
// TODO(Ohad): Change split to 8 after seq is implemented. NOTE: it is possible to split further
// with an expansion trick similar to the one used in XOR. Investigate if it is worth it.
```
___
*[`stwo_cairo_prover/out.txt` line 1 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/241#-ODjsqAg0Dx4lzZ3vlUk:-ODjsqAg0Dx4lzZ3vlUl:b9fwg9o) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/114c97854e9ca27daa64a33530f0884f2be30dcc/stwo_cairo_prover/out.txt#L1)):*
> ```help
> 
> ```

Cool file but we don't need it in git :)

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/241)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/241#-ODjvBcA9U_6zI_geAQV:-ODjvBcA9U_6zI_geAQW:b-91gbi0) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/114c97854e9ca27daa64a33530f0884f2be30dcc/stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs#L83)):*
> ```XML
>         let next_multiple_of_16 = ((self.ids.len() + 15) >> 4) << 4;
>         self.ids.resize(next_multiple_of_16, 0);
>         self.multiplicities.resize(next_multiple_of_16, 0);
> ```

can we replace this by asserting that ids.len() >= 256?



_Code quote:_
```XML
        // Pad to a multiple of `N_LANES`.
        let next_multiple_of_16 = ((self.ids.len() + 15) >> 4) << 4;
        self.ids.resize(next_multiple_of_16, 0);
        self.multiplicities.resize(next_multiple_of_16, 0);
```
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/component.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/241#-ODjvgm84POAHuzQ0yJd:-ODjvgm84POAHuzQ0yJe:b-p9xdxl) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/114c97854e9ca27daa64a33530f0884f2be30dcc/stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/component.rs#L59)):*
> ```XML
>     fn evaluate<E: EvalAtRow>(&self, mut eval: E) -> E {
>         let address = eval.next_trace_mask();
>         for i in 0..SPLIT_SIZE {
> ```

I think SPLIT_SIZE should be generic



_Code quote:_
```XML
for i in 0..SPLIT_SIZE {
```

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/241)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @ohad-starkware and @shaharsamocha7)

___
*[`stwo_cairo_prover/out.txt` line 1 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/241#-ODjsqAg0Dx4lzZ3vlUk:-ODjuarI5D92ZVG6VirS:b32vhv) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/114c97854e9ca27daa64a33530f0884f2be30dcc/stwo_cairo_prover/out.txt#L1)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Cool file but we don't need it in git :)
</blockquote></details>

:(
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/component.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/241#-ODjuDEc-rDJaVzpOHPw:-OE9WTaO7sGOhXZI_LYQ:bewxupf) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/114c97854e9ca27daa64a33530f0884f2be30dcc/stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/component.rs#L19)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I don't like those changes as we probably need to change everything here again.
I think the correct approach is to use the EXPAND_BITS as we have in XOR.
</blockquote></details>

deleted comment
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/component.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/241#-ODjvgm84POAHuzQ0yJd:-OE9WbhYDlRvxVT-OWvo:b-aga1ut) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/114c97854e9ca27daa64a33530f0884f2be30dcc/stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/component.rs#L59)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I think SPLIT_SIZE should be generic
</blockquote></details>

does it matter? youll use this const as the generic parameter.
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/241#-ODjvBcA9U_6zI_geAQV:-OE9XaGE6V8ebPhkDiwM:b-nssagp) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/114c97854e9ca27daa64a33530f0884f2be30dcc/stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs#L83)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

can we replace this by asserting that ids.len() >= 256?
</blockquote></details>

im doing this to avoid dealing with .remainder

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/241)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/241#-ODjvBcA9U_6zI_geAQV:-OE9o8UYBYjXCZhYQ4tm:bechob7) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/114c97854e9ca27daa64a33530f0884f2be30dcc/stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs#L83)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

im doing this to avoid dealing with .remainder
</blockquote></details>

Will it work if the memory size < SPLIT_SIZE * N_LANES?
Maybe we can just assert that
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs` line 81 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/241#-OE9oMJ41VgJBtJ85lg6:-OE9oMJ57GWIdEKt2JCf:bwm6zej) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c526108fd9323ed54cf303ea00e7b29554efc462/stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs#L81)):*
> ```XML
> 
>         // Pad to a multiple of `N_LANES`.
>         let next_multiple_of_16 = ((self.ids.len() + 15) >> 4) << 4;
> ```

I think it will be more clear if you call div_ceil here



_Code quote:_
```XML
((self.ids.len() + 15) >> 4) << 4
```
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/component.rs` line 82 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/241#-OE9nxHJEujqH7PDzGx2:-OE9nxHK71trdCgLu0w1:b-dw5c67) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c526108fd9323ed54cf303ea00e7b29554efc462/stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/component.rs#L82)):*
> ```XML
>         let preprocessed_log_sizes = vec![self.log_size];
>         let trace_log_sizes = vec![self.log_size; N_TRACE_COLUMNS];
>         let interaction_log_sizes = vec![self.log_size; SECURE_EXTENSION_DEGREE * SPLIT_SIZE];
> ```

Do we want to combine the lookups here?



_Code quote:_
```XML
let interaction_log_sizes = vec![self.log_size; SECURE_EXTENSION_DEGREE * SPLIT_SIZE];
```

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/241)* status: all files reviewed, 6 unresolved discussions (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs` line 97 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/241#-OE9qn-q-drV-73y8Ckq:-OE9qn-q-drV-73y8Ckr:b-l6mkjh) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c526108fd9323ed54cf303ea00e7b29554efc462/stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs#L97)):*
> ```XML
>         let inc =
>             PackedM31::from_array(std::array::from_fn(|i| M31::from_u32_unchecked((i) as u32)));
>         for i in 0..packed_size {
> ```

rename



_Suggestion:_
```XML
for i in 0..n_packed_rows
```
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs` line 108 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/241#-OE9rZmT7F6vPwun9cd6:-OE9rZmT7F6vPwun9cd7:b-dizuiv) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c526108fd9323ed54cf303ea00e7b29554efc462/stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs#L108)):*
> ```XML
>             trace[1 + chunk_idx * N_ID_AND_MULT_COLUMNS_PER_CHUNK].data[i] = id;
>             trace[2 + chunk_idx * N_ID_AND_MULT_COLUMNS_PER_CHUNK].data[i] = multiplicity;
>         }
> ```

Instead of this logic, couldn't you create the columns using `from_iter, take` funcs?



_Code quote:_
```XML
        for (i, (id, multiplicity)) in zip(id_it, multiplicities_it).enumerate() {
            let chunk_idx = i / packed_size;
            let i = i % packed_size;
            trace[1 + chunk_idx * N_ID_AND_MULT_COLUMNS_PER_CHUNK].data[i] = id;
            trace[2 + chunk_idx * N_ID_AND_MULT_COLUMNS_PER_CHUNK].data[i] = multiplicity;
        }
```
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs` line 138 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/241#-OE9rwVABko2bd9q_GWP:-OE9rwVABko2bd9q_GWQ:b4bj506) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c526108fd9323ed54cf303ea00e7b29554efc462/stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs#L138)):*
> ```XML
> 
> pub struct InteractionClaimGenerator {
>     pub addresses: Vec<PackedM31>,
> ```

maybe comment that these are not all the addresses, just those up to SPLIT_SIZE



_Code quote:_
```XML
pub addresses: Vec<PackedM31>,
```

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/241)* status: all files reviewed, 6 unresolved discussions (waiting on @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/component.rs` line 82 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/241#-OE9nxHJEujqH7PDzGx2:-OE9wVEQEfXyHsBxAQeE:b-em26ly) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c526108fd9323ed54cf303ea00e7b29554efc462/stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/component.rs#L82)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Do we want to combine the lookups here?
</blockquote></details>

ill have a pr for that shortly
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/241#-ODjvBcA9U_6zI_geAQV:-OE9x2Gr8yyjP1rEAESi:b-poedqd) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/114c97854e9ca27daa64a33530f0884f2be30dcc/stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs#L83)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Will it work if the memory size < SPLIT_SIZE * N_LANES?
Maybe we can just assert that
</blockquote></details>

I think test_memory_trace_prover tests that
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs` line 81 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/241#-OE9oMJ41VgJBtJ85lg6:-OE9x-4VCVi4ad0YCHmZ:bb7f2mf) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c526108fd9323ed54cf303ea00e7b29554efc462/stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs#L81)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I think it will be more clear if you call div_ceil here
</blockquote></details>

done
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs` line 97 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/241#-OE9qn-q-drV-73y8Ckq:-OE9xcEb87IvhbxIFba7:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c526108fd9323ed54cf303ea00e7b29554efc462/stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs#L97)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

rename
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs` line 108 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/241#-OE9rZmT7F6vPwun9cd6:-OEA2FnD4lTmofUmKF2j:b-rh6y9q) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c526108fd9323ed54cf303ea00e7b29554efc462/stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs#L108)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Instead of this logic, couldn't you create the columns using `from_iter, take` funcs?
</blockquote></details>

no, im because im padding every column instead of padding only the last
wdyt?
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs` line 138 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/241#-OE9rwVABko2bd9q_GWP:-OEA34fu-RyPeEKlLYL7:bq44nme) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c526108fd9323ed54cf303ea00e7b29554efc462/stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs#L138)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

maybe comment that these are not all the addresses, just those up to SPLIT_SIZE
</blockquote></details>

suggestion?

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/241)* status: all files reviewed, 3 unresolved discussions (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs` line 97 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/241#-OE9qn-q-drV-73y8Ckq:-OEDOIBl783-9IFVmm8L:b-6b0jxv) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c526108fd9323ed54cf303ea00e7b29554efc462/stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs#L97)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

forgot to push or didn't change?
packed_size stand for 16 so it is confusing IMO
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs` line 108 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/241#-OE9rZmT7F6vPwun9cd6:-OEDP8gq9fomJLlyFHc0:bn3ygx7) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c526108fd9323ed54cf303ea00e7b29554efc462/stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs#L108)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

no, im because im padding every column instead of padding only the last
wdyt?
</blockquote></details>

Can't we only pad the last column? I think it will be more straightforward, no?
Let me know what you think
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs` line 138 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/241#-OE9rwVABko2bd9q_GWP:-OEDPXG91B_T1G0DuJxW:b-fygsb8) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c526108fd9323ed54cf303ea00e7b29554efc462/stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs#L138)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

suggestion?
</blockquote></details>

Ok forget it as we are going to discard this anyway, right?

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/241)* status: all files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs` line 97 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/241#-OE9qn-q-drV-73y8Ckq:-OEDddB_0S-tzoRjtiHI:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c526108fd9323ed54cf303ea00e7b29554efc462/stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs#L97)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

forgot to push or didn't change?
packed_size stand for 16 so it is confusing IMO
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs` line 108 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/241#-OE9rZmT7F6vPwun9cd6:-OEDdpp90b0FP-xVAOmw:br9dql9) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c526108fd9323ed54cf303ea00e7b29554efc462/stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs#L108)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can't we only pad the last column? I think it will be more straightforward, no?
Let me know what you think
</blockquote></details>

in the take approache I will have more padding in the tail, because the 0s will have to be generated by the iterator
in the current approach, I'm taking a zeroed vector and writing where I want
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs` line 138 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/241#-OE9rwVABko2bd9q_GWP:-OEDeEMi6nxcrRqHrRNw:b2nign6) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c526108fd9323ed54cf303ea00e7b29554efc462/stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs#L138)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Ok forget it as we are going to discard this anyway, right?
</blockquote></details>

yes

**Review by shaharsamocha7 — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/241)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @ohad-starkware)

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/241)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs` line 108 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/241#-OE9rZmT7F6vPwun9cd6:-OEEqblt2lutjGz8WfAJ:b-auzrlc) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c526108fd9323ed54cf303ea00e7b29554efc462/stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs#L108)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

in the take approache I will have more padding in the tail, because the 0s will have to be generated by the iterator
in the current approach, I'm taking a zeroed vector and writing where I want
</blockquote></details>

I'm ok with that impl, but I think it's worth a comment about the structure of the trace
I.e. comment that each split takes exactly self.ids / SPLIT_SIZE values and the rest of the column is padded

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/241)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs` line 108 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/241#-OE9rZmT7F6vPwun9cd6:-OEFK5qJ7KSXlioNSLh7:bb7f2mf) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c526108fd9323ed54cf303ea00e7b29554efc462/stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs#L108)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I'm ok with that impl, but I think it's worth a comment about the structure of the trace
I.e. comment that each split takes exactly self.ids / SPLIT_SIZE values and the rest of the column is padded
</blockquote></details>

done

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/241)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/component.rs` line 28 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/241#-OEIg7as32BxziM348_m:-OEIg7at0OujqL7yVEv7:b45h) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f0adec09156aa79b9690d3a5cfb17c183f5587eb/stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/component.rs#L28)):*
> ```XML
> /// ID1 = [id3, id4, id5, 0]
> /// ID2 = [id6, id7, id8, 0]
> /// ID3 = [id9, id10, 0, 0]
> ```





_Suggestion:_
```XML

/// 1. The ID and Multiplicity vectors are split to 'N_SPLIT_CHUNKS' chunks of size
///    `ids.len()` / `N_SPLIT_CHUNKS`.
/// 2. The chunks are padded with 0s to the next power of 2.
/// 
/// #  Example
/// ID = [id0..id10], N_SPLIT_CHUNKS = 4
///
/// ID0 = [id0, id1, id2, 0]
/// ID1 = [id3, id4, id5, 0]
/// ID2 = [id6, id7, id8, 0]
/// ID3 = [id9, id10, 0, 0]
```

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/241#-:-OEIi9gQ4IYMhBG4Hzo5:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @ohad-starkware)

**Comment by ohad-starkware** [comment]
### Merge activity

* **Dec 17, 4:12 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/241).

**Pull request merged**
