### PR TITLE
add tests for big mul and add

### PR DESCRIPTION
**Pull request by Stavbe**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/232)

### CODE REVIEW

**Review by ohad-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/232)* status: all files reviewed, 4 unresolved discussions (waiting on @shaharsamocha7 and @Stavbe)

___
*[`stwo_cairo_prover/crates/prover/src/lib.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/232#-OD_82va8USFy3VRyhWI:-OD_82va8USFy3VRyhWJ:b1t8ir2) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/37f649bb247518029bb9d5dd9ecdb3913846e3d4/stwo_cairo_prover/crates/prover/src/lib.rs#L10)):*
> ```XML
> pub mod input;
> pub mod relations;
> ```

can you add a todo to move all these tests under 'input'?
___
*[`stwo_cairo_prover/crates/prover/src/lib.rs` line 182 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/232#-OD_6vwh43Fcffz0he-D:-OD_6vwh43Fcffz0he-E:bf4lrte) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/37f649bb247518029bb9d5dd9ecdb3913846e3d4/stwo_cairo_prover/crates/prover/src/lib.rs#L182)):*
> ```XML
>         let instructions = casm! {
>             call rel 2;
>             [ap] = 134217725, ap++;
> ```

document these numbers again here, so the test is self sufficient 



_Code quote:_
```XML
134217725
```
___
*[`stwo_cairo_prover/crates/prover/src/lib.rs` line 229 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/232#-OD_8DZW9mf2QRH3D0jQ:-OD_8DZW9mf2QRH3D0jR:bx5og8q) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/37f649bb247518029bb9d5dd9ecdb3913846e3d4/stwo_cairo_prover/crates/prover/src/lib.rs#L229)):*
> ```XML
>     #[ignore = "mul small opcode is not implemented yet"]
>     #[test]
>     fn test_mul_small() {
> ```

can you do exactly 2**27 to test edge cases?
___
*[`stwo_cairo_prover/crates/prover/src/lib.rs` line 262 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/232#-OD_8AGJ8kX345bIQT03:-OD_8AGJ8kX345bIQT04:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/37f649bb247518029bb9d5dd9ecdb3913846e3d4/stwo_cairo_prover/crates/prover/src/lib.rs#L262)):*
> ```XML
>         .instructions;
> 
>         let inp = input_from_plain_casm(instructions, false);
> ```





_Suggestion:_
```XML
input
```

**Review by Stavbe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/232)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @ohad-starkware and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/lib.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/232#-OD_82va8USFy3VRyhWI:-OD_J6q6DFw7BMX43dhW:b-kkqtvx) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/37f649bb247518029bb9d5dd9ecdb3913846e3d4/stwo_cairo_prover/crates/prover/src/lib.rs#L10)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

can you add a todo to move all these tests under 'input'?
</blockquote></details>

Not sure what does it mean? Your todo or mine?
___
*[`stwo_cairo_prover/crates/prover/src/lib.rs` line 182 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/232#-OD_6vwh43Fcffz0he-D:-OD_R0Ec4W5YtgfUjnNF:beomvm4) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/37f649bb247518029bb9d5dd9ecdb3913846e3d4/stwo_cairo_prover/crates/prover/src/lib.rs#L182)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

document these numbers again here, so the test is self sufficient
</blockquote></details>

Document the result
___
*[`stwo_cairo_prover/crates/prover/src/lib.rs` line 229 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/232#-OD_8DZW9mf2QRH3D0jQ:-OD_R2mPEqB7H2EyFlPn:b2nhstf) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/37f649bb247518029bb9d5dd9ecdb3913846e3d4/stwo_cairo_prover/crates/prover/src/lib.rs#L229)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

can you do exactly 2**27 to test edge cases?
</blockquote></details>

Yap
___
*[`stwo_cairo_prover/crates/prover/src/lib.rs` line 262 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/232#-OD_8AGJ8kX345bIQT03:-OD_M07H5VLRBan5k7Ee:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/37f649bb247518029bb9d5dd9ecdb3913846e3d4/stwo_cairo_prover/crates/prover/src/lib.rs#L262)):*
> ```XML
>         .instructions;
> 
>         let inp = input_from_plain_casm(instructions, false);
> ```

Done.

**Review by ohad-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/232)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @shaharsamocha7 and @Stavbe)

___
*[`stwo_cairo_prover/crates/prover/src/lib.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/232#-OD_82va8USFy3VRyhWI:-OD_uiIdBAmOZc7HiB4V:b-43oda5) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/37f649bb247518029bb9d5dd9ecdb3913846e3d4/stwo_cairo_prover/crates/prover/src/lib.rs#L10)):*
<details><summary><i>Previously, Stavbe wrote…</i></summary><blockquote>

Not sure what does it mean? Your todo or mine?
</blockquote></details>

you choose 
___
*[`stwo_cairo_prover/crates/prover/src/lib.rs` line 186 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/232#-OD_v73p1MgC_PHDQzb_:-OD_v73qDlcrFADv1oL3:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/83091c20d6da3b0bfd5409d77fd94730ac485cd0/stwo_cairo_prover/crates/prover/src/lib.rs#L186)):*
> ```XML
>             // The sum is 2^27-1 which is the maximal value for a small number.
>             [ap] = [fp] + [ap-1], ap++;
>             // The sum is 2^27-1 which is the maximal value for a small number.
> ```





_Suggestion:_
```XML
2^27-1 is the maximal value of a small number.
```
___
*[`stwo_cairo_prover/crates/prover/src/lib.rs` line 236 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/232#-OD_vFch9Qz265hg63_B:-OD_vFch9Qz265hg63_C:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/83091c20d6da3b0bfd5409d77fd94730ac485cd0/stwo_cairo_prover/crates/prover/src/lib.rs#L236)):*
> ```XML
>             [ap] =  7, ap++;
>             [ap] = 19173961, ap++;
>             // The multiplication result is 2^27 - 1 which is the maximal value for a small number.
> ```





_Suggestion:_
```XML
The product is
```

**Review by Stavbe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/232)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @ohad-starkware and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/lib.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/232#-OD_82va8USFy3VRyhWI:-ODa3Exm5_3O-zByMxGb:b7oae13) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/37f649bb247518029bb9d5dd9ecdb3913846e3d4/stwo_cairo_prover/crates/prover/src/lib.rs#L10)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

you choose
</blockquote></details>

Do you want to mv lib as a file to the input dir? Can do in this PR
___
*[`stwo_cairo_prover/crates/prover/src/lib.rs` line 236 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/232#-OD_vFch9Qz265hg63_B:-ODa543R0qbY1Dao_xM2:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/83091c20d6da3b0bfd5409d77fd94730ac485cd0/stwo_cairo_prover/crates/prover/src/lib.rs#L236)):*
> ```XML
>             [ap] =  7, ap++;
>             [ap] = 19173961, ap++;
>             // The multiplication result is 2^27 - 1 which is the maximal value for a small number.
> ```

Done.

**Review by ohad-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/232)* status: 0 of 3 files reviewed, 8 unresolved discussions (waiting on @shaharsamocha7 and @Stavbe)

___
*[`stwo_cairo_prover/crates/prover/src/lib.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/232#-OD_82va8USFy3VRyhWI:-ODaG9pNBZUrTuMfjqQx:bgc41vs) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/37f649bb247518029bb9d5dd9ecdb3913846e3d4/stwo_cairo_prover/crates/prover/src/lib.rs#L10)):*
<details><summary><i>Previously, Stavbe wrote…</i></summary><blockquote>

Do you want to mv lib as a file to the input dir? Can do in this PR
</blockquote></details>

only move the tests to where they should be
___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 12 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/232#-ODaHQwpBYQ8Fd8K0tuH:-ODaHQwpBYQ8Fd8K0tuI:b-9gy1i1) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/9ed3300ade23a5970f64aa27a5d94c52df122c70/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L12)):*
> ```XML
> const SMALL_ADD_MIN_VALUE: i32 = -(2_i32.pow(27));
> 
> // The range of small values for the mul opcode is usighned 15 bits.
> ```

and unsigned*



_Suggestion:_
```XML
 Small mul operands are 15 bits.
```
___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 13 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/232#-ODaHwtEED48OHtGME2u:-ODaHwtEED48OHtGME2v:bb7ong0) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/9ed3300ade23a5970f64aa27a5d94c52df122c70/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L13)):*
> ```XML
> 
> // The range of small values for the mul opcode is usighned 15 bits.
> const SMALL_MUL_MAX_VALUE: i32 = 2_i32.pow(15) - 1;
> ```

u32?
___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 613 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/232#-ODaJcFh5FKuckKCv15T:-ODaJcFh5FKuckKCv15U:b-9sy5bl) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/9ed3300ade23a5970f64aa27a5d94c52df122c70/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L613)):*
> ```XML
>     }
> }
> ```

maybe define 
fn is_within_range(val: MemoryValue, min: i128, max: i128) -> booll }{}
and use it for add and mull with their respective bounds
___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 616 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/232#-ODaJQbw0QXttA9o299E:-ODaJQbw0QXttA9o299F:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/9ed3300ade23a5970f64aa27a5d94c52df122c70/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L616)):*
> ```XML
> // Returns 'true' if all the operands are within the range of [-2^27, 2^27 - 1].
> fn are_small_add_operands(dst: MemoryValue, op0: MemoryValue, op1: MemoryValue) -> bool {
>     is_small_add(dst) && is_small_add(op0) && is_small_add(op1)
> ```





_Suggestion:_
```XML
[dst, op0, op1].iter().all(|val| is_within_range(*val,add_lower,add_higher))
```
___
*[`stwo_cairo_prover/crates/prover/src/lib.rs` line 185 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/232#-ODaGOPl0fuNkNPYrpfH:-ODaGOPl0fuNkNPYrpfI:bko593j) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/9ed3300ade23a5970f64aa27a5d94c52df122c70/stwo_cairo_prover/crates/prover/src/lib.rs#L185)):*
> ```XML
>             [ap] = 134217725, ap++;
>             [ap] = 2, ap++;
>             // 134217725 + 2= 2^27-1 is the maximal sum for a small add.
> ```

maybe thats enough, if it's in the same file as where the constants are defined then it should be Ok



_Suggestion:_
```XML
// 134217725 + 2 = 2^27-1.
```
___
*[`stwo_cairo_prover/crates/prover/src/lib.rs` line 187 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/232#-ODaGYP-2JFnwEtX5R8W:-ODaGYP-2JFnwEtX5R8X:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/9ed3300ade23a5970f64aa27a5d94c52df122c70/stwo_cairo_prover/crates/prover/src/lib.rs#L187)):*
> ```XML
>             // 134217725 + 2= 2^27-1 is the maximal sum for a small add.
>             [ap] = [fp] + [ap-1], ap++;
>             // 134217724 + 3 = 2^27-1 is the maximal sum for a small add.
> ```





_Suggestion:_
```XML
/ 134217724 + 3 = 2^27-1.
```
___
*[`stwo_cairo_prover/crates/prover/src/lib.rs` line 211 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/232#-ODaGazLCzbkGQt9BA-R:-ODaGazLCzbkGQt9BA-S:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/9ed3300ade23a5970f64aa27a5d94c52df122c70/stwo_cairo_prover/crates/prover/src/lib.rs#L211)):*
> ```XML
>             [ap] = 134217725, ap++;
>             [ap] = 3, ap++;
>             // 134217725 + 3 = is 2^27 is the minimal sum value for a big add.
> ```


___
*[`stwo_cairo_prover/crates/prover/src/lib.rs` line 235 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/232#-ODaGiJu9XPW46m-iJ4h:-ODaGiJu9XPW46m-iJ4i:bbn2wla) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/9ed3300ade23a5970f64aa27a5d94c52df122c70/stwo_cairo_prover/crates/prover/src/lib.rs#L235)):*
> ```XML
>     fn test_mul_small() {
>         let instructions = casm! {
>             // 2^15-1 is the maximal factor value for a small mul.
> ```

not sure this is true, 2^17 * 1 is  small mul? 



_Code quote:_
```XML
 2^15-1 is the maximal factor value for a small mul.
```

**Review by Stavbe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/232)* status: 0 of 3 files reviewed, 8 unresolved discussions (waiting on @ohad-starkware and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/lib.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/232#-OD_82va8USFy3VRyhWI:-ODai0ChAm_qLyhPaVVn:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/37f649bb247518029bb9d5dd9ecdb3913846e3d4/stwo_cairo_prover/crates/prover/src/lib.rs#L10)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

only move the tests to where they should be
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/lib.rs` line 235 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/232#-ODaGiJu9XPW46m-iJ4h:-ODaf14G6yHEyGb0NxnD:bgq9pf0) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/9ed3300ade23a5970f64aa27a5d94c52df122c70/stwo_cairo_prover/crates/prover/src/lib.rs#L235)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

not sure this is true, 2^17 * 1 is  small mul?
</blockquote></details>

No, it's big:
currenly: is_small = true : multiplication factors are in the range \[0, 2^15-1\].
Will be changed soon (to avoid range check3)
___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 13 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/232#-ODaHwtEED48OHtGME2u:-ODai7yHAodpMG3cRdxO:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/9ed3300ade23a5970f64aa27a5d94c52df122c70/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L13)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

u32?
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 613 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/232#-ODaJcFh5FKuckKCv15T:-ODahQOCCEibBcLoOOwU:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/9ed3300ade23a5970f64aa27a5d94c52df122c70/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L613)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

maybe define 
fn is_within_range(val: MemoryValue, min: i128, max: i128) -> booll }{}
and use it for add and mull with their respective bounds
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 616 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/232#-ODaJQbw0QXttA9o299E:-ODahOGAB113caW69UxT:bb7lbs2) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/9ed3300ade23a5970f64aa27a5d94c52df122c70/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L616)):*
> ```XML
> // Returns 'true' if all the operands are within the range of [-2^27, 2^27 - 1].
> fn are_small_add_operands(dst: MemoryValue, op0: MemoryValue, op1: MemoryValue) -> bool {
>     is_small_add(dst) && is_small_add(op0) && is_small_add(op1)
> ```

nice

**Review by ohad-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/232#-:-ODaqlyv8ZeGeudXYhvO:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7 and @Stavbe)

___
*[`stwo_cairo_prover/crates/prover/src/lib.rs` line 235 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/232#-ODaGiJu9XPW46m-iJ4h:-ODaqhxU5WwpAN65_iNc:b-3dqjom) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/9ed3300ade23a5970f64aa27a5d94c52df122c70/stwo_cairo_prover/crates/prover/src/lib.rs#L235)):*
<details><summary><i>Previously, Stavbe wrote…</i></summary><blockquote>

No, it's big:
currenly: is_small = true : multiplication factors are in the range \[0, 2^15-1\].
Will be changed soon (to avoid range check3)
</blockquote></details>

nice ok

**Review by Stavbe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/232)* status: all files reviewed, 1 unresolved discussion (waiting on @ohad-starkware and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/lib.rs` line 235 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/232#-ODaGiJu9XPW46m-iJ4h:-ODb0Gun1wXKE-6TDTNr:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/9ed3300ade23a5970f64aa27a5d94c52df122c70/stwo_cairo_prover/crates/prover/src/lib.rs#L235)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

nice ok
</blockquote></details>

Done.

**Review by ohad-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/232)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Pull request merged**
