### PR TITLE
Renamed instructions to components in Adapter

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/111)

### CODE REVIEW

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/111)* status: 7 of 8 files reviewed, 3 unresolved discussions (waiting on @yuvalsw)

*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo-cairo/111#-O9ctLSu6ChUs16eBPZR:-O9ctLSv82eZjr_N-AB6:bjjnm2p) (no related file):*
About that naming:
All Cairo instructions/ builtins have a corresponding component.
There are also components that are not related to an instruction (e.g. blake_round component)

WDYT about vm_components?

___
___
*[`stwo_cairo_prover/crates/adapted_prover/src/main.rs` line 66 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/111#-O9cu-ZGA_4sR-id-WLM:-O9cu-ZGA_4sR-id-WLN:bj6gnc3) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/0d3d37f7d93568ee6a1c32056527cd2c63c8c153/stwo_cairo_prover/crates/adapted_prover/src/main.rs#L66)):*
> ```XML
>         import_from_vm_output(args.pub_json.as_path(), args.priv_json.as_path())?;
> 
>     let component_counts = vm_output.components_usage.counts();
> ```

Re my comment above, this won't contain all the components.



_Code quote:_
```XML
let component_counts = vm_output.components_usage.counts();
```
___
*[`stwo_cairo_prover/crates/prover/src/input/components_usage.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/111#-O9cuaOSD0-f2DCIitR6:-O9cuaOSD0-f2DCIitR7:b6noue1) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/0d3d37f7d93568ee6a1c32056527cd2c63c8c153/stwo_cairo_prover/crates/prover/src/input/components_usage.rs#L31)):*
> ```XML
> /// no ap++ (0=false). Note: for the flag "fp/ap", true means fp-based and false means ap-based.
> #[derive(Debug, Default)]
> pub struct ComponentsUsage {
> ```

WDYT?
I don't think the word usage fits here well



_Suggestion:_
```XML
pub struct VMComponents
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/111)* status: 7 of 8 files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7)

*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo-cairo/111#-O9ctLSu6ChUs16eBPZR:-O9nWogu53U9HnWr9111:b-smsd7y) (no related file):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

About that naming:
All Cairo instructions/ builtins have a corresponding component.
There are also components that are not related to an instruction (e.g. blake_round component)

WDYT about vm_components?
</blockquote></details>

You suggest vm_components to represent the set of components (out of all) that represent instructions?
As in external components (as opposed to internal ones)?
I am ok with it, or with external/internal (I got from David there is no overlap) - what do you prefer?

___
___
*[`stwo_cairo_prover/crates/adapted_prover/src/main.rs` line 66 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/111#-O9cu-ZGA_4sR-id-WLM:-O9nWh316xvNEa6Za9xO:b-coq03e) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/0d3d37f7d93568ee6a1c32056527cd2c63c8c153/stwo_cairo_prover/crates/adapted_prover/src/main.rs#L66)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Re my comment above, this won't contain all the components.
</blockquote></details>

Do we need the list of all?
If you mention it to support the previous comment - ack.
___
*[`stwo_cairo_prover/crates/prover/src/input/components_usage.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/111#-O9cuaOSD0-f2DCIitR6:-O9nXiOE6G2uRoqe1Y2q:b-hgllff) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/0d3d37f7d93568ee6a1c32056527cd2c63c8c153/stwo_cairo_prover/crates/prover/src/input/components_usage.rs#L31)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

WDYT?
I don't think the word usage fits here well
</blockquote></details>

The whole point of this struct is to collect the usages of each component/vm-component. See the comment too. Don't you agree with the description?
IMO just Components/VMComponents may be thought of the list of all (vm) components or something.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/111)* status: 5 of 8 files reviewed, 3 unresolved discussions (waiting on @yuvalsw)

*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo-cairo/111#-O9ctLSu6ChUs16eBPZR:-OAGzF4-0SfPQ071zxNs:bejmmg7) (no related file):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

You suggest vm_components to represent the set of components (out of all) that represent instructions?
As in external components (as opposed to internal ones)?
I am ok with it, or with external/internal (I got from David there is no overlap) - what do you prefer?
</blockquote></details>

I less like external/internal
Will those also include the builtin components?
If not maybe CasmOpcodes is also an option

Anyway was just mentioned it, your call

___
___
*[`stwo_cairo_prover/crates/adapted_prover/src/main.rs` line 66 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/111#-O9cu-ZGA_4sR-id-WLM:-OAGzk2B1OC9KzU4vj8-:b-ilfoyo) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/0d3d37f7d93568ee6a1c32056527cd2c63c8c153/stwo_cairo_prover/crates/adapted_prover/src/main.rs#L66)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Do we need the list of all?
If you mention it to support the previous comment - ack.
</blockquote></details>

Ack.
I do we need a good naming here, because it can be confusing
___
*[`stwo_cairo_prover/crates/prover/src/input/components_usage.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/111#-O9cuaOSD0-f2DCIitR6:-OAH-AJf0CjKEH1v8Gl6:bes0o2b) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/0d3d37f7d93568ee6a1c32056527cd2c63c8c153/stwo_cairo_prover/crates/prover/src/input/components_usage.rs#L31)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

The whole point of this struct is to collect the usages of each component/vm-component. See the comment too. Don't you agree with the description?
IMO just Components/VMComponents may be thought of the list of all (vm) components or something.
</blockquote></details>

I'm confused because this struct stores the actual VmState for each opcode and not just a usize with the number of usages, what am I missing?

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/111)* status: 5 of 8 files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7)

*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo-cairo/111#-O9ctLSu6ChUs16eBPZR:-OAHLp0q04IVIZZgwVkg:b-896fix) (no related file):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I less like external/internal
Will those also include the builtin components?
If not maybe CasmOpcodes is also an option

Anyway was just mentioned it, your call
</blockquote></details>

Done.

___
___
*[`stwo_cairo_prover/crates/prover/src/input/components_usage.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/111#-O9cuaOSD0-f2DCIitR6:-OAHFxYL4SB1ioFIuGJk:b-8ct8k6) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/0d3d37f7d93568ee6a1c32056527cd2c63c8c153/stwo_cairo_prover/crates/prover/src/input/components_usage.rs#L31)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I'm confused because this struct stores the actual VmState for each opcode and not just a usize with the number of usages, what am I missing?
</blockquote></details>

Right, the one for the number of usages in ComponentsCount. This is the struct for collecting the actual usage (that is, with details). Tried to make it clearer in the docs

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/111#-:-OAHlBrHAY_Yu_DxGwse:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by shaharsamocha7 — APPROVED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/111)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
