### PR TITLE
update verify generic and ret from auto gen

### PR DESCRIPTION
**Pull request by ohad-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/214)

### CODE REVIEW

**Comment by ohad-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/214?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#214** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/214?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/214?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#209** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/209?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#208** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/208?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#207** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/207?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#206** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/206?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Comment by ilyalesokhin-starkware** [comment]
*[`stwo_cairo_prover/crates/prover/src/components/verify_instruction/prover.rs` line 138 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/214#-OD1NGqO6WONF3ZrMw_w:-OD1NGqO6WONF3ZrMw_x:bppxsjm) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/943d0faa3a62742b95ea1e4506e60801eaccd7ae/stwo_cairo_prover/crates/prover/src/components/verify_instruction/prover.rs#L138)):*
> ```XML
>     }
> 
>     fn bit_reverse_coset_to_circle_domain_order(&mut self) {
> ```

what does this do?



_Code quote:_
```XML
bit_reverse_coset_to_circle_domain_order
```

**Comment by ilyalesokhin-starkware** [comment]
*[`stwo_cairo_prover/crates/prover/src/components/verify_instruction/prover.rs` line 138 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/214#-OD1NGqO6WONF3ZrMw_w:-OD1OEK88vs21EsOyy06:b-kl43c0) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/943d0faa3a62742b95ea1e4506e60801eaccd7ae/stwo_cairo_prover/crates/prover/src/components/verify_instruction/prover.rs#L138)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

what does this do?
</blockquote></details>

document

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 7 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/214)* status: 7 of 10 files reviewed, 1 unresolved discussion (waiting on @ohad-starkware)

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/214)* status: 5 of 10 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/components/verify_instruction/prover.rs` line 138 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/214#-OD1NGqO6WONF3ZrMw_w:-OD1tCPaALkVBR9U2ckb:b9c3164) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/943d0faa3a62742b95ea1e4506e60801eaccd7ae/stwo_cairo_prover/crates/prover/src/components/verify_instruction/prover.rs#L138)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

document
</blockquote></details>

I documented after if need_padding
this is auto gen code, so my question is wether this should be auto generated, IMO yes.
lmk if the doc is clear and then ill add it to auto gen

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/214)* status: 7 of 10 files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware and @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/components/verify_instruction/prover.rs` line 60 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/214#-OD5-qUECuiYfSTirYmw:-OD5-qUF-sUlPft4co1X:bwnwonm) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/5c42ce09c4b4b383b4a54720f1436794cbbf8bc8/stwo_cairo_prover/crates/prover/src/components/verify_instruction/prover.rs#L60)):*
> ```XML
>             // permutes the natural ordered values to the native trace order. So as to make the
>             // 'neighbor' function evaluate to the next natural index after permutation.
>             // Used when padding is needed, to make the partial sum mechanism work.
> ```

We are going to have this comment in all the opcodes?



_Code quote:_
```XML
            // permutes the natural ordered values to the native trace order. So as to make the
            // 'neighbor' function evaluate to the next natural index after permutation.
            // Used when padding is needed, to make the partial sum mechanism work.
```
___
*[`stwo_cairo_prover/crates/prover/src/components/verify_instruction/prover.rs` line 308 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/214#-OD50F0V48MPY3pKfCYl:-OD50F0V48MPY3pKfCYm:b-68nuh6) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/5c42ce09c4b4b383b4a54720f1436794cbbf8bc8/stwo_cairo_prover/crates/prover/src/components/verify_instruction/prover.rs#L308)):*
> ```XML
>             lookup_data.rangecheck_4_3[0].push([offset2_low_col24, offset2_high_col26]);
> 
>             // encode_flags.
> ```

Why no code was generated here?



_Code quote:_
```XML
// encode_flags.
```
___
*[`stwo_cairo_prover/crates/prover/src/components/ret_opcode/component.rs` line 23 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/214#-OD5-4Mj0qNuRPaaagMh:-OD5-4Mj0qNuRPaaagMi:bap8abf) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/5c42ce09c4b4b383b4a54720f1436794cbbf8bc8/stwo_cairo_prover/crates/prover/src/components/ret_opcode/component.rs#L23)):*
> ```XML
>     pub memoryidtobig_lookup_elements: relations::MemoryIdToBig,
>     pub opcodes_lookup_elements: relations::Opcodes,
>     pub verifyinstruction_lookup_elements: relations::VerifyInstruction,
> ```

Also, why the order was changed?



_Suggestion:_
```XML
pub verify_instruction_lookup_elements: relations::VerifyInstruction,
```
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/air.rs` line 380 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/214#-OD4zLPD1E2juZFgCsiI:-OD4zLPD1E2juZFgCsiJ:bcak50y) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/5c42ce09c4b4b383b4a54720f1436794cbbf8bc8/stwo_cairo_prover/crates/prover/src/cairo_air/air.rs#L380)):*
> ```XML
>                 tree_builder,
>                 &mut self.memory_address_to_id_trace_generator,
>                 &mut self.memory_id_to_value_trace_generator,
> ```

Maybe we should also rename this to id_to_big
Not for this pr



_Code quote:_
```XML
memory_id_to_value_trace_generator
```

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/214)* status: 7 of 10 files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware, @ohad-starkware, and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/air.rs` line 380 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/214#-OD4zLPD1E2juZFgCsiI:-OD50dpn7BfRiBmIMwaL:bsijqyk) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/5c42ce09c4b4b383b4a54720f1436794cbbf8bc8/stwo_cairo_prover/crates/prover/src/cairo_air/air.rs#L380)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Maybe we should also rename this to id_to_big
Not for this pr
</blockquote></details>

yes neglected these everywhere, wip
___
*[`stwo_cairo_prover/crates/prover/src/components/ret_opcode/component.rs` line 23 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/214#-OD5-4Mj0qNuRPaaagMh:-OD50htYAUWAunfkS7jn:bv576qj) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/5c42ce09c4b4b383b4a54720f1436794cbbf8bc8/stwo_cairo_prover/crates/prover/src/components/ret_opcode/component.rs#L23)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Also, why the order was changed?
</blockquote></details>

the sorting in the codegen was bugged (case sensitive)
___
*[`stwo_cairo_prover/crates/prover/src/components/verify_instruction/prover.rs` line 60 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/214#-OD5-qUECuiYfSTirYmw:-OD50tUkAUxaCvX_Qv1p:b-spigw) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/5c42ce09c4b4b383b4a54720f1436794cbbf8bc8/stwo_cairo_prover/crates/prover/src/components/verify_instruction/prover.rs#L60)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

We are going to have this comment in all the opcodes?
</blockquote></details>

wdyt? 
it needs to be stated somwhere but I'm not sure where
___
*[`stwo_cairo_prover/crates/prover/src/components/verify_instruction/prover.rs` line 308 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/214#-OD50F0V48MPY3pKfCYl:-OD515J81LZDfgnIL_Ws:b-lw71nx) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/5c42ce09c4b4b383b4a54720f1436794cbbf8bc8/stwo_cairo_prover/crates/prover/src/components/verify_instruction/prover.rs#L308)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Why no code was generated here?
</blockquote></details>

autogen artifcat, the air has a code block but the code induces only constrains and no trace gen
anatg is familiar with the issue

**Comment by ilyalesokhin-starkware** [comment]
*[`stwo_cairo_prover/crates/prover/src/components/verify_instruction/prover.rs` line 60 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/214#-OD5-qUECuiYfSTirYmw:-OD5Gb0M9I2UPSkNj1fx:bac6oak) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/5c42ce09c4b4b383b4a54720f1436794cbbf8bc8/stwo_cairo_prover/crates/prover/src/components/verify_instruction/prover.rs#L60)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

better?
</blockquote></details>


  /// When padding is needed, the inputs must be arranged in order defined by the neighbor function.
  /// This order allows using the partial sum mechanism to sum only the first `n_call` inputs.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 2 of 10 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/214)* status: 9 of 11 files reviewed, 1 unresolved discussion (waiting on @ohad-starkware and @shaharsamocha7)

**Comment by ilyalesokhin-starkware** [comment]
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 18 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/214#-OD6Ir-QB1OBkJXm9e_1:-OD6Ir-QB1OBkJXm9e_2:bhvqcm0) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/d21e0b7b754b3d7b4570f2dcac985c1da466cdce/stwo_cairo_prover/crates/prover/src/components/mod.rs#L18)):*
> ```XML
> // bit-reversed-circle-domain ordered values to the natural order. Used  to ignore padded values at
> // the tail of the natural ordered vector.
> // TODO(Ohad): generalize the padding logic, and move above doc to the relevant function.
> ```

It is not clear what "Natural order" mean in this context.



_Suggestion:_
```XML
// When padding is needed, the inputs must be arranged in the order defined by the neighbor
// function. This order allows using the partial sum mechanism to sum only the first n_call inputs.
// After getting the `SubComponentInputs` we apply the premutation again to ignore padded values at
// the tail of the vector.
// TODO(Ohad): generalize the padding logic, and move above doc to the relevant function.
```

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/214)* status: 8 of 11 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 18 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/214#-OD6Ir-QB1OBkJXm9e_1:-ODBG6BA0r4yB7RsEC0k:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/d21e0b7b754b3d7b4570f2dcac985c1da466cdce/stwo_cairo_prover/crates/prover/src/components/mod.rs#L18)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

It is not clear what "Natural order" mean in this context.
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 10 files at r1, 1 of 2 files at r2, 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/214#-:-ODBLUjY-k9UYpypnLVn:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ohad-starkware)

**Review by shaharsamocha7 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/214)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ohad-starkware)

**Comment by ohad-starkware** [comment]
### Merge activity

* **Dec 3, 6:55 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/214).

**Pull request merged**
