### PR TITLE
separate opcodes

### PR DESCRIPTION
**Pull request by ohad-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/193)

### CODE REVIEW

**Comment by ohad-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/193?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#193** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/193?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/193?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#190** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/190?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#189** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/189?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#188** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/188?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#187** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/187?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#180** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/180?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#182](https://github.com/starkware-libs/stwo-cairo/pull/182) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/182?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#179** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/179?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#177** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/177?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#178** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/178?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#176** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/176?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/193)* status: all files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/air.rs` line 285 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/193#-OCXVXecDQIKwjbQXlRr:-OCXaA-d3ZwcpEC4LqKy:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/0aad7410ec63091d71c1c3f7c840bac98661d610/stwo_cairo_prover/crates/prover/src/cairo_air/air.rs#L285)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Remove
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/air.rs` line 307 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/193#-OCXVR155jjniT2idD6W:-OCXZgQM6vTdRRgpliNk:b-21619p) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/0aad7410ec63091d71c1c3f7c840bac98661d610/stwo_cairo_prover/crates/prover/src/cairo_air/air.rs#L307)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Why did you remove the old todo?
Also I don't think we should try to avoid that clone (this is only 1 value)
</blockquote></details>

it's weird that initial and final states are inside this struct, but the proof only uses these clones, so I could have get rid of them here
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/air.rs` line 579 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/193#-OCXVlBIE8WnFH95W6SS:-OCX_lVzEmMrt4F63wPe:b-8sgcry) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/0aad7410ec63091d71c1c3f7c840bac98661d610/stwo_cairo_prover/crates/prover/src/cairo_air/air.rs#L579)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

what does it mean?
</blockquote></details>

#194

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/193)* status: all files reviewed, 1 unresolved discussion (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/air.rs` line 307 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/193#-OCXVR155jjniT2idD6W:-OCXhrGxBjlhlFVEwQMG:bqoto48) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/0aad7410ec63091d71c1c3f7c840bac98661d610/stwo_cairo_prover/crates/prover/src/cairo_air/air.rs#L307)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

it's weird that initial and final states are inside this struct, but the proof only uses these clones, so I could have get rid of them here
</blockquote></details>

Really not worth the time.
but don't we need the old todo anyway?

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/193)* status: all files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/air.rs` line 307 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/193#-OCXVR155jjniT2idD6W:-OCXiXdB2nTWGFWJlpg7:bm2i91b) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/0aad7410ec63091d71c1c3f7c840bac98661d610/stwo_cairo_prover/crates/prover/src/cairo_air/air.rs#L307)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Really not worth the time.
but don't we need the old todo anyway?
</blockquote></details>

it's in the opcodes new

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/193#-:-OCXj2Zl28f0WQJlZj3s:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @ohad-starkware)

**Comment by ohad-starkware** [comment]
### Merge activity

* **Nov 25, 4:54 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/193).

**Pull request merged**
