### PR TITLE
delete VmState and use CasmState

### PR DESCRIPTION
**Pull request by Stavbe**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/181)

### CODE REVIEW

**Review by ohad-starkware — COMMENTED** [review]
nice!
the name should stay `VmState`

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/181#-:-OC3fxlHAna7sLj_WkT_:b-t9glfz)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @anatgstarkware, @DavidLevitGurevich, @shaharsamocha7, and @yuvalsw)

**Review by Stavbe — COMMENTED** [review]
This is the name defined in prover types

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/181#-:-OCDZhUF33yN3T_TwH4S:bdm05s6)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @anatgstarkware, @DavidLevitGurevich, @shaharsamocha7, and @yuvalsw)

**Review by ohad-starkware — COMMENTED** [review]
Change it?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/181#-:-OCTBI4_CZXgZwu15Vpi:b-pv3evr)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @anatgstarkware, @DavidLevitGurevich, @shaharsamocha7, and @yuvalsw)

**Review by Stavbe — COMMENTED** [review]
@anatgstarkware WDYT  ? 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/181#-:-OCTflRc5x_nJD2KBMNq:b-orgqm9)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @anatgstarkware, @DavidLevitGurevich, @shaharsamocha7, and @yuvalsw)

**Review by DavidLevitGurevich — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/181#-:-OCZ-eez24AJjxYcIgOe:bnfp4nl)* status: 3 of 6 files reviewed, all discussions resolved (waiting on @anatgstarkware, @shaharsamocha7, and @yuvalsw)

**Review by ohad-starkware — COMMENTED** [review]
lets rename later (but soon) :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/181#-:-OCdBiLP-ZhALfQflrU8:b-v0paia)* status: 1 of 6 files reviewed, all discussions resolved (waiting on @anatgstarkware, @DavidLevitGurevich, @shaharsamocha7, and @yuvalsw)

**Pull request merged**
