### PR TITLE
Ohadn/from felt252 array

### PR DESCRIPTION
**Pull request by ohad-nir-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/156)

### CODE REVIEW

**Review by DavidLevitGurevich — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/156)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @anatgstarkware and @ohad-nir-starkware)

___
*[`stwo_cairo_prover/crates/prover_types/src/cpu.rs` line 620 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/156#-OCE2WONASkIZgzS87SI:-OCE2WOOCGEQ5ZDTwT5n:b-kmnwf6) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/898211bdc8783a1d80f7a56365113c1643bda6f6/stwo_cairo_prover/crates/prover_types/src/cpu.rs#L620)):*
> ```XML
>         let needed_bits = mod_words.len() * MOD_BUILTIN_WORD_BIT_LEN;
>         assert!(needed_bits <= B, "BigUIntExpr can have at most {B} bits");
>         let needed_limbs_per252 = (MOD_BUILTIN_WORD_BIT_LEN + 63) / 64;
> ```

`MOD_BUILTIN_WORD_BIT_LEN.div_ceil(64)`
___
*[`stwo_cairo_prover/crates/prover_types/src/cpu.rs` line 626 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/156#-OCE4rHq29vThVTulyAp:-OCE4rHq29vThVTulyAq:b-31uli6) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/898211bdc8783a1d80f7a56365113c1643bda6f6/stwo_cairo_prover/crates/prover_types/src/cpu.rs#L626)):*
> ```XML
>                     MOD_BUILTIN_WORD_BIT_LEN & 0x3F
>                 } else {
>                     64
> ```

on one hand you make it generic and on the other hand you use magic numbers all over. 
this is shorter:
```
let inner_limbs_lengths = vec![64, 32];
```

**Review by DavidLevitGurevich — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/156)* status: all files reviewed, 2 unresolved discussions (waiting on @anatgstarkware and @ohad-nir-starkware)

**Review by ohad-nir-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/156)* status: all files reviewed, 2 unresolved discussions (waiting on @anatgstarkware and @DavidLevitGurevich)

___
*[`stwo_cairo_prover/crates/prover_types/src/cpu.rs` line 620 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/156#-OCE2WONASkIZgzS87SI:-OCEP-Xs28S9Efzx1s6a:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/898211bdc8783a1d80f7a56365113c1643bda6f6/stwo_cairo_prover/crates/prover_types/src/cpu.rs#L620)):*
<details><summary><i>Previously, DavidLevitGurevich wrote…</i></summary><blockquote>

`MOD_BUILTIN_WORD_BIT_LEN.div_ceil(64)`
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover_types/src/cpu.rs` line 626 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/156#-OCE4rHq29vThVTulyAp:-OCEP-Ee9mKm1iljue4u:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/898211bdc8783a1d80f7a56365113c1643bda6f6/stwo_cairo_prover/crates/prover_types/src/cpu.rs#L626)):*
<details><summary><i>Previously, DavidLevitGurevich wrote…</i></summary><blockquote>

on one hand you make it generic and on the other hand you use magic numbers all over. 
this is shorter:
```
let inner_limbs_lengths = vec![64, 32];
```
</blockquote></details>

Done.

**Review by az-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/156)* status: all files reviewed, 2 unresolved discussions (waiting on @anatgstarkware and @DavidLevitGurevich)

**Review by DavidLevitGurevich — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/156)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @anatgstarkware, @ohad-starkware, and @shaharsamocha7)

**Review by anatgstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/156)* status: all files reviewed, 2 unresolved discussions (waiting on @ohad-nir-starkware, @ohad-starkware, and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover_types/src/cpu.rs` line 616 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/156#-OCYAEhp7AF45z2FWVQ1:-OCYAEhp7AF45z2FWVQ2:b-ky8403) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/dc3d08a53c4d6aef927f93473237259a2e7defae/stwo_cairo_prover/crates/prover_types/src/cpu.rs#L616)):*
> ```XML
> 
> impl<const B: usize, const L: usize> BigUInt<B, L> {
>     pub fn from_felt252_array(mod_words: Vec<Felt252>) -> Self {
> ```

I remember that @ohad-nir-starkware wanted it to be `from_mod_number` and get an array of fixed length.
It might be more straightforward. @DavidLevitGurevich, what do you think?



_Code quote:_
```XML
from_felt252_array
```
___
*[`stwo_cairo_prover/crates/prover_types/src/cpu.rs` line 622 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/156#-OCYC6uN6GW1qI2IMOeb:-OCYC6uN6GW1qI2IMOec:bhjpmtn) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/dc3d08a53c4d6aef927f93473237259a2e7defae/stwo_cairo_prover/crates/prover_types/src/cpu.rs#L622)):*
> ```XML
>         let needed_limbs_per252 = MOD_BUILTIN_WORD_BIT_LEN.div_ceil(64);
>         let inner_limbs_lengths = vec![64, 32];
>         let word_pieces = mod_words
> ```

@az-starkware , can you please check if there's a simpler way to do that?

**Review by az-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/156)* status: all files reviewed, 2 unresolved discussions

___
*[`stwo_cairo_prover/crates/prover_types/src/cpu.rs` line 622 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/156#-OCYC6uN6GW1qI2IMOeb:-OCcWfWmB70aBUnYGej-:b-xfodtw) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/dc3d08a53c4d6aef927f93473237259a2e7defae/stwo_cairo_prover/crates/prover_types/src/cpu.rs#L622)):*
<details><summary><i>Previously, anatgstarkware (anatg) wrote…</i></summary><blockquote>

@az-starkware , can you please check if there's a simpler way to do that?
</blockquote></details>

I don't think so, as long as we want it to work for multiple `BigUInt` sizes.

**Pull request merged**
