### PR TITLE
par opcodes

### PR DESCRIPTION
**Pull request by ohad-starkware**
par opcodes

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/288)

### CODE REVIEW

**Comment by ohad-starkware** [comment]
* **#288** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/288?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/288?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 37 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/288)* status: 2 of 37 files reviewed, 4 unresolved discussions (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/components/add_ap_opcode_is_imm_t_op_1_base_fp_f/prover.rs` line 95 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/288#-OFN1f9U2NZPe2bbSWJw:-OFN1f9U2NZPe2bbSWJx:b-i0nb6h) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ec86f2e15f57447d3adaad944f4715c76f9e92f7/stwo_cairo_prover/crates/prover/src/components/add_ap_opcode_is_imm_t_op_1_base_fp_f/prover.rs#L95)):*
> ```XML
>             });
> 
>         tree_builder.extend_evals(trace.to_evals());
> ```

This is a separate pr



_Code quote:_
```XML
trace.to_evals()
```
___
*[`stwo_cairo_prover/Cargo.toml` line 39 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/288#-OFN09W_EdYoUwRGrpDV:-OFN09Wa2YDUJjVxX685:be9rehw) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ec86f2e15f57447d3adaad944f4715c76f9e92f7/stwo_cairo_prover/Cargo.toml#L39)):*
> ```TOML
> stwo_cairo_utils = { path = "crates/utils", version = "~0.1.0" }
> # TODO(ShaharS): take stwo version from the source repository.
> stwo-prover = { git = "https://github.com/starkware-libs/stwo", rev = "234821a5", features = [
> ```

Don't merge until fixes



_Code quote:_
```TOML
rev = "234821a5"
```
___
*[`stwo_cairo_prover/crates/air_structs_derive/src/lib.rs` line 75 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/288#-OFN0xY38lao9dLJKz50:-OFN0xY38lao9dLJKz51:b58yjjt) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ec86f2e15f57447d3adaad944f4715c76f9e92f7/stwo_cairo_prover/crates/air_structs_derive/src/lib.rs#L75)):*
> ```XML
> }
> 
> fn generate_with_capacity_method(vec_array_fields: &[VecArrayField]) -> TokenStream {
> ```

should we also remove with_capacity?



_Code quote:_
```XML
fn generate_with_capacity_method(vec_array_fields: &[VecArrayField]) -> TokenStream {
```
___
*[`stwo_cairo_prover/crates/prover/src/components/add_ap_opcode_is_imm_f_op_1_base_fp_t/prover.rs` line 243 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/288#-OFN1PfB5o6DFFtSBu9d:-OFN1PfB5o6DFFtSBu9e:brnsw4n) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ec86f2e15f57447d3adaad944f4715c76f9e92f7/stwo_cairo_prover/crates/prover/src/components/add_ap_opcode_is_imm_f_op_1_base_fp_t/prover.rs#L243)):*
> ```XML
>                 {
>                     *sub_components_inputs[i].memory_address_to_id_inputs[0] = input;
>                 }
> ```

why remove the function call here?



_Code quote:_
```XML
                for (i, &input) in ((input_fp_col2) + ((offset2_col3) - (M31_32768)))
                    .unpack()
                    .iter()
                    .enumerate()
                {
                    *sub_components_inputs[i].memory_address_to_id_inputs[0] = input;
                }
```

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/288)* status: 2 of 37 files reviewed, 4 unresolved discussions (waiting on @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/air_structs_derive/src/lib.rs` line 75 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/288#-OFN0xY38lao9dLJKz50:-OFQMuNS6wKgtZFJY2JF:b-w9i3zi) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ec86f2e15f57447d3adaad944f4715c76f9e92f7/stwo_cairo_prover/crates/air_structs_derive/src/lib.rs#L75)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

should we also remove with_capacity?
</blockquote></details>

yes but verify instruction is using it atm and I want to handle it later (not autogen)
___
*[`stwo_cairo_prover/crates/prover/src/components/add_ap_opcode_is_imm_f_op_1_base_fp_t/prover.rs` line 243 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/288#-OFN1PfB5o6DFFtSBu9d:-OFQNAU54oC2lgtWapAO:b-r46hae) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ec86f2e15f57447d3adaad944f4715c76f9e92f7/stwo_cairo_prover/crates/prover/src/components/add_ap_opcode_is_imm_f_op_1_base_fp_t/prover.rs#L243)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

why remove the function call here?
</blockquote></details>

what function call?
___
*[`stwo_cairo_prover/crates/prover/src/components/add_ap_opcode_is_imm_t_op_1_base_fp_f/prover.rs` line 95 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/288#-OFN1f9U2NZPe2bbSWJw:-OFQo_sV5wGrarE-Jwkg:bv7orxf) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ec86f2e15f57447d3adaad944f4715c76f9e92f7/stwo_cairo_prover/crates/prover/src/components/add_ap_opcode_is_imm_t_op_1_base_fp_f/prover.rs#L95)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

This is a separate pr
</blockquote></details>

is it ?
this pr is use "the witness framework"
I either use the entire thing or I don't

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 37 files at r1, 32 of 35 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/288)* status: all files reviewed, 2 unresolved discussions (waiting on @ohad-starkware and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/air_structs_derive/src/lib.rs` line 75 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/288#-OFN0xY38lao9dLJKz50:-OFS-UXK9GcGLTV_alI2:byhntlc) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ec86f2e15f57447d3adaad944f4715c76f9e92f7/stwo_cairo_prover/crates/air_structs_derive/src/lib.rs#L75)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

yes but verify instruction is using it atm and I want to handle it later (not autogen)
</blockquote></details>

can you add a TODO so we actually do it?
___
*[`stwo_cairo_prover/crates/prover/Cargo.toml` line 21 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/288#-OFS-x4vBNW8iu2AEjfY:-OFS-x4vBNW8iu2AEjfZ:bvt0yyc) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/a4a03794d108f414d735f54d85bb5042786a99ff/stwo_cairo_prover/crates/prover/Cargo.toml#L21)):*
> ```TOML
> paste.workspace = true
> prover_types = { path = "../prover_types" }
> rayon = { version = "1.10.0", optional = false }
> ```

todo - add parallel config



_Suggestion:_
```TOML
rayon = { version = "1.10.0"}
```

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/288)* status: all files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/air_structs_derive/src/lib.rs` line 75 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/288#-OFN0xY38lao9dLJKz50:-OFS3h1m8v11stVzNjrX:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ec86f2e15f57447d3adaad944f4715c76f9e92f7/stwo_cairo_prover/crates/air_structs_derive/src/lib.rs#L75)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

can you add a TODO so we actually do it?
</blockquote></details>

Done.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/288#-:-OFS9D0D5RZ51aImHS8R:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ohad-starkware)

**Pull request merged**
