### PR TITLE
Dynamic memory small range

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/47)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/47?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#47** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/47?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#46** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/46?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ohad-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/47)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @spapinistarkware)

___
*[`stwo_cairo_prover/src/input/mem.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/47#-O4EWj4V5sFfLbnakUYo:-O4EWj4V5sFfLbnakUYp:bvjnyal) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/0cca086bdd5d7d9bd6b304d1d4fb00e3f7256b52/stwo_cairo_prover/src/input/mem.rs#L28)):*
> ```XML
> const SMALL_VALUE_SHIFT: u32 = 1 << 26;
> pub struct MemConfig {
>     small_min_neg: u32,
> ```

can these be generic params for memory?
if so, you can assert the sizes at compile time,
and omit the mem_config as argument to from_iter
___
*[`stwo_cairo_prover/src/input/mem.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/47#-O4EWGgo9LtP2qG5IAK0:-O4EWGgo9LtP2qG5IAK1:b-cz7il9) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/0cca086bdd5d7d9bd6b304d1d4fb00e3f7256b52/stwo_cairo_prover/src/input/mem.rs#L44)):*
> ```XML
>     fn default() -> Self {
>         MemConfig {
>             small_min_neg: (1 << 20) - 1,
> ```

const DEFAULT_MIN_NEG

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/47)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @ohad-starkware)

___
*[`stwo_cairo_prover/src/input/mem.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/47#-O4EWj4V5sFfLbnakUYo:-O4EaCkH1De4XLhe4eJd:bbertt4) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/0cca086bdd5d7d9bd6b304d1d4fb00e3f7256b52/stwo_cairo_prover/src/input/mem.rs#L28)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

can these be generic params for memory?
if so, you can assert the sizes at compile time,
and omit the mem_config as argument to from_iter
</blockquote></details>

This value will be dynamic, based on the proven program trace.
___
*[`stwo_cairo_prover/src/input/mem.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/47#-O4EWGgo9LtP2qG5IAK0:-O4Eb-AMCAyMPSH9LV2X:b774aul) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/0cca086bdd5d7d9bd6b304d1d4fb00e3f7256b52/stwo_cairo_prover/src/input/mem.rs#L44)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

const DEFAULT_MIN_NEG
</blockquote></details>

Added some doc on the struct itself.

**Review by ohad-starkware — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/47#-:-O4Ee1vM2ETtqHBHbuUC:bnfp4nl)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @alonh5)

___
*[`stwo_cairo_prover/src/input/mem.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/47#-O4EWGgo9LtP2qG5IAK0:-O4Edzf7C5aI8ANM61Nw:b-k73z76) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/0cca086bdd5d7d9bd6b304d1d4fb00e3f7256b52/stwo_cairo_prover/src/input/mem.rs#L44)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Added some doc on the struct itself.
</blockquote></details>

thanks

**Pull request merged**
