### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/259)

### CODE REVIEW

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/259)* status: all files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`stwo_cairo_verifier/.cairofmtignore` line 1 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/259#-OEJKv5CDBGH2ACffLZq:-OEJKv5CDBGH2ACffLZr:b-fgunc) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c6fc20708a21835b7a2c2bc490c2970dc1d7adfc/stwo_cairo_verifier/.cairofmtignore#L1)):*
> ```
> *_proof.cairo
> ```

Not sure whether this is a good idea, we could have cairo files with this name, no?



_Code quote:_
```
*_proof.cairo
```
___
*[`stwo_cairo_verifier/crates/verifier_core/tests/verifier.cairo` line 79 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/259#-OEJLJW09MheFpeMqeSk:-OEJLJW09MheFpeMqeSl:b-o1lhz9) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c6fc20708a21835b7a2c2bc490c2970dc1d7adfc/stwo_cairo_verifier/crates/verifier_core/tests/verifier.cairo#L79)):*
> ```Cairo
> }
> ```

remove extra line
___
*[`stwo_cairo_verifier/crates/verifier_core/src/fields/m31.cairo` line 152 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/259#-OEJLOZr2l-qx1X9lnJe:-OEJLOZr2l-qx1X9lnJf:b-sn8uej) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c6fc20708a21835b7a2c2bc490c2970dc1d7adfc/stwo_cairo_verifier/crates/verifier_core/src/fields/m31.cairo#L152)):*
> ```Cairo
> }
> 
> impl U32TryIntoM31 of TryInto<u32, M31> {
> ```

What code uses this impl?



_Code quote:_
```Cairo
impl U32TryIntoM31 of TryInto<u32, M31> {
```
___
*[`stwo_cairo_verifier/crates/verifier_core/src/fields/m31.cairo` line 159 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/259#-OEJLqFh4p9CuIRJITtB:-OEJLqFh4p9CuIRJITtC:b-256x3a) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c6fc20708a21835b7a2c2bc490c2970dc1d7adfc/stwo_cairo_verifier/crates/verifier_core/src/fields/m31.cairo#L159)):*
> ```Cairo
>         }
> 
>         Option::Some(M31Impl::reduce_u32(self))
> ```

Why do you need to call reduce here?

You also have this function
https://github.com/starkware-libs/stwo-cairo/blob/c6fc20708a21835b7a2c2bc490c2970dc1d7adfc/stwo_cairo_verifier/crates/verifier_core/src/fields/m31.cairo#L174



_Code quote:_
```Cairo
Option::Some(M31Impl::reduce_u32(self))
```

**Comment by ilyalesokhin-starkware** [comment]
*[`stwo_cairo_verifier/.cairofmtignore` line 1 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/259#-OEJKv5CDBGH2ACffLZq:-OEJMjhiAwzbtRPUO4Vb:b5e7eor) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c6fc20708a21835b7a2c2bc490c2970dc1d7adfc/stwo_cairo_verifier/.cairofmtignore#L1)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Not sure whether this is a good idea, we could have cairo files with this name, no?
</blockquote></details>

Andrew made this change; I don't mind.

**Comment by ilyalesokhin-starkware** [comment]
*[`stwo_cairo_verifier/.cairofmtignore` line 1 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/259#-OEJKv5CDBGH2ACffLZq:-OEJNmaW448O-1VULxqG:b-74b3qp) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c6fc20708a21835b7a2c2bc490c2970dc1d7adfc/stwo_cairo_verifier/.cairofmtignore#L1)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Andrew made this change; I don't mind.
</blockquote></details>

How likely are we to have such files?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/259)* status: 7 of 9 files reviewed, 4 unresolved discussions (waiting on @shaharsamocha7)

___
*[`stwo_cairo_verifier/crates/verifier_core/tests/verifier.cairo` line 79 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/259#-OEJLJW09MheFpeMqeSk:-OEJOKcy18enHFrI16KF:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c6fc20708a21835b7a2c2bc490c2970dc1d7adfc/stwo_cairo_verifier/crates/verifier_core/tests/verifier.cairo#L79)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

remove extra line
</blockquote></details>

Done.
___
*[`stwo_cairo_verifier/crates/verifier_core/src/fields/m31.cairo` line 152 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/259#-OEJLOZr2l-qx1X9lnJe:-OEJO2Vt2KokoWvdBDrb:b-1hxvfw) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c6fc20708a21835b7a2c2bc490c2970dc1d7adfc/stwo_cairo_verifier/crates/verifier_core/src/fields/m31.cairo#L152)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

What code uses this impl?
</blockquote></details>

No one is using it.
Removed for now.
___
*[`stwo_cairo_verifier/crates/verifier_core/src/fields/m31.cairo` line 159 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/259#-OEJLqFh4p9CuIRJITtB:-OEJNx8T3_JNPU7ZD-zj:bwa84ns) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c6fc20708a21835b7a2c2bc490c2970dc1d7adfc/stwo_cairo_verifier/crates/verifier_core/src/fields/m31.cairo#L159)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Why do you need to call reduce here?

You also have this function
https://github.com/starkware-libs/stwo-cairo/blob/c6fc20708a21835b7a2c2bc490c2970dc1d7adfc/stwo_cairo_verifier/crates/verifier_core/src/fields/m31.cairo#L174
</blockquote></details>

It changes the type.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/259)* status: 7 of 9 files reviewed, 4 unresolved discussions (waiting on @shaharsamocha7)

___
*[`stwo_cairo_verifier/crates/verifier_core/src/fields/m31.cairo` line 159 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/259#-OEJLqFh4p9CuIRJITtB:-OEJPY3W2hWJ2Dyr0kkY:b7nrej3) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c6fc20708a21835b7a2c2bc490c2970dc1d7adfc/stwo_cairo_verifier/crates/verifier_core/src/fields/m31.cairo#L159)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

It changes the type.
</blockquote></details>

There is a more efficient way of doing it, but this is the simplest.

**Review by shaharsamocha7 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/259)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`stwo_cairo_verifier/.cairofmtignore` line 1 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/259#-OEJKv5CDBGH2ACffLZq:-OEJQNqKAxvO7ep5rAAQ:bl1hpoy) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c6fc20708a21835b7a2c2bc490c2970dc1d7adfc/stwo_cairo_verifier/.cairofmtignore#L1)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

How likely are we to have such files?
</blockquote></details>

Not sure,
maybe `cairo_proof.cairo` that contain the struct?

or do you mean files as tests proof?
maybe we can just rename it to somethings less likely (_large_proof)?

**Comment by ilyalesokhin-starkware** [comment]
*[`stwo_cairo_verifier/.cairofmtignore` line 1 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/259#-OEJKv5CDBGH2ACffLZq:-OEJRiJB2YTCRMXH13pR:bus5dsw) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c6fc20708a21835b7a2c2bc490c2970dc1d7adfc/stwo_cairo_verifier/.cairofmtignore#L1)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Not sure,
maybe `cairo_proof.cairo` that contain the struct?

or do you mean files as tests proof?
maybe we can just rename it to somethings less likely (_large_proof)?
</blockquote></details>

is
test/*_proof.cairo
ok?

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/259#-:-OEJSKId2oJQCBfnk2qE:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
