### PR TITLE
auto expand rangecheck evals

### PR DESCRIPTION
**Pull request by ohad-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/145)

### CODE REVIEW

**Comment by ohad-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/145?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#145** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/145?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#144** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/144?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ohad-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by ilyalesokhin-starkware** [comment]
*[`stwo_cairo_prover/crates/prover/Cargo.toml` line 18 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/145#-OASEQvD6ZabP4UbqW1a:-OASEQvEEEZ311Z6wobG:b-esll4m) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/7793603d96d23b5d1aeb2393210a65b27cc7e250/stwo_cairo_prover/crates/prover/Cargo.toml#L18)):*
> ```TOML
> thiserror.workspace = true
> tracing.workspace = true
> paste = "1.0"
> ```

Why not in the workspace?



_Code quote:_
```TOML
paste = "1.0"
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 3 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/145)* status: 1 of 8 files reviewed, 1 unresolved discussion (waiting on @ohad-starkware)

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/145)* status: 1 of 8 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/Cargo.toml` line 18 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/145#-OASEQvD6ZabP4UbqW1a:-OASIhZr-GbwN4jwej3T:b-1zaym6) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/7793603d96d23b5d1aeb2393210a65b27cc7e250/stwo_cairo_prover/crates/prover/Cargo.toml#L18)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Why not in the workspace?
</blockquote></details>

moved to workspace

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 8 files at r1, 1 of 2 files at r2, 4 of 4 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/145#-:-OASK7QX5TNlbv4_sVKg:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ohad-starkware)

**Comment by ohad-starkware** [comment]
### Merge activity

* **Oct 30, 8:12 AM EDT**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/145).

**Pull request merged**
