### PR TITLE
verify mults manual reference

### PR DESCRIPTION
**Pull request by ohad-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/233)

### CODE REVIEW

**Comment by ohad-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/233?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#233** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/233?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/233?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#229** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/229?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#231](https://github.com/starkware-libs/stwo-cairo/pull/231) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/231?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#222** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/222?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#228** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/228?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#221** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/221?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#220** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/220?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#219** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/219?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#218** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/218?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#217** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/217?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#216** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/216?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#215** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/215?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#214** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/214?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#209** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/209?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#208** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/208?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#207** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/207?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#206** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/206?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/233)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/debug.rs` line 468 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/233#-ODanV-gC-fd3W3dHSZU:-ODanV-gC-fd3W3dHSZV:b-tdzegt) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e8663e00e5441815ebb9297661f147523997093d/stwo_cairo_prover/crates/prover/src/cairo_air/debug.rs#L468)):*
> ```XML
>                 verifyinstruction_lookup_elements: relations::VerifyInstruction::dummy(),
>             },
>             claim.verify_instruction.n_calls.next_power_of_two(),
> ```

Do we need here n_calls at all? 
or could we use log_rows directly because we don't have padding



_Code quote:_
```XML
claim.verify_instruction.n_calls.next_power_of_two(),
```
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/air.rs` line 395 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/233#-ODanJ1P8-kfAAT520rT:-ODanJ1P8-kfAAT520rU:b-tsgfof) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e8663e00e5441815ebb9297661f147523997093d/stwo_cairo_prover/crates/prover/src/cairo_air/air.rs#L395)):*
> ```XML
>     // TODO(Ohad): hide this logic behind `InteractionClaim`, and only sum here.
>     sum += interaction_claim.opcodes.sum();
>     sum += interaction_claim.verify_instruction.logup_sums.value();
> ```

consider to rename



_Suggestion:_
```XML
sum += interaction_claim.verify_instruction.logup_sums.claimed_sum();
```

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/233)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/air.rs` line 395 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/233#-ODanJ1P8-kfAAT520rT:-ODemKmCEZIhBNHhMN3Q:bf2y99h) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e8663e00e5441815ebb9297661f147523997093d/stwo_cairo_prover/crates/prover/src/cairo_air/air.rs#L395)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

consider to rename
</blockquote></details>

this change is in stwo
can we postpone it? titelman made changes to the framework that would require auto-gen update
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/debug.rs` line 468 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/233#-ODanV-gC-fd3W3dHSZU:-ODemTPNAP6f1MIOIPL-:b-jp377f) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e8663e00e5441815ebb9297661f147523997093d/stwo_cairo_prover/crates/prover/src/cairo_air/debug.rs#L468)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Do we need here n_calls at all? 
or could we use log_rows directly because we don't have padding
</blockquote></details>

correct

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/233#-:-ODeqa-lAjBnSE0ofiyX:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/air.rs` line 395 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/233#-ODanJ1P8-kfAAT520rT:-ODeqC9o8X3a5p95Ue3R:bcg3epl) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e8663e00e5441815ebb9297661f147523997093d/stwo_cairo_prover/crates/prover/src/cairo_air/air.rs#L395)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

this change is in stwo
can we postpone it? titelman made changes to the framework that would require auto-gen update
</blockquote></details>

which changes?
Sure we can delay the change

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/233)* status: all files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/air.rs` line 395 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/233#-ODanJ1P8-kfAAT520rT:-ODf0VDaDhTiWrrvyYaU:b-onoetl) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e8663e00e5441815ebb9297661f147523997093d/stwo_cairo_prover/crates/prover/src/cairo_air/air.rs#L395)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

which changes?
Sure we can delay the change
</blockquote></details>

the batching thing, now add_to_relation takes single entries and I don't want to deal with the air infra update because of my renaming

**Pull request merged**
