### PR TITLE
renamed component structures

### PR DESCRIPTION
**Pull request by ohad-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/146)

### CODE REVIEW

**Comment by ohad-starkware** [comment]
* **#146** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/146?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ohad-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by ilyalesokhin-starkware** [comment]
*[`stwo_cairo_prover/crates/prover/src/components/range_check_vector/mod.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/146#-OAWJ4RF-qj3ESt5iAPE:-OAWJ4RGC269ImpPTBmm:b-7jc0as) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/4b68069fb7e050d53e8fb31cdfed15aaf373a4bf/stwo_cairo_prover/crates/prover/src/components/range_check_vector/mod.rs#L65)):*
> ```XML
>                 use stwo_prover::core::fields::qm31::QM31;
>                 use stwo_prover::constraint_framework::FrameworkEval;
>                 use stwo_prover::constraint_framework::EvalAtRow;
> ```

sort?



_Code quote:_
```XML
                use stwo_prover::constraint_framework::FrameworkComponent;
                use $crate::components::range_check_vector::RangeCheckVectorEval;
                use stwo_prover::constraint_framework::logup::LookupElements;
                use stwo_prover::core::fields::qm31::QM31;
                use stwo_prover::constraint_framework::FrameworkEval;
                use stwo_prover::constraint_framework::EvalAtRow;
```

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/146#-:-OAWJJLG1DkMr3r28V0r:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ohad-starkware)

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/146)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_vector/mod.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/146#-OAWJ4RF-qj3ESt5iAPE:-OAWRfNB4hgI6lqd2EfR:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/4b68069fb7e050d53e8fb31cdfed15aaf373a4bf/stwo_cairo_prover/crates/prover/src/components/range_check_vector/mod.rs#L65)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

sort?
</blockquote></details>

Done.

**Comment by ohad-starkware** [comment]
### Merge activity

* **Oct 31, 3:41 AM EDT**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/146).

**Pull request merged**
