### PR TITLE
Adjust range check builtin.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/64)

### CODE REVIEW

**Comment by alonh5** [comment]
* **#65** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/65?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#64** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/64?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alonh5 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/64)* status: 0 of 2 files reviewed, 7 unresolved discussions (waiting on @alonh5 and @spapinistarkware)

___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_builtin/component.rs` line 95 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/64#-O58Kzuc6OAFGoXUw_hP:-O58Kzuc6OAFGoXUw_hQ:b-6mokys) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/215c4a2bbeaf398f75ae5bcb2713aa4073e12d14/stwo_cairo_prover/crates/prover/src/components/range_check_builtin/component.rs#L95)):*
> ```XML
> pub struct RangeCheckClaim {
>     pub log_size: u32,
>     pub n_values: usize,
> ```

Aren't those the same up to exponent?
Why we need both in the claim?



_Code quote:_
```XML
    pub log_size: u32,
    pub n_values: usize,
```
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_builtin/component.rs` line 105 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/64#-O58LSNr8xVVQOOewjc3:-O58LSNr8xVVQOOewjc4:bajai6q) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/215c4a2bbeaf398f75ae5bcb2713aa4073e12d14/stwo_cairo_prover/crates/prover/src/components/range_check_builtin/component.rs#L105)):*
> ```XML
>     pub fn log_sizes(&self) -> TreeVec<Vec<u32>> {
>         let interaction_0_log_sizes = vec![self.log_size; N_ADDRESS_FELTS + N_VALUES_FELTS];
>         let interaction_1_log_sizes = vec![self.log_size; SECURE_EXTENSION_DEGREE * 2];
> ```

This 2 is due to that we have 2 lookups in this component?
Can we make it a constant?



_Code quote:_
```XML
let interaction_1_log_sizes = vec![self.log_size; SECURE_EXTENSION_DEGREE * 2];
```
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_builtin/component.rs` line 118 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/64#-O58LmXu3JkN_6pxkTLj:-O58LmXv9N2uxI6kUBOo:b-1z5bt) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/215c4a2bbeaf398f75ae5bcb2713aa4073e12d14/stwo_cairo_prover/crates/prover/src/components/range_check_builtin/component.rs#L118)):*
> ```XML
> impl RangeCheckInteractionClaim {
>     pub fn log_sizes(&self) -> Vec<u32> {
>         vec![self.log_size; 12]
> ```

what's this 12?



_Code quote:_
```XML
vec![self.log_size; 12]
```
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_builtin/simd_trace.rs` line 25 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/64#-O58M7lh3I5JhVfmTfpz:-O58M7lh3I5JhVfmTfq-:bvsgl4q) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/215c4a2bbeaf398f75ae5bcb2713aa4073e12d14/stwo_cairo_prover/crates/prover/src/components/range_check_builtin/simd_trace.rs#L25)):*
> ```XML
> pub struct RangeCheckInput {
>     pub address: PackedM31,
> }
> ```

Is this struct still necessary?
and does it need a dafault impl?



_Code quote:_
```XML
pub struct RangeCheckInput {
    pub address: PackedM31,
}
```
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_builtin/simd_trace.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/64#-O58LooH8_2v_gy8yGl9:-O58LooH8_2v_gy8yGlA:ba3dfna) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/215c4a2bbeaf398f75ae5bcb2713aa4073e12d14/stwo_cairo_prover/crates/prover/src/components/range_check_builtin/simd_trace.rs#L35)):*
> ```XML
> }
> 
> /////////////////////////////////////////
> ```

Remove?



_Code quote:_
```XML
/////////////////////////////////////////
```
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_builtin/simd_trace.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/64#-O58MMrT74RHHgpdyIw6:-O58MMrT74RHHgpdyIw7:bygaj7q) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/215c4a2bbeaf398f75ae5bcb2713aa4073e12d14/stwo_cairo_prover/crates/prover/src/components/range_check_builtin/simd_trace.rs#L44)):*
> ```XML
>         let mut addresses = (input.begin_addr..input.end_addr).collect_vec();
>         // TODO(spapini): Split to multiple components.
>         let size = addresses.len().next_power_of_two().max(64);
> ```

Is this the minimum rows for all of our airs?



_Code quote:_
```XML
.max(64)
```
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_builtin/simd_trace.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/64#-O58Ms3o1xm6NJ-F-csz:-O58Ms3o1xm6NJ-F-ct-:b-6eaqj1) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/215c4a2bbeaf398f75ae5bcb2713aa4073e12d14/stwo_cairo_prover/crates/prover/src/components/range_check_builtin/simd_trace.rs#L80)):*
> ```XML
> pub struct RangeCheckInteractionProver {
>     pub memory_inputs: Vec<PackedM31>,
>     pub memory_outputs: Vec<[PackedM31; N_VALUES_FELTS]>,
> ```

Consider to change



_Suggestion:_
```XML
    pub memory_adresses: Vec<PackedM31>,
    pub memory_values: Vec<[PackedM31; N_VALUES_FELTS]>,
```

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/64)* status: 0 of 2 files reviewed, 7 unresolved discussions (waiting on @alonh5 and @spapinistarkware)

___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_builtin/component.rs` line 95 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/64#-O58Kzuc6OAFGoXUw_hP:-O58OnK28rfp8Ro_OW2K:b-vxsiyq) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/215c4a2bbeaf398f75ae5bcb2713aa4073e12d14/stwo_cairo_prover/crates/prover/src/components/range_check_builtin/component.rs#L95)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Aren't those the same up to exponent?
Why we need both in the claim?
</blockquote></details>

Don't we need here the offset in memory?

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/64)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_builtin/component.rs` line 95 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/64#-O58Kzuc6OAFGoXUw_hP:-O5CjJZZCCRAjJ6Fhy0Q:b-7nczqv) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/215c4a2bbeaf398f75ae5bcb2713aa4073e12d14/stwo_cairo_prover/crates/prover/src/components/range_check_builtin/component.rs#L95)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Don't we need here the offset in memory?
</blockquote></details>

1. n_values isn't necesarily a power of 2, we need it to know how much padding to add. I removed log_size.

2. Yes I added it.
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_builtin/component.rs` line 105 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/64#-O58LSNr8xVVQOOewjc3:-O5ClstX38feu8N-8Ysa:bhtm2rc) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/215c4a2bbeaf398f75ae5bcb2713aa4073e12d14/stwo_cairo_prover/crates/prover/src/components/range_check_builtin/component.rs#L105)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

This 2 is due to that we have 2 lookups in this component?
Can we make it a constant?
</blockquote></details>

It's actually 1 because we are merging the two columns into 1.
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_builtin/component.rs` line 118 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/64#-O58LmXu3JkN_6pxkTLj:-O5CmQKN7Kudj2v3NOtw:b-8fteqy) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/215c4a2bbeaf398f75ae5bcb2713aa4073e12d14/stwo_cairo_prover/crates/prover/src/components/range_check_builtin/component.rs#L118)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

what's this 12?
</blockquote></details>

Removed, it was a mistake and this function is not needed anyway.
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_builtin/simd_trace.rs` line 25 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/64#-O58M7lh3I5JhVfmTfpz:-O5CfA8a7rJhyi9efafR:b-v8o4f3) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/215c4a2bbeaf398f75ae5bcb2713aa4073e12d14/stwo_cairo_prover/crates/prover/src/components/range_check_builtin/simd_trace.rs#L25)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Is this struct still necessary?
and does it need a dafault impl?
</blockquote></details>

I removed the struct and create a type instead, that's how it is in the code gen so I want it to match as much as possible.
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_builtin/simd_trace.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/64#-O58MMrT74RHHgpdyIw6:-O5Cfz5iDIFRWkGvbp6A:b-jgzdsc) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/215c4a2bbeaf398f75ae5bcb2713aa4073e12d14/stwo_cairo_prover/crates/prover/src/components/range_check_builtin/simd_trace.rs#L44)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Is this the minimum rows for all of our airs?
</blockquote></details>

It is a minimum bound we have in the simd implementation. We need to add a fallback to CPU for smaller sizes. We should add it as a task.
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_builtin/simd_trace.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/64#-O58Ms3o1xm6NJ-F-csz:-O5Ci4YI38DqR28Km7MI:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/215c4a2bbeaf398f75ae5bcb2713aa4073e12d14/stwo_cairo_prover/crates/prover/src/components/range_check_builtin/simd_trace.rs#L80)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Consider to change
</blockquote></details>

Done.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/64)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @alonh5 and @spapinistarkware)

___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_builtin/component.rs` line 95 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/64#-O58Kzuc6OAFGoXUw_hP:-O5DA926ByEgFDnV2mRR:bn2mv8n) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/215c4a2bbeaf398f75ae5bcb2713aa4073e12d14/stwo_cairo_prover/crates/prover/src/components/range_check_builtin/component.rs#L95)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

1. n_values isn't necesarily a power of 2, we need it to know how much padding to add. I removed log_size.

2. Yes I added it.
</blockquote></details>

I think we can discard n_values here, no?
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_builtin/simd_trace.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/64#-O58MMrT74RHHgpdyIw6:-O5D9ip892M8RD9bLytJ:bj7kr50) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/215c4a2bbeaf398f75ae5bcb2713aa4073e12d14/stwo_cairo_prover/crates/prover/src/components/range_check_builtin/simd_trace.rs#L44)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

It is a minimum bound we have in the simd implementation. We need to add a fallback to CPU for smaller sizes. We should add it as a task.
</blockquote></details>

so can you make a general constant for now
and add a TODO?
___
*[`stwo_cairo_prover/crates/prover/src/components/ret_opcode/component.rs` line 87 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/64#-O5DA2PG6xliH3J3WqAB:-O5DA2PG6xliH3J3WqAC:bgav424) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/d39486d0a8b1f2e1a9e35fefbc029062b33eb164/stwo_cairo_prover/crates/prover/src/components/ret_opcode/component.rs#L87)):*
> ```XML
> 
> #[derive(Clone)]
> pub struct RetOpcodeClaim {
> ```

Can we do those changed in another pr?
It is unrelated to this one

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/64)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_builtin/component.rs` line 95 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/64#-O58Kzuc6OAFGoXUw_hP:-O5DAqSx11wNCUn7z_Wp:bcucovx) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/215c4a2bbeaf398f75ae5bcb2713aa4073e12d14/stwo_cairo_prover/crates/prover/src/components/range_check_builtin/component.rs#L95)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I think we can discard n_values here, no?
</blockquote></details>

I explained above why we do need it.
___
*[`stwo_cairo_prover/crates/prover/src/components/ret_opcode/component.rs` line 87 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/64#-O5DA2PG6xliH3J3WqAB:-O5DDjuS2Xi2pKb2yWSs:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/d39486d0a8b1f2e1a9e35fefbc029062b33eb164/stwo_cairo_prover/crates/prover/src/components/ret_opcode/component.rs#L87)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can we do those changed in another pr?
It is unrelated to this one
</blockquote></details>

Done.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r3, 2 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/64)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @spapinistarkware)

___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_builtin/simd_trace.rs` line 107 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/64#-O5HiZaz2vC6DOqgtwZm:-O5HiZaz2vC6DOqgtwZn:b-tyrlmf) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/a9d4e640831cbbca7b9bd11a58eeda74fdf84255/stwo_cairo_prover/crates/prover/src/components/range_check_builtin/simd_trace.rs#L107)):*
> ```XML
> 
> pub fn write_trace_simd(
>     inputs: &[RangeCheckInput],
> ```

Does it really need all the addresses prepared in advance?
Seems that it could only get the initial/end address, WDYT?



_Code quote:_
```XML
inputs: &[RangeCheckInput],
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/64)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_builtin/simd_trace.rs` line 107 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/64#-O5HiZaz2vC6DOqgtwZm:-O5SqlmrEVuQadKQBpFO:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/a9d4e640831cbbca7b9bd11a58eeda74fdf84255/stwo_cairo_prover/crates/prover/src/components/range_check_builtin/simd_trace.rs#L107)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Does it really need all the addresses prepared in advance?
Seems that it could only get the initial/end address, WDYT?
</blockquote></details>

Done.

**Review by shaharsamocha7 — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/64)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5 and @spapinistarkware)

___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_builtin/component.rs` line 94 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/64#-O5StUBiE37vinUL6RT8:-O5StUBiE37vinUL6RT9:bp9i9zb) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/4d227e9a5d0db8632b2ec21cc8e777aa613c1ad4/stwo_cairo_prover/crates/prover/src/components/range_check_builtin/component.rs#L94)):*
> ```XML
> 
> #[derive(Clone)]
> pub struct RangeCheckClaim {
> ```

RangeCheckClaim is already taken for the unit
Should we rename everything to RangeCheckBuiltinX?



_Suggestion:_
```XML
pub struct RangeCheckBuiltinClaim {
```
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_builtin/component.rs` line 109 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/64#-O5StbK82F5CVXRbhGq4:-O5StbK82F5CVXRbhGq5:brv6pjy) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/4d227e9a5d0db8632b2ec21cc8e777aa613c1ad4/stwo_cairo_prover/crates/prover/src/components/range_check_builtin/component.rs#L109)):*
> ```XML
>         let interaction_0_log_sizes = vec![log_size; N_ADDRESS_FELTS + N_VALUES_FELTS];
>         let interaction_1_log_sizes = vec![log_size; SECURE_EXTENSION_DEGREE];
>         TreeVec::new(vec![interaction_0_log_sizes, interaction_1_log_sizes])
> ```

Consider



_Suggestion:_
```XML
        let trace_log_sizes = vec![log_size; N_ADDRESS_FELTS + N_VALUES_FELTS];
        let interaction_trace_log_sizes = vec![log_size; SECURE_EXTENSION_DEGREE];
        TreeVec::new(vec![trace_log_sizes, interaction_trace_log_sizes])
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/64)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_builtin/component.rs` line 94 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/64#-O5StUBiE37vinUL6RT8:-O5T2b5F5WqG-B2U1jQi:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/4d227e9a5d0db8632b2ec21cc8e777aa613c1ad4/stwo_cairo_prover/crates/prover/src/components/range_check_builtin/component.rs#L94)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

RangeCheckClaim is already taken for the unit
Should we rename everything to RangeCheckBuiltinX?
</blockquote></details>

Done.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/64)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @spapinistarkware)

___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_builtin/simd_trace.rs` line 206 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/64#-O5TN7MT-atP0hQSAZXg:-O5TN7MT-atP0hQSAZXh:bl8o1cv) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f49a13f342f4a52d2b5ac24bcb038723657dd301/stwo_cairo_prover/crates/prover/src/components/range_check_builtin/simd_trace.rs#L206)):*
> ```XML
>         let mut rng = rand::thread_rng();
>         let log_size = 8;
>         let address_initial_offset = 10032;
> ```

Why did you remove this initial offset?



_Code quote:_
```XML
let address_initial_offset = 10032;
```

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/64#-:-O5TWSn-Dk-RJPIS36mC:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
