### PR TITLE
update stwo

### PR DESCRIPTION
**Pull request by ohad-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/131)

### CODE REVIEW

**Comment by ohad-starkware** [comment]
* **#131** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/131?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ohad-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/131)* status: 7 of 11 files reviewed, 3 unresolved discussions (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/components/memory/prover.rs` line 171 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/131#-OAC52DyB9KBYYtZ19ct:-OAC52DyB9KBYYtZ19cu:bxyt9cz) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/26349e9096abe433131f65052c7e02c44945ae4f/stwo_cairo_prover/crates/prover/src/components/memory/prover.rs#L171)):*
> ```XML
>             col_gen.finalize_col();
>         }
>         let (trace, [claimed_sum]) = logup_gen.finalize_at([(1 << log_size) - 1]);
> ```

I think you should have finalize_last() function
You should use that (in all places)



_Code quote:_
```XML
logup_gen.finalize_at([(1 << log_size) - 1]);
```
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_builtin/component.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/131#-OAC59UQ93NcGOKnBxaa:-OAC59URCKXKL-bL9MQU:b-4gtbh6) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/26349e9096abe433131f65052c7e02c44945ae4f/stwo_cairo_prover/crates/prover/src/components/range_check_builtin/component.rs#L65)):*
> ```XML
>         let mut eval = eval;
>         let mut values: [_; N_ADDRESS_FELTS + N_VALUES_FELTS] =
>             std::array::from_fn(|_| E::F::zero());
> ```

Why is this change?



_Code quote:_
```XML
        let mut values: [_; N_ADDRESS_FELTS + N_VALUES_FELTS] =
            std::array::from_fn(|_| E::F::zero());
```
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_unit/component.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/131#-OAC5URq-uFYosC0tN_D:-OAC5URrAl-gmaBuykdm:b3kre) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/26349e9096abe433131f65052c7e02c44945ae4f/stwo_cairo_prover/crates/prover/src/components/range_check_unit/component.rs#L1)):*
> ```XML
> use std::vec;
> ```

?



_Code quote:_
```XML
use std::vec;
```

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/131)* status: 7 of 11 files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/components/memory/prover.rs` line 171 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/131#-OAC52DyB9KBYYtZ19ct:-OAC7XHy6BunrvkHO_aN:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/26349e9096abe433131f65052c7e02c44945ae4f/stwo_cairo_prover/crates/prover/src/components/memory/prover.rs#L171)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I think you should have finalize_last() function
You should use that (in all places)
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_builtin/component.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/131#-OAC59UQ93NcGOKnBxaa:-OAC7soB6q7yOkaUbaYC:b-hre20h) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/26349e9096abe433131f65052c7e02c44945ae4f/stwo_cairo_prover/crates/prover/src/components/range_check_builtin/component.rs#L65)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Why is this change?
</blockquote></details>

[E::F ; N] attempts to copy 'E::F',and E::F is no longer copy,  
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_unit/component.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/131#-OAC5URq-uFYosC0tN_D:-OAC8H-o6FqWVqMs36MS:b-hfpv0l) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/26349e9096abe433131f65052c7e02c44945ae4f/stwo_cairo_prover/crates/prover/src/components/range_check_unit/component.rs#L1)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

?
</blockquote></details>

removed

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/131#-:-OACBu4yDApcj12OjXil:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ohad-starkware)

**Pull request merged**
