### PR TITLE
derive lookup_data

### PR DESCRIPTION
**Pull request by ohad-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/261)

### CODE REVIEW

**Comment by ohad-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/261?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#261** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/261?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/261?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#260** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/260?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Comment by ilyalesokhin-starkware** [comment]
*[`stwo_cairo_prover/crates/air_structs_derive/src/lib.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/261#-OENOYsj7Kdh5S_rMx2j:-OENOYsj7Kdh5S_rMx2k:b-r58bi1) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/dccdc01f2041386a3e359839f69e1bc511f4e4b8/stwo_cairo_prover/crates/air_structs_derive/src/lib.rs#L58)):*
> ```XML
> fn assert_is_struct(input: &DeriveInput) {
>     if !matches!(input.data, Data::Struct(_)) {
>         panic!("Derive(SubComponentInputs/LookupData) can only be applied to structs.");
> ```

I don't want this to be a list, and I think you get the error location from the compiler anyway, can you confirm?



_Suggestion:_
```XML
   panic!("Expected a struct");
```

**Comment by ilyalesokhin-starkware** [comment]
*[`stwo_cairo_prover/crates/air_structs_derive/src/lib.rs` line 62 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/261#-OENPRVw4Elo-sENOK_s:-OENPRVw4Elo-sENOK_t:bh5u559) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/dccdc01f2041386a3e359839f69e1bc511f4e4b8/stwo_cairo_prover/crates/air_structs_derive/src/lib.rs#L62)):*
> ```XML
> }
> 
> fn extract_vec_array_fields(input: &DeriveInput) -> Vec<VecArrayField> {
> ```

Can you fix the input to be a struct?



_Suggestion:_
```XML
strct: &DataStruct
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 8 of 26 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/261)* status: 8 of 26 files reviewed, 3 unresolved discussions (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/crates/air_structs_derive/src/lib.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/261#-OENPhew6QDAaZgb8r_m:-OENPhew6QDAaZgb8r_n:b750iln) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/dccdc01f2041386a3e359839f69e1bc511f4e4b8/stwo_cairo_prover/crates/air_structs_derive/src/lib.rs#L30)):*
> ```XML
> 
> #[proc_macro_derive(LookupData)]
> pub fn derive_lookup_data(input: proc_macro::TokenStream) -> proc_macro::TokenStream {
> ```

are you sure this should be in stwo-cairo and not in stwo?



_Code quote:_
```XML
derive_lookup_data
```

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/261)* status: 8 of 26 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @ohad-starkware)

___
*[`stwo_cairo_prover/crates/air_structs_derive/src/lib.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/261#-OENPhew6QDAaZgb8r_m:-OEOXINdCodwtYedbY9r:b-2orkcs) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/dccdc01f2041386a3e359839f69e1bc511f4e4b8/stwo_cairo_prover/crates/air_structs_derive/src/lib.rs#L30)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

are you sure this should be in stwo-cairo and not in stwo?
</blockquote></details>

for now yes because airs in stwo do not share the same structure (sub components, add inputs etc) and I do want that logic to be all in the same place.
perhaps in the future, I added a todo
___
*[`stwo_cairo_prover/crates/air_structs_derive/src/lib.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/261#-OENOYsj7Kdh5S_rMx2j:-OEOWYO4A8n8Ef0y0bKw:b-m4n3es) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/dccdc01f2041386a3e359839f69e1bc511f4e4b8/stwo_cairo_prover/crates/air_structs_derive/src/lib.rs#L58)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I don't want this to be a list, and I think you get the error location from the compiler anyway, can you confirm?
</blockquote></details>

yes that is the case
done.
___
*[`stwo_cairo_prover/crates/air_structs_derive/src/lib.rs` line 62 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/261#-OENPRVw4Elo-sENOK_s:-OEOXlit8h_TJpzAhPn0:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/dccdc01f2041386a3e359839f69e1bc511f4e4b8/stwo_cairo_prover/crates/air_structs_derive/src/lib.rs#L62)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Can you fix the input to be a struct?
</blockquote></details>

Done.

**Pull request closed without merging**
