### PR TITLE
Rust fmt and clippy

### PR DESCRIPTION
**Pull request by shaharsamocha7**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/8)

### CODE REVIEW

**Comment by shaharsamocha7** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/8?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#8** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/8?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#7** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/7?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @shaharsamocha7 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/8)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`scripts/clippy.sh` line 3 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/8#-O-pwVh7A_pGY_LIRK-m:-O-qKfn27bpTCql140tU:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/54751ae7552bbda59e757bbbb1a114808f7d6075/scripts/clippy.sh#L3)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Line too long
</blockquote></details>

Done.

**Review by spapinistarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/8)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/8#-:-O096xixE1Ur5_CoCkAN:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Comment by shaharsamocha7** [comment]
### Merge activity

* **Jun 25, 3:00 AM EDT**: @shaharsamocha7 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/8).

**Pull request merged**
