### PR TITLE
add bool ops and change biguint supported types

### PR DESCRIPTION
**Pull request by anatgstarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/150)

### CODE REVIEW

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/150)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @anatgstarkware, @DavidLevitGurevich, and @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover_types/src/cpu.rs` line 614 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/150#-OAlwLLT35bisQ4PgQRj:-OAlwLLT35bisQ4PgQRk:bve7l6w) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/1fea24f3ecc815b6730e260c55dbe8456353e109/stwo_cairo_prover/crates/prover_types/src/cpu.rs#L614)):*
> ```XML
>             6 => "BigUInt<384, 6>".to_string(),
>             7 => "BigUInt<448, 7>".to_string(),
>             12 => "BigUInt<768, 12>".to_string(),
> ```

Don't we need 4,8 anymore?
Also, can we just format the expression x -> <64*x, x>?



_Code quote:_
```XML
            6 => "BigUInt<384, 6>".to_string(),
            7 => "BigUInt<448, 7>".to_string(),
            12 => "BigUInt<768, 12>".to_string(),
```

**Comment by anatgstarkware** [comment]
*[`stwo_cairo_prover/crates/prover_types/src/cpu.rs` line 614 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/150#-OAlwLLT35bisQ4PgQRj:-OAqfygA2oHeR_CYnA81:bqz7u8z) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/1fea24f3ecc815b6730e260c55dbe8456353e109/stwo_cairo_prover/crates/prover_types/src/cpu.rs#L614)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Don't we need 4,8 anymore?
Also, can we just format the expression x -> <64*x, x>?
</blockquote></details>

* We don't need 4 & 8
* AFAIK there's no way to do that in rust

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/150)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @anatgstarkware, @DavidLevitGurevich, and @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover_types/src/cpu.rs` line 614 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/150#-OAlwLLT35bisQ4PgQRj:-OAqoTpi56moeQUixDhJ:bytd72y) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/1fea24f3ecc815b6730e260c55dbe8456353e109/stwo_cairo_prover/crates/prover_types/src/cpu.rs#L614)):*
<details><summary><i>Previously, anatgstarkware (anatg) wrote…</i></summary><blockquote>

* We don't need 4 & 8
* AFAIK there's no way to do that in rust
</blockquote></details>

https://doc.rust-lang.org/std/fmt/

**Review by anatgstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/150)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @DavidLevitGurevich, @ohad-starkware, and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover_types/src/cpu.rs` line 614 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/150#-OAlwLLT35bisQ4PgQRj:-OB1o7KU4Obb2nFcxGv_:bm6rj1b) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/1fea24f3ecc815b6730e260c55dbe8456353e109/stwo_cairo_prover/crates/prover_types/src/cpu.rs#L614)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

https://doc.rust-lang.org/std/fmt/
</blockquote></details>

ahhh, done, thanks

**Comment by ohad-starkware** [comment]
-

**Review by ohad-starkware — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/150#-:-OB_T8WB2g2KLAICeUHH:bnfp4nl)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @DavidLevitGurevich and @shaharsamocha7)

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/150#-:-OB_b_8l79IsDBWEgf-w:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @DavidLevitGurevich)

**Pull request merged**
