### PR TITLE
Add PCS verifier

### PR DESCRIPTION
**Pull request by andrewmilson**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/173)

### CODE REVIEW

**Comment by andrewmilson** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/173?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#173** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/173?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/173?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#172** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/172?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#170** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/170?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#127](https://github.com/starkware-libs/stwo-cairo/pull/127) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/127?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/173)* status: all files reviewed, 2 unresolved discussions (waiting on @andrewmilson)

___
*[`stwo_cairo_verifier/src/pcs/verifier.cairo` line 109 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/173#-OBy_MXV46du6H85yvFM:-OBy_MXW-NfMRBvR4Jbn:bbvxuo9) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/17575620339442e42c63984b151e2173971d53e5/stwo_cairo_verifier/src/pcs/verifier.cairo#L109)):*
> ```Cairo
>         if channel.trailing_zeros() < *self.config.pow_bits {
>             return Result::Err(VerificationError::ProofOfWork);
>         }
> ```

Can you change that to your new channel api?



_Code quote:_
```Cairo
        if channel.trailing_zeros() < *self.config.pow_bits {
            return Result::Err(VerificationError::ProofOfWork);
        }
```
___
*[`stwo_cairo_verifier/src/pcs/verifier.cairo` line 275 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/173#-OByacxW9wBJBIM3P-6w:-OByacxW9wBJBIM3P-6x:b7mcvqd) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/17575620339442e42c63984b151e2173971d53e5/stwo_cairo_verifier/src/pcs/verifier.cairo#L275)):*
> ```Cairo
>     pub proof_of_work: u64,
>     pub fri_proof: FriProof,
> }
> ```

Can we move this struct declaration to top of file?
Also, can you explain the difference between sampled_values, queried_values? (I don't recall)



_Code quote:_
```Cairo
#[derive(Drop)]
pub struct CommitmentSchemeProof {
    pub sampled_values: TreeArray<ColumnArray<Array<QM31>>>,
    pub decommitments: TreeArray<MerkleDecommitment<PoseidonMerkleHasher>>,
    pub queried_values: TreeArray<ColumnArray<Array<M31>>>,
    pub proof_of_work: u64,
    pub fri_proof: FriProof,
}
```

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/173)* status: all files reviewed, 3 unresolved discussions (waiting on @andrewmilson)

___
*[`stwo_cairo_verifier/src/pcs/verifier.cairo` line 61 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/173#-OBz3KE393EvtmOAKc0b:-OBz3KE393EvtmOAKc0c:b-s5url3) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/17575620339442e42c63984b151e2173971d53e5/stwo_cairo_verifier/src/pcs/verifier.cairo#L61)):*
> ```Cairo
>     }
> 
>     // TODO(andrew): Introduce ColumnArray and TreeArray to make types less confusing.
> ```

You can remove this TODO, right?



_Code quote:_
```Cairo
// TODO(andrew): Introduce ColumnArray and TreeArray to make types less confusing.
```

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/173)* status: all files reviewed, 3 unresolved discussions (waiting on @andrewmilson)

___
*[`stwo_cairo_verifier/src/pcs/verifier.cairo` line 109 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/173#-OBy_MXV46du6H85yvFM:-OBz3Xae9QcRh2edHDkO:b4x4osv) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/17575620339442e42c63984b151e2173971d53e5/stwo_cairo_verifier/src/pcs/verifier.cairo#L109)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can you change that to your new channel api?
</blockquote></details>

I see it is in the next pr

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/173)* status: all files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7)

___
*[`stwo_cairo_verifier/src/pcs/verifier.cairo` line 61 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/173#-OBz3KE393EvtmOAKc0b:-OC-NZOoBqBeBCKHqQ7O:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/17575620339442e42c63984b151e2173971d53e5/stwo_cairo_verifier/src/pcs/verifier.cairo#L61)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

You can remove this TODO, right?
</blockquote></details>

Done.
___
*[`stwo_cairo_verifier/src/pcs/verifier.cairo` line 109 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/173#-OBy_MXV46du6H85yvFM:-OC-NOmG1VARqkNOF0b7:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/17575620339442e42c63984b151e2173971d53e5/stwo_cairo_verifier/src/pcs/verifier.cairo#L109)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I see it is in the next pr
</blockquote></details>

Done.
___
*[`stwo_cairo_verifier/src/pcs/verifier.cairo` line 275 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/173#-OByacxW9wBJBIM3P-6w:-OC-NPrE4CM9ZMZSW61U:b-rs5huu) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/17575620339442e42c63984b151e2173971d53e5/stwo_cairo_verifier/src/pcs/verifier.cairo#L275)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can we move this struct declaration to top of file?
Also, can you explain the difference between sampled_values, queried_values? (I don't recall)
</blockquote></details>

Done. Added docs.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/173#-:-OC-PF1104L9tv-K1lr4:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @andrewmilson)

**Pull request merged**
