### PR TITLE
Added range check to memory.

### PR DESCRIPTION
**Pull request by Alon-Ti**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/67)

### CODE REVIEW

**Comment by Alon-Ti** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/67?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#67** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/67?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#63** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/63?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#59** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/59?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Alon-Ti and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/67)* status: 2 of 9 files reviewed, 3 unresolved discussions (waiting on @Alon-Ti)

___
*[`stwo_cairo_prover/crates/prover/src/components/memory/component.rs` line 70 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/67#-O5mXblX2zjfTuhZG6Pq:-O5mXblX2zjfTuhZG6Pr:bpz5ryl) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/bb2f7c471bc583abc0e7d1d4cdc8a39c477cd6fe/stwo_cairo_prover/crates/prover/src/components/memory/component.rs#L70)):*
> ```XML
> 
>         // Range check elements.
>         for value in address_and_value[1..].iter() {
> ```

I think that this 1 should be a constant
Also below



_Suggestion:_
```XML
        // Range check elements, first value is the address
        for value in address_and_value.iter().skip(MEMORY_VALUES_OFFSET) {
```
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/prover.rs` line 163 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/67#-O5mY1JrBqV4y--q0yxm:-O5mY1JrBqV4y--q0yxn:bj36uv5) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/bb2f7c471bc583abc0e7d1d4cdc8a39c477cd6fe/stwo_cairo_prover/crates/prover/src/components/memory/prover.rs#L163)):*
> ```XML
>                 let value: PackedM31 = self.adresses_and_values[limb_idx][vec_row];
> 
>                 // TOOD(alont) add parametric chunks.
> ```

Don't we want to combine two of them?



_Code quote:_
```XML
// TOOD(alont) add parametric chunks.
```
___
*[`stwo_cairo_prover/crates/prover/src/input/mem.rs` line 106 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/67#-O5mZlOA3SARQavuIZty:-O5mZlOA3SARQavuIZtz:b5uyhnx) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/bb2f7c471bc583abc0e7d1d4cdc8a39c477cd6fe/stwo_cairo_prover/crates/prover/src/input/mem.rs#L106)):*
> ```XML
>     }
> 
>     pub fn iter_values(&self) -> impl Iterator<Item = MemoryValue> + '_ {
> ```

What's that?



_Code quote:_
```XML
pub fn iter_values(&self) -> impl Iterator<Item = MemoryValue> + '_ {
```

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 9 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/67)* status: 7 of 9 files reviewed, 8 unresolved discussions (waiting on @Alon-Ti and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs` line 266 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/67#-O5mZbk3AlcDWWZRbsuR:-O5mZbk3AlcDWWZRbsuS:bl13k5z) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/bb2f7c471bc583abc0e7d1d4cdc8a39c477cd6fe/stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs#L266)):*
> ```XML
>         &interaction_elements.range9_lookup,
>     );
> ```

Remove blank line
___
*[`stwo_cairo_prover/crates/prover/src/input/plain.rs` line 68 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/67#-O5mgWcbAFBWCufoTzt7:-O5mgWcbAFBWCufoTzt8:b-6goux) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/bb2f7c471bc583abc0e7d1d4cdc8a39c477cd6fe/stwo_cairo_prover/crates/prover/src/input/plain.rs#L68)):*
> ```XML
>     });
> 
>     let mut range_check9 = RangeCheckUnitInput::new();
> ```

I'm not sure the range_check9 has a public input. The memory should add inputs to it during trace generation.



_Code quote:_
```XML
let mut range_check9 = RangeCheckUnitInput::new();
```
___
*[`stwo_cairo_prover/crates/prover/src/input/range_check_unit.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/67#-O5mburi6k9_a-8Q2l6s:-O5mburi6k9_a-8Q2l6t:bflq5l4) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/bb2f7c471bc583abc0e7d1d4cdc8a39c477cd6fe/stwo_cairo_prover/crates/prover/src/input/range_check_unit.rs#L20)):*
> ```XML
>         for value in memory.iter_values() {
>             let value = split_f252(value.as_u256());
>             for limb in value {
> ```

Are you sure this is the fiiting term? It's confusing to me
How about just felt?



_Code quote:_
```XML
limb
```
___
*[`stwo_cairo_prover/crates/prover/src/input/range_check_unit.rs` line 28 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/67#-O5mfWDWBIKc9hJcr6La:-O5mfWDWBIKc9hJcr6Lb:b48vmvp) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/bb2f7c471bc583abc0e7d1d4cdc8a39c477cd6fe/stwo_cairo_prover/crates/prover/src/input/range_check_unit.rs#L28)):*
> ```XML
>     // Returns a 2D vector of SIMD vectors, where the first dimension is the repetition index and
>     // the second dimension is the SIMD vector of multiplicities.
>     pub fn to_2d_simd_vec<const LOG_HEIGHT: u32, const N_REPETITIONS: usize>(
> ```

Add unit test?



_Code quote:_
```XML
pub fn to_2d_simd_vec<const LOG_HEIGHT: u32, const N_REPETITIONS: usize>(
```
___
*[`stwo_cairo_prover/crates/prover/src/prover_types/mod.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/67#-O5mfnVwEeTpn8IXJcw0:-O5mfnVwEeTpn8IXJcw1:bopgos3) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/bb2f7c471bc583abc0e7d1d4cdc8a39c477cd6fe/stwo_cairo_prover/crates/prover/src/prover_types/mod.rs#L27)):*
> ```XML
> 
>     pub fn from_m31_array(arr: [m31::M31; N_LANES]) -> Self {
>         // Safe because UInt32 is u32.
> ```

Did you mean?



_Suggestion:_
```XML
M31
```

**Review by Alon-Ti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/67)* status: 0 of 11 files reviewed, 7 unresolved discussions (waiting on @alonh5 and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/components/memory/component.rs` line 70 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/67#-O5mXblX2zjfTuhZG6Pq:-O5xBubf36p-T1A627m0:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/bb2f7c471bc583abc0e7d1d4cdc8a39c477cd6fe/stwo_cairo_prover/crates/prover/src/components/memory/component.rs#L70)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I think that this 1 should be a constant
Also below
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/prover.rs` line 163 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/67#-O5mY1JrBqV4y--q0yxm:-O5xCHm78Uvnu_-ALL98:b-knlj7d) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/bb2f7c471bc583abc0e7d1d4cdc8a39c477cd6fe/stwo_cairo_prover/crates/prover/src/components/memory/prover.rs#L163)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Don't we want to combine two of them?
</blockquote></details>

Yes, I'm fixing the TOOD, will do this in the  next PR after I eliminate CHUNKS from logup.
___
*[`stwo_cairo_prover/crates/prover/src/input/mem.rs` line 106 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/67#-O5mZlOA3SARQavuIZty:-O5xCaHy7x7Nljx_fZkW:bzdrgj5) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/bb2f7c471bc583abc0e7d1d4cdc8a39c477cd6fe/stwo_cairo_prover/crates/prover/src/input/mem.rs#L106)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

What's that?
</blockquote></details>

It iterates over all the memory values,  I use it for `collect_from_memory` in the RC unit, this way when the memory changes to efficient memory the impl will be abstracted away from RC.
___
*[`stwo_cairo_prover/crates/prover/src/input/range_check_unit.rs` line 28 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/67#-O5mfWDWBIKc9hJcr6La:-O6Fh20E9qQ6suvNlsc6:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/bb2f7c471bc583abc0e7d1d4cdc8a39c477cd6fe/stwo_cairo_prover/crates/prover/src/input/range_check_unit.rs#L28)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Add unit test?
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/prover_types/mod.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/67#-O5mfnVwEeTpn8IXJcw0:-O61p2675rzhVQsyLVyh:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/bb2f7c471bc583abc0e7d1d4cdc8a39c477cd6fe/stwo_cairo_prover/crates/prover/src/prover_types/mod.rs#L27)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Did you mean?
</blockquote></details>

Done.

**Review by Alon-Ti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/67)* status: 0 of 11 files reviewed, 7 unresolved discussions (waiting on @alonh5 and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/input/range_check_unit.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/67#-O5mburi6k9_a-8Q2l6s:-O6Fh6ZPEx8JDXgilwW0:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/bb2f7c471bc583abc0e7d1d4cdc8a39c477cd6fe/stwo_cairo_prover/crates/prover/src/input/range_check_unit.rs#L20)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Are you sure this is the fiiting term? It's confusing to me
How about just felt?
</blockquote></details>

Done.

**Review by shaharsamocha7 — COMMENTED** [review]
> Reviewed 2 of 9 files at r3, 3 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/67)* status: 5 of 11 files reviewed, 4 unresolved discussions (waiting on @Alon-Ti and @alonh5)

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 7 of 9 files at r3, 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/67#-:-O6Fux2a8bh0wmXLuEH-:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Alon-Ti)

___
*[`stwo_cairo_prover/crates/prover/src/prover_types/mod.rs` line 27 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/67#-O6Fulwz9O6-lxz9sQVz:-O6Fulwz9O6-lxz9sQW-:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/70a2955fd96e0f44dc55353cf66ba473bcb2b553/stwo_cairo_prover/crates/prover/src/prover_types/mod.rs#L27)):*
> ```XML
> 
>     pub fn from_m31_array(arr: [m31::M31; N_LANES]) -> Self {
>         // Safe because M32 is u32.
> ```





_Suggestion:_
```XML
M31
```

**Review by shaharsamocha7 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/67)* status: all files reviewed, 1 unresolved discussion (waiting on @Alon-Ti)

**Pull request merged**
