### PR TITLE
fix bug in the adapter for small/big add and mul

### PR DESCRIPTION
**Pull request by Stavbe**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/225)

### CODE REVIEW

**Review by ohad-starkware — COMMENTED** [review]
sorry I didn't notice earlier, MemoryValue::small is not the same as your definition of small [-2^27, 2^27 -1]

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/225#-:-ODFexmc8vesIOi8z8Pv:bwnpgc5)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @DavidLevitGurevich and @shaharsamocha7)

**Review by Stavbe — COMMENTED** [review]
Fixed

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/225#-:-ODHQD4wE6Rq9ZkMGChF:b-886gsx)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @DavidLevitGurevich and @shaharsamocha7)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo-cairo/225#-ODFlIfV50MBlnLdijH_:-ODHQEPC0XbzzSZFV3KF:b-yts6iv) (no related file):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Would we find this bug if the tests weren't ignored?
If not, can you add a unit test for this specific scenario?
</blockquote></details>

No, the test passes when not ignored.  
We needed all the components to be integrated with stwo so we could create a proof and perform verification to ensure the adapter is sorted correctly. Now that it’s happening, I will work on this test.

**Review by ohad-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/225)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @DavidLevitGurevich, @shaharsamocha7, and @Stavbe)

___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 8 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/225#-ODKf1fO1laNN5hPhelB:-ODKf1fP27Eybtxkf_ML:b-mn7wpi) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ace6b6a00135993ed996902b3fa1c57c792f1e43/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L8)):*
> ```XML
> use super::vm_import::TraceEntry;
> 
> const SMALL_MAX_VALUE: i128 = 134217727;
> ```

const functions gets evaluated at compile time 



_Suggestion:_
```XML
2.pow(27) - 1
```
___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 8 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/225#-ODKfDeTCLiFleph0dlC:-ODKfDeTCLiFleph0dlD:bx5m4v) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ace6b6a00135993ed996902b3fa1c57c792f1e43/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L8)):*
> ```XML
> use super::vm_import::TraceEntry;
> 
> const SMALL_MAX_VALUE: i128 = 134217727;
> ```

64 bit?



_Code quote:_
```XML
i128
```
___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 592 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/225#-ODKfIxP-H2MZoKNzCAf:-ODKfIxP-H2MZoKNzCAg:b55v0iz) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ace6b6a00135993ed996902b3fa1c57c792f1e43/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L592)):*
> ```XML
> }
> 
> /// Checks if all the operands are within the range of [-2^27, 2^27 - 1].
> ```

you don't need /// for sub routines



_Suggestion:_
```XML
//
```

**Review by Stavbe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/225)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @DavidLevitGurevich, @ohad-starkware, and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 8 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/225#-ODKfDeTCLiFleph0dlC:-ODL5MbUDBKcfMIs3igl:b-uq9db4) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ace6b6a00135993ed996902b3fa1c57c792f1e43/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L8)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

64 bit?
</blockquote></details>

Even 32
___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 8 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/225#-ODKf1fO1laNN5hPhelB:-ODL5u8Z18prFL-zqOKM:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ace6b6a00135993ed996902b3fa1c57c792f1e43/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L8)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

const functions gets evaluated at compile time
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 592 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/225#-ODKfIxP-H2MZoKNzCAf:-ODL5uRf0jmfsgNx76W8:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ace6b6a00135993ed996902b3fa1c57c792f1e43/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L592)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

you don't need /// for sub routines
</blockquote></details>

Done.

**Review by ohad-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/225)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @DavidLevitGurevich, @shaharsamocha7, and @Stavbe)

___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 8 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/225#-ODKfDeTCLiFleph0dlC:-ODL7JeYC5K9Y46uIOGF:b-46i6b8) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ace6b6a00135993ed996902b3fa1c57c792f1e43/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L8)):*
<details><summary><i>Previously, Stavbe wrote…</i></summary><blockquote>

Even 32
</blockquote></details>

im supid, thought 27+27 is 54 but it's really 28
___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 8 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/225#-ODKf1fO1laNN5hPhelB:-ODL8VtvA3Yw3nJepaQ_:b-4hvula) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ace6b6a00135993ed996902b3fa1c57c792f1e43/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L8)):*
<details><summary><i>Previously, Stavbe wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nice, document this const to avoid confusion with the other small
___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 498 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/225#-ODL9Xru4eZukImcY8Vh:-ODL9Xru4eZukImcY8Vi:b-k0fs7r) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/45f253fe4b01ef9505734582b8d3f8ddaecff116/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L498)):*
> ```XML
>             } if !dev_mode => {
>                 let dst_addr = if dst_base_fp { fp } else { ap };
>                 let dst = mem.get(dst_addr.0.checked_add_signed(offset0 as i32).unwrap());
> ```

you have redundent control flow here - checked_add and .unwrap both check the same thing
refactor?
___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 502 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/225#-ODL9SgC9DEpKV9QF0EM:-ODL9SgD9fo-ZeQjUads:b-r611zn) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/45f253fe4b01ef9505734582b8d3f8ddaecff116/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L502)):*
> ```XML
>                 let op0 = mem.get(op0_addr.0.checked_add_signed(offset1 as i32).unwrap());
>                 let op1_addr = if op1_base_fp { fp } else { ap };
>                 let op1 = mem.get(op1_addr.0.checked_add_signed(offset2 as i32).unwrap());
> ```

non blocking



_Suggestion:_
```XML
                let (dst_addr, op0_addr, op1_addr) = (
                    if dst_base_fp { fp } else { ap },
                    if op0_base_fp { fp } else { ap },
                    if op1_base_fp { fp } else { ap },
                );
                let (dst, op0, op1) = (
                    mem.get(dst_addr.0.checked_add_signed(offset0 as i32).unwrap()),
                    mem.get(op0_addr.0.checked_add_signed(offset1 as i32).unwrap()),
                    mem.get(op1_addr.0.checked_add_signed(offset2 as i32).unwrap()),
                );
```
___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 592 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/225#-ODLA14D5X_h58_DDunt:-ODLA14D5X_h58_DDunu:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/45f253fe4b01ef9505734582b8d3f8ddaecff116/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L592)):*
> ```XML
> }
> 
> // Checks if all the operands are within the range of [-2^27, 2^27 - 1].
> ```





_Suggestion:_
```XML
Returns `true`
```
___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 599 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/225#-ODLAAh93YTYjhv6djCZ:-ODLAAh93YTYjhv6djC_:b-77c4p6) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/45f253fe4b01ef9505734582b8d3f8ddaecff116/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L599)):*
> ```XML
> // Checks if the a memory value is within the range of [-2^27, 2^27 - 1].
> fn is_small(val: MemoryValue) -> bool {
>     matches!(val, MemoryValue::Small(val) if (val as i32 >= SMALL_MIN_VALUE) && (val as i32<= SMALL_MAX_VALUE))
> ```

I think this can cause overflow and bugs?
val is 128 bit, maybe you can cast SMALL_MIN_VALUE instead?



_Code quote:_
```XML
val as i32
```

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/225)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @DavidLevitGurevich, @shaharsamocha7, and @Stavbe)

___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 498 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/225#-ODL9Xru4eZukImcY8Vh:-ODLGJvPAVjRKJdXs3us:b-ujpp53) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/45f253fe4b01ef9505734582b8d3f8ddaecff116/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L498)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

you have redundent control flow here - checked_add and .unwrap both check the same thing
refactor?
</blockquote></details>

nevermind

**Review by Stavbe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/225)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @DavidLevitGurevich, @ohad-starkware, and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 8 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/225#-ODKf1fO1laNN5hPhelB:-ODLCrpo0FwMo5RpDCGb:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ace6b6a00135993ed996902b3fa1c57c792f1e43/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L8)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

nice, document this const to avoid confusion with the other small
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 8 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/225#-ODKfDeTCLiFleph0dlC:-ODLCscL1RXhCOiNIkOx:b-wrlua2) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ace6b6a00135993ed996902b3fa1c57c792f1e43/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L8)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

im supid, thought 27+27 is 54 but it's really 28
</blockquote></details>

Youre smart
___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 502 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/225#-ODL9SgC9DEpKV9QF0EM:-ODLErlN5Jwz8uP21oB9:bpzgyxd) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/45f253fe4b01ef9505734582b8d3f8ddaecff116/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L502)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

non blocking
</blockquote></details>

Match better!
___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 599 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/225#-ODLAAh93YTYjhv6djCZ:-ODLF1EFEHNRwf7JkwxC:b-9c8hzx) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/45f253fe4b01ef9505734582b8d3f8ddaecff116/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L599)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

I think this can cause overflow and bugs?
val is 128 bit, maybe you can cast SMALL_MIN_VALUE instead?
</blockquote></details>

I need to convert itto a sign value

**Review by ohad-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/225)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @DavidLevitGurevich, @shaharsamocha7, and @Stavbe)

___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 599 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/225#-ODLAAh93YTYjhv6djCZ:-ODLZwy6966KCCtEmM2z:bjprxga) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/45f253fe4b01ef9505734582b8d3f8ddaecff116/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L599)):*
<details><summary><i>Previously, Stavbe wrote…</i></summary><blockquote>

I need to convert itto a sign value
</blockquote></details>

oh i see
___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 607 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/225#-ODL_Lwl4QQPSFtFhF4m:-ODL_LwmBfnyAv98zvWJ:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/a4c58321bbc83f47a3619baaf5c67a11d7e76943/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L607)):*
> ```XML
> }
> 
> // Returns 'true' if the a memory value is within the range of [-2^27, 2^27 - 1].
> ```

**Review by ohad-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/225)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @DavidLevitGurevich, @shaharsamocha7, and @Stavbe)

___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 216 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/225#-ODL_UHv4u3r6DWvi5E_:-ODL_UHv4u3r6DWvi5Ea:bh69jqc) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/45f253fe4b01ef9505734582b8d3f8ddaecff116/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L216)):*
> ```XML
>     }
> 
>     // When not ignored, the test passes only with dev_mod = false.
> ```

add a todo to remove that doc when possible



_Code quote:_
```XML
// When not ignored, the test passes only with dev_mod = false.
```

**Review by Stavbe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/225)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @DavidLevitGurevich, @ohad-starkware, and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 216 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/225#-ODL_UHv4u3r6DWvi5E_:-ODLcN0t-rItlgajbIqQ:bfzhope) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/45f253fe4b01ef9505734582b8d3f8ddaecff116/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L216)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

add a todo to remove that doc when possible
</blockquote></details>

I put it on you because you will delete dev_mod...

**Review by ohad-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/225#-:-ODLf2YO8Fz7p4SE_cVo:bnfp4nl)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @DavidLevitGurevich and @shaharsamocha7)

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/225)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @DavidLevitGurevich)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo-cairo/225#-ODFlIfV50MBlnLdijH_:-ODLgSBp7vX4cNYT3rqj:b111fnw) (no related file):*
<details><summary><i>Previously, Stavbe wrote…</i></summary><blockquote>

No, the test passes when not ignored.  
We needed all the components to be integrated with stwo so we could create a proof and perform verification to ensure the adapter is sorted correctly. Now that it’s happening, I will work on this test.
</blockquote></details>

The test that you suggesting will also check the flow of generating the trace and apply the constraints?
It is a good test, but IMO this is e2e test.
I think we should also have test that only checks the adapter behaviour

Anyway, unblocking.

**Review by shaharsamocha7 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/225)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @DavidLevitGurevich)

**Review by shaharsamocha7 — APPROVED** [review]

**Pull request merged**
