### PR TITLE
Add PoW check to channel

### PR DESCRIPTION
**Pull request by andrewmilson**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/172)

### CODE REVIEW

**Comment by andrewmilson** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/172?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#173** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/173?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#172** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/172?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/172?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#170** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/170?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#127](https://github.com/starkware-libs/stwo-cairo/pull/127) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/127?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/172)* status: all files reviewed, 3 unresolved discussions (waiting on @andrewmilson)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo-cairo/172#-OByWDa48zSi9oDqxA_-:-OByWDa48zSi9oDqxA_0:b-2sptw5) (no related file):*
Why do we check the proof of work on the digest directly?
Don't we want to hash the digest with some salt and then check that the hash result has n_bits pow bits?
___
*[`stwo_cairo_verifier/src/channel.cairo` line 11 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/172#-OByVQV13igu64JAn9m4:-OByVQV28qQcShLcz2T5:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/39dd175680aa8b3a6d9f5efb38451716cd733427/stwo_cairo_verifier/src/channel.cairo#L11)):*
> ```Cairo
> 
> /// Equals `2^31`.
> const M31_SHIFT: felt252 = 0x80000000;
> ```





_Suggestion:_
```Cairo
const M31_SHIFT: felt252 = 0x80000000; // 2^31.
```
___
*[`stwo_cairo_verifier/src/channel.cairo` line 150 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/172#-OByVoQV7CUviE1ILQBl:-OByVoQV7CUviE1ILQBm:b-7yd83l) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/39dd175680aa8b3a6d9f5efb38451716cd733427/stwo_cairo_verifier/src/channel.cairo#L150)):*
> ```Cairo
>         let u256 { low, .. } = (*self.digest).into();
>         low & gen_bit_mask(n_bits) == 0
>     }
> ```

Should we test this function directly?



_Code quote:_
```Cairo
    fn check_proof_of_work(self: @Channel, n_bits: u32) -> bool {
        let u256 { low, .. } = (*self.digest).into();
        low & gen_bit_mask(n_bits) == 0
    }
```

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/172)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo-cairo/172#-OByWDa48zSi9oDqxA_-:-OBzSSVw7nUeiOXPKyW2:b43on51) (no related file):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Why do we check the proof of work on the digest directly?
Don't we want to hash the digest with some salt and then check that the hash result has n_bits pow bits?
</blockquote></details>

Currently it happens in two parts: (1) channel seeded with nonce (2) check proof of work bits on the digest.
___
*[`stwo_cairo_verifier/src/channel.cairo` line 150 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/172#-OByVoQV7CUviE1ILQBl:-OBzR4M8DGmojx2_a6Dg:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/39dd175680aa8b3a6d9f5efb38451716cd733427/stwo_cairo_verifier/src/channel.cairo#L150)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Should we test this function directly?
</blockquote></details>

Done.
___
*[`stwo_cairo_verifier/src/channel.cairo` line 11 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/172#-OByVQV13igu64JAn9m4:-OBzQYjOE_HteLjxpWvS:b-nli5jn) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/39dd175680aa8b3a6d9f5efb38451716cd733427/stwo_cairo_verifier/src/channel.cairo#L11)):*
> ```Cairo
> 
> /// Equals `2^31`.
> const M31_SHIFT: felt252 = 0x80000000;
> ```

The reason I don't like comments like this because they aren't helpful in the IDE. With the new comment if I hover over the variable somewhere it has the popup with "Equals 2^31" which I find helpful. WDYT?

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/172#-:-OC-Oh3z9W1c1ErpOabb:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @andrewmilson)

___
*[`stwo_cairo_verifier/src/channel.cairo` line 11 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/172#-OByVQV13igu64JAn9m4:-OC-OHIa27ekkS0j1Hi8:b-yqby2g) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/39dd175680aa8b3a6d9f5efb38451716cd733427/stwo_cairo_verifier/src/channel.cairo#L11)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

The reason I don't like comments like this because they aren't helpful in the IDE. With the new comment if I hover over the variable somewhere it has the popup with "Equals 2^31" which I find helpful. WDYT?
</blockquote></details>

Really? I don't have that IDE thing.
I'm cool with your choice (I guess you need the comment twice for that which is also annoying)

Unblocking

**Pull request merged**
