### PR TITLE
code refactoring and component ordering

### PR DESCRIPTION
**Pull request by ohad-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/177)

### CODE REVIEW

**Comment by ohad-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/177?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#177** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/177?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/177?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#178** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/178?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 9 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/177)* status: all files reviewed, 8 unresolved discussions (waiting on @ohad-starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo-cairo/177#-OC3zeTJ4Zlysf47W89z:-OC3zeTJ4Zlysf47W8A-:b-wq9za7) (no related file):*
Nice Pr!
___
*[`stwo_cairo_prover/crates/prover/src/components/verifyinstruction/prover.rs` line 64 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/177#-OC3zIko8IHccrEHfU8C:-OC3zIko8IHccrEHfU8D:b-643eqp) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/9090988b8b1286ccde20fa65cd2f1f4f47aee981/stwo_cairo_prover/crates/prover/src/components/verifyinstruction/prover.rs#L64)):*
> ```XML
> 
>         memoryaddresstoid_state
>             .add_inputs(&sub_components_inputs.memoryaddresstoid_inputs[..n_calls]);
> ```

this was not really used as the memory_address_to_id trace was already written.
Writing to document



_Code quote:_
```XML
        memoryaddresstoid_state
            .add_inputs(&sub_components_inputs.memoryaddresstoid_inputs[..n_calls]);
```
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/air.rs` line 76 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/177#-OC3uBAAA8Tw-At699YP:-OC3uBAAA8Tw-At699YQ:b-jimjls) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/19dc8d2fad64a1fdea48399d0f04933002c2a60b/stwo_cairo_prover/crates/prover/src/cairo_air/air.rs#L76)):*
> ```XML
> }
> 
> pub struct AuxData {
> ```

Document



_Suggestion:_
```XML
pub struct PublicData {
```
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/air.rs` line 82 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/177#-OC3tqupDAqhkZZIQK0f:-OC3tqupDAqhkZZIQK0g:bg4cebv) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/19dc8d2fad64a1fdea48399d0f04933002c2a60b/stwo_cairo_prover/crates/prover/src/cairo_air/air.rs#L82)):*
> ```XML
> }
> 
> pub struct CairoClaimGenerator {
> ```

We need to write something about the order of those components.
Do you think this should be documented in the beginning of the file?

Not for this pr 



_Code quote:_
```XML
pub struct CairoClaimGenerator {
```
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/air.rs` line 83 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/177#-OC3uLWrEfNQ7bvAuXGy:-OC3uLWrEfNQ7bvAuXGz:beu44mh) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/19dc8d2fad64a1fdea48399d0f04933002c2a60b/stwo_cairo_prover/crates/prover/src/cairo_air/air.rs#L83)):*
> ```XML
> 
> pub struct CairoClaimGenerator {
>     aux_data: AuxData,
> ```

rename everywhere



_Suggestion:_
```XML
public_data: PublicData
```
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/air.rs` line 91 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/177#-OC3yER_6Mcx0brx_fB0:-OC3yER_6Mcx0brx_fB1:b-w399w8) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/19dc8d2fad64a1fdea48399d0f04933002c2a60b/stwo_cairo_prover/crates/prover/src/cairo_air/air.rs#L91)):*
> ```XML
>     range_check_7_2_5_trace_generator: range_check_7_2_5::ClaimGenerator,
>     range_check_4_3_trace_generator: range_check_4_3::ClaimGenerator,
>     // ...
> ```

Can you add such comments so in the future we will know where to add new components?



_Suggestion:_
```XML
    aux_data: AuxData,
    // Opcodes.
    ret_trace_generator: ret_opcode::ClaimGenerator,
    
    // Internal components.
    verify_instruction_trace_generator: verifyinstruction::ClaimGenerator,
    memory_addr_to_id_trace_generator: addr_to_id::ClaimGenerator,
    memory_id_to_value_trace_generator: id_to_f252::ClaimGenerator,
    
    // Const tables
    range_check_9_9_trace_generator: range_check_9_9::ClaimGenerator,
    range_check_7_2_5_trace_generator: range_check_7_2_5::ClaimGenerator,
    range_check_4_3_trace_generator: range_check_4_3::ClaimGenerator,
    // ...
```
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/air.rs` line 174 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/177#-OC3yhBR1l6QwaZsapxm:-OC3yhBS7gWdgybaxC89:b-g38c00) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/19dc8d2fad64a1fdea48399d0f04933002c2a60b/stwo_cairo_prover/crates/prover/src/cairo_air/air.rs#L174)):*
> ```XML
>                 public_memory: self.aux_data.public_memory,
>                 initial_state: self.aux_data.initial_state,
>                 final_state: self.aux_data.final_state,
> ```

I think that CairoClaim can just get the public_data



_Code quote:_
```XML
                public_memory: self.aux_data.public_memory,
                initial_state: self.aux_data.initial_state,
                final_state: self.aux_data.final_state,
```
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/air.rs` line 250 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/177#-OC3ywlA99ln8L2e8RKy:-OC3ywlA99ln8L2e8RKz:b-p977y0) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/19dc8d2fad64a1fdea48399d0f04933002c2a60b/stwo_cairo_prover/crates/prover/src/cairo_air/air.rs#L250)):*
> ```XML
> 
>         CairoInteractionClaim {
>             ret: vec![ret_interaction_claim],
> ```

Why does it get a vector?



_Code quote:_
```XML
            ret: vec![ret_interaction_claim],
```

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/177)* status: all files reviewed, 6 unresolved discussions (waiting on @shaharsamocha7)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo-cairo/177#-OC3zeTJ4Zlysf47W89z:-OC7RuaHAF63ewywGaeF:b32vhw) (no related file):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Nice Pr!
</blockquote></details>

:)
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/air.rs` line 76 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/177#-OC3uBAAA8Tw-At699YP:-OC43tSQ5VMr3vf_CyP4:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/19dc8d2fad64a1fdea48399d0f04933002c2a60b/stwo_cairo_prover/crates/prover/src/cairo_air/air.rs#L76)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Document
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/air.rs` line 82 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/177#-OC3tqupDAqhkZZIQK0f:-OC44v2h9h2Kn5GlHak6:bfmtvpv) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/19dc8d2fad64a1fdea48399d0f04933002c2a60b/stwo_cairo_prover/crates/prover/src/cairo_air/air.rs#L82)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

We need to write something about the order of those components.
Do you think this should be documented in the beginning of the file?

Not for this pr
</blockquote></details>

I wrote something small but this should be given more respect.
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/air.rs` line 83 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/177#-OC3uLWrEfNQ7bvAuXGy:-OC44OosCuR2d8XlqG7X:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/19dc8d2fad64a1fdea48399d0f04933002c2a60b/stwo_cairo_prover/crates/prover/src/cairo_air/air.rs#L83)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

rename everywhere
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/air.rs` line 91 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/177#-OC3yER_6Mcx0brx_fB0:-OC456Va5JLlFL_4Wegs:b-t3jdp8) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/19dc8d2fad64a1fdea48399d0f04933002c2a60b/stwo_cairo_prover/crates/prover/src/cairo_air/air.rs#L91)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can you add such comments so in the future we will know where to add new components?
</blockquote></details>

they are not really const tables
they are last because everybody lookups those
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/air.rs` line 174 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/177#-OC3yhBR1l6QwaZsapxm:-OC7RrbG70KwXUDAOHI2:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/19dc8d2fad64a1fdea48399d0f04933002c2a60b/stwo_cairo_prover/crates/prover/src/cairo_air/air.rs#L174)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I think that CairoClaim can just get the public_data
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/air.rs` line 250 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/177#-OC3ywlA99ln8L2e8RKy:-OC43Eqb0yae72nFu8iI:be5k4t8) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/19dc8d2fad64a1fdea48399d0f04933002c2a60b/stwo_cairo_prover/crates/prover/src/cairo_air/air.rs#L250)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Why does it get a vector?
</blockquote></details>

they all should
I can change it in a different pr, 
or wait a few days until the split to components thing is implemented (I think it's soon)

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/177#-:-OC7_FdCAyEMKO_-vozk:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ohad-starkware)

**Pull request merged**
