### PR TITLE
Update stwo version

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/40)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
* **#40** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/40?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/40)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`stwo_cairo_prover/Cargo.toml` line 10 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/40#-O3ahDAg69m7FcDBwwq8:-O3ahDAg69m7FcDBwwq9:b-zd35c8) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/35d4a700bae57861bfcb9ebeb96b7f0808869e0c/stwo_cairo_prover/Cargo.toml#L10)):*
> ```TOML
> num-traits = "0.2.17"
> # TODO(ShaharS): take stwo version from the source repository.
> stwo-prover = { git = "https://github.com/starkware-libs/stwo", rev = "b4c2153d" }
> ```

This branch is not on dev.



_Code quote:_
```TOML
b4c2153d
```
___
*[`stwo_cairo_prover/src/components/memory/mod.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/40#-O3ahPWm-FifeWOYZ4eZ:-O3ahPWm-FifeWOYZ4e_:bnhtj65) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/35d4a700bae57861bfcb9ebeb96b7f0808869e0c/stwo_cairo_prover/src/components/memory/mod.rs#L10)):*
> ```XML
> pub const N_VALUE_FELTS: usize = FELT_BITS.div_ceil(N_BITS_PER_FELT);
> 
> pub type MemoryElements = LookupElements<{ 1 + N_VALUE_FELTS }>;
> ```

I have N_ADDRESS_FELTS const in the RCBuiltin component.
Do we want to move it here?



_Code quote:_
```XML
1 + 
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/40)* status: 6 of 8 files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7)

___
*[`stwo_cairo_prover/Cargo.toml` line 10 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/40#-O3ahDAg69m7FcDBwwq8:-O3aiQDeBn_ewkOED5Y5:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/35d4a700bae57861bfcb9ebeb96b7f0808869e0c/stwo_cairo_prover/Cargo.toml#L10)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

This branch is not on dev.
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/src/components/memory/mod.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/40#-O3ahPWm-FifeWOYZ4eZ:-O3ainyN3YftN-BZQd3W:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/35d4a700bae57861bfcb9ebeb96b7f0808869e0c/stwo_cairo_prover/src/components/memory/mod.rs#L10)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I have N_ADDRESS_FELTS const in the RCBuiltin component.
Do we want to move it here?
</blockquote></details>

Done.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/40#-:-O3aiz_62G8aYu9J3PzC:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
