### PR TITLE
Remove pow function

### PR DESCRIPTION
**Pull request by andrewmilson**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/184)

### CODE REVIEW

**Comment by andrewmilson** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/184?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#184** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/184?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/184?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#164** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/164?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#174** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/174?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#163** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/163?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#162** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/162?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#137** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/137?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#138](https://github.com/starkware-libs/stwo-cairo/pull/138) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/138?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#135** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/135?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#134** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/134?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#153** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/153?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 6 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/184#-:-OC7AM7B4Xzdd5XFdBHF:bnfp4nl)* status: 6 of 7 files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/184)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @andrewmilson and @ilyalesokhin-starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo-cairo/184#-OC7eCH578ymxXazRdDr:-OC7eCH578ymxXazRdDs:bgvcdlw) (no related file):*
Actually we can implement mul_by_2_power (actually this goes down to circ_left)
Not sure if this would yield a better impl

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/184)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @shaharsamocha7)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo-cairo/184#-OC7eCH578ymxXazRdDr:-OCE74Rh71V_jcDzZ1cc:b-76ap8k) (no related file):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Actually we can implement mul_by_2_power (actually this goes down to circ_left)
Not sure if this would yield a better impl
</blockquote></details>

By circ_left do you mean left shift? I don't think Cairo has this operation

**Pull request merged**
