### PR TITLE
Bump stwo-prover version.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/157)

### CODE REVIEW

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/157)* status: all files reviewed, 6 unresolved discussions (waiting on @Alon-Ti, @andrewmilson, @ilyalesokhin-starkware, and @ohad-starkware)

___
*[`stwo_cairo_prover/Cargo.toml` line 33 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/157#-OBUJZhs4KMo3ea_E_YO:-OBUJZhs4KMo3ea_E_YP:buqftaw) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3273cf43f905e7820224e770f44de5b7b7a93170/stwo_cairo_prover/Cargo.toml#L33)):*
> ```TOML
> sonic-rs = "0.3.10"
> # TODO(ShaharS): take stwo version from the source repository.
> stwo-prover = { git = "https://github.com/starkware-libs/stwo", rev = "796bcdf" }
> ```

Is this on top of dev?



_Code quote:_
```TOML
"796bcdf"
```
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/id_to_f252/component.rs` line 103 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/157#-OBUMHwQ5N555p0BdQ4-:-OBUMHwQ5N555p0BdQ40:b-wrp0cp) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3273cf43f905e7820224e770f44de5b7b7a93170/stwo_cairo_prover/crates/prover/src/components/memory/id_to_f252/component.rs#L103)):*
> ```XML
> impl Claim {
>     pub fn log_sizes(&self) -> TreeVec<Vec<u32>> {
>         let preprocessed_log_sizes = vec![self.log_size];
> ```

Why do we need `preprocessed_log_sizes` at all if we are going to ignore that?
Do you plan to remove it in a later pr?



_Code quote:_
```XML
 let preprocessed_log_sizes = vec![self.log_size];
```
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_vector/component_prover.rs` line 180 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/157#-OBUN-dg7HBi46EsmzJi:-OBUN-dg7HBi46EsmzJj:b-l6mkjh) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3273cf43f905e7820224e770f44de5b7b7a93170/stwo_cairo_prover/crates/prover/src/components/range_check_vector/component_prover.rs#L180)):*
> ```XML
>         // Preprocessed trace.
>         let mut tree_builder = commitment_scheme.tree_builder();
>         let range_check_constant_trace = gen_is_first::<SimdBackend>(LOG_HEIGHT);
> ```

rename



_Suggestion:_
```XML
let range_check_preprocessed_trace = gen_is_first::<SimdBackend>(LOG_HEIGHT);
```
___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/157#-OBUM-Ye2v6zdFNegEmQ:-OBUM-Ye2v6zdFNegEmR:b-og7xt0) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3273cf43f905e7820224e770f44de5b7b7a93170/stwo_cairo_prover/crates/prover/src/components/mod.rs#L10)):*
> ```XML
> 
> // TODO(ShaharS): Move to a common file.
> pub const LOOKUP_INTERACTION_PHASE: usize = INTERACTION_TRACE_IDX;
> ```

I think that this constant can be removed now and use `INTERACTION_TRACE_IDX` directly



_Code quote:_
```XML
// TODO(ShaharS): Move to a common file.
pub const LOOKUP_INTERACTION_PHASE: usize = INTERACTION_TRACE_IDX;
```
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/157#-OBUJt7h1lE-vzg_bBlP:-OBUJt7h1lE-vzg_bBlQ:b-l6mkjh) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3273cf43f905e7820224e770f44de5b7b7a93170/stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs#L61)):*
> ```XML
> 
>     pub fn log_sizes(&self) -> TreeVec<Vec<u32>> {
>         let mut log_size = TreeVec::concat_cols(chain!(
> ```

rename



_Suggestion:_
```XML
let mut log_sizes = TreeVec::concat_cols(chain!(
```
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/157#-OBUK-Lq5j9JMLF99bD8:-OBUK-Lq5j9JMLF99bD9:b-k9lq1j) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3273cf43f905e7820224e770f44de5b7b7a93170/stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs#L71)):*
> ```XML
>         // Overwrite the preprocessed trace log sizes.
>         log_size[PREPROCESSED_TRACE_IDX] = IS_FIRST_LOG_SIZES.to_vec();
>         log_size
> ```

How other types of constant columns will be added here?
Eventually, we want to sort the columns of this tree by size, no?



_Code quote:_
```XML
        // Overwrite the preprocessed trace log sizes.
        log_size[PREPROCESSED_TRACE_IDX] = IS_FIRST_LOG_SIZES.to_vec();
        log_size
```

**Comment by ilyalesokhin-starkware** [comment]
*[`stwo_cairo_prover/crates/prover/src/components/memory/id_to_f252/component.rs` line 103 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/157#-OBUMHwQ5N555p0BdQ4-:-OBUym5DEUI9CT_-BqBo:b-wsxyk5) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3273cf43f905e7820224e770f44de5b7b7a93170/stwo_cairo_prover/crates/prover/src/components/memory/id_to_f252/component.rs#L103)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Why do we need `preprocessed_log_sizes` at all if we are going to ignore that?
Do you plan to remove it in a later pr?
</blockquote></details>

I don't know what to return in this function.
if you test the component on its on than the value is needed

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/157)* status: all files reviewed, 6 unresolved discussions (waiting on @Alon-Ti, @andrewmilson, @ilyalesokhin-starkware, and @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/components/memory/id_to_f252/component.rs` line 103 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/157#-OBUMHwQ5N555p0BdQ4-:-OBV-5UsAylg3WbmKnKm:b-t3ht5v) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3273cf43f905e7820224e770f44de5b7b7a93170/stwo_cairo_prover/crates/prover/src/components/memory/id_to_f252/component.rs#L103)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I don't know what to return in this function.
if you test the component on its on than the value is needed
</blockquote></details>

I see, right.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/157)* status: 9 of 13 files reviewed, 5 unresolved discussions (waiting on @Alon-Ti, @andrewmilson, @ohad-starkware, and @shaharsamocha7)

___
*[`stwo_cairo_prover/Cargo.toml` line 33 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/157#-OBUJZhs4KMo3ea_E_YO:-OBV-Bjf201KZ0BdbN_0:bb7f2mf) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3273cf43f905e7820224e770f44de5b7b7a93170/stwo_cairo_prover/Cargo.toml#L33)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Is this on top of dev?
</blockquote></details>

done
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/157#-OBUJt7h1lE-vzg_bBlP:-OBV-RZdBzoY8STy7sUn:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3273cf43f905e7820224e770f44de5b7b7a93170/stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs#L61)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

rename
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/157#-OBUK-Lq5j9JMLF99bD8:-OBUycL56X_maxsI4yDf:b-axyexr) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3273cf43f905e7820224e770f44de5b7b7a93170/stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs#L71)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

How other types of constant columns will be added here?
Eventually, we want to sort the columns of this tree by size, no?
</blockquote></details>

Not sure yet, lets merge it like this and fix it in the future.
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_vector/component_prover.rs` line 180 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/157#-OBUN-dg7HBi46EsmzJi:-OBV-hvD674BxOF4YY8h:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3273cf43f905e7820224e770f44de5b7b7a93170/stwo_cairo_prover/crates/prover/src/components/range_check_vector/component_prover.rs#L180)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

rename
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/157)* status: 7 of 13 files reviewed, 4 unresolved discussions (waiting on @Alon-Ti, @andrewmilson, @ohad-starkware, and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/157#-OBUM-Ye2v6zdFNegEmQ:-OBV-jcd5QK48K6dzm-9:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3273cf43f905e7820224e770f44de5b7b7a93170/stwo_cairo_prover/crates/prover/src/components/mod.rs#L10)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I think that this constant can be removed now and use `INTERACTION_TRACE_IDX` directly
</blockquote></details>

Done.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/157#-:-OBV1Biq1J_hBl3WJHhu:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Alon-Ti, @andrewmilson, and @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/157#-OBUM-Ye2v6zdFNegEmQ:-OBV16ze81cNeK-6axvp:b32wy2) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3273cf43f905e7820224e770f44de5b7b7a93170/stwo_cairo_prover/crates/prover/src/components/mod.rs#L10)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

ty

**Review by ohad-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/157#-:-OBV3g1U-PqijwIWzUGH:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Alon-Ti and @andrewmilson)

**Pull request merged**
