### PR TITLE
Read proof jsons

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/53)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/53?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#53** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/53?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#52** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/52?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#51** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/51?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 1 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/53)* status: 1 of 13 files reviewed, all discussions resolved (waiting on @alonh5)

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 11 of 13 files at r1, 1 of 1 files at r2, 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/53)* status: 13 of 14 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/json.rs` line 81 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/53#-O4Zw1RmCPRiV68q4kxa:-O4Zw1RmCPRiV68q4kxb:b48vmvp) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c673f21c7358f39740a5e189e8420897f4c9e8f0/stwo_cairo_prover/crates/prover/src/input/vm_import/json.rs#L81)):*
> ```XML
>         Ok(FeltValue(bytes))
>     }
> }
> ```

Add unit test?



_Code quote:_
```XML
impl Serialize for FeltValue {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        // Convert the [u8; 32] to a hexadecimal string
        let hex_string = format!("0x{}", hex::encode(self.0));
        serializer.serialize_str(&hex_string)
    }
}

impl<'de> Deserialize<'de> for FeltValue {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let hex_string = String::deserialize(deserializer)?;

        // Remove the "0x" prefix if present
        let hex_str = hex_string.strip_prefix("0x").unwrap_or(&hex_string);
        let hex_str = format!("{:0>64}", hex_str);

        // Convert the hexadecimal string back into a [u8; 32]
        let mut bytes = [0u8; 32];
        hex::decode_to_slice(hex_str, &mut bytes).map_err(serde::de::Error::custom)?;

        Ok(FeltValue(bytes))
    }
}
```
___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 17 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/53#-O4_0u-0ASXmoCsdD64T:-O4_0u-1CQG44PThpo1x:b20ba13) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c673f21c7358f39740a5e189e8420897f4c9e8f0/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L17)):*
> ```XML
>         sonic_rs::from_str(&std::fs::read_to_string(pub_json).unwrap()).unwrap();
>     let priv_data: PrivateInput =
>         sonic_rs::from_str(&std::fs::read_to_string(priv_json).unwrap()).unwrap();
> ```

Add error messages for the lfs error.
Also Add this to the readme:
```
git lfs fetch --all
git lfs pull
```



_Code quote:_
```XML
    let pub_data: PublicInput =
        sonic_rs::from_str(&std::fs::read_to_string(pub_json).unwrap()).unwrap();
    let priv_data: PrivateInput =
        sonic_rs::from_str(&std::fs::read_to_string(priv_json).unwrap()).unwrap();
```

**Review by alonh5 — COMMENTED** [review]
> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/53)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 1 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/53)* status: 11 of 14 files reviewed, 2 unresolved discussions (waiting on @alonh5)

___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/json.rs` line 81 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/53#-O4Zw1RmCPRiV68q4kxa:-O4_3IjH0C-M1yFw93Cl:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c673f21c7358f39740a5e189e8420897f4c9e8f0/stwo_cairo_prover/crates/prover/src/input/vm_import/json.rs#L81)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Add unit test?
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 17 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/53#-O4_0u-0ASXmoCsdD64T:-O4_3YQiEps1OKAvqx7A:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c673f21c7358f39740a5e189e8420897f4c9e8f0/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L17)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Add error messages for the lfs error.
Also Add this to the readme:
```
git lfs fetch --all
git lfs pull
```
</blockquote></details>

Done.

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/53#-:-O4_6x-n9yIJ4_LBvabM:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Comment by spapinistarkware** [comment]
### Merge activity

* **Aug 18, 7:48 AM EDT**: @spapinistarkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/53).

**Pull request merged**
