### PR TITLE
Added repetitions to range check unit.

### PR DESCRIPTION
**Pull request by Alon-Ti**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/63)

### CODE REVIEW

**Comment by Alon-Ti** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/63?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#63** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/63?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#59** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/59?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Alon-Ti and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/63)* status: 2 of 3 files reviewed, 7 unresolved discussions (waiting on @Alon-Ti and @alonh5)

___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_unit/component.rs` line 26 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/63#-O5JNbOE5c97foKSjWSL:-O5JNbOF6RgWtkBAzmgp:b-kwcu2j) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ef6bd9bc2656838b65711b5a5c4798f94a444c3b/stwo_cairo_prover/crates/prover/src/components/range_check_unit/component.rs#L26)):*
> ```XML
>     }
>     fn evaluate<E: EvalAtRow>(&self, mut eval: E) -> E {
>         let mut logup = LogupAtRow::<N_REPETITIONS, E>::new(1, self.claimed_sum, self.log_size());
> ```

I don't think BATCH_SIZE should be larger than 2, that would increase the degree of the constraints.



_Suggestion:_
```XML
let mut logup = LogupAtRow::<min(2, N_REPETITIONS), E>::new(1, self.claimed_sum, self.log_size());
```
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_unit/component.rs` line 35 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/63#-O5JNxv77NkHVl0dLLJL:-O5JNxv77NkHVl0dLLJM:b-5fitcu) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ef6bd9bc2656838b65711b5a5c4798f94a444c3b/stwo_cairo_prover/crates/prover/src/components/range_check_unit/component.rs#L35)):*
> ```XML
>                 &[rc_value
>                     + E::F::from(BaseField::from_u32_unchecked(
>                         (repetition as u32) << self.log_n_rows,
> ```

Should we have any (const?) assert on those parameters?



_Code quote:_
```XML
(repetition as u32) << self.log_n_rows,
```
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_unit/component.rs` line 49 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/63#-O5JOPDN9p5P74UwM3f1:-O5JOPDN9p5P74UwM3f2:bv4lqf) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ef6bd9bc2656838b65711b5a5c4798f94a444c3b/stwo_cairo_prover/crates/prover/src/components/range_check_unit/component.rs#L49)):*
> ```XML
> pub struct RangeCheckClaim<const N_REPETITIONS: usize> {
>     pub log_rc_height: u32,
> }
> ```

This should be documented



_Code quote:_
```XML
pub struct RangeCheckClaim<const N_REPETITIONS: usize> {
    pub log_rc_height: u32,
}
```
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_unit/component.rs` line 54 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/63#-O5JPp_2BzeqBuufgGXM:-O5JPp_2BzeqBuufgGXN:b-91wuvk) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ef6bd9bc2656838b65711b5a5c4798f94a444c3b/stwo_cairo_prover/crates/prover/src/components/range_check_unit/component.rs#L54)):*
> ```XML
>         TreeVec::new(vec![
>             vec![self.log_rc_height; 1 + N_REPETITIONS],
>             vec![self.log_rc_height; SECURE_EXTENSION_DEGREE],
> ```

Note this should change if you change logup batch size



_Suggestion:_
```XML
vec![self.log_rc_height; SECURE_EXTENSION_DEGREE * C],
```
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_unit/component_prover.rs` line 21 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/63#-O5JOm-_CiGvFphW-IC8:-O5JOm-_CiGvFphW-IC9:b-j1img) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ef6bd9bc2656838b65711b5a5c4798f94a444c3b/stwo_cairo_prover/crates/prover/src/components/range_check_unit/component_prover.rs#L21)):*
> ```XML
> const TRACE_MULTIPLICITIES_OFFSET: usize = 1;
> 
> pub struct RangeCheckClaimProver<const RC_LOG_HEIGHT: u32, const N_REPETITIONS: usize> {
> ```

Document the structure of multiplicities table



_Code quote:_
```XML
pub struct RangeCheckClaimProver<const RC_LOG_HEIGHT: u32, const N_REPETITIONS: usize> {
```
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_unit/component_prover.rs` line 22 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/63#-O5JOv7F8sG6I5iOc5Yk:-O5JOv7F8sG6I5iOc5Yl:bxwj8vc) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ef6bd9bc2656838b65711b5a5c4798f94a444c3b/stwo_cairo_prover/crates/prover/src/components/range_check_unit/component_prover.rs#L22)):*
> ```XML
> 
> pub struct RangeCheckClaimProver<const RC_LOG_HEIGHT: u32, const N_REPETITIONS: usize> {
>     pub multiplicities: Vec<Vec<PackedUInt32>>,
> ```

here you don't have that problem, no?



_Suggestion:_
```XML
pub multiplicities: [Vec<PackedUInt32>; N_REPITITIONS]
```
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_unit/component_prover.rs` line 45 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/63#-O5JPGBD-neLzFRTvjm1:-O5JPGBD-neLzFRTvjm2:b-b61i4b) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ef6bd9bc2656838b65711b5a5c4798f94a444c3b/stwo_cairo_prover/crates/prover/src/components/range_check_unit/component_prover.rs#L45)):*
> ```XML
>     }
> 
>     pub fn add_inputs(&mut self, inputs: &[M31]) {
> ```

I think you should be doing the unpacking here, as the caller would probably have this as Packed element



_Code quote:_
```XML
&[M31]
```

**Review by Alon-Ti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/63)* status: 2 of 3 files reviewed, 7 unresolved discussions (waiting on @alonh5 and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_unit/component.rs` line 26 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/63#-O5JNbOE5c97foKSjWSL:-O5PUrPLA4kQb0vOdYki:b-ae1ikx) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ef6bd9bc2656838b65711b5a5c4798f94a444c3b/stwo_cairo_prover/crates/prover/src/components/range_check_unit/component.rs#L26)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I don't think BATCH_SIZE should be larger than 2, that would increase the degree of the constraints.
</blockquote></details>

You're right, the next^2 PR makes this parametric in both `N_REPETITIONS` and `BATCH_SIZE`, in practice it's okay for now because for RC9 we probably don't need more than 2.
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_unit/component.rs` line 35 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/63#-O5JNxv77NkHVl0dLLJL:-O5PZJFd1qFFpDPm5Bal:b-1wurnp) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ef6bd9bc2656838b65711b5a5c4798f94a444c3b/stwo_cairo_prover/crates/prover/src/components/range_check_unit/component.rs#L35)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Should we have any (const?) assert on those parameters?
</blockquote></details>

What asserts? I guess the height should be bounded by maximum column length, reps are really unbounded?
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_unit/component.rs` line 49 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/63#-O5JOPDN9p5P74UwM3f1:-O5PVxjt93aPNRPQYssT:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ef6bd9bc2656838b65711b5a5c4798f94a444c3b/stwo_cairo_prover/crates/prover/src/components/range_check_unit/component.rs#L49)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

This should be documented
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_unit/component.rs` line 54 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/63#-O5JPp_2BzeqBuufgGXM:-O5PXDs_07kUrM6E1mve:b-vo5w7b) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ef6bd9bc2656838b65711b5a5c4798f94a444c3b/stwo_cairo_prover/crates/prover/src/components/range_check_unit/component.rs#L54)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Note this should change if you change logup batch size
</blockquote></details>

I'll change this when I add variable batch sizes.
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_unit/component_prover.rs` line 21 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/63#-O5JOm-_CiGvFphW-IC8:-O5PXCDPCTKikNssHW56:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ef6bd9bc2656838b65711b5a5c4798f94a444c3b/stwo_cairo_prover/crates/prover/src/components/range_check_unit/component_prover.rs#L21)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Document the structure of multiplicities table
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_unit/component_prover.rs` line 22 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/63#-O5JOv7F8sG6I5iOc5Yk:-O5PYGHp-dtjgnUUyEau:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ef6bd9bc2656838b65711b5a5c4798f94a444c3b/stwo_cairo_prover/crates/prover/src/components/range_check_unit/component_prover.rs#L22)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

here you don't have that problem, no?
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_unit/component_prover.rs` line 45 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/63#-O5JPGBD-neLzFRTvjm1:-O5PYtxx-ciw7oTqBRtn:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ef6bd9bc2656838b65711b5a5c4798f94a444c3b/stwo_cairo_prover/crates/prover/src/components/range_check_unit/component_prover.rs#L45)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I think you should be doing the unpacking here, as the caller would probably have this as Packed element
</blockquote></details>

Done.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/63)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @Alon-Ti and @alonh5)

___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_unit/component.rs` line 35 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/63#-O5JNxv77NkHVl0dLLJL:-O5SvMxO1Oq2T6XBWeof:b4iv8yh) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ef6bd9bc2656838b65711b5a5c4798f94a444c3b/stwo_cairo_prover/crates/prover/src/components/range_check_unit/component.rs#L35)):*
<details><summary><i>Previously, Alon-Ti wrote…</i></summary><blockquote>

What asserts? I guess the height should be bounded by maximum column length, reps are really unbounded?
</blockquote></details>

I guess this value shouldn't exceed P_M31,
maybe we should handle that later on
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_unit/component.rs` line 74 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/63#-O5Svs-K8Q4ZeZShAMUY:-O5Svs-K8Q4ZeZShAMUZ:bhuux3o) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c2d52a10cea47db4a18919cd42fea3b5d8069a63/stwo_cairo_prover/crates/prover/src/components/range_check_unit/component.rs#L74)):*
> ```XML
>     pub fn mix_into(&self, channel: &mut impl Channel) {
>         channel.mix_felts(&[self.claimed_sum]);
>         channel.mix_nonce(N_REPETITIONS as u64);
> ```

Do we really need to mix it twice? It was already mixed in the RangeCheckClaim.



_Code quote:_
```XML
        channel.mix_nonce(N_REPETITIONS as u64);
```

**Review by Alon-Ti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/63)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_unit/component.rs` line 74 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/63#-O5Svs-K8Q4ZeZShAMUY:-O5T0tmL4qz-Unr7oWfj:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c2d52a10cea47db4a18919cd42fea3b5d8069a63/stwo_cairo_prover/crates/prover/src/components/range_check_unit/component.rs#L74)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Do we really need to mix it twice? It was already mixed in the RangeCheckClaim.
</blockquote></details>

Done.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/63#-:-O5mVb08D4t2E_4WVceN:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Review by shaharsamocha7 — APPROVED** [review]
> Reviewed 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/63)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Pull request merged**
