### PR TITLE
made components implement our interfaces

### PR DESCRIPTION
**Pull request by ohad-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/149)

### CODE REVIEW

**Comment by ohad-starkware** [comment]
* **#149** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/149?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ohad-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by ilyalesokhin-starkware** [comment]
*[`stwo_cairo_prover/crates/prover/src/components/memory/addr_to_id/mod.rs` line 7 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/149#-OAq9Jrk4MTGFvJzgaD7:-OAq9Jrk4MTGFvJzgaD8:bg9f26u) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/63b3d604655b073b2982013f3eccb91d8187576d/stwo_cairo_prover/crates/prover/src/components/memory/addr_to_id/mod.rs#L7)):*
> ```XML
> 
> pub use component::{Claim, Component, Eval, InteractionClaim, RelationElements};
> pub use prover::{ClaimGenerator, InputType};
> ```

why did you add it?



_Code quote:_
```XML
 InputType
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 3 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/149)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @ohad-starkware)

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/149)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/components/memory/addr_to_id/mod.rs` line 7 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/149#-OAq9Jrk4MTGFvJzgaD7:-OAqC2leCYsqZny_WGn4:b-ibp3ll) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/63b3d604655b073b2982013f3eccb91d8187576d/stwo_cairo_prover/crates/prover/src/components/memory/addr_to_id/mod.rs#L7)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why did you add it?
</blockquote></details>

for every component Im generating a SubComponentInputs struct with members that looks like this:

                   $component_name_inputs: Vec<$component_name::InputType>

**Comment by ilyalesokhin-starkware** [comment]
*[`stwo_cairo_prover/crates/prover/src/components/memory/addr_to_id/mod.rs` line 7 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/149#-OAq9Jrk4MTGFvJzgaD7:-OAqayu9EzvMFHuB0KUT:bic6jpf) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/63b3d604655b073b2982013f3eccb91d8187576d/stwo_cairo_prover/crates/prover/src/components/memory/addr_to_id/mod.rs#L7)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

for every component Im generating a SubComponentInputs struct with members that looks like this:

                   $component_name_inputs: Vec<$component_name::InputType>
</blockquote></details>

I don't understand, I don't see any macro call in this file.

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/149)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/components/memory/addr_to_id/mod.rs` line 7 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/149#-OAq9Jrk4MTGFvJzgaD7:-OAqeTDe7sbmVnrrpR3j:b-94sw44) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/63b3d604655b073b2982013f3eccb91d8187576d/stwo_cairo_prover/crates/prover/src/components/memory/addr_to_id/mod.rs#L7)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I don't understand, I don't see any macro call in this file.
</blockquote></details>

I took it from the auto gen,
the generated verfify_instruction component I want to integrate has a 

            $memory_id_to_big_inputs: Vec<$memory_id_to_vbig::InputType>

field in it's subcomponents.
if it wasn't clear-  the purpose for this is to collect the inputs for the function calls and after finishing the trace calling .add_inputs once (better for multithreading)

**Pull request closed without merging**
