### PR TITLE
separate components

### PR DESCRIPTION
**Pull request by ohad-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/194)

### CODE REVIEW

**Comment by ohad-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/194?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#194** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/194?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/194?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#193** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/193?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#190** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/190?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#189** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/189?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#188** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/188?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#187** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/187?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#180** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/180?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#182](https://github.com/starkware-libs/stwo-cairo/pull/182) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/182?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#179** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/179?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#177** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/177?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#178** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/178?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#176** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/176?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/194#-:-OCXaS0X5MxkCJvukDkY:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ohad-starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo-cairo/194#-OCXaHu_3vdVzxWCj-wA:-OCXaHu_3vdVzxWCj-wB:b-ntv5ds) (no related file):*
are you going to have a similiar pr for the range check components?

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/194)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo-cairo/194#-OCXaHu_3vdVzxWCj-wA:-OCXap_f-3y2dyAjRS9x:b-eite06) (no related file):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

are you going to have a similiar pr for the range check components?
</blockquote></details>

probably,  first issue?

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/194#-:-OCXiItl4zBUZT06T-4r:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ohad-starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo-cairo/194#-OCXaHu_3vdVzxWCj-wA:-OCXiKrF2PLDoINibURV:bb73djm) (no related file):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

probably,  first issue?
</blockquote></details>

SGTM

**Review by shaharsamocha7 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/194)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ohad-starkware)

**Comment by ohad-starkware** [comment]
### Merge activity

* **Nov 25, 4:54 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/194).

**Pull request merged**
