### PR TITLE
Create CairoAir.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/30)

### CODE REVIEW

**Comment by alonh5** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/30?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#30** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/30?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#29** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/29?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alonh5 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/30)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`stwo_cairo_prover/src/air/mod.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/30#-O2Tnujk6nSqidNkPcS2:-O2Tnujk6nSqidNkPcS3:bu3g4zi) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/99fe01cc1d1f6fc6e952288f7f53186704cc1ea9/stwo_cairo_prover/src/air/mod.rs#L1)):*
> ```XML
> pub mod air;
> ```

rename to cairo.rs / cairo_air.rs



_Code quote:_
```XML
pub mod air;
```

**Review by shaharsamocha7 — COMMENTED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/30)* status: 1 of 6 files reviewed, 1 unresolved discussion (waiting on @alonh5)

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/30)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

___
*[`stwo_cairo_prover/src/air/mod.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/30#-O2Tnujk6nSqidNkPcS2:-O2cxfPpCc14x2MfCavR:b-rnlqrr) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/99fe01cc1d1f6fc6e952288f7f53186704cc1ea9/stwo_cairo_prover/src/air/mod.rs#L1)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

rename to cairo.rs / cairo_air.rs
</blockquote></details>

Are we going to have more airs? I renamed it mod.rs for now.

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/30)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @spapinistarkware)

___
*[`stwo_cairo_prover/src/air/mod.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/30#-O2Tnujk6nSqidNkPcS2:-O2sQiiRE0WNcFwjpjMg:b-fejwo6) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/99fe01cc1d1f6fc6e952288f7f53186704cc1ea9/stwo_cairo_prover/src/air/mod.rs#L1)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Are we going to have more airs? I renamed it mod.rs for now.
</blockquote></details>

We could have more, yes.

Cairo-air is the air that contains all the casm components (and builtins).
In the future we could have an M31-cairo air for example, or a specific verifier AIR (e.g. for bitcoin)

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/30)* status: 0 of 13 files reviewed, all discussions resolved (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`stwo_cairo_prover/src/air/mod.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/30#-O2Tnujk6nSqidNkPcS2:-O2sSwNe0rohRJ2FRbNV:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/99fe01cc1d1f6fc6e952288f7f53186704cc1ea9/stwo_cairo_prover/src/air/mod.rs#L1)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

We could have more, yes.

Cairo-air is the air that contains all the casm components (and builtins).
In the future we could have an M31-cairo air for example, or a specific verifier AIR (e.g. for bitcoin)
</blockquote></details>

Done.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 11 files at r2, 2 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/30)* status: 5 of 13 files reviewed, 5 unresolved discussions (waiting on @alonh5 and @spapinistarkware)

___
*[`stwo_cairo_prover/src/components/memory/component.rs` line 39 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/30#-O2xbxYOCdaq2JT7zXXL:-O2xbxYOCdaq2JT7zXXM:b-2n9jg4) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/7043048d6c6b6e2b6b3b2b3e4d1cfc1767a347ba/stwo_cairo_prover/src/components/memory/component.rs#L39)):*
> ```XML
> pub const MEMORY_RC_LOOKUP_VALUE_1: &str = "MEMORY_RC_LOOKUP_1";
> pub const MEMORY_RC_LOOKUP_VALUE_2: &str = "MEMORY_RC_LOOKUP_2";
> pub const MEMORY_RC_LOOKUP_VALUE_3: &str = "MEMORY_RC_LOOKUP_3";
> ```

Is this interaction relevant specifically for memory?
Other components that lookup RC should use that as well, no?



_Suggestion:_
```XML
pub const RC_LOOKUP_VALUE_3: &str = "RC_LOOKUP_3";
```
___
*[`stwo_cairo_prover/src/components/memory/component.rs` line 47 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/30#-O2xcDGHDKF1uH8Ry51v:-O2xcDGHDKF1uH8Ry51w:b6hf7p3) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/7043048d6c6b6e2b6b3b2b3e4d1cfc1767a347ba/stwo_cairo_prover/src/components/memory/component.rs#L47)):*
> ```XML
> pub const LOG_MEMORY_ADDRESS_BOUND: u32 = 3;
> pub const MEMORY_ADDRESS_BOUND: usize = 1 << LOG_MEMORY_ADDRESS_BOUND;
> pub const N_MEMORY_COLUMNS: usize = N_M31_IN_FELT252 + 2;
> ```

what the +2 stands for? addresses, multiplicities?
Consider to comment somewhere what is the component structure.



_Code quote:_
```XML
pub const N_MEMORY_COLUMNS: usize = N_M31_IN_FELT252 + 2;
```
___
*[`stwo_cairo_prover/src/components/memory/component.rs` line 126 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/30#-O2xcbxt6vsxL-yS3G8g:-O2xcbxuDA2_kUiIAF4C:b-m019j5) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/7043048d6c6b6e2b6b3b2b3e4d1cfc1767a347ba/stwo_cairo_prover/src/components/memory/component.rs#L126)):*
> ```XML
>                 .iter()
>                 .for_each(|input| rc_generator.add_inputs(input));
>         }
> ```

Can you call add_inputs for the entire column at once?



_Code quote:_
```XML
        for column in trace[1..MULTIPLICITY_COLUMN_OFFSET].iter() {
            column
                .iter()
                .for_each(|input| rc_generator.add_inputs(input));
        }
```
___
*[`stwo_cairo_prover/src/components/memory/component.rs` line 181 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/30#-O2xd1hu-VbvkQgZLmz4:-O2xd1hv5X0TAfnjqfec:b6wlksn) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/7043048d6c6b6e2b6b3b2b3e4d1cfc1767a347ba/stwo_cairo_prover/src/components/memory/component.rs#L181)):*
> ```XML
>                 + (rc_z - trace[N_M31_IN_FELT252].values[index]).inverse();
>             rc_logup_values[N_M31_IN_FELT252 - 1][index] = rc_interaction_value;
>             column_rc_last = rc_interaction_value;
> ```

Is this the prefix_sum column? Don't we have a function for that?



_Code quote:_
```XML
            let mut row_rc_last = SecureField::zero();
            // TODO(AlonH): Batch inverse.
            for j in 0..(N_M31_IN_FELT252 - 1) {
                let rc_interaction_value =
                    row_rc_last + (rc_z - trace[j + 1].values[index]).inverse();
                rc_logup_values[j][index] = rc_interaction_value;
                row_rc_last = rc_interaction_value;
            }
            let rc_interaction_value = column_rc_last
                + row_rc_last
                + (rc_z - trace[N_M31_IN_FELT252].values[index]).inverse();
            rc_logup_values[N_M31_IN_FELT252 - 1][index] = rc_interaction_value;
            column_rc_last = rc_interaction_value;
```
___
*[`stwo_cairo_prover/src/components/memory/component_prover.rs` line 47 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/30#-O2xdjCX5H_yV10LRCnw:-O2xdjCX5H_yV10LRCnx:bqi27c2) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/7043048d6c6b6e2b6b3b2b3e4d1cfc1767a347ba/stwo_cairo_prover/src/components/memory/component_prover.rs#L47)):*
> ```XML
>         let last_point_denom_inverses = point_vanish_denominator_inverses(
>             trace_eval_domain,
>             zero_domain.at(zero_domain.size() - 1),
> ```

Why did it changed?



_Code quote:_
```XML
zero_domain.size() - 1
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/30)* status: 5 of 13 files reviewed, 4 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`stwo_cairo_prover/src/components/memory/component.rs` line 39 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/30#-O2xbxYOCdaq2JT7zXXL:-O2xfkCX4COG-lOnUh0K:bbx2k6q) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/7043048d6c6b6e2b6b3b2b3e4d1cfc1767a347ba/stwo_cairo_prover/src/components/memory/component.rs#L39)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Is this interaction relevant specifically for memory?
Other components that lookup RC should use that as well, no?
</blockquote></details>

This is specific to the range check the memory is doing. `RC_LOOKUP_X` is defined in the range check module.
I'm changing this though to combine the lookups of the component so there will only be 1 lookup value (split into 4).
___
*[`stwo_cairo_prover/src/components/memory/component.rs` line 126 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/30#-O2xcbxt6vsxL-yS3G8g:-O2xgVt8EEyG4so03Aie:bb1jv67) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/7043048d6c6b6e2b6b3b2b3e4d1cfc1767a347ba/stwo_cairo_prover/src/components/memory/component.rs#L126)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can you call add_inputs for the entire column at once?
</blockquote></details>

We changed the inputs of rc to receive them one by one so we don't have to store the values twice. Here we a re range checking all of the values in the columns but it won't always be like that. Do you think this hurts efficiency?
___
*[`stwo_cairo_prover/src/components/memory/component.rs` line 181 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/30#-O2xd1hu-VbvkQgZLmz4:-O2xhH_aByO7bSEnpeB6:b9y65nv) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/7043048d6c6b6e2b6b3b2b3e4d1cfc1767a347ba/stwo_cairo_prover/src/components/memory/component.rs#L181)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Is this the prefix_sum column? Don't we have a function for that?
</blockquote></details>

Yes now it's merged, I'll try using it here.
___
*[`stwo_cairo_prover/src/components/memory/component_prover.rs` line 47 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/30#-O2xdjCX5H_yV10LRCnw:-O2xhZFQ51NOx1Pd9tm_:b-as4tb7) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/7043048d6c6b6e2b6b3b2b3e4d1cfc1767a347ba/stwo_cairo_prover/src/components/memory/component_prover.rs#L47)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Why did it changed?
</blockquote></details>

Bug fix. The final sum is actually at that point.

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/30)* status: 5 of 13 files reviewed, 4 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`stwo_cairo_prover/src/components/memory/component.rs` line 181 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/30#-O2xd1hu-VbvkQgZLmz4:-O2xxJdVEbe8R8JSMuCb:b-ceg4dz) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/7043048d6c6b6e2b6b3b2b3e4d1cfc1767a347ba/stwo_cairo_prover/src/components/memory/component.rs#L181)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Yes now it's merged, I'll try using it here.
</blockquote></details>

Actually the `LogupTraceGenerator` is for SIMD backend. I'll use it in a SIMD implementation in a new PR.

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 11 files at r2, 1 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/30)* status: 5 of 14 files reviewed, 5 unresolved discussions (waiting on @alonh5 and @shaharsamocha7)

___
*[`stwo_cairo_prover/src/air/cairo.rs` line 55 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/30#-O31I2hj0z69YVNGdjkB:-O31I2hkDAQCe93ECOle:b-7pggbl) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/2f5a94c407dcecd54120ed363297390a00987fcf/stwo_cairo_prover/src/air/cairo.rs#L55)):*
> ```XML
> 
> impl AirTraceGenerator<CpuBackend> for CairoAirGenerator {
>     fn write_trace(&mut self) -> Vec<CircleEvaluation<CpuBackend, BaseField, BitReversedOrder>> {
> ```

I'd love to see all these actually using the engine. I think it might shed some light on how this code should look like.
For example, I think we don't really need to keep the components in the registry once all of their inputs are added - and in particular, after the write_trace phase.

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/30)* status: 5 of 14 files reviewed, 5 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`stwo_cairo_prover/src/air/cairo.rs` line 55 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/30#-O31I2hj0z69YVNGdjkB:-O322a2v2RyksrBrWeNY:b-jn5s6n) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/2f5a94c407dcecd54120ed363297390a00987fcf/stwo_cairo_prover/src/air/cairo.rs#L55)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I'd love to see all these actually using the engine. I think it might shed some light on how this code should look like.
For example, I think we don't really need to keep the components in the registry once all of their inputs are added - and in particular, after the write_trace phase.
</blockquote></details>

Discussed offline.

**Review by shaharsamocha7 — COMMENTED** [review]
> Reviewed 1 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/30)* status: 6 of 14 files reviewed, 4 unresolved discussions (waiting on @alonh5 and @spapinistarkware)

___
*[`stwo_cairo_prover/src/components/memory/component.rs` line 126 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/30#-O2xcbxt6vsxL-yS3G8g:-O322n-OBQj6p8y6FuvK:b-87e4hg) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/7043048d6c6b6e2b6b3b2b3e4d1cfc1767a347ba/stwo_cairo_prover/src/components/memory/component.rs#L126)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

We changed the inputs of rc to receive them one by one so we don't have to store the values twice. Here we a re range checking all of the values in the columns but it won't always be like that. Do you think this hurts efficiency?
</blockquote></details>

No, I forgot that you change it to be one by one.

**Pull request closed without merging**
