### PR TITLE
Memory addr to id component

### PR DESCRIPTION
**Pull request by shaharsamocha7**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/130)

### CODE REVIEW

**Comment by shaharsamocha7** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/130?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#130** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/130?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#129** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/129?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#128** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/128?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @shaharsamocha7 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by ohad-starkware** [comment]
*[`stwo_cairo_prover/crates/prover/src/components/memory/addr_to_id/prover.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/130#-O9jprGM2T35PPBTyaRl:-O9jprGM2T35PPBTyaRm:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ff6937a33f9750316e5fc0f53e8b9a36636cf7a4/stwo_cairo_prover/crates/prover/src/components/memory/addr_to_id/prover.rs#L26)):*
> ```XML
>         let ids = (0..mem.address_to_id.len())
>             .map(|addr| BaseField::from_u32_unchecked(mem.get_id(addr as u32)))
>             .collect_vec();
> ```

**Review by ohad-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/130)* status: 2 of 7 files reviewed, 6 unresolved discussions (waiting on @Alon-Ti and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/components/memory/addr_to_id/component.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/130#-O9joNrOERjzOGdXH80Z:-O9joNrOERjzOGdXH80_:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ff6937a33f9750316e5fc0f53e8b9a36636cf7a4/stwo_cairo_prover/crates/prover/src/components/memory/addr_to_id/component.rs#L20)):*
> ```XML
> }
> 
> impl AddrToIdEval {
> ```





_Suggestion:_
```XML
}
impl AddrToIdEval {
```
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/addr_to_id/component.rs` line 25 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/130#-O9jnvRfE_OyYCuALI9H:-O9jnvRfE_OyYCuALI9I:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ff6937a33f9750316e5fc0f53e8b9a36636cf7a4/stwo_cairo_prover/crates/prover/src/components/memory/addr_to_id/component.rs#L25)):*
> ```XML
>         N_ADDR_TO_ID_COLUMNS
>     }
>     pub fn new(
> ```





_Suggestion:_
```XML
    }
    
    pub fn new(
```
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/addr_to_id/prover.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/130#-O9jq3W75KNyCc2S9cxi:-O9jq3W75KNyCc2S9cxj:b7rzy7y) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ff6937a33f9750316e5fc0f53e8b9a36636cf7a4/stwo_cairo_prover/crates/prover/src/components/memory/addr_to_id/prover.rs#L37)):*
> ```XML
>             ids: packed_ids,
>             multiplicities,
>         }
> ```

the ids is only syntactic

multiplicities - forgot to divide by N_LANES? 
we need to impl Zeroed for packeduint32, either add it here or in a different pr, its really short.
reference: https://github.com/starkware-libs/stwo/blob/aac3e370dd415fd5f37d10ff56eee8062a56a138/crates/prover/src/core/backend/simd/qm31.rs#L242-L246



_Suggestion:_
```XML
        let ids = (0..mem.address_to_id.len())
            .map(|addr| BaseField::from_u32_unchecked(mem.get_id(addr as u32)))
            .array_chunks::<N_LANES>()
            .map(PackedBaseField::from_array)
            .collect_vec();
        let multiplicities =
            vec![PackedUInt32::broadcast(0); mem.address_to_id.len() / N_LANES];

        Self {
            ids
            multiplicities,
        }
```
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/addr_to_id/prover.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/130#-O9jrT6OBfUN2yRAWlib:-O9jrT6OBfUN2yRAWlic:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ff6937a33f9750316e5fc0f53e8b9a36636cf7a4/stwo_cairo_prover/crates/prover/src/components/memory/addr_to_id/prover.rs#L39)):*
> ```XML
>         }
>     }
>     pub fn deduce_output(&self, input: PackedBaseField) -> PackedBaseField {
> ```





_Suggestion:_
```XML
    }
    
    pub fn deduce_output(&self, input: PackedBaseField) -> PackedBaseField {
```
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/addr_to_id/prover.rs` line 76 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/130#-O9js72cBCk1pJVsYq6A:-O9js72cBCk1pJVsYq6B:b-4b4hxz) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ff6937a33f9750316e5fc0f53e8b9a36636cf7a4/stwo_cairo_prover/crates/prover/src/components/memory/addr_to_id/prover.rs#L76)):*
> ```XML
>                 PackedM31::broadcast(BaseField::from_u32_unchecked((i * N_LANES) as u32)) + inc;
>             trace[1].data[i] = *id;
>             trace[2].data[i] = multiplicity.as_m31_unchecked();
> ```

if we're doing as_m31_unchecked, maybe we can steal the column itself? this is essentially a copy
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/addr_to_id/prover.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/130#-O9jsagG6K_1j_FQ9JOL:-O9jsagG6K_1j_FQ9JOM:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ff6937a33f9750316e5fc0f53e8b9a36636cf7a4/stwo_cairo_prover/crates/prover/src/components/memory/addr_to_id/prover.rs#L79)):*
> ```XML
>         }
> 
>         let addresses = trace[0].data.clone();
> ```





_Suggestion:_
```XML
        }

        // Lookup data.
        let addresses = trace[0].data.clone();
```
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/addr_to_id/prover.rs` line 128 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/130#-O9jsqvkCoNRrrEm5J7Z:-O9jsqvkCoNRrrEm5J7_:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ff6937a33f9750316e5fc0f53e8b9a36636cf7a4/stwo_cairo_prover/crates/prover/src/components/memory/addr_to_id/prover.rs#L128)):*
> ```XML
>         let mut col_gen = logup_gen.new_col();
> 
>         for vec_row in 0..1 << (log_size - LOG_N_LANES) {
> ```





_Suggestion:_
```XML
        
        let mut col_gen = logup_gen.new_col();
        for vec_row in 0..1 << (log_size - LOG_N_LANES) {
```

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/130)* status: 2 of 8 files reviewed, 6 unresolved discussions (waiting on @Alon-Ti and @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/components/memory/addr_to_id/component.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/130#-O9joNrOERjzOGdXH80Z:-OACbVcR-yFYlU-eHTU2:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ff6937a33f9750316e5fc0f53e8b9a36636cf7a4/stwo_cairo_prover/crates/prover/src/components/memory/addr_to_id/component.rs#L20)):*
> ```XML
> }
> 
> impl AddrToIdEval {
> ```

Done.
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/addr_to_id/component.rs` line 25 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/130#-O9jnvRfE_OyYCuALI9H:-OACsWO3DtKC7glsUSIL:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ff6937a33f9750316e5fc0f53e8b9a36636cf7a4/stwo_cairo_prover/crates/prover/src/components/memory/addr_to_id/component.rs#L25)):*
> ```XML
>         N_ADDR_TO_ID_COLUMNS
>     }
>     pub fn new(
> ```

Done.
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/addr_to_id/prover.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/130#-O9jq3W75KNyCc2S9cxi:-OACtR5H2tOYwpTpKK6o:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ff6937a33f9750316e5fc0f53e8b9a36636cf7a4/stwo_cairo_prover/crates/prover/src/components/memory/addr_to_id/prover.rs#L37)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

the ids is only syntactic

multiplicities - forgot to divide by N_LANES? 
we need to impl Zeroed for packeduint32, either add it here or in a different pr, its really short.
reference: https://github.com/starkware-libs/stwo/blob/aac3e370dd415fd5f37d10ff56eee8062a56a138/crates/prover/src/core/backend/simd/qm31.rs#L242-L246
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/addr_to_id/prover.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/130#-O9jrT6OBfUN2yRAWlib:-OACtTJP0yIZwUFFpgPU:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ff6937a33f9750316e5fc0f53e8b9a36636cf7a4/stwo_cairo_prover/crates/prover/src/components/memory/addr_to_id/prover.rs#L39)):*
> ```XML
>         }
>     }
>     pub fn deduce_output(&self, input: PackedBaseField) -> PackedBaseField {
> ```

Done.
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/addr_to_id/prover.rs` line 76 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/130#-O9js72cBCk1pJVsYq6A:-OACuFew5nCcu1VgSRmd:b-ks3tc2) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ff6937a33f9750316e5fc0f53e8b9a36636cf7a4/stwo_cairo_prover/crates/prover/src/components/memory/addr_to_id/prover.rs#L76)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

if we're doing as_m31_unchecked, maybe we can steal the column itself? this is essentially a copy
</blockquote></details>

We probably can, but for that we need a from_iter() with PackedM31
Can do that in another pr if you think it is better.
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/addr_to_id/prover.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/130#-O9jsagG6K_1j_FQ9JOL:-OACuPa2DzHzy2MsX2PU:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ff6937a33f9750316e5fc0f53e8b9a36636cf7a4/stwo_cairo_prover/crates/prover/src/components/memory/addr_to_id/prover.rs#L79)):*
> ```XML
>         }
> 
>         let addresses = trace[0].data.clone();
> ```

Done.

**Review by ohad-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 7 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/130#-:-OAD4lvB5oU4iB4oFrEi:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Alon-Ti)

___
*[`stwo_cairo_prover/crates/prover/src/components/memory/addr_to_id/prover.rs` line 76 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/130#-O9js72cBCk1pJVsYq6A:-OAD4a5_A9Ajl0RsMXGj:bb7oryy) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ff6937a33f9750316e5fc0f53e8b9a36636cf7a4/stwo_cairo_prover/crates/prover/src/components/memory/addr_to_id/prover.rs#L76)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

We probably can, but for that we need a from_iter() with PackedM31
Can do that in another pr if you think it is better.
</blockquote></details>

sure

**Review by Alon-Ti — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r1, 2 of 2 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/130)* status: all files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/components/memory/addr_to_id/component.rs` line 57 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/130#-OAIkw1p4Z-2Ug5H4LHY:-OAIkw1p4Z-2Ug5H4LHZ:b93hq0q) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/2322dd513d9cbe8cbad35330f2a4f0052852d38e/stwo_cairo_prover/crates/prover/src/components/memory/addr_to_id/component.rs#L57)):*
> ```XML
>             self.lookup_elements.combine(&address_and_id),
>         );
>         logup.write_frac(&mut eval, frac);
> ```

Is batching worse?

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/130)* status: 6 of 8 files reviewed, 1 unresolved discussion (waiting on @Alon-Ti and @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/components/memory/addr_to_id/component.rs` line 57 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/130#-OAIkw1p4Z-2Ug5H4LHY:-OAMOr-F9fpcZbX8swRp:b-lkmn5) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/2322dd513d9cbe8cbad35330f2a4f0052852d38e/stwo_cairo_prover/crates/prover/src/components/memory/addr_to_id/component.rs#L57)):*
<details><summary><i>Previously, Alon-Ti wrote…</i></summary><blockquote>

Is batching worse?
</blockquote></details>

Added a todo to break the component to repetitions

**Review by Alon-Ti — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/130#-:-OANGoM52qz2gZm-Y6JV:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Comment by shaharsamocha7** [comment]
### Merge activity

* **Oct 29, 8:50 AM EDT**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/130).

**Pull request merged**
