### PR TITLE
Add CairoSerialize trait and implmentations

### PR DESCRIPTION
**Pull request by andrewmilson**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/251)

### CODE REVIEW

**Review by ohad-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/251)* status: 0 of 73 files reviewed, 1 unresolved discussion (waiting on @andrewmilson)

___
*[`stwo_cairo_prover/crates/cairo-serialize/Cargo.toml` line 9 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/251#-OEE8HfK06ocuA8XE1EN:-OEE8HfL10NrMYSTr_5c:b-wmp80x) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/7044f1a54da91cf2aeb77ed83d71880429900576/stwo_cairo_prover/crates/cairo-serialize/Cargo.toml#L9)):*
> ```TOML
> starknet-ff.workspace = true
> stwo-prover.workspace = true
> stwo-cairo-serialize-derive = { path = "../cairo-serialize-derive" }
> ```

drop line?

**Review by ohad-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 73 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/251)* status: 1 of 73 files reviewed, 2 unresolved discussions (waiting on @andrewmilson)

___
*[`stwo_cairo_prover/crates/cairo-serialize-derive/src/lib.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/251#-OEE96TzDwjHoc0P7ItY:-OEE96TzDwjHoc0P7ItZ:b-hfpv1m) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/7044f1a54da91cf2aeb77ed83d71880429900576/stwo_cairo_prover/crates/cairo-serialize-derive/src/lib.rs#L53)):*
> ```XML
>     };
> 
>     // let expanded = quote! {
> ```

remove?

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/251)* status: 1 of 73 files reviewed, 2 unresolved discussions (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/crates/cairo-serialize/Cargo.toml` line 9 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/251#-OEE8HfK06ocuA8XE1EN:-OEE9PfsBf5qDIpHwSP-:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/7044f1a54da91cf2aeb77ed83d71880429900576/stwo_cairo_prover/crates/cairo-serialize/Cargo.toml#L9)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

drop line?
</blockquote></details>

Done.

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/251)* status: 0 of 73 files reviewed, 2 unresolved discussions (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/crates/cairo-serialize-derive/src/lib.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/251#-OEE96TzDwjHoc0P7ItY:-OEE9X9EA8WhYpcz1Vid:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/7044f1a54da91cf2aeb77ed83d71880429900576/stwo_cairo_prover/crates/cairo-serialize-derive/src/lib.rs#L53)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

remove?
</blockquote></details>

Done.

**Review by ohad-starkware — CHANGES_REQUESTED** [review]
> Reviewed 10 of 73 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 4 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/251)* status: 16 of 74 files reviewed, 10 unresolved discussions (waiting on @andrewmilson)

___
*[`stwo_cairo_prover/crates/cairo-serialize/Cargo.toml` line 9 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/251#-OEE8HfK06ocuA8XE1EN:-OEECzgtD8ZaEtELQCl6:bs1j3x3) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/7044f1a54da91cf2aeb77ed83d71880429900576/stwo_cairo_prover/crates/cairo-serialize/Cargo.toml#L9)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

? I meant after the file ends
that's the convention correct?
___
*[`stwo_cairo_prover/crates/cairo-serialize/src/lib.rs` line 12 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/251#-OEEDEbB4HFrpN9ncbXl:-OEEDEbB4HFrpN9ncbXm:bx379xo) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/38e4aa8828ea45f5f30a66c03018f60e915f0664/stwo_cairo_prover/crates/cairo-serialize/src/lib.rs#L12)):*
> ```XML
> 
> /// Serializes types into a format for deserialization by corresponding types in a Cairo program.
> pub trait CairoSerialize {
> ```

why is this called cairoserialize and not proofserialize?
other s.two users will also want to write this code  
___
*[`stwo_cairo_prover/crates/cairo-serialize/src/lib.rs` line 186 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/251#-OEEDeGaD76bk0gkxey9:-OEEDeGaD76bk0gkxeyA:bne2x7x) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/38e4aa8828ea45f5f30a66c03018f60e915f0664/stwo_cairo_prover/crates/cairo-serialize/src/lib.rs#L186)):*
> ```XML
> 
> // Make derive macro available.
> pub use stwo_cairo_serialize_derive::CairoSerialize;
> ```

at the top of the file?
___
*[`stwo_cairo_prover/crates/adapted_prover/src/main.rs` line 74 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/251#-OEECpng-Ge-YXWR2wp4:-OEECpng-Ge-YXWR2wp5:b-6b0jy5) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/38e4aa8828ea45f5f30a66c03018f60e915f0664/stwo_cairo_prover/crates/adapted_prover/src/main.rs#L74)):*
> ```XML
>     log::info!("Casm states by opcode count: {casm_states_by_opcode_count:?}");
> 
>     let proof =
> ```

add a todo to propagate the hash type from the CLI
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs` line 39 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/251#-OEEEscn364toMiaewAq:-OEEEscn364toMiaewAr:b-l6mwxj) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/38e4aa8828ea45f5f30a66c03018f60e915f0664/stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs#L39)):*
> ```XML
> {
>     let _span = span!(Level::INFO, "prove_cairo").entered();
>     // let config = PcsConfig::default();
> ```

remove
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs` line 40 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/251#-OEEF0vk7IcNaLiQY0Pz:-OEEF0vk7IcNaLiQY0Q-:btnin53) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/38e4aa8828ea45f5f30a66c03018f60e915f0664/stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs#L40)):*
> ```XML
>     let _span = span!(Level::INFO, "prove_cairo").entered();
>     // let config = PcsConfig::default();
>     let config = PcsConfig {
> ```

add a todo(ohad) to propagate this from outside
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs` line 41 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/251#-OEEEtep7POsXTv8I356:-OEEEtep7POsXTv8I357:b-1hotwg) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/38e4aa8828ea45f5f30a66c03018f60e915f0664/stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs#L41)):*
> ```XML
>     // let config = PcsConfig::default();
>     let config = PcsConfig {
>         pow_bits: 0,
> ```

maybe more than 0?
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs` line 131 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/251#-OEEF7E7-OqfnP0VSMjJ:-OEEF7E7-OqfnP0VSMjK:bb7od0r) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/38e4aa8828ea45f5f30a66c03018f60e915f0664/stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs#L131)):*
> ```XML
> ) -> Result<(), CairoVerificationError> {
>     // Verify.
>     // let config = PcsConfig::default();
> ```

same
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/air.rs` line 43 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/251#-OEEEbE09bMp42yp2uYZ:-OEEEbE09bMp42yp2uY_:b3tma3a) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/38e4aa8828ea45f5f30a66c03018f60e915f0664/stwo_cairo_prover/crates/prover/src/cairo_air/air.rs#L43)):*
> ```XML
> }
> 
> impl<H: MerkleHasher> CairoSerialize for CairoProof<H>
> ```

this is not a derive due to starkproof not being CairoSerialize? why isn't it?

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/251)* status: 16 of 74 files reviewed, 10 unresolved discussions (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/crates/adapted_prover/src/main.rs` line 74 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/251#-OEECpng-Ge-YXWR2wp4:-OEEJtwg75O4z8RKJ1H8:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/38e4aa8828ea45f5f30a66c03018f60e915f0664/stwo_cairo_prover/crates/adapted_prover/src/main.rs#L74)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

add a todo to propagate the hash type from the CLI
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/cairo-serialize/Cargo.toml` line 9 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/251#-OEE8HfK06ocuA8XE1EN:-OEEK5vv1FPAragg_LxO:btj1120) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/7044f1a54da91cf2aeb77ed83d71880429900576/stwo_cairo_prover/crates/cairo-serialize/Cargo.toml#L9)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

? I meant after the file ends
that's the convention correct?
</blockquote></details>

Yes. That is the case currently.
___
*[`stwo_cairo_prover/crates/cairo-serialize/src/lib.rs` line 12 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/251#-OEEDEbB4HFrpN9ncbXl:-OEEKGeZDJuu-KXfpzGG:b2lkfgp) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/38e4aa8828ea45f5f30a66c03018f60e915f0664/stwo_cairo_prover/crates/cairo-serialize/src/lib.rs#L12)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

why is this called cairoserialize and not proofserialize?
other s.two users will also want to write this code
</blockquote></details>

It's not coupled with proofs. It works for any type that can be deserialised in cairo.
___
*[`stwo_cairo_prover/crates/cairo-serialize/src/lib.rs` line 186 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/251#-OEEDeGaD76bk0gkxey9:-OEEKOv60mBF3aCsNSPb:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/38e4aa8828ea45f5f30a66c03018f60e915f0664/stwo_cairo_prover/crates/cairo-serialize/src/lib.rs#L186)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

at the top of the file?
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/air.rs` line 43 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/251#-OEEEbE09bMp42yp2uYZ:-OEEK_rkAfJA7UrM_3sK:bagu38z) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/38e4aa8828ea45f5f30a66c03018f60e915f0664/stwo_cairo_prover/crates/prover/src/cairo_air/air.rs#L43)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

this is not a derive due to starkproof not being CairoSerialize? why isn't it?
</blockquote></details>

It's not starkproof not being cairoserialize. It's that MerkleHasher doesn't implement Cairoserialize. Just a limitation of derive macros. If they were implemented differently it would realise it only needs `StarkProof<H>` to be cairoserialize not H Cairoserialize
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs` line 39 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/251#-OEEEscn364toMiaewAq:-OEEL5OC5wtxnmrruqL3:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/38e4aa8828ea45f5f30a66c03018f60e915f0664/stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs#L39)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs` line 40 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/251#-OEEF0vk7IcNaLiQY0Pz:-OEEL7s-B2SZnaQcAUdW:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/38e4aa8828ea45f5f30a66c03018f60e915f0664/stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs#L40)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

add a todo(ohad) to propagate this from outside
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs` line 41 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/251#-OEEEtep7POsXTv8I356:-OEEL8u74NnkDW15itCl:b-kk1tz4) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/38e4aa8828ea45f5f30a66c03018f60e915f0664/stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs#L41)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

maybe more than 0?
</blockquote></details>

Sure. Feel free to change after merge.  It's just a dummy value I use for the proof generation ATM
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs` line 131 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/251#-OEEF7E7-OqfnP0VSMjJ:-OEELV846fJKN7WmSbKe:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/38e4aa8828ea45f5f30a66c03018f60e915f0664/stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs#L131)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.

**Review by ohad-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/251#-:-OEE_OES-jTzon1PsLtH:bnfp4nl)* status: 15 of 74 files reviewed, 1 unresolved discussion (waiting on @andrewmilson)

___
*[`stwo_cairo_prover/crates/cairo-serialize/Cargo.toml` line 9 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/251#-OEE8HfK06ocuA8XE1EN:-OEEZx8w7mgH1EremJY6:b-bijdm5) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/7044f1a54da91cf2aeb77ed83d71880429900576/stwo_cairo_prover/crates/cairo-serialize/Cargo.toml#L9)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Yes. That is the case currently.
</blockquote></details>

oh ok my bad
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/air.rs` line 43 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/251#-OEEEbE09bMp42yp2uYZ:-OEE_IRh9xjUhSXrastE:br3x0ry) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/38e4aa8828ea45f5f30a66c03018f60e915f0664/stwo_cairo_prover/crates/prover/src/cairo_air/air.rs#L43)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

It's not starkproof not being cairoserialize. It's that MerkleHasher doesn't implement Cairoserialize. Just a limitation of derive macros. If they were implemented differently it would realise it only needs `StarkProof<H>` to be cairoserialize not H Cairoserialize
</blockquote></details>

oh such a shame

**Pull request merged**
