### PR TITLE
MerkleVerifier

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/3)

### CODE REVIEW

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/3)* status: 5 of 7 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`stwo_cairo_verifier/src/vcs/hasher.cairo` line 56 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/3#-O-_xdiC3mKkewlk0jDT:-O-_xdiC3mKkewlk0jDU:b-ed1x9f) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3552bc824a02b0d8ba943e2dc36f11ed4183455d/stwo_cairo_verifier/src/vcs/hasher.cairo#L56)):*
> ```Cairo
>             word = word * M31_IN_HASH_SHIFT + column_values.pop_front().unwrap().inner.into();
>             word = word * M31_IN_HASH_SHIFT + column_values.pop_front().unwrap().inner.into();
>             hash_array.append(word);
> ```

You added this line. Is that on purpose?



_Code quote:_
```Cairo
hash_array.append(word);
```
___
*[`stwo_cairo_verifier/src/vcs/hasher.cairo` line 72 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/3#-O-_yByLDIZerDfk4vzt:-O-_yByLDIZerDfk4vzu:brg62t5) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3552bc824a02b0d8ba943e2dc36f11ed4183455d/stwo_cairo_verifier/src/vcs/hasher.cairo#L72)):*
> ```Cairo
>         assert_eq!(
>             PoseidonMerkleHasher::hash_node(Option::None, array![m31(0), m31(1)]),
>             2552053700073128806553921687214114320458351061521275103654266875084493044716
> ```

Why the result was changed?



_Code quote:_
```Cairo
            PoseidonMerkleHasher::hash_node(Option::None, array![m31(0), m31(1)]),
            2552053700073128806553921687214114320458351061521275103654266875084493044716
```

**Comment by ilyalesokhin-starkware** [comment]
*[`stwo_cairo_verifier/src/utils.cairo` line 11 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/3#-O-eA3Di8k1oVjgUahGG:-O-eA3Di8k1oVjgUahGH:b78e0jb) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3552bc824a02b0d8ba943e2dc36f11ed4183455d/stwo_cairo_verifier/src/utils.cairo#L11)):*
> ```Cairo
> #[generate_trait]
> pub impl DictImpl<T, +Felt252DictValue<T>, +PanicDestruct<T>> of DictTrait<T> {
>     fn replace(ref self: Felt252Dict<T>, key: felt252, def: T) -> T {
> ```

why def?



_Code quote:_
```Cairo
 def: T
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/3)* status: 5 of 7 files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware and @shaharsamocha7)

___
*[`stwo_cairo_verifier/src/utils.cairo` line 11 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/3#-O-eA3Di8k1oVjgUahGG:-O-eBRtu266vz_zjMScP:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3552bc824a02b0d8ba943e2dc36f11ed4183455d/stwo_cairo_verifier/src/utils.cairo#L11)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why def?
</blockquote></details>

Done.
___
*[`stwo_cairo_verifier/src/vcs/hasher.cairo` line 56 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/3#-O-_xdiC3mKkewlk0jDT:-O-eBWfH-CXWMhpbhTYy:bdutwkq) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3552bc824a02b0d8ba943e2dc36f11ed4183455d/stwo_cairo_verifier/src/vcs/hasher.cairo#L56)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

You added this line. Is that on purpose?
</blockquote></details>

Yes. It was a bug before. I'm packing the words, then adding to hash_array, then hashing hash_array.
___
*[`stwo_cairo_verifier/src/vcs/hasher.cairo` line 72 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/3#-O-_yByLDIZerDfk4vzt:-O-eBcx22hWuSUw07m3y:b-5l0tbb) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3552bc824a02b0d8ba943e2dc36f11ed4183455d/stwo_cairo_verifier/src/vcs/hasher.cairo#L72)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Why the result was changed?
</blockquote></details>

Because it had a bug before.
___
*[`stwo_cairo_verifier/src/vcs/verifier.cairo` line 41 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/3#-O-VByBM3zUDbKs-SF9R:-O-eCJ-iEJFri27_hFhN:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3552bc824a02b0d8ba943e2dc36f11ed4183455d/stwo_cairo_verifier/src/vcs/verifier.cairo#L41)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

docunent
</blockquote></details>

Done.

**Comment by ilyalesokhin-starkware** [comment]
*[`stwo_cairo_verifier/src/vcs/verifier.cairo` line 97 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/3#-O-j6Eq21wH7iV08BPbj:-O-j6Eq30_ObFHgNmZZ4:bv8ourb) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ffa3b7b78854bfccd94e120ec817d032eff9e880/stwo_cairo_verifier/src/vcs/verifier.cairo#L97)):*
> ```Cairo
>             let mut layer_cols = cols_by_size
>                 .replace(layer_log_size.into(), Default::default())
>                 .deref_or(array![]);
> ```

What is this?
is this the same as unwrap_or?



_Code quote:_
```Cairo
 .deref_or
```

**Comment by ilyalesokhin-starkware** [comment]
*[`stwo_cairo_verifier/src/vcs/verifier.cairo` line 102 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/3#-O-j6aQxEY9UieLrMF4H:-O-j6aQyBC9BeepxLro0:bpfm04i) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ffa3b7b78854bfccd94e120ec817d032eff9e880/stwo_cairo_verifier/src/vcs/verifier.cairo#L102)):*
> ```Cairo
>             let mut layer_queried_values = array![];
> 
>             while !layer_cols.is_empty() {
> ```

Can you use while let?



_Code quote:_
```Cairo
 while !layer_cols.is_empty()
```

**Comment by ilyalesokhin-starkware** [comment]
*[`stwo_cairo_verifier/src/vcs/verifier.cairo` line 245 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/3#-O-j7Vg43NQn6riGHmCO:-O-j7Vg43NQn6riGHmCP:b-9deq3d) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ffa3b7b78854bfccd94e120ec817d032eff9e880/stwo_cairo_verifier/src/vcs/verifier.cairo#L245)):*
> ```Cairo
> fn fetch_prev_node_hash<H, +Copy<H>, +Drop<H>>(
>     ref prev_layer_hashes: Array<(u32, H)>, ref hash_witness: Array<H>, expected_query: u32
> ) -> Option<H> {
> ```

document,

+ In what sense is this a 'prev' node hash?



_Code quote:_
```Cairo
fn fetch_prev_node_hash<H, +Copy<H>, +Drop<H>>(
    ref prev_layer_hashes: Array<(u32, H)>, ref hash_witness: Array<H>, expected_query: u32
) -> Option<H> {
```

**Comment by ilyalesokhin-starkware** [comment]
*[`stwo_cairo_verifier/src/vcs/verifier.cairo` line 127 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/3#-O-j7gWKB83VMSrvtDjv:-O-j7gWKB83VMSrvtDjw:bac1co9) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ffa3b7b78854bfccd94e120ec817d032eff9e880/stwo_cairo_verifier/src/vcs/verifier.cairo#L127)):*
> ```Cairo
>                     Option::None
>                 } else {
>                     // If the left child was not computed, read it from the witness.
> ```

Isn't this done inside ` fetch_prev_node_hash`? why is this comment there?



_Code quote:_
```Cairo
   // If the left child was not computed, read it from the witness.
```

**Comment by ilyalesokhin-starkware** [comment]
*[`stwo_cairo_verifier/src/vcs/verifier.cairo` line 154 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/3#-O-j8-fg8BmrD7h7FEgd:-O-j8-fh-bBtAEC-UAW6:b3kre) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ffa3b7b78854bfccd94e120ec817d032eff9e880/stwo_cairo_verifier/src/vcs/verifier.cairo#L154)):*
> ```Cairo
>                     let mut i = 0;
>                     while i != n_columns_in_layer {
>                         let col_queried = layer_queried_values[i];
> ```

?



_Suggestion:_
```Cairo
queried_column 
```

**Comment by ilyalesokhin-starkware** [comment]
*[`stwo_cairo_verifier/src/vcs/verifier.cairo` line 240 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/3#-O-jASjXA-fGbM_xzw05:-O-jASjXA-fGbM_xzw06:bp6erfa) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ffa3b7b78854bfccd94e120ec817d032eff9e880/stwo_cairo_verifier/src/vcs/verifier.cairo#L240)):*
> ```Cairo
>             Option::Some(column_query), Option::Some(prev_query)
>         ) => { Option::Some(min(*column_query, prev_query)) },
>     }
> ```

Don't you query everything in the same place with OODS why do we have this complicated logic?



_Code quote:_
```Cairo
    match (layer_query_head, prev_query_head) {
        (Option::None, Option::None) => { Option::None },
        (Option::Some(column_query), Option::None) => { Option::Some(*column_query) },
        (Option::None, Option::Some(prev_query)) => { Option::Some(prev_query) },
        (
            Option::Some(column_query), Option::Some(prev_query)
        ) => { Option::Some(min(*column_query, prev_query)) },
    }
```

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/3)* status: 5 of 7 files reviewed, 10 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`stwo_cairo_verifier/src/vcs/hasher.cairo` line 48 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/3#-O-oLfM0AHv9MAI4SLaM:-O-oLfM0AHv9MAI4SLaN:b-sntedn) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ffa3b7b78854bfccd94e120ec817d032eff9e880/stwo_cairo_verifier/src/vcs/hasher.cairo#L48)):*
> ```Cairo
>         while !column_values.is_empty() {
>             let mut word = 0;
>             word = word * M31_IN_HASH_SHIFT + column_values.pop_front().unwrap().inner.into();
> ```

Consider changing to a for loop of 8 times
Document that 2**31 **8 < Felt252, no?



_Code quote:_
```Cairo
word = word * M31_IN_HASH_SHIFT + column_values.pop_front().unwrap().inner.into();
```

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/3#-:-O-pK7p65hN4ed6LWgXK:bnfp4nl)* status: 5 of 7 files reviewed, 9 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/3)* status: 5 of 7 files reviewed, 9 unresolved discussions (waiting on @ilyalesokhin-starkware and @shaharsamocha7)

___
*[`stwo_cairo_verifier/src/vcs/verifier.cairo` line 97 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/3#-O-j6Eq21wH7iV08BPbj:-O-pKIU67vYnNF1WtyUt:b9cil0u) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ffa3b7b78854bfccd94e120ec817d032eff9e880/stwo_cairo_verifier/src/vcs/verifier.cairo#L97)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

What is this?
is this the same as unwrap_or?
</blockquote></details>

It's unwrap, but deref() on the positive branch.
___
*[`stwo_cairo_verifier/src/vcs/verifier.cairo` line 102 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/3#-O-j6aQxEY9UieLrMF4H:-O-pM5I04Pf5YADc4llj:b-83sjoh) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ffa3b7b78854bfccd94e120ec817d032eff9e880/stwo_cairo_verifier/src/vcs/verifier.cairo#L102)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Can you use while let?
</blockquote></details>

Nice!
___
*[`stwo_cairo_verifier/src/vcs/verifier.cairo` line 127 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/3#-O-j7gWKB83VMSrvtDjv:-O-pMMzd9OZnBt2Cc2OL:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ffa3b7b78854bfccd94e120ec817d032eff9e880/stwo_cairo_verifier/src/vcs/verifier.cairo#L127)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Isn't this done inside ` fetch_prev_node_hash`? why is this comment there?
</blockquote></details>

Done.
___
*[`stwo_cairo_verifier/src/vcs/verifier.cairo` line 154 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/3#-O-j8-fg8BmrD7h7FEgd:-O-pMQLN6ff8BPjB7Ii1:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ffa3b7b78854bfccd94e120ec817d032eff9e880/stwo_cairo_verifier/src/vcs/verifier.cairo#L154)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.
___
*[`stwo_cairo_verifier/src/vcs/verifier.cairo` line 240 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/3#-O-jASjXA-fGbM_xzw05:-O-pMcqrD8oQLVA70ASG:bz6bqd6) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ffa3b7b78854bfccd94e120ec817d032eff9e880/stwo_cairo_verifier/src/vcs/verifier.cairo#L240)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Don't you query everything in the same place with OODS why do we have this complicated logic?
</blockquote></details>

Unfortunately, no. Because each layer has a circle poly commitment.
I need to open f(P) and f(-P).
However, the mixed degree fri, required my parent layer to be opened at 2P.
This means my sybling must be P+(1,0).

Come to think about it, maybe I could always keep P and -P together in the same leaf. This pairing is preserved under P -> 2P...
I'll see if it work in the main repo, but for now, that's how the algo works.
___
*[`stwo_cairo_verifier/src/vcs/verifier.cairo` line 245 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/3#-O-j7Vg43NQn6riGHmCO:-O-pQZhy-wJYFf3PtZ8p:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ffa3b7b78854bfccd94e120ec817d032eff9e880/stwo_cairo_verifier/src/vcs/verifier.cairo#L245)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

document,

+ In what sense is this a 'prev' node hash?
</blockquote></details>

Done.

**Comment by ilyalesokhin-starkware** [comment]
*[`stwo_cairo_verifier/src/vcs/hasher.cairo` line 3 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/3#-O1Aziie9M0SFJAphtGh:-O1Aziie9M0SFJAphtGi:b3kre) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/2e9c03bdb030a62d93c29ff09470c71b69f0c570/stwo_cairo_verifier/src/vcs/hasher.cairo#L3)):*
> ```Cairo
> use core::array::ArrayTrait;
> use core::option::OptionTrait;
> // use core::poseidon::poseidon_hash_span;
> ```

?



_Code quote:_
```Cairo
// use core::poseidon::poseidon_hash_span;
```

**Comment by ilyalesokhin-starkware** [comment]
*[`stwo_cairo_verifier/src/vcs/hasher.cairo` line 8 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/3#-O1AzvdZ5IYK3eDlAy-A:-O1AzvdZ5IYK3eDlAy-B:b19kiqc) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/2e9c03bdb030a62d93c29ff09470c71b69f0c570/stwo_cairo_verifier/src/vcs/hasher.cairo#L8)):*
> ```Cairo
> use core::poseidon::{hades_permutation, HashState};
> 
> // Modified version of poseidon_hash_span that doesn't require builtin gas costs
> ```

how does the recursion work without the builtin gas costs?



_Code quote:_
```Cairo
 require builtin gas costs
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/3)* status: 3 of 7 files reviewed, 11 unresolved discussions (waiting on @ilyalesokhin-starkware and @shaharsamocha7)

___
*[`stwo_cairo_verifier/src/vcs/hasher.cairo` line 3 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/3#-O1Aziie9M0SFJAphtGh:-O1B-TNvAFzvgXnMcp9-:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/2e9c03bdb030a62d93c29ff09470c71b69f0c570/stwo_cairo_verifier/src/vcs/hasher.cairo#L3)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.
___
*[`stwo_cairo_verifier/src/vcs/hasher.cairo` line 8 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/3#-O1AzvdZ5IYK3eDlAy-A:-O1B-dkaDLd5GuUADrG6:b-6t96hp) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/2e9c03bdb030a62d93c29ff09470c71b69f0c570/stwo_cairo_verifier/src/vcs/hasher.cairo#L8)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

how does the recursion work without the builtin gas costs?
</blockquote></details>

Oops, this is leftover from, debugging, sorry. Reverted

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r1, 1 of 2 files at r2, 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/3)* status: 5 of 7 files reviewed, 6 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`stwo_cairo_verifier/src/vcs/verifier.cairo` line 242 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/3#-O1B02iVCcKEwto6O1qW:-O1B02iVCcKEwto6O1qX:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/2e9c03bdb030a62d93c29ff09470c71b69f0c570/stwo_cairo_verifier/src/vcs/verifier.cairo#L242)):*
> ```Cairo
> 
> /// Fetches the hash of the next node from the previous layer in the Merkle tree.
> /// Either from the computed values or from the witness.
> ```





_Suggestion:_
```Cairo
/// The hash Either from the computed values or from the witness.
```
___
*[`stwo_cairo_verifier/src/vcs/verifier.cairo` line 270 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/3#-O1B0-dOEjq8W86ASFXf:-O1B0-dOEjq8W86ASFXg:b3kre) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/2e9c03bdb030a62d93c29ff09470c71b69f0c570/stwo_cairo_verifier/src/vcs/verifier.cairo#L270)):*
> ```Cairo
> 
> 
> // use core::poseidon::poseidon_hash_span;
> ```

?



_Code quote:_
```Cairo
// use core::poseidon::poseidon_hash_span
```

**Comment by ilyalesokhin-starkware** [comment]
*[`stwo_cairo_verifier/src/vcs/verifier.cairo` line 242 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/3#-O1B02iVCcKEwto6O1qW:-O1B0f4h0Nkw85nqBj-k:b-kygo9c) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/2e9c03bdb030a62d93c29ff09470c71b69f0c570/stwo_cairo_verifier/src/vcs/verifier.cairo#L242)):*
> ```Cairo
> 
> /// Fetches the hash of the next node from the previous layer in the Merkle tree.
> /// Either from the computed values or from the witness.
> ```

sorry, ignore.

**Comment by ilyalesokhin-starkware** [comment]
*[`stwo_cairo_verifier/src/vcs/verifier.cairo` line 242 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/3#-O1B0kqVACtlhFQL-ndp:-O1B0kqVACtlhFQL-ndq:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/2e9c03bdb030a62d93c29ff09470c71b69f0c570/stwo_cairo_verifier/src/vcs/verifier.cairo#L242)):*
> ```Cairo
> 
> /// Fetches the hash of the next node from the previous layer in the Merkle tree.
> /// Either from the computed values or from the witness.
> ```





_Suggestion:_
```Cairo
/// Fetches the hash of the next node from the previous layer in the Merkle tree.
/// The hash is fetched either from the computed values or from the witness.
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/3)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @shaharsamocha7)

___
*[`stwo_cairo_verifier/src/vcs/verifier.cairo` line 242 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/3#-O1B0kqVACtlhFQL-ndp:-O1B27Nf6lDR8LRZk8gH:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/2e9c03bdb030a62d93c29ff09470c71b69f0c570/stwo_cairo_verifier/src/vcs/verifier.cairo#L242)):*
> ```Cairo
> 
> /// Fetches the hash of the next node from the previous layer in the Merkle tree.
> /// Either from the computed values or from the witness.
> ```

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/3#-:-O1B2m8X4guAo5ntRaQ0:bnfp4nl)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/3)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @shaharsamocha7)

**Pull request merged**
