### PR TITLE
Split memory values into 9 bit values.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/29)

### CODE REVIEW

**Comment by alonh5** [comment]
* **#30** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/30?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#29** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/29?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alonh5 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/29#-:-O2TjhIU7M8Pkdfn83V1:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`stwo_cairo_prover/src/components/memory/component.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/29#-O2Tjd3E3c5YDpW1djpN:-O2Tjd3E3c5YDpW1djpO:baf6zlm) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/672a2415a9d55450b69b04eb92838fa35569aaa2/stwo_cairo_prover/src/components/memory/component.rs#L34)):*
> ```XML
> 
> pub const N_M31_IN_FELT252: usize = 28;
> pub const MULTIPLICITY_COLUMN: usize = N_M31_IN_FELT252 + 1;
> ```

non-blocking



_Suggestion:_
```XML
pub const MULTIPLICITY_COLUMN_OFFSET: usize = N_M31_IN_FELT252 + 1;
```

**Review by alonh5 — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/29)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Review by shaharsamocha7 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/29)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Pull request merged**
