### PR TITLE
Add FRI layer 0 commitment

### PR DESCRIPTION
**Pull request by andrewmilson**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/186)

### CODE REVIEW

**Comment by andrewmilson** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/186?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#186** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/186?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/186?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#185** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/185?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#184** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/184?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#164** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/164?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#174** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/174?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#163** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/163?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#162** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/162?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#137** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/137?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#138](https://github.com/starkware-libs/stwo-cairo/pull/138) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/138?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#135** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/135?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#134** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/134?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#153** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/153?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Comment by ilyalesokhin-starkware** [comment]
*[`stwo_cairo_verifier/src/pcs/quotients.cairo` line 30 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/186#-OC7_wJb8Ktd-Xh4AgXb:-OC7_wJb8Ktd-Xh4AgXc:b-cqqg05) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/50a34505366205b7f91e51e9056e81dfb8ddd8a9/stwo_cairo_verifier/src/pcs/quotients.cairo#L30)):*
> ```Cairo
>     mut query_positions_per_log_size: Felt252Dict<Nullable<Span<usize>>>,
>     queried_values_per_column: @Array<Array<M31>>,
>     mut missing_values: Span<QM31>,
> ```

Please document the arguments.



_Code quote:_
```Cairo
    log_size_per_column: @Array<u32>,
    samples_per_column: @Array<Array<PointSample>>,
    random_coeff: QM31,
    mut query_positions_per_log_size: Felt252Dict<Nullable<Span<usize>>>,
    queried_values_per_column: @Array<Array<M31>>,
    mut missing_values: Span<QM31>,
```

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/186)* status: 0 of 29 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @shaharsamocha7)

___
*[`stwo_cairo_verifier/src/pcs/quotients.cairo` line 30 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/186#-OC7_wJb8Ktd-Xh4AgXb:-OCaciqX2NijMrcNlzr3:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/50a34505366205b7f91e51e9056e81dfb8ddd8a9/stwo_cairo_verifier/src/pcs/quotients.cairo#L30)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Please document the arguments.
</blockquote></details>

Done.
___
*[`stwo_cairo_verifier/src/utils.cairo` line 14 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/186#-OCWVUcR0J6fU58czjTe:-OCWVUcR0J6fU58czjTf:b8y7k35) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/dcc159a2e70440f2e51e6e3c72604260d3eca9a3/stwo_cairo_verifier/src/utils.cairo#L14)):*
> ```Cairo
> /// Look up table where index `i` stores value `2^i`.
> const POW_2: [u32; 32] = [
>     0b1, // 
> ```

Formatter in new version wants to squash multiple into the same line. The empty comment stops that from happening

**Comment by ilyalesokhin-starkware** [comment]
*[`stwo_cairo_verifier/src/queries.cairo` line 47 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/186#-OCaz5sz7VG5TURqeRUr:-OCaz5sz7VG5TURqeRUs:bs99lcf) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f8bd423a9feeba17de08323e1d3a1751659fab4e/stwo_cairo_verifier/src/queries.cairo#L47)):*
> ```Cairo
> 
>     fn len(self: @Queries) -> usize {
>         (*self.positions).len()
> ```

doesn't span have len?



_Suggestion:_
```Cairo
 self.positions.len()
```

**Comment by ilyalesokhin-starkware** [comment]
*[`stwo_cairo_verifier/src/queries.cairo` line 55 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/186#-OCazMtH2oHAX2jOS_gl:-OCazMtH2oHAX2jOS_gm:bt54hv4) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f8bd423a9feeba17de08323e1d3a1751659fab4e/stwo_cairo_verifier/src/queries.cairo#L55)):*
> ```Cairo
>         Queries {
>             positions: get_folded_query_positions(self.positions, n_folds),
>             // TODO(andrew): Check Cairo does checked sub in all profiles.
> ```

it does, sierra is type safe.

only felt252 can overflow.



_Code quote:_
```Cairo
 // TODO(andrew): Check Cairo does checked sub in all profiles.
```

**Comment by ilyalesokhin-starkware** [comment]
*[`stwo_cairo_verifier/src/queries.cairo` line 75 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/186#-OCazd-S5VigJix_CMpO:-OCazd-S5VigJix_CMpP:b912yj6) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f8bd423a9feeba17de08323e1d3a1751659fab4e/stwo_cairo_verifier/src/queries.cairo#L75)):*
> ```Cairo
>     for position in query_positions {
>         folded_positions.append(*position / folding_factor);
>     };
> ```

Consider deduping inside this loop.



_Suggestion:_
```Cairo
    for position in query_positions {
        new_position = *position / folding_factor;
        if new_position != prev_position
            folded_positions.append(*position / folding_factor);
        prev_position = new_position.
    };
```

**Comment by ilyalesokhin-starkware** [comment]
*[`stwo_cairo_verifier/src/utils.cairo` line 166 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/186#-OCb3T-_1--ggJizHrgz:-OCb3T-_1--ggJizHrh-:b-8nn0c2) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f8bd423a9feeba17de08323e1d3a1751659fab4e/stwo_cairo_verifier/src/utils.cairo#L166)):*
> ```Cairo
>     fn first(mut self: Span<T>) -> Option<@T> {
>         self.pop_front()
>     }
> ```

Does this work?



_Suggestion:_
```Cairo
    fn first(self: @Span<T>) -> Option<@T> {
        *self.pop_front()
    }
```

**Comment by ilyalesokhin-starkware** [comment]
*[`stwo_cairo_verifier/src/utils.cairo` line 184 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/186#-OCb3oaZ3F6JdoV5bfEX:-OCb3oaZ3F6JdoV5bfEY:b-7m74ox) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f8bd423a9feeba17de08323e1d3a1751659fab4e/stwo_cairo_verifier/src/utils.cairo#L184)):*
> ```Cairo
>             if value == other {
>                 self = self_copy;
>                 return Option::Some(other);
> ```

nice!



_Code quote:_
```Cairo
                self = self_copy;
                return Option::Some(other);
```

**Comment by ilyalesokhin-starkware** [comment]
*[`stwo_cairo_verifier/src/pcs/quotients.cairo` line 242 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/186#-OCb8Fq-8Pf1IIISZD7d:-OCb8Fq-8Pf1IIISZD7e:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f8bd423a9feeba17de08323e1d3a1751659fab4e/stwo_cairo_verifier/src/pcs/quotients.cairo#L242)):*
> ```Cairo
> /// * `sampled_batches`: OOD column samples grouped by eval point.
> /// * `queried_values_by_column`: Sampled query evals by trace column.
> /// * `row`: The index of the query to compute the quotients for.
> ```





_Suggestion:_
```Cairo
/// * `query_idx`: The index of the query to compute the quotients for
```

**Comment by ilyalesokhin-starkware** [comment]
*[`stwo_cairo_verifier/src/pcs/quotients.cairo` line 262 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/186#-OCb9er969MUyh-UIqyN:-OCb9erA47-xIRlhyfhN:bo6bij1) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f8bd423a9feeba17de08323e1d3a1751659fab4e/stwo_cairo_verifier/src/pcs/quotients.cairo#L262)):*
> ```Cairo
>     let mut row_accumulator: QM31 = Zero::zero();
> 
>     for batch_i in 0..n_batches {
> ```

You have 4 loops here.

I'd consider refactoring it in the future as
1. compute an array if (numerator, denumerator)
2. batch_inverse +  row_accumulator.

you can add a todo.



_Code quote:_
```Cairo
  for batch_i in 0..n_batches {
```

**Comment by ilyalesokhin-starkware** [comment]
*[`stwo_cairo_verifier/src/vcs/verifier.cairo` line 300 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/186#-OCbAZDf2UzqCffoogsj:-OCbAZDg9nueIeLyPPN6:b-l6hdjr) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f8bd423a9feeba17de08323e1d3a1751659fab4e/stwo_cairo_verifier/src/vcs/verifier.cairo#L300)):*
> ```Cairo
>     use core::nullable::NullableTrait;
>     use core::result::ResultTrait;
>     use stwo_cairo_verifier::fields::m31::m31;
> ```

revert



_Code quote:_
```Cairo
  use stwo_cairo_verifier::fields::m31::m31;
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 2 of 13 files at r1, 4 of 17 files at r3, 9 of 24 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/186)* status: 13 of 29 files reviewed, 7 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

**Comment by ilyalesokhin-starkware** [comment]
*[`stwo_cairo_verifier/src/pcs/quotients.cairo` line 38 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/186#-OCdt8Gf7pO-eHWTGKeW:-OCdt8Gf7pO-eHWTGKeX:bh6lpsl) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f8bd423a9feeba17de08323e1d3a1751659fab4e/stwo_cairo_verifier/src/pcs/quotients.cairo#L38)):*
> ```Cairo
> 
>     // Group columns by log size.
>     // TODO(andrew): Refactor. Use a dict.
> ```

If the columns are stored by size is the dict still nessiary?



_Code quote:_
```Cairo
 // TODO(andrew): Refactor. Use a dict.
```

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/186)* status: 13 of 29 files reviewed, 7 unresolved discussions (waiting on @ilyalesokhin-starkware and @shaharsamocha7)

___
*[`stwo_cairo_verifier/src/queries.cairo` line 47 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/186#-OCaz5sz7VG5TURqeRUr:-OCcrqwXCCIfuJ_eNCcV:b-kjhp9l) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f8bd423a9feeba17de08323e1d3a1751659fab4e/stwo_cairo_verifier/src/queries.cairo#L47)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

doesn't span have len?
</blockquote></details>

`Span` does but `@Span` doesn't
___
*[`stwo_cairo_verifier/src/queries.cairo` line 55 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/186#-OCazMtH2oHAX2jOS_gl:-OCctkaOBUVpdCwZDL3o:b1k6aiu) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f8bd423a9feeba17de08323e1d3a1751659fab4e/stwo_cairo_verifier/src/queries.cairo#L55)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

it does, sierra is type safe.

only felt252 can overflow.
</blockquote></details>

Great. Removed
___
*[`stwo_cairo_verifier/src/queries.cairo` line 75 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/186#-OCazd-S5VigJix_CMpO:-OCdPqRW2s4tf8JmtkuD:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f8bd423a9feeba17de08323e1d3a1751659fab4e/stwo_cairo_verifier/src/queries.cairo#L75)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Consider deduping inside this loop.
</blockquote></details>

Done.
___
*[`stwo_cairo_verifier/src/utils.cairo` line 166 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/186#-OCb3T-_1--ggJizHrgz:-OCcsKGw7e_uu6xFVH7F:b-bt47v2) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f8bd423a9feeba17de08323e1d3a1751659fab4e/stwo_cairo_verifier/src/utils.cairo#L166)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Does this work?
</blockquote></details>

Complains "ref argument must be a variable".
It's possible with 
```
    fn first(self: @Span<T>) -> Option<@T> {
        let mut self_copy = *self;
        self_copy.pop_front()
    }
```
but leaving as is seems more consistent with the other Span impls like .len() being implemented on `Span` not `@Span`. WDYT?
___
*[`stwo_cairo_verifier/src/pcs/quotients.cairo` line 38 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/186#-OCdt8Gf7pO-eHWTGKeW:-OCdtxLV7ERlPr9zn5Ri:b-9344lb) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f8bd423a9feeba17de08323e1d3a1751659fab4e/stwo_cairo_verifier/src/pcs/quotients.cairo#L38)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

If the columns are stored by size is the dict still nessiary?
</blockquote></details>

Ahh nice. True
___
*[`stwo_cairo_verifier/src/pcs/quotients.cairo` line 262 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/186#-OCb9er969MUyh-UIqyN:-OCdtreoDaXnfrra9Ax8:b-jn5s6n) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f8bd423a9feeba17de08323e1d3a1751659fab4e/stwo_cairo_verifier/src/pcs/quotients.cairo#L262)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

You have 4 loops here.

I'd consider refactoring it in the future as
1. compute an array if (numerator, denumerator)
2. batch_inverse +  row_accumulator.

you can add a todo.
</blockquote></details>

Discussed offline.
___
*[`stwo_cairo_verifier/src/vcs/verifier.cairo` line 300 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/186#-OCbAZDf2UzqCffoogsj:-OCdudL70VR2Ff1sc1T8:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f8bd423a9feeba17de08323e1d3a1751659fab4e/stwo_cairo_verifier/src/vcs/verifier.cairo#L300)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

revert
</blockquote></details>

Done.
___
*[`stwo_cairo_verifier/src/pcs/quotients.cairo` line 242 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/186#-OCb8Fq-8Pf1IIISZD7d:-OCduGyI6GdrcMMzbzOG:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f8bd423a9feeba17de08323e1d3a1751659fab4e/stwo_cairo_verifier/src/pcs/quotients.cairo#L242)):*
> ```Cairo
> /// * `sampled_batches`: OOD column samples grouped by eval point.
> /// * `queried_values_by_column`: Sampled query evals by trace column.
> /// * `row`: The index of the query to compute the quotients for.
> ```

Done.

**Comment by ilyalesokhin-starkware** [comment]
*[`stwo_cairo_verifier/src/utils.cairo` line 166 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/186#-OCb3T-_1--ggJizHrgz:-OClkIsvB9iU0i8YsHdx:b-a2kzma) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f8bd423a9feeba17de08323e1d3a1751659fab4e/stwo_cairo_verifier/src/utils.cairo#L166)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Complains "ref argument must be a variable".
It's possible with 
```
    fn first(self: @Span<T>) -> Option<@T> {
        let mut self_copy = *self;
        self_copy.pop_front()
    }
```
but leaving as is seems more consistent with the other Span impls like .len() being implemented on `Span` not `@Span`. WDYT?
</blockquote></details>

I find it strange that you must consume the span to get the first element.

Maybe:


 fn first(self: @Span<T>) -> Option<@T> {
        self.iter().next()
  }

**Comment by ilyalesokhin-starkware** [comment]
*[`stwo_cairo_verifier/tests/verifier.cairo` line 20 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/186#-OCllg1mDW_8O-_NdIX5:-OCllg1mDW_8O-_NdIX6:b3kre) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/2d874fc12a8be56a177f3720fec8609498aaa302/stwo_cairo_verifier/tests/verifier.cairo#L20)):*
> ```Cairo
> //     let test_proof = proofs::test_proof::proof();
> //     println!("TEST PROOF WORKED");
> // }
> ```

?



_Code quote:_
```Cairo
// #[test]
// fn test_deserialise() {
//     let test_proof = proofs::test_proof::proof();
//     println!("TEST PROOF WORKED");
// }
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 11 of 24 files at r5, 6 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/186)* status: 27 of 29 files reviewed, 2 unresolved discussions (waiting on @andrewmilson, @shaharsamocha7, @span, and @t)

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 24 files at r5, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/186#-:-OD5-N176nmfzbc0gxZR:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Pull request merged**
