### PR TITLE
Implement ComponentProver for RangeCheckUnitComponent.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/13)

### CODE REVIEW

**Comment by alonh5** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/13?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#13** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/13?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#12** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/12?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#11** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/11?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alonh5 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/13)* status: 4 of 6 files reviewed, 6 unresolved discussions (waiting on @alonh5)

___
*[`stwo_cairo_prover/rustfmt.toml` line 1 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/13#-O1QajdQCTEx0dtOqA58:-O1QajdQCTEx0dtOqA59:bxvb0sj) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/2a5c91e91d447839ddb0b503f9b128578990d14a/stwo_cairo_prover/rustfmt.toml#L1)):*
> ```TOML
> # See: https://rust-lang.github.io/rustfmt
> ```

Can you merge it in a separate pr?
___
*[`stwo_cairo_prover/src/components/mod.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/13#-O1Qaxid04nqHNYDcvpb:-O1Qaxid04nqHNYDcvpc:b505oog) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/2a5c91e91d447839ddb0b503f9b128578990d14a/stwo_cairo_prover/src/components/mod.rs#L1)):*
> ```XML
> pub mod range_check;
> ```

Why?
Do you think we'll put here the other range checks?



_Code quote:_
```XML
pub mod range_check;
```
___
*[`stwo_cairo_prover/src/components/range_check/component_prover.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/13#-O1Qbtjo8bji8znosPP2:-O1Qbtjo8bji8znosPP3:byp18fd) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/2a5c91e91d447839ddb0b503f9b128578990d14a/stwo_cairo_prover/src/components/range_check/component_prover.rs#L24)):*
> ```XML
>         accum: &mut ColumnAccumulator<'_, CpuBackend>,
>         interaction_elements: &InteractionElements,
>         _lookup_values: &LookupValues,
> ```

Remove



_Code quote:_
```XML
        _lookup_values: &LookupValues,
```
___
*[`stwo_cairo_prover/src/components/range_check/mod.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/13#-O1Qbihb65r-hRv3FAUq:-O1Qbihb65r-hRv3FAUr:b-2coz5b) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/2a5c91e91d447839ddb0b503f9b128578990d14a/stwo_cairo_prover/src/components/range_check/mod.rs#L29)):*
> ```XML
> 
>     pub fn register_test_rc() -> ComponentGenerationRegistry {
>         let mut registry = ComponentGenerationRegistry::default();
> ```

Consider to get a mut registry as input and register to it.



_Code quote:_
```XML
let mut registry = ComponentGenerationRegistry::default();
```
___
*[`stwo_cairo_prover/src/components/range_check/mod.rs` line 139 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/13#-O1Qc8HIEp45ao1va6Lb:-O1Qc8HIEp45ao1va6Lc:b-mtuviq) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/2a5c91e91d447839ddb0b503f9b128578990d14a/stwo_cairo_prover/src/components/range_check/mod.rs#L139)):*
> ```XML
>         // let verifier_channel =
>         //     &mut Blake2sChannel::new(Blake2sHasher::hash(BaseField::into_slice(&[])));
>         // verify(proof, &air.to_air_prover(), verifier_channel).unwrap();
> ```

Verify doesn't work?



_Code quote:_
```XML
        // verify(proof, &air.to_air_prover(), verifier_channel).unwrap();
```
___
*[`stwo_cairo_prover/src/components/range_check/component.rs` line 77 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/13#-O1QbUWI6K1KiDQoua-q:-O1QbUWI6K1KiDQoua-r:bkzrwbu) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/2a5c91e91d447839ddb0b503f9b128578990d14a/stwo_cairo_prover/src/components/range_check/component.rs#L77)):*
> ```XML
>     ) -> TreeVec<ColumnVec<Vec<CirclePoint<SecureField>>>> {
>         TreeVec::new(vec![
>             fixed_mask_points(&vec![vec![0_usize]; 2], point),
> ```

Was it a bug? the 2 change



_Code quote:_
```XML
fixed_mask_points(&vec![vec![0_usize]; 2], point),
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/13)* status: 4 of 6 files reviewed, 6 unresolved discussions (waiting on @shaharsamocha7)

___
*[`stwo_cairo_prover/rustfmt.toml` line 1 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/13#-O1QajdQCTEx0dtOqA58:-O1REz7R64dy5siQ8Nmo:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/2a5c91e91d447839ddb0b503f9b128578990d14a/stwo_cairo_prover/rustfmt.toml#L1)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can you merge it in a separate pr?
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/src/components/mod.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/13#-O1Qaxid04nqHNYDcvpb:-O1REI4TD8qWcwGDp7wm:b-46rabx) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/2a5c91e91d447839ddb0b503f9b128578990d14a/stwo_cairo_prover/src/components/mod.rs#L1)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Why?
Do you think we'll put here the other range checks?
</blockquote></details>

This is where we'll declare each component model. I'm not sure if that answers the question.
___
*[`stwo_cairo_prover/src/components/range_check/component_prover.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/13#-O1Qbtjo8bji8znosPP2:-O1RCDg85_niiCOyFJ7f:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/2a5c91e91d447839ddb0b503f9b128578990d14a/stwo_cairo_prover/src/components/range_check/component_prover.rs#L24)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Remove
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/src/components/range_check/mod.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/13#-O1Qbihb65r-hRv3FAUq:-O1RCsz27fDXAEp1WUpX:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/2a5c91e91d447839ddb0b503f9b128578990d14a/stwo_cairo_prover/src/components/range_check/mod.rs#L29)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Consider to get a mut registry as input and register to it.
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/src/components/range_check/mod.rs` line 139 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/13#-O1Qc8HIEp45ao1va6Lb:-O1RDwtiEDRwbMbkVuO_:bcrqdjh) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/2a5c91e91d447839ddb0b503f9b128578990d14a/stwo_cairo_prover/src/components/range_check/mod.rs#L139)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Verify doesn't work?
</blockquote></details>

It does, forgot to uncomment.
___
*[`stwo_cairo_prover/src/components/range_check/component.rs` line 77 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/13#-O1QbUWI6K1KiDQoua-q:-O1RBxCF2KE9tCDbMxQQ:b-pewmeu) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/2a5c91e91d447839ddb0b503f9b128578990d14a/stwo_cairo_prover/src/components/range_check/component.rs#L77)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Was it a bug? the 2 change
</blockquote></details>

Yes there are 2 columns and not 1.

**Review by shaharsamocha7 — COMMENTED** [review]
> Reviewed 1 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/13)* status: 2 of 6 files reviewed, all discussions resolved

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/13)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5)

___
*[`stwo_cairo_prover/src/components/range_check_unit/component_prover.rs` line 16 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/13#-O1VjMmx1P6arCwkXHqZ:-O1VjMmx1P6arCwkXHq_:bzhzbrg) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/dbcd5a755de75ceb13ddd462d13f311b362910a9/stwo_cairo_prover/src/components/range_check_unit/component_prover.rs#L16)):*
> ```XML
> use super::component::{RangeCheckUnitComponent, RC_Z};
> 
> impl RangeCheckUnitComponent {
> ```

Let's try to put impls on structs only near the struct definition. Here, you can make this a function instead of a method (i.e., not inside an impl).
___
*[`stwo_cairo_prover/src/components/range_check_unit/component_prover.rs` line 17 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/13#-O1Vjbpd0HuzO2F6dpi-:-O1Vjbpd0HuzO2F6dpi0:b-1bj8rl) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/dbcd5a755de75ceb13ddd462d13f311b362910a9/stwo_cairo_prover/src/components/range_check_unit/component_prover.rs#L17)):*
> ```XML
> 
> impl RangeCheckUnitComponent {
>     fn evaluate_lookup_boundary_constraints(
> ```

Bring this function down, after its use. This is not the first thing the reader should see in this file.

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/13)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`stwo_cairo_prover/src/components/range_check_unit/component_prover.rs` line 16 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/13#-O1VjMmx1P6arCwkXHqZ:-O1kaZcG3Njoy1Dyb8vw:bx506ne) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e03e436b288a17d5047d2e5425acaaadf950d0a4/stwo_cairo_prover/src/components/range_check_unit/component_prover.rs#L16)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Let's try to put impls on structs only near the struct definition. Here, you can make this a function instead of a method (i.e., not inside an impl).
</blockquote></details>

I removed this impl in a later PR (18).
___
*[`stwo_cairo_prover/src/components/range_check_unit/component_prover.rs` line 17 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/13#-O1Vjbpd0HuzO2F6dpi-:-O1kacxFBiN9tpMSbOzv:bx94nwr) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e03e436b288a17d5047d2e5425acaaadf950d0a4/stwo_cairo_prover/src/components/range_check_unit/component_prover.rs#L17)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Bring this function down, after its use. This is not the first thing the reader should see in this file.
</blockquote></details>

I removed this function altogether in said PR (18).

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/13)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5)

___
*[`stwo_cairo_prover/src/components/range_check_unit/component_prover.rs` line 16 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/13#-O1VjMmx1P6arCwkXHqZ:-O1kfMf9EEmcCXB_6Qma:b-wc74yr) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e03e436b288a17d5047d2e5425acaaadf950d0a4/stwo_cairo_prover/src/components/range_check_unit/component_prover.rs#L16)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

I removed this impl in a later PR (18).
</blockquote></details>

But right now it's not near the component, and I will surely forget to check it by then.
Can you juse make it a function here instead? Shouldn't eb a lot of work

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/13)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5)

___
*[`stwo_cairo_prover/src/components/range_check_unit/component_prover.rs` line 17 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/13#-O1Vjbpd0HuzO2F6dpi-:-O1kfXQS44slbqCuWbmw:b-pqcj41) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e03e436b288a17d5047d2e5425acaaadf950d0a4/stwo_cairo_prover/src/components/range_check_unit/component_prover.rs#L17)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

I removed this function altogether in said PR (18).
</blockquote></details>

Can you do it now?

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/13)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`stwo_cairo_prover/src/components/range_check_unit/component_prover.rs` line 16 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/13#-O1VjMmx1P6arCwkXHqZ:-O1knTka44KjHs3qZkTK:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e03e436b288a17d5047d2e5425acaaadf950d0a4/stwo_cairo_prover/src/components/range_check_unit/component_prover.rs#L16)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

But right now it's not near the component, and I will surely forget to check it by then.
Can you juse make it a function here instead? Shouldn't eb a lot of work
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/src/components/range_check_unit/component_prover.rs` line 17 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/13#-O1Vjbpd0HuzO2F6dpi-:-O1knTvs2bgF4HcZOO7K:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e03e436b288a17d5047d2e5425acaaadf950d0a4/stwo_cairo_prover/src/components/range_check_unit/component_prover.rs#L17)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Can you do it now?
</blockquote></details>

Done.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/13#-:-O1kvBmp-NVKcXmPnXVc:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Pull request merged**
