### PR TITLE
Refactor FRI implementation

### PR DESCRIPTION
**Pull request by andrewmilson**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/115)

### CODE REVIEW

**Comment by andrewmilson** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/115?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#115** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/115?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#114** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/114?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#113** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/113?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#112** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/112?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @andrewmilson and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Alon-Ti — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/115)* status: all files reviewed, 1 unresolved discussion (waiting on @andrewmilson and @shaharsamocha7)

___
*[`stwo_cairo_verifier/src/utils.cairo` line 53 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/115#-O9AIVcZ0snxUwLa_swj:-O9AIVcZ0snxUwLa_swk:b-ytg0cy) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/1eaef30d7a2fb679b67122b9d3ace849863deb1e/stwo_cairo_verifier/src/utils.cairo#L53)):*
> ```Cairo
> 
>     /// Sorts an array in ascending order. Uses quicksort algorithm.
>     fn sort_ascending<+PartialOrd<T>>(self: Array<T>) -> Array<T> {
> ```

Doesn't Cairo1 have O(n) sort for `PartialOrd`?

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/115)* status: all files reviewed, 1 unresolved discussion (waiting on @Alon-Ti and @shaharsamocha7)

___
*[`stwo_cairo_verifier/src/utils.cairo` line 53 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/115#-O9AIVcZ0snxUwLa_swj:-O9aigyp3NcIuqiDHEoE:b-lq9wxy) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/1eaef30d7a2fb679b67122b9d3ace849863deb1e/stwo_cairo_verifier/src/utils.cairo#L53)):*
<details><summary><i>Previously, Alon-Ti wrote…</i></summary><blockquote>

Doesn't Cairo1 have O(n) sort for `PartialOrd`?
</blockquote></details>

Unfortunately not it seems.

**Review by Alon-Ti — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/115#-:-O9ea3Ud0tPYG2-DoGQS:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Pull request merged**
