### PR TITLE
Implement Serde on StarkProof

### PR DESCRIPTION
**Pull request by andrewmilson**
Also includes (1) proofs to test the deserialization and (2) updates the project to latest Scarb version.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/164)

### CODE REVIEW

**Comment by andrewmilson** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/164?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#164** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/164?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#163** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/163?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#162** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/162?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#137** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/137?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#138](https://github.com/starkware-libs/stwo-cairo/pull/138) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/138?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#135** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/135?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#134** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/134?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#153** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/153?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#133** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/133?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#152](https://github.com/starkware-libs/stwo-cairo/pull/152) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/152?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#127** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/127?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#118** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/118?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/117?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#116** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/116?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#115** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/115?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#114** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/114?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#113** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/113?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#112** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/112?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @andrewmilson and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — DISMISSED** [review]
> Reviewed 33 of 37 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/164)* status: all files reviewed, 4 unresolved discussions (waiting on @andrewmilson and @ilyalesokhin-starkware)

___
*[`stwo_cairo_verifier/.cairofmtignore` line 1 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/164#-OBdms4f7y7KwSmYZQxl:-OBdms4f7y7KwSmYZQxm:b-d0wxhj) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/88e38278876c34b681a8d475aec505b2049c7936/stwo_cairo_verifier/.cairofmtignore#L1)):*
> ```
> tests/verifier/proofs
> ```

new line



_Code quote:_
```
tests/verifier/proofs
```
___
*[`stwo_cairo_verifier/tests/verifier/proofs.cairo` line 17 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/164#-OBdoRR_4wQ0vFSewRZl:-OBdoRR_4wQ0vFSewRZm:b3fftho) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/88e38278876c34b681a8d475aec505b2049c7936/stwo_cairo_verifier/tests/verifier/proofs.cairo#L17)):*
> ```Cairo
> // pub mod horizontal_fib_512_column_with_blowup_16;
> // pub mod horizontal_fib_1024_column_with_blowup_2;
> // pub mod horizontal_fib_1024_column_with_blowup_16;
> ```

You can just remove the commented code
Eventually we are going to read proofs from the input



_Suggestion:_
```Cairo
pub mod horizontal_fib_128_column_with_blowup_16;
pub mod horizontal_fib_128_column_with_blowup_2;
```
___
*[`stwo_cairo_verifier/src/poly/line.cairo` line 135 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/164#-OBdnOE1DBfRqH-uPTX1:-OBdnOE1DBfRqH-uPTX2:bpbulxo) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/88e38278876c34b681a8d475aec505b2049c7936/stwo_cairo_verifier/src/poly/line.cairo#L135)):*
> ```Cairo
>                 next_values.append_span(next_r_values.span());
>             };
>             next_values.append_span(chunk_values_rhs.span());
> ```

What is this change?



_Code quote:_
```Cairo
 next_values.append_span(chunk_values_rhs.span());
```
___
*[`stwo_cairo_verifier/src/poly/line.cairo` line 176 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/164#-OBdnXjWD0EvJ_TMtNbW:-OBdnXjWD0EvJ_TMtNbX:be0di94) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/88e38278876c34b681a8d475aec505b2049c7936/stwo_cairo_verifier/src/poly/line.cairo#L176)):*
> ```Cairo
>         Option::Some(res)
>     }
> }
> ```

Q: why we need to serde the entire poly - is it for when fri_last_layer is 64 elements?
Also, why derive serde doesn't work?



_Code quote:_
```Cairo
pub impl LinePolySerde of Serde<LinePoly> {
    fn serialize(self: @LinePoly, ref output: Array<felt252>) {
        self.coeffs.serialize(ref output);
        self.log_size.serialize(ref output);
    }

    fn deserialize(ref serialized: Span<felt252>) -> Option<LinePoly> {
        let res = LinePoly {
            coeffs: Serde::deserialize(ref serialized)?,
            log_size: Serde::deserialize(ref serialized)?,
        };

        // Check the sizes match.
        if res.coeffs.len() != pow(2, res.log_size) {
            return Option::None;
        }

        Option::Some(res)
    }
}
```

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/164)* status: 9 of 39 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @shaharsamocha7)

___
*[`stwo_cairo_verifier/.cairofmtignore` line 1 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/164#-OBdms4f7y7KwSmYZQxl:-OC4BbG00xTtNuRtuoWe:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/88e38278876c34b681a8d475aec505b2049c7936/stwo_cairo_verifier/.cairofmtignore#L1)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

new line
</blockquote></details>

Done.
___
*[`stwo_cairo_verifier/tests/verifier/proofs.cairo` line 17 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/164#-OBdoRR_4wQ0vFSewRZl:-OC4Bg5C9rkhheuyMiE_:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/88e38278876c34b681a8d475aec505b2049c7936/stwo_cairo_verifier/tests/verifier/proofs.cairo#L17)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

You can just remove the commented code
Eventually we are going to read proofs from the input
</blockquote></details>

Done.
___
*[`stwo_cairo_verifier/src/channel.cairo` line 40 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/164#-OBt15L64PWoUxK_uhpY:-OC4Bm2XAcsqgy8Xrmpd:b39pkuk) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/5a5874d8714f46167f5d7cdd16f57135527b74cf/stwo_cairo_verifier/src/channel.cairo#L40)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Why so many unrelated changes in this PR?
</blockquote></details>

Because of changing Cairo version to 2.8.4. The new version had formatting upgrades.
Split these changes into seperate PR now: https://reviewable.io/reviews/starkware-libs/stwo-cairo/174

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 10 of 37 files at r1, 2 of 9 files at r3, 1 of 1 files at r4, 1 of 3 files at r5, 6 of 21 files at r6, 12 of 14 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/164)* status: 29 of 39 files reviewed, 3 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

___
*[`stwo_cairo_verifier/src/fields/qm31.cairo` line 161 at r7](https://reviewable.io/reviews/starkware-libs/stwo-cairo/164#-OC7BJy93V-yhtWN_RtT:-OC7BJy93V-yhtWN_RtU:b-v0x5j2) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/a05ee315691d2cd3eeded3aca71a4d0a7d1577ac/stwo_cairo_verifier/src/fields/qm31.cairo#L161)):*
> ```Cairo
> 
> pub impl QM31Mul of core::traits::Mul<QM31> {
>     #[inline(never)]
> ```

why make this change?



_Code quote:_
```Cairo
 #[inline(never)]
```

**Comment by ilyalesokhin-starkware** [comment]
why do you need to deserialize the proof?

**Review by andrewmilson — COMMENTED** [review]
Discussed offline. Added TODO

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/164#-:-OCAHmcmEjrcLoy7CZM_:bakndh1)* status: 29 of 39 files reviewed, all discussions resolved (waiting on @shaharsamocha7)

___
*[`stwo_cairo_verifier/src/fields/qm31.cairo` line 161 at r7](https://reviewable.io/reviews/starkware-libs/stwo-cairo/164#-OC7BJy93V-yhtWN_RtT:-OCBVOMs6JuQJ7pFdleH:b-43apu2) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/a05ee315691d2cd3eeded3aca71a4d0a7d1577ac/stwo_cairo_verifier/src/fields/qm31.cairo#L161)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why make this change?
</blockquote></details>

Removed. Thanks

**Review by ilyalesokhin-starkware — APPROVED** [review]
> Reviewed 8 of 21 files at r6, 2 of 14 files at r7, 1 of 2 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/164)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Pull request merged**
