### PR TITLE
batched logup in opcodes

### PR DESCRIPTION
**Pull request by ohad-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/266)

### CODE REVIEW

**Comment by ohad-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/266?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#266** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/266?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/266?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#265** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/265?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#264** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/264?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by shaharsamocha7 — COMMENTED** [review]
> Reviewed 25 of 50 files at r1, 24 of 25 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/266)* status: 49 of 50 files reviewed, all discussions resolved

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 9 of 24 files at r3, 3 of 28 files at r4, 25 of 25 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/266#-:-OErkFVFEpkdftpAqOnQ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/components/add_opcode_is_small_f_is_imm_f/prover.rs` line 141 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/266#-OErijc78yuLgexgs3lm:-OErijc78yuLgexgs3ln:b-yvepgh) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/652510c80cc74946e769b11276f1891221eef6a4/stwo_cairo_prover/crates/prover/src/components/add_opcode_is_small_f_is_imm_f/prover.rs#L141)):*
> ```XML
>     LookupData,
> ) {
>     const N_TRACE_COLUMNS: usize = 102;
> ```

Not for now, but why is it here? we have a definition in top of file



_Code quote:_
```XML
const N_TRACE_COLUMNS: usize = 102;
```

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/266)* status: all files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/components/add_opcode_is_small_f_is_imm_f/prover.rs` line 141 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/266#-OErijc78yuLgexgs3lm:-OErknUh5xrrBppfrHKr:byh07j1) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/652510c80cc74946e769b11276f1891221eef6a4/stwo_cairo_prover/crates/prover/src/components/add_opcode_is_small_f_is_imm_f/prover.rs#L141)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Not for now, but why is it here? we have a definition in top of file
</blockquote></details>

I hoped you wouldn't notice before I got to that
Will be fixed soon

**Pull request merged**
