### PR TITLE
vec generic

### PR DESCRIPTION
**Pull request by ohad-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/190)

### CODE REVIEW

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/190)* status: all files reviewed, 1 unresolved discussion (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/air.rs` line 438 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/190#-OCXQvm1BXtkBeFDG16W:-OCXQvm1BXtkBeFDG16X:b-nefaex) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e04a7f19732b8a14330ee57e34d8dfe20f899db8/stwo_cairo_prover/crates/prover/src/cairo_air/air.rs#L438)):*
> ```XML
>         };
>     }
>     sum += interaction_claim.ret[0].claimed_sum.unwrap().0;
> ```

Don't we need here the same logic as we have with the generic?



_Code quote:_
```XML
    sum += interaction_claim.ret[0].claimed_sum.unwrap().0;
```

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/190)* status: all files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/air.rs` line 438 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/190#-OCXQvm1BXtkBeFDG16W:-OCXZVBIC37uEnPXAPj9:buk9y26) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e04a7f19732b8a14330ee57e34d8dfe20f899db8/stwo_cairo_prover/crates/prover/src/cairo_air/air.rs#L438)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Don't we need here the same logic as we have with the generic?
</blockquote></details>

yes, in #194

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/190#-:-OCX_wdQ-IGRZHyQSIAK:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ohad-starkware)

**Comment by ohad-starkware** [comment]
### Merge activity

* **Nov 25, 4:54 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/190).

**Pull request merged**
