### PR TITLE
Optimize decommiting last FRI layer using univariate FFT

### PR DESCRIPTION
**Pull request by andrewmilson**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/133)

### CODE REVIEW

**Comment by andrewmilson** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/133?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#135** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/135?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#134** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/134?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#133** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/133?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#127** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/127?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#118** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/118?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/117?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#116** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/116?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#115** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/115?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#114** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/114?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#113** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/113?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#112** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/112?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @andrewmilson and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by ilyalesokhin-starkware** [comment]
*[`stwo_cairo_verifier/src/poly/utils.cairo` line 35 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/133#-OAHOxaWCw9GEnXY67ZY:-OAHOxaWCw9GEnXY67ZZ:b-6n7nk5) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/32cd8df6affbe57e994b199ed603325760444931/stwo_cairo_verifier/src/poly/utils.cairo#L35)):*
> ```Cairo
>     let lhs_val = fold(values, folding_factors, index, level + 1, n / 2);
>     let rhs_val = fold(values, folding_factors, index + n / 2, level + 1, n / 2);
>     return lhs_val + rhs_val.mul_m31(*folding_factors[level]);
> ```

This change is independent of the other changes, right?



_Code quote:_
```Cairo
 return lhs_val + rhs_val.mul_m31(*folding_factors[level]);
```

**Comment by ilyalesokhin-starkware** [comment]
*[`stwo_cairo_verifier/src/fri.cairo` line 550 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/133#-OAHPa_X8VSv2zeWWlX5:-OAHPa_X8VSv2zeWWlX6:b-sdeazg) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/32cd8df6affbe57e994b199ed603325760444931/stwo_cairo_verifier/src/fri.cairo#L550)):*
> ```Cairo
>     #[test]
>     fn test_fold_line_1() {
>         let domain = LineDomainImpl::new_unchecked(
> ```

Why not keep the `new` function and use it here?



_Code quote:_
```Cairo
  let domain = LineDomainImpl::new_unchecked(
```

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/133)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @Alon-Ti and @ilyalesokhin-starkware)

___
*[`stwo_cairo_verifier/src/fri.cairo` line 550 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/133#-OAHPa_X8VSv2zeWWlX5:-OAL4v545pjoJrVz6iYX:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/32cd8df6affbe57e994b199ed603325760444931/stwo_cairo_verifier/src/fri.cairo#L550)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Why not keep the `new` function and use it here?
</blockquote></details>

Done.
___
*[`stwo_cairo_verifier/src/poly/utils.cairo` line 35 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/133#-OAHOxaWCw9GEnXY67ZY:-OAIrQfV2y0tX5ywgd5N:b-ql99de) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/32cd8df6affbe57e994b199ed603325760444931/stwo_cairo_verifier/src/poly/utils.cairo#L35)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

This change is independent of the other changes, right?
</blockquote></details>

Yes my bad should have put in a seperate PR

**Comment by ilyalesokhin-starkware** [comment]
*[`stwo_cairo_verifier/src/poly/line.cairo` line 115 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/133#-OANRBxVBPQuUITJLQ03:-OANRBxVBPQuUITJLQ04:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/32cd8df6affbe57e994b199ed603325760444931/stwo_cairo_verifier/src/poly/line.cairo#L115)):*
> ```Cairo
>     while domain_i != 0 {
>         domain_i -= 1;
>         let domain = domains[domain_i];
> ```





_Suggestion:_
```Cairo
    let domains_span = domains.span()
    while Some(domain) = domains_span.pop_back() {
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/133)* status: 1 of 5 files reviewed, 3 unresolved discussions (waiting on @Alon-Ti, @andrewmilson, and @ilyalesokhin-starkware)

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/133)* status: 1 of 5 files reviewed, 3 unresolved discussions (waiting on @Alon-Ti and @ilyalesokhin-starkware)

___
*[`stwo_cairo_verifier/src/poly/line.cairo` line 115 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/133#-OANRBxVBPQuUITJLQ03:-OAtvKG3CxO3iuf-6Wci:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/32cd8df6affbe57e994b199ed603325760444931/stwo_cairo_verifier/src/poly/line.cairo#L115)):*
> ```Cairo
>     while domain_i != 0 {
>         domain_i -= 1;
>         let domain = domains[domain_i];
> ```

Done.

**Comment by ilyalesokhin-starkware** [comment]
*[`stwo_cairo_verifier/src/poly/line.cairo` line 128 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/133#-OBZy-EmAptW7mMt5lLo:-OBZy-EmAptW7mMt5lLp:b-qi3pwg) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c7df8ae1fffce979d5a110d5d4175b29ab70d8ff/stwo_cairo_verifier/src/poly/line.cairo#L128)):*
> ```Cairo
>                 let mut i1 = i0 + stride;
>                 for twiddle in twiddles {
>                     let (v0, v1) = butterfly(*values[i0], *values[i1], *twiddle);
> ```

pop_front is more efficient than random access.

Can you use spans here?



_Code quote:_
```Cairo
*values[i0]
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 1 of 3 files at r2, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/133)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @Alon-Ti, @andrewmilson, and @shaharsamocha7)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/133)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @Alon-Ti, @andrewmilson, and @shaharsamocha7)

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/133#-:-OBdKtWi23sxq2dZ6mfD:bnfp4nl)* status: 3 of 5 files reviewed, all discussions resolved (waiting on @Alon-Ti and @shaharsamocha7)

**Pull request merged**
