### PR TITLE
Add lookup step constraint.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/17)

### CODE REVIEW

**Comment by alonh5** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/17?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#17** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/17?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#16** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/16?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#13** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/13?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#12** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/12?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#11** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/11?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#14** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/14?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alonh5 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/17)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`stwo_cairo_prover/src/components/range_check_unit/component.rs` line 207 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/17#-O1lCXCkCbyoswDRdhDg:-O1lCXCkCbyoswDRdhDh:bs29p6i) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/7618445b97d3a687dab3fc4c9c6e8d6e0c84f9b6/stwo_cairo_prover/src/components/range_check_unit/component.rs#L207)):*
> ```XML
>             } else {
>                 (1 << (log_size - 1)) + ((1 << log_size) - 1 - i) / 2
>             };
> ```

Can we extract this to a function? Maybe in stwo?



_Code quote:_
```XML
            let index = if i & 1 == 0 {
                i / 2
            } else {
                (1 << (log_size - 1)) + ((1 << log_size) - 1 - i) / 2
            };
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/17)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`stwo_cairo_prover/src/components/range_check_unit/component.rs` line 207 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/17#-O1lCXCkCbyoswDRdhDg:-O1pOZDM0TsAUXh42Mug:bi0snu0) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/7618445b97d3a687dab3fc4c9c6e8d6e0c84f9b6/stwo_cairo_prover/src/components/range_check_unit/component.rs#L207)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Can we extract this to a function? Maybe in stwo?
</blockquote></details>

Yes, done in PR 728 in stwo. ptal :)

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/17)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`stwo_cairo_prover/src/components/range_check_unit/component.rs` line 207 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/17#-O1lCXCkCbyoswDRdhDg:-O1poMKN8BqefJOd1h1p:b9nykiw) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/7618445b97d3a687dab3fc4c9c6e8d6e0c84f9b6/stwo_cairo_prover/src/components/range_check_unit/component.rs#L207)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Yes, done in PR 728 in stwo. ptal :)
</blockquote></details>

Great. lgtmed. Now, let's use it here

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/17)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`stwo_cairo_prover/src/components/range_check_unit/component.rs` line 207 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/17#-O1lCXCkCbyoswDRdhDg:-O1prSyq25UwTmRZUuwQ:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/7618445b97d3a687dab3fc4c9c6e8d6e0c84f9b6/stwo_cairo_prover/src/components/range_check_unit/component.rs#L207)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Great. lgtmed. Now, let's use it here
</blockquote></details>

Done.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/17#-:-O1pyD4-8lfSEUQ6lB9z:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Pull request merged**
