### PR TITLE
Add README for cairo verifier

### PR DESCRIPTION
**Pull request by andrewmilson**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/153)

### CODE REVIEW

**Comment by andrewmilson** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/153?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#153** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/153?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#133** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/133?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 2 other dependent PRs ([#134](https://github.com/starkware-libs/stwo-cairo/pull/134) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/134?utm_source=stack-comment-icon" target="_blank">Graphite</a>, [#152](https://github.com/starkware-libs/stwo-cairo/pull/152) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/152?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#127** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/127?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#118** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/118?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/117?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#116** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/116?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#115** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/115?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#114** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/114?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#113** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/113?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#112** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/112?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @andrewmilson and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by ilyalesokhin-starkware** [comment]
*[`stwo_cairo_verifier/README.md` line 7 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/153#-OBtywpy6FcL8LYvwDN0:-OBtywpy6FcL8LYvwDN1:ba000y0) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/a9ad4a64c5467719abd393ea2b4a8ad00bb0269e/stwo_cairo_verifier/README.md#L7)):*
> ```Markdown
> ## Running tests
> 
> [Install asdf](https://asdf-vm.com/guide/getting-started.html#_3-install-asdf).
> ```

install scarb?

**Comment by ilyalesokhin-starkware** [comment]
*[`stwo_cairo_verifier/README.md` line 15 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/153#-OBuK8Ij7JNH-mMBteBs:-OBuK8Ik0obCr8o8qJw-:b-pnnh87) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/a9ad4a64c5467719abd393ea2b4a8ad00bb0269e/stwo_cairo_verifier/README.md#L15)):*
> ```Markdown
> ## Visualising test step counts.
> 
> Modify [`Scarb.toml`](./Scarb.toml) to use [Starknet Foundary](https://github.com/foundry-rs/starknet-foundry).
> ```

install?



_Code quote:_
```Markdown
Modify [`Scarb.toml`](./Scarb.toml) to use [Starknet Foundary](https://github.com/foundry-rs/starknet-foundry).
```

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/153)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @shaharsamocha7)

___
*[`stwo_cairo_verifier/README.md` line 7 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/153#-OBtywpy6FcL8LYvwDN0:-OBvIF4XED6FvfIUQC_I:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/44ffaa704c8ac7886303c785a3458ef2e5b5a91b/stwo_cairo_verifier/README.md#L7)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

install scarb?
</blockquote></details>

Done.
___
*[`stwo_cairo_verifier/README.md` line 15 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/153#-OBuK8Ij7JNH-mMBteBs:-OBvIHS43TmUlyd_JaKB:b1i1w0s) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/44ffaa704c8ac7886303c785a3458ef2e5b5a91b/stwo_cairo_verifier/README.md#L15)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

install?
</blockquote></details>

Should be handled by the `asdf install` command. 
It installs everything in `.tool-versions`

**Comment by ilyalesokhin-starkware** [comment]
*[`stwo_cairo_verifier/README.md` line 15 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/153#-OBuK8Ij7JNH-mMBteBs:-OC262POD1_CAx1iUfMB:bq3m0ec) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/44ffaa704c8ac7886303c785a3458ef2e5b5a91b/stwo_cairo_verifier/README.md#L15)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Should be handled by the `asdf install` command. 
It installs everything in `.tool-versions`
</blockquote></details>

You need to do it from the stwo_cairo_verifier folder right?

**Comment by ilyalesokhin-starkware** [comment]
*[`stwo_cairo_verifier/README.md` line 15 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/153#-OBuK8Ij7JNH-mMBteBs:-OC28n9Y4i7bSRjzrZef:b-gbqd9w) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/44ffaa704c8ac7886303c785a3458ef2e5b5a91b/stwo_cairo_verifier/README.md#L15)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I get:
ilya@ilya-ThinkPad-T14-Gen-2i:~/workspaces/stwo-cairo/stwo_cairo_verifier$ asdf install
scarb plugin is not installed
starknet-foundry plugin is not installed
</blockquote></details>

I seems that I need to do:
asdf plugin add scarb
asdf plugin add starknet-foundry

**Comment by ilyalesokhin-starkware** [comment]
*[`stwo_cairo_verifier/README.md` line 33 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/153#-OC3EykZ7Xz-yJzbe1kQ:-OC3EykZ7Xz-yJzbe1kR:brkfrw6) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c6144cb0d9208381d46198861d5070458d7623eb/stwo_cairo_verifier/README.md#L33)):*
> ```Markdown
> 
> ```bash
> scarb test -- --save-trace-data
> ```

ilya@ilya-ThinkPad-T14-Gen-2i:~/workspaces/stwo-cairo/stwo_cairo_verifier$ scarb test -- --save-trace-data
     Running test stwo_cairo_verifier (snforge test --max-n-steps 100000000)
   Compiling snforge_scarb_plugin v0.32.0 (git+https://github.com/foundry-rs/starknet-foundry?tag=v0.32.0#3817c903b640201c72e743b9bbe70a97149828a2)
error: package `lalrpop-util v0.20.2` cannot be built because it requires rustc 1.70 or newer, while the currently active rustc version is 1.67.0
Either upgrade to rustc 1.70 or newer, or use
cargo update -p lalrpop-util@0.20.2 --precise ver
where `ver` is the latest version of `lalrpop-util` supporting rustc 1.67.0



_Code quote:_
```Markdown
scarb test -- --save-trace-data
```

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/153)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @shaharsamocha7)

___
*[`stwo_cairo_verifier/README.md` line 15 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/153#-OBuK8Ij7JNH-mMBteBs:-OC3o1Fs8_0trhTwrX3j:boyexbg) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/44ffaa704c8ac7886303c785a3458ef2e5b5a91b/stwo_cairo_verifier/README.md#L15)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I seems that I need to do:
asdf plugin add scarb
asdf plugin add starknet-foundry
</blockquote></details>

Done. Thanks.
___
*[`stwo_cairo_verifier/README.md` line 33 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/153#-OC3EykZ7Xz-yJzbe1kQ:-OC3o6GrBJOn6s3Alg7f:b-3nw7nt) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c6144cb0d9208381d46198861d5070458d7623eb/stwo_cairo_verifier/README.md#L33)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

ilya@ilya-ThinkPad-T14-Gen-2i:~/workspaces/stwo-cairo/stwo_cairo_verifier$ scarb test -- --save-trace-data
     Running test stwo_cairo_verifier (snforge test --max-n-steps 100000000)
   Compiling snforge_scarb_plugin v0.32.0 (git+https://github.com/foundry-rs/starknet-foundry?tag=v0.32.0#3817c903b640201c72e743b9bbe70a97149828a2)
error: package `lalrpop-util v0.20.2` cannot be built because it requires rustc 1.70 or newer, while the currently active rustc version is 1.67.0
Either upgrade to rustc 1.70 or newer, or use
cargo update -p lalrpop-util@0.20.2 --precise ver
where `ver` is the latest version of `lalrpop-util` supporting rustc 1.67.0
</blockquote></details>

Added TODO to investigate error.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/153#-:-OC3pUjM43hrjiHR8u7t:bnfp4nl)* status: 1 of 6 files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Pull request merged**
