### PR TITLE
range check 128 builtin framework component

### PR DESCRIPTION
**Pull request by shaharsamocha7**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/36)

### CODE REVIEW

**Comment by shaharsamocha7** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/36?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#36** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/36?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#35** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/35?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @shaharsamocha7 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/36#-:-O3RAWzcBq8iKuFuiT9A:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @alonh5 and @shaharsamocha7)

___
*[`stwo_cairo_prover/src/components/range_check_builtin/component.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/36#-O3R9VMH773KKHsYXPut:-O3R9VMH773KKHsYXPuu:be2qtlk) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ea921564709a841f0a79389e10e709c86bc19345/stwo_cairo_prover/src/components/range_check_builtin/component.rs#L17)):*
> ```XML
>     pub initial_memory_address: E::F,
>     pub memory_lookup_elements: &'a LookupElements,
>     pub rcunit2_lookup_elements: &'a LookupElements,
> ```

Add a static assert that the remainder 128%9==2.
```
const _: () = assert!(FOO == BAR, "bla");
````
___
*[`stwo_cairo_prover/src/components/range_check_builtin/component.rs` line 25 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/36#-O3R8YBM2bpNPf0DPRjb:-O3R8YBM2bpNPf0DPRjc:bd3wlu5) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ea921564709a841f0a79389e10e709c86bc19345/stwo_cairo_prover/src/components/range_check_builtin/component.rs#L25)):*
> ```XML
> 
>         // Memory address.
>         // TODO: Use a constant column instead of taking the next_trace_mask().
> ```

TODO on who?
___
*[`stwo_cairo_prover/src/components/range_check_builtin/component.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/36#-O3RAMyd3-B-KILzlth7:-O3RAMyd3-B-KILzlth8:brv6pjy) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ea921564709a841f0a79389e10e709c86bc19345/stwo_cairo_prover/src/components/range_check_builtin/component.rs#L59)):*
> ```XML
>     pub initial_memory_address: M31,
>     pub memory_lookup_elements: LookupElements,
>     pub rcunit2_lookup_elements: LookupElements,
> ```

Consider



_Suggestion:_
```XML
range2_lookup_elements
```
___
*[`stwo_cairo_prover/src/components/range_check_builtin/component.rs` line 77 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/36#-O3RA1f3Cz8aTtVwtbQn:-O3RA1f3Cz8aTtVwtbQo:b-ya2b09) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ea921564709a841f0a79389e10e709c86bc19345/stwo_cairo_prover/src/components/range_check_builtin/component.rs#L77)):*
> ```XML
>             memory_lookup_elements: &self.memory_lookup_elements,
>             rcunit2_lookup_elements: &self.rcunit2_lookup_elements,
>             logup: LogupAtRow::new(1, self.claimed_sum, is_first),
> ```

We should probaly add a constant in the cpu air main module for this interaction phase.
Note that if later we need any component in different interactions, we could pass `interaction` in the struct.



_Code quote:_
```XML
1
```

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/36)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @spapinistarkware)

___
*[`stwo_cairo_prover/src/components/range_check_builtin/component.rs` line 25 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/36#-O3R8YBM2bpNPf0DPRjb:-O3RWl_D1Af9EUwwOdt9:bn4rhr2) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ea921564709a841f0a79389e10e709c86bc19345/stwo_cairo_prover/src/components/range_check_builtin/component.rs#L25)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

TODO on who?
</blockquote></details>

I put it on myself but we should do it once we understand how to pass the constant columns.
___
*[`stwo_cairo_prover/src/components/range_check_builtin/component.rs` line 77 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/36#-O3RA1f3Cz8aTtVwtbQn:-O3RXRWeCxLTwmBRJtyC:b-e9ws62) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ea921564709a841f0a79389e10e709c86bc19345/stwo_cairo_prover/src/components/range_check_builtin/component.rs#L77)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

We should probaly add a constant in the cpu air main module for this interaction phase.
Note that if later we need any component in different interactions, we could pass `interaction` in the struct.
</blockquote></details>

but components are defined independently from cpu air.
Maybe here we can only have an internal interaction offset?

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/36)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @shaharsamocha7)

___
*[`stwo_cairo_prover/src/components/range_check_builtin/component.rs` line 77 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/36#-O3RA1f3Cz8aTtVwtbQn:-O3RpbKq1mce6zbXkcwy:b-kvqunm) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ea921564709a841f0a79389e10e709c86bc19345/stwo_cairo_prover/src/components/range_check_builtin/component.rs#L77)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

but components are defined independently from cpu air.
Maybe here we can only have an internal interaction offset?
</blockquote></details>

Those are the 2 options, yes.
I feel a constant is ok for now, and when we need to generalize it, we'll pass an internal offset in the struct.

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/36)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @spapinistarkware)

___
*[`stwo_cairo_prover/src/components/range_check_builtin/component.rs` line 77 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/36#-O3RA1f3Cz8aTtVwtbQn:-O3RsQ_wAo2T-Q7RQq8J:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ea921564709a841f0a79389e10e709c86bc19345/stwo_cairo_prover/src/components/range_check_builtin/component.rs#L77)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Those are the 2 options, yes.
I feel a constant is ok for now, and when we need to generalize it, we'll pass an internal offset in the struct.
</blockquote></details>

Done.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/36#-:-O3Rz5fI0pK0VWnvXZKf:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Pull request merged**
