### PR TITLE
Compute FRI quotients

### PR DESCRIPTION
**Pull request by andrewmilson**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/118)

### CODE REVIEW

**Comment by andrewmilson** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/118?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#118** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/118?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#117** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/117?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#116** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/116?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#115** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/115?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#114** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/114?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#113** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/113?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#112** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/112?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @andrewmilson and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Alon-Ti — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/118)* status: all files reviewed, 4 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

___
*[`stwo_cairo_verifier/src/pcs/quotients.cairo` line 196 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/118#-O9El71QEuLOPfytXOO7:-O9El71QEuLOPfytXOO8:b9fmu9c) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/d95c68e3a90b4068472602b54f0f46b8dc7ff069/stwo_cairo_verifier/src/pcs/quotients.cairo#L196)):*
> ```Cairo
>     let mut queried_values_per_column_iter = queried_values_per_column.span().into_iter();
> 
>     loop {
> ```

Can't this work as an iteration on `queried_values_per_column`?
___
*[`stwo_cairo_verifier/src/pcs/quotients.cairo` line 213 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/118#-O9ElJYLA2DUM57uY1ML:-O9ElJYLA2DUM57uY1MM:byp18fd) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/d95c68e3a90b4068472602b54f0f46b8dc7ff069/stwo_cairo_verifier/src/pcs/quotients.cairo#L213)):*
> ```Cairo
>     let mut column_eval_offset = 0;
> 
>     // return Result::Err(VerificationError::InvalidStructure('queried vals'));
> ```

Remove
___
*[`stwo_cairo_verifier/src/pcs/quotients.cairo` line 329 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/118#-O9EDnX877kWJqmUTzdk:-O9EDnX877kWJqmUTzdl:bfg5x7o) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/d95c68e3a90b4068472602b54f0f46b8dc7ff069/stwo_cairo_verifier/src/pcs/quotients.cairo#L329)):*
> ```Cairo
>         for sample_batch in sample_batches
>             .span() {
>                 // TODO(AlonH): This assertion will fail at a probability of 1 to 2^62.
> ```

Reassign TODO (I think Shahar wanted to add salt for this)
___
*[`stwo_cairo_verifier/src/pcs/quotients.cairo` line 474 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/118#-O9EurKhBKPDyTa2KXbF:-O9EurKhBKPDyTa2KXbG:b3kre) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/d95c68e3a90b4068472602b54f0f46b8dc7ff069/stwo_cairo_verifier/src/pcs/quotients.cairo#L474)):*
> ```Cairo
>         sample_point: @CirclePoint<QM31>, sample_value: QM31, alpha: QM31
>     ) -> ComplexConjugateLineCoeffs {
>         // 12321564
> ```

?

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/118)* status: all files reviewed, 4 unresolved discussions (waiting on @Alon-Ti and @shaharsamocha7)

___
*[`stwo_cairo_verifier/src/pcs/quotients.cairo` line 196 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/118#-O9El71QEuLOPfytXOO7:-O9GVrnQ6YB-hHWqohX0:bbsui1) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/d95c68e3a90b4068472602b54f0f46b8dc7ff069/stwo_cairo_verifier/src/pcs/quotients.cairo#L196)):*
<details><summary><i>Previously, Alon-Ti wrote…</i></summary><blockquote>

Can't this work as an iteration on `queried_values_per_column`?
</blockquote></details>

For and while loops don't allow breaking with a value
___
*[`stwo_cairo_verifier/src/pcs/quotients.cairo` line 213 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/118#-O9ElJYLA2DUM57uY1ML:-O9GWqvf84fWGM902rE7:b-p7hop8) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/d95c68e3a90b4068472602b54f0f46b8dc7ff069/stwo_cairo_verifier/src/pcs/quotients.cairo#L213)):*
<details><summary><i>Previously, Alon-Ti wrote…</i></summary><blockquote>

Remove
</blockquote></details>

Whoops. Thanks
___
*[`stwo_cairo_verifier/src/pcs/quotients.cairo` line 329 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/118#-O9EDnX877kWJqmUTzdk:-O9cJDS8BlSElj-_LiV-:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/d95c68e3a90b4068472602b54f0f46b8dc7ff069/stwo_cairo_verifier/src/pcs/quotients.cairo#L329)):*
<details><summary><i>Previously, Alon-Ti wrote…</i></summary><blockquote>

Reassign TODO (I think Shahar wanted to add salt for this)
</blockquote></details>

Done.
___
*[`stwo_cairo_verifier/src/pcs/quotients.cairo` line 474 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/118#-O9EurKhBKPDyTa2KXbF:-O9GX-Us0gVncF_EXx4F:b32unsi) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/d95c68e3a90b4068472602b54f0f46b8dc7ff069/stwo_cairo_verifier/src/pcs/quotients.cairo#L474)):*
<details><summary><i>Previously, Alon-Ti wrote…</i></summary><blockquote>

?
</blockquote></details>

Removed. Ty

**Review by Alon-Ti — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/118#-:-O9eaIAK2A8IbmtCIrzO:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Pull request merged**
