### PR TITLE
Update stwo and fix changes.

### PR DESCRIPTION
**Pull request by alonh5**
`

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/11)

### CODE REVIEW

**Comment by alonh5** [comment]
* **#11** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/11?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alonh5 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/11)* status: all files reviewed, 3 unresolved discussions (waiting on @alonh5)

___
*[`stwo_cairo_prover/src/components/range_check_unit.rs` line 124 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/11#-O1QQ1Dx-fgF02OH0mOj:-O1QQ1Dx-fgF02OH0mOk:b-mf6krt) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/21185a0ce8da2233d161f9f22c789c79afaf6558/stwo_cairo_prover/src/components/range_check_unit.rs#L124)):*
> ```XML
> 
>         let mut last = SecureField::zero();
>         let interaction_values = zip_eq(&trace[0].values, &trace[1].values).fold(
> ```

Does it sum it in the bit_reverse order?

Also consider to rename



_Suggestion:_
```XML
let logup_values = zip_eq(&trace[0].values, &trace[1].values).fold(
```
___
*[`stwo_cairo_prover/src/components/range_check_unit.rs` line 126 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/11#-O1QQPLj4feoSG-e42Rm:-O1QQPLj4feoSG-e42Rn:byp1ktf) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/21185a0ce8da2233d161f9f22c789c79afaf6558/stwo_cairo_prover/src/components/range_check_unit.rs#L126)):*
> ```XML
>         let interaction_values = zip_eq(&trace[0].values, &trace[1].values).fold(
>             Vec::new(),
>             |mut acc, (trace_value, multiplicity)| {
> ```

Rename



_Suggestion:_
```XML
|mut acc, (interaction_input, multiplicity)| {
```
___
*[`stwo_cairo_prover/src/components/range_check_unit.rs` line 127 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/11#-O1QPwcb48RzP2-RHIxk:-O1QPwcc4Y7EIY7eYDKO:bvjgg3n) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/21185a0ce8da2233d161f9f22c789c79afaf6558/stwo_cairo_prover/src/components/range_check_unit.rs#L127)):*
> ```XML
>             Vec::new(),
>             |mut acc, (trace_value, multiplicity)| {
>                 let interaction_value = last + ((z - *trace_value).inverse() * *multiplicity);
> ```

Add a TODO to optimize this inverse



_Code quote:_
```XML
let interaction_value = last + ((z - *trace_value).inverse() * *multiplicity);
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/11)* status: all files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7)

___
*[`stwo_cairo_prover/src/components/range_check_unit.rs` line 126 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/11#-O1QQPLj4feoSG-e42Rm:-O1Qs1GNA1_UNd0T0rgC:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/21185a0ce8da2233d161f9f22c789c79afaf6558/stwo_cairo_prover/src/components/range_check_unit.rs#L126)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Rename
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/src/components/range_check_unit.rs` line 127 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/11#-O1QPwcb48RzP2-RHIxk:-O1R4sKf19ao9KSvCfqJ:bkd8217) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/21185a0ce8da2233d161f9f22c789c79afaf6558/stwo_cairo_prover/src/components/range_check_unit.rs#L127)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Add a TODO to optimize this inverse
</blockquote></details>

It's simple I did it here.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/11#-:-O1RNG7d8OzFw1P-l-z-:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Comment by alonh5** [comment]
### Merge activity

* **Jul 11, 3:20 AM EDT**: @alonh5 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/11).

**Pull request merged**
