### PR TITLE
Add verifier

### PR DESCRIPTION
**Pull request by andrewmilson**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/127)

### CODE REVIEW

**Comment by andrewmilson** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/127?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#127** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/127?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#118** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/118?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/117?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#116** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/116?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#115** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/115?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#114** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/114?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#113** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/113?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#112** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/112?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @andrewmilson and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 13 of 31 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/127)* status: 13 of 31 files reviewed, 6 unresolved discussions (waiting on @Alon-Ti and @andrewmilson)

___
*[`.gitignore` line 1 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/127#-OB_my9h3ZeAiw_8FVwn:-OB_my9h3ZeAiw_8FVwo:b-sg1ijm) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/637377f809f6d5b8a82b6698c136c4e3beb0f159/.gitignore#L1)):*
> ```ignore
> /target
> ```

is it on purpose?
___
*[`stwo_cairo_verifier/src/fri.cairo` line 318 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/127#-OBa-Ipl94rbDLu_Jrc0:-OBa-Ipl94rbDLu_Jrc1:b-3l9h3k) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f24730b0b5061096889b6c88cf046aa075082903/stwo_cairo_verifier/src/fri.cairo#L318)):*
> ```Cairo
>         self: @FriVerifier, queries: @Queries, decommitted_values: Array<SparseCircleEvaluation>
>     ) -> Result<(), FriVerificationError> {
>         assert!(queries.log_domain_size == self.expected_query_log_domain_size);
> ```

why did you change this?



_Code quote:_
```Cairo
assert!(queries.log_domain_size == self.expected_query_log_domain_size);
```
___
*[`stwo_cairo_verifier/.gitattributes` line 2 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/127#-OB_n2a12AwgO25HvZEO:-OB_n2a12AwgO25HvZEP:bb7od0r) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f24730b0b5061096889b6c88cf046aa075082903/stwo_cairo_verifier/.gitattributes#L2)):*
> ```gitattributes
> # Excluded proof files from GitHub stats and hide in diffs.
> tests/proofs/* linguist-generated
> ```

same
___
*[`stwo_cairo_verifier/Scarb.toml` line 22 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/127#-OB_xfG_BqcDi2YDENKQ:-OB_xfG_BqcDi2YDENKR:b-l6mwxj) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f24730b0b5061096889b6c88cf046aa075082903/stwo_cairo_verifier/Scarb.toml#L22)):*
> ```TOML
> 
> # [scripts]
> # test = "snforge test --max-n-steps 100000000"
> ```

remove



_Code quote:_
```TOML
# snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.32.0" }
# # TODO(andrew): Remove once get scarb >=2.8.3 working.
# assert_macros = "2.8.0"


# [scripts]
# test = "snforge test --max-n-steps 100000000"
```
___
*[`stwo_cairo_verifier/.cairofmtignore` line 1 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/127#-OB_n1U3-NWmrAutmGNM:-OB_n1U3-NWmrAutmGNN:b-hvbrl4) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f24730b0b5061096889b6c88cf046aa075082903/stwo_cairo_verifier/.cairofmtignore#L1)):*
> ```
> tests/proofs
> ```

add new line



_Code quote:_
```
tests/proofs
```
___
*[`stwo_cairo_verifier/src/utils.cairo` line 218 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/127#-OBa0Gsp3016PXAd45-4:-OBa0Gsp3016PXAd45-5:bpkkqvv) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f24730b0b5061096889b6c88cf046aa075082903/stwo_cairo_verifier/src/utils.cairo#L218)):*
> ```Cairo
>         };
>         n_trailing_zeros
>     }
> ```

is this just for proof of work?



_Code quote:_
```Cairo
    fn trailing_zeros(mut self: u128) -> u32 {
        let mut n_trailing_zeros = 0;
        loop {
            let (quotient, remainder) = DivRem::div_rem(self, 2);
            if remainder != 0 {
                break;
            }
            self = quotient;
            n_trailing_zeros += 1;
        };
        n_trailing_zeros
    }
```

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 31 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/127)* status: 17 of 31 files reviewed, 7 unresolved discussions (waiting on @Alon-Ti and @andrewmilson)

___
*[`stwo_cairo_verifier/src/poly/circle.cairo` line 104 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/127#-OBaF_V8AlitS1ePoPq5:-OBaF_V8AlitS1ePoPq6:bjsks14) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f24730b0b5061096889b6c88cf046aa075082903/stwo_cairo_verifier/src/poly/circle.cairo#L104)):*
> ```Cairo
>     /// Evaluates the coset's vanishing polynomial at point `p`.
>     fn eval_vanishing(self: @CanonicCoset, p: CirclePoint<QM31>) -> QM31 {
>         let mut x = p.x;
> ```

don't you need to shift p.x by the coset initial?



_Code quote:_
```Cairo
        let mut x = p.x;
```

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/127)* status: 13 of 31 files reviewed, 7 unresolved discussions (waiting on @Alon-Ti and @shaharsamocha7)

___
*[`.gitignore` line 1 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/127#-OB_my9h3ZeAiw_8FVwn:-OBf-8Eo5YyIwz0htKuP:b-7k4itg) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/637377f809f6d5b8a82b6698c136c4e3beb0f159/.gitignore#L1)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

is it on purpose?
</blockquote></details>

Yeah since prover and verifier already had a .gitignore with target in it this one was redundant.
___
*[`stwo_cairo_verifier/.cairofmtignore` line 1 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/127#-OB_n1U3-NWmrAutmGNM:-OBf-dcQE2K81cnGNxlY:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f24730b0b5061096889b6c88cf046aa075082903/stwo_cairo_verifier/.cairofmtignore#L1)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

add new line
</blockquote></details>

Done.
___
*[`stwo_cairo_verifier/.gitattributes` line 2 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/127#-OB_n2a12AwgO25HvZEO:-OBf-dN87dmT2rgB77UM:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f24730b0b5061096889b6c88cf046aa075082903/stwo_cairo_verifier/.gitattributes#L2)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[`stwo_cairo_verifier/src/fri.cairo` line 318 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/127#-OBa-Ipl94rbDLu_Jrc0:-OBf-tLH8_ctTI3boXSw:brcw3d3) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f24730b0b5061096889b6c88cf046aa075082903/stwo_cairo_verifier/src/fri.cairo#L318)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

why did you change this?
</blockquote></details>

Starknet foundry doesn't allow assert_eq macros unless it's a test.
___
*[`stwo_cairo_verifier/src/utils.cairo` line 218 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/127#-OBa0Gsp3016PXAd45-4:-OBf01KTBEAxLji4RWsD:b2nhswy) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f24730b0b5061096889b6c88cf046aa075082903/stwo_cairo_verifier/src/utils.cairo#L218)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

is this just for proof of work?
</blockquote></details>

Yes
___
*[`stwo_cairo_verifier/src/poly/circle.cairo` line 104 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/127#-OBaF_V8AlitS1ePoPq5:-OBell0O-3Ci34GYXsIh:b-8bj80w) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f24730b0b5061096889b6c88cf046aa075082903/stwo_cairo_verifier/src/poly/circle.cairo#L104)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

don't you need to shift p.x by the coset initial?
</blockquote></details>

Not for canonic coset. In the Rust the shift is "initial - half step" which is the identity for canonic cosets

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/127)* status: 16 of 31 files reviewed, 3 unresolved discussions (waiting on @Alon-Ti and @andrewmilson)

___
*[`stwo_cairo_verifier/src/utils.cairo` line 218 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/127#-OBa0Gsp3016PXAd45-4:-OBf2oEU9qbSwmutdrXZ:blcn9d4) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f24730b0b5061096889b6c88cf046aa075082903/stwo_cairo_verifier/src/utils.cairo#L218)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Yes
</blockquote></details>

Then I don't think we need this code.
To check if a code has at least x trailing bits you only need one AND op

TODO maybe?
___
*[`stwo_cairo_verifier/src/poly/circle.cairo` line 104 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/127#-OBaF_V8AlitS1ePoPq5:-OBf3I5B2tB7Ta4srMrV:b-5e88me) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f24730b0b5061096889b6c88cf046aa075082903/stwo_cairo_verifier/src/poly/circle.cairo#L104)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Not for canonic coset. In the Rust the shift is "initial - half step" which is the identity for canonic cosets
</blockquote></details>

cool, should we document that?

**Review by shaharsamocha7 — COMMENTED** [review]
> Reviewed 12 of 31 files at r1, 1 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/127)* status: 29 of 31 files reviewed, 3 unresolved discussions (waiting on @Alon-Ti and @andrewmilson)

___
*[`stwo_cairo_verifier/tests/verifier.cairo` line 24 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/127#-OBf8_yK5_0Eb3BPxprO:-OBf8_yK5_0Eb3BPxprP:bqcm75k) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/931481a444299e17795139e0ac39dc56a25cb820/stwo_cairo_verifier/tests/verifier.cairo#L24)):*
> ```Cairo
> //             log_last_layer_degree_bound: 5, log_blowup_factor: 4, n_queries: 64
> //         }
> //     };
> ```

what's that?
We have a last layer bound?



_Code quote:_
```Cairo
// TODO(andrew): Report bug. Data is invalid i.e. for some reason when using
// this type it thinks `log_last_layer_degree_bound` is 4.
//
// const PCS_CONFIG: PcsConfig =
//     PcsConfig {
//         pow_bits: 10,
//         fri_config: FriConfig {
//             log_last_layer_degree_bound: 5, log_blowup_factor: 4, n_queries: 64
//         }
//     };
```

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/127)* status: 29 of 31 files reviewed, 1 unresolved discussion (waiting on @Alon-Ti and @andrewmilson)

___
*[`stwo_cairo_verifier/src/poly/circle.cairo` line 104 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/127#-OBaF_V8AlitS1ePoPq5:-OBfGP-24Px4lnEfVqzX:b-g1y7tq) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f24730b0b5061096889b6c88cf046aa075082903/stwo_cairo_verifier/src/poly/circle.cairo#L104)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

In the Rust code? As in make it clear the shift is to shift the coset to a canonic coset?
</blockquote></details>

I thought we should document here that for canonic cosets the shift is identity

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 31 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/127)* status: 30 of 31 files reviewed, 2 unresolved discussions (waiting on @Alon-Ti and @andrewmilson)

___
*[`stwo_cairo_verifier/src/verifier.cairo` line 32 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/127#-OBfHJTnCxxtSFS9Qwjw:-OBfHJTnCxxtSFS9Qwjx:bmpj0o) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/931481a444299e17795139e0ac39dc56a25cb820/stwo_cairo_verifier/src/verifier.cairo#L32)):*
> ```Cairo
> ) -> Result<(), VerificationError> {
>     let random_coeff = channel.draw_felt();
> ```

Please add a TODO to deal with preprocessed columns

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/127)* status: 30 of 31 files reviewed, 4 unresolved discussions (waiting on @Alon-Ti and @andrewmilson)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo-cairo/127#-OBfPHW9BJKtUrMeaALn:-OBfPHW9BJKtUrMeaALo:byieqfy) (no related file):*
We should split this pr
___
*[`stwo_cairo_verifier/src/pcs/verifier.cairo` line 183 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/127#-OBfP9UICjka24p491m2:-OBfP9UICjka24p491m3:b9hdv7z) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/931481a444299e17795139e0ac39dc56a25cb820/stwo_cairo_verifier/src/pcs/verifier.cairo#L183)):*
> ```Cairo
> /// Returns all column log bounds deduped and sorted in ascending order.
> #[inline]
> fn get_column_log_bounds(
> ```

can this be replaced with a dict



_Code quote:_
```Cairo
fn get_column_log_bounds(
```

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/127)* status: 24 of 31 files reviewed, 3 unresolved discussions (waiting on @Alon-Ti and @shaharsamocha7)

___
*[`stwo_cairo_verifier/src/pcs/verifier.cairo` line 183 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/127#-OBfP9UICjka24p491m2:-OBflJwgBeSnGLmWdKPt:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/931481a444299e17795139e0ac39dc56a25cb820/stwo_cairo_verifier/src/pcs/verifier.cairo#L183)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

can this be replaced with a dict
</blockquote></details>

Done.
___
*[`stwo_cairo_verifier/src/poly/circle.cairo` line 104 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/127#-OBaF_V8AlitS1ePoPq5:-OBfklXvDX_5irD2WRbk:b-qa4alu) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f24730b0b5061096889b6c88cf046aa075082903/stwo_cairo_verifier/src/poly/circle.cairo#L104)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I thought we should document here that for canonic cosets the shift is identity
</blockquote></details>

Resolved offline.
___
*[`stwo_cairo_verifier/Scarb.toml` line 22 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/127#-OB_xfG_BqcDi2YDENKQ:-OBflLd88Of5iID5GzkN:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f24730b0b5061096889b6c88cf046aa075082903/stwo_cairo_verifier/Scarb.toml#L22)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/127#-:-OBtVuDt1CcZ3EhU_Xfq:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Alon-Ti)

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/127)* status: 24 of 31 files reviewed, all discussions resolved (waiting on @Alon-Ti and @shaharsamocha7)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo-cairo/127#-OBfPHW9BJKtUrMeaALn:-OBxTZc87cmKZH_Mli-f:b-mnezz1) (no related file):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

We should split this pr
</blockquote></details>

Done.
-   [https://reviewable.io/reviews/starkware-libs/stwo-cairo/173](https://reviewable.io/reviews/starkware-libs/stwo-cairo/173)
-   [https://reviewable.io/reviews/starkware-libs/stwo-cairo/172](https://reviewable.io/reviews/starkware-libs/stwo-cairo/172)

**Review by shaharsamocha7 — APPROVED** [review]
> Reviewed 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/127)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Alon-Ti)

**Pull request merged**
