### PR TITLE
migrated opcodes air out of cairo air

### PR DESCRIPTION
**Pull request by ohad-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/216)

### CODE REVIEW

**Comment by ohad-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/216?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#216** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/216?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/216?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#215** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/215?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#214** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/214?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#209** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/209?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#208** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/208?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#207** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/207?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#206** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/206?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/216#-:-OD6VbolCGMyEOz3W32m:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 51 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/216#-OD6V_0S3R_s3dRLSi0g:-OD6V_0S3R_s3dRLSi0h:bcwjn3e) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/4936aeb08c3f17c33e040246ca7fb0f6d56afed8/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L51)):*
> ```XML
>     let mut mem_file = std::io::BufReader::new(std::fs::File::open(mem_path)?);
>     let mut mem = MemoryBuilder::from_iter(mem_config, MemEntryIter(&mut mem_file));
>     let state_transitions = StateTransitions::from_iter(TraceIter(&mut trace_file), &mut mem, true);
> ```

how did it work if it was set to false?



_Code quote:_
```XML
, true
```

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/216)* status: all files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 51 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/216#-OD6V_0S3R_s3dRLSi0g:-ODBFh2z8zZ7RezHmnbk:b-e47q48) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/4936aeb08c3f17c33e040246ca7fb0f6d56afed8/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L51)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

how did it work if it was set to false?
</blockquote></details>

the test that takes casm doesnt pass here
and the other tests are ignored

**Comment by ohad-starkware** [comment]
### Merge activity

* **Dec 3, 6:55 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/216).

**Review by shaharsamocha7 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/216)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ohad-starkware)

**Pull request merged**
