### PR TITLE
range check 128 builtin generate trace

### PR DESCRIPTION
**Pull request by shaharsamocha7**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/37)

### CODE REVIEW

**Comment by shaharsamocha7** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/37?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#37** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/37?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#36** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/36?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#35** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/35?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @shaharsamocha7 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/37)* status: all files reviewed, 6 unresolved discussions (waiting on @alonh5 and @shaharsamocha7)

___
*[`stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs` line 17 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/37#-O3RBJuf-4G_xjDM4NKe:-O3RBJuf-4G_xjDM4NKf:by57q9c) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c3261089d18f0bd446b034b6f753abe11b7d3e70/stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs#L17)):*
> ```XML
> pub struct RangeCheckInput {
>     pub address: PackedM31,
>     pub values: [u128; N_LANES],
> ```

RangeCheckInput is a packed representation of the inputs. Therefore, you can decide to represent it in a way that better suits you. For example, [u32x16;4].
Let the guy that creates this Input do the transpose.
___
*[`stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs` line 22 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/37#-O3RC_7j29fHqDbO9SGW:-O3RC_7j29fHqDbO9SGX:b-einkb0) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c3261089d18f0bd446b034b6f753abe11b7d3e70/stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs#L22)):*
> ```XML
> pub struct RangeCheck128BuiltinLookupData {
>     pub memory_lookups: [BaseColumn; ADDRESS_FELTS + N_VALUES_FELTS],
>     pub rcunit2_lookups: [BaseColumn; 1],
> ```

No need to keep this twice. Just grab it from memory_lookups.
___
*[`stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs` line 53 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/37#-O3RBxaC9D2HsA0zmTgS:-O3RBxaC9D2HsA0zmTgT:b-gxnqei) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c3261089d18f0bd446b034b6f753abe11b7d3e70/stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs#L53)):*
> ```XML
>     for vec_row in 0..(1 << (log_size - LOG_N_LANES)) {
>         // TODO: remove address from the trace.
>         let address = inputs[vec_row].address - PackedM31::broadcast(address_initial_offset);
> ```

inputs might be shorter than the power of 2 we are using, and we'll need padding.



_Suggestion:_
```XML
inputs.get(vec_row).or_default()
```
___
*[`stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs` line 72 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/37#-O3RCwYB3c8rPseODvZj:-O3RCwYB3c8rPseODvZk:b-51vkij) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c3261089d18f0bd446b034b6f753abe11b7d3e70/stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs#L72)):*
> ```XML
>             .into_iter()
>             .map(|eval| CircleEvaluation::<SimdBackend, _, BitReversedOrder>::new(domain, eval))
>             .collect_vec(),
> ```

Perhaps we need a utility function for this in stwo?



_Code quote:_
```XML
    let domain = CanonicCoset::new(log_size).circle_domain();
    (
        trace
            .into_iter()
            .map(|eval| CircleEvaluation::<SimdBackend, _, BitReversedOrder>::new(domain, eval))
            .collect_vec(),
```
___
*[`stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs` line 77 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/37#-O3RD0rY2f9mpMMvQhIY:-O3RD0rY2f9mpMMvQhIZ:bd3wlu5) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c3261089d18f0bd446b034b6f753abe11b7d3e70/stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs#L77)):*
> ```XML
> }
> 
> // TODO: replace this code with prover_types when available.
> ```

TODO on who?
___
*[`stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs` line 78 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/37#-O3RD6Nh4aQ9SpwPxy1I:-O3RD6Nh4aQ9SpwPxy1J:b-53kbsd) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c3261089d18f0bd446b034b6f753abe11b7d3e70/stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs#L78)):*
> ```XML
> 
> // TODO: replace this code with prover_types when available.
> fn split_u128(mut x: [u128; N_LANES]) -> [PackedM31; N_VALUES_FELTS] {
> ```

If you take the suggestion above, of keeping values as [u32x16;4], here you would jkust have ands, shift and ors, all packed.

Otherwise, we should do the transpose here in a simd way.

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/37)* status: 3 of 5 files reviewed, 5 unresolved discussions (waiting on @alonh5 and @spapinistarkware)

___
*[`stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs` line 17 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/37#-O3RBJuf-4G_xjDM4NKe:-O3RbgzI2oJAkt5zD18v:b-4p2a3h) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c3261089d18f0bd446b034b6f753abe11b7d3e70/stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs#L17)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

RangeCheckInput is a packed representation of the inputs. Therefore, you can decide to represent it in a way that better suits you. For example, [u32x16;4].
Let the guy that creates this Input do the transpose.
</blockquote></details>

I did wonder about what is the best way to get the inputs in this case.
I'm not sure I understand the `[u32x16;4]` suggestion.
Let's talk
___
*[`stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs` line 22 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/37#-O3RC_7j29fHqDbO9SGW:-O3RnO374Iy5FPay4sbD:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c3261089d18f0bd446b034b6f753abe11b7d3e70/stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs#L22)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

No need to keep this twice. Just grab it from memory_lookups.
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs` line 53 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/37#-O3RBxaC9D2HsA0zmTgS:-O3Rk5WH5s8syVxAFNzs:bommho0) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c3261089d18f0bd446b034b6f753abe11b7d3e70/stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs#L53)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

inputs might be shorter than the power of 2 we are using, and we'll need padding.
</blockquote></details>

The compiler made me use cloned()..
Also, I'll need PackedM31 to derive Default.
___
*[`stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs` line 72 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/37#-O3RCwYB3c8rPseODvZj:-O3RheUhB4I8P1K5UNRX:bwt1f6d) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c3261089d18f0bd446b034b6f753abe11b7d3e70/stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs#L72)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Perhaps we need a utility function for this in stwo?
</blockquote></details>

Yeah, should be in eval framework utils IMO
___
*[`stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs` line 78 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/37#-O3RD6Nh4aQ9SpwPxy1I:-O3Ri6QcAWT7lw_O7sHk:b-ir4m2f) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c3261089d18f0bd446b034b6f753abe11b7d3e70/stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs#L78)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

If you take the suggestion above, of keeping values as [u32x16;4], here you would jkust have ands, shift and ors, all packed.

Otherwise, we should do the transpose here in a simd way.
</blockquote></details>

I don't want to do tricky stuff here ATM, as I intend it to be replaced anyway.

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/37)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @alonh5 and @shaharsamocha7)

___
*[`stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs` line 17 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/37#-O3RBJuf-4G_xjDM4NKe:-O3RpsVX7axZ-VVeQqmm:bnffqtx) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c3261089d18f0bd446b034b6f753abe11b7d3e70/stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs#L17)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I did wonder about what is the best way to get the inputs in this case.
I'm not sure I understand the `[u32x16;4]` suggestion.
Let's talk
</blockquote></details>

We are working with vectors of size 16. To not have swizzles, it would be ebst to stay this way. Thus, I suggest to store a u128 as 4 u32s. Or, a u128x16 as 4 u32x16.
___
*[`stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs` line 53 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/37#-O3RBxaC9D2HsA0zmTgS:-O3RqDss2rFM8edJNyQJ:b-byovhl) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c3261089d18f0bd446b034b6f753abe11b7d3e70/stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs#L53)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

The compiler made me use cloned()..
Also, I'll need PackedM31 to derive Default.
</blockquote></details>

Implement Default directly
___
*[`stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs` line 78 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/37#-O3RD6Nh4aQ9SpwPxy1I:-O3RqJwK64EBODXf3z-0:b-1vzog7) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c3261089d18f0bd446b034b6f753abe11b7d3e70/stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs#L78)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I don't want to do tricky stuff here ATM, as I intend it to be replaced anyway.
</blockquote></details>

Replaced by what, and when? Why should this be replaced?

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/37)* status: 3 of 6 files reviewed, 3 unresolved discussions (waiting on @alonh5 and @spapinistarkware)

___
*[`stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs` line 17 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/37#-O3RBJuf-4G_xjDM4NKe:-O3SPclgEBdMus01ljCw:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c3261089d18f0bd446b034b6f753abe11b7d3e70/stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs#L17)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

We are working with vectors of size 16. To not have swizzles, it would be ebst to stay this way. Thus, I suggest to store a u128 as 4 u32s. Or, a u128x16 as 4 u32x16.
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs` line 53 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/37#-O3RBxaC9D2HsA0zmTgS:-O3SPemv9TWckS1Y7k-W:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c3261089d18f0bd446b034b6f753abe11b7d3e70/stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs#L53)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Implement Default directly
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs` line 78 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/37#-O3RD6Nh4aQ9SpwPxy1I:-O3SPg9v8TEXS-HiNcxM:b-psk5qr) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c3261089d18f0bd446b034b6f753abe11b7d3e70/stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs#L78)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Replaced by what, and when? Why should this be replaced?
</blockquote></details>

Done.

I'm not a fan of my implementation though.
Any suggestions?

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/37)* status: 3 of 6 files reviewed, 4 unresolved discussions (waiting on @alonh5 and @spapinistarkware)

___
*[`stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs` line 123 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/37#-O3SxMYSATlQrLKpAnDP:-O3SxMYSATlQrLKpAnDQ:b-i43x6) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/fb802075c6c771b827edfbf6c2d7d0a0ec147ad5/stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs#L123)):*
> ```XML
>                 input >>= N_BITS_PER_FELT;
>             }
>         }
> ```

I was having hard time to adapt these asserts.
Do you think it is necessary?



_Code quote:_
```XML
        for row_offset in 0..(1 << log_size) {
            let mut input = inputs[row_offset / N_LANES].values[row_offset % N_LANES];
            for col in trace.iter().skip(1) {
                assert_eq!(
                    input % (1 << N_BITS_PER_FELT),
                    col.values.at(row_offset).0.into()
                );
                input >>= N_BITS_PER_FELT;
            }
        }
```

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/37)* status: 3 of 6 files reviewed, 5 unresolved discussions (waiting on @alonh5 and @shaharsamocha7)

___
*[`stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs` line 84 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/37#-O3WQsn9EHrSDrzKB1CO:-O3WQsn9EHrSDrzKB1CP:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/cc9ffe8b6e64fda298194a34b79b3cae24382a1c/stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs#L84)):*
> ```XML
> // Given 16 128-bit values, stored as 4 32-bit values, split them into 9-bit values elements.
> fn split_u128(x: [u32x16; 4]) -> [PackedM31; N_VALUES_FELTS] {
>     let mut curr_bit = 0;
> ```





_Suggestion:_
```XML
let mut curr_bit = 0u32;
```
___
*[`stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs` line 88 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/37#-O3WQwkA0vHY1nIlB50s:-O3WPyTn4zB-XU4hSyn9:b-qijhhh) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/cc9ffe8b6e64fda298194a34b79b3cae24382a1c/stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs#L88)):*
> ```XML
>     let full_mask: u32x16 = u32x16::splat((1 << N_BITS_PER_FELT) - 1);
>     let mut res = [PackedM31::zero(); N_VALUES_FELTS];
>     for e in res.iter_mut().take(N_VALUES_FELTS) {
> ```

Why take?



_Suggestion:_
```XML
for e in res.iter_mut()
```
___
*[`stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs` line 89 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/37#-O3Wglo40GTvfqeVYBoG:-O3WPnyCCBfJUVpmBfa2:b-51jndn) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/cc9ffe8b6e64fda298194a34b79b3cae24382a1c/stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs#L89)):*
> ```XML
>     let mut res = [PackedM31::zero(); N_VALUES_FELTS];
>     for e in res.iter_mut().take(N_VALUES_FELTS) {
>         // Check if the element bits overlap two 32-bit values.
> ```

Consider something like this
```

let mut n_bits_in_word = 32;
let mut word_i = 0;
let mut word = x[0];
for e in res.iter_mut().take(N_VALUES_FELTS) {
	*e = cur;
	// If we word has more bits than needed, chop it.
	if n_bits_in_word > N_BITS_PER_FELT {
		*e = *e & mask;
		word >>= N_BITS_PER_FELT;
		n_bits_in_word -= N_BITS_PER_FELT;
		continue;
	}

	// Fetch next word.
	word_i += 1
	word = x.get(word_i + 1).unwrap_or_default();
	// If we need more bits to fill, take from next word.
	if n_bits_in_word < N_BITS_PER_FELT {
		*e |= (word << n_bits_in_word) & mask;
		word >>= (N_BITS_PER_FELT - n_bits_in_word)
	}

	n_bits_in_word += 32 - N_BITS_PER_FELT;
}

```

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/37)* status: 5 of 6 files reviewed, 5 unresolved discussions (waiting on @alonh5 and @shaharsamocha7)

___
*[`stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs` line 123 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/37#-O3SxMYSATlQrLKpAnDP:-O3WiWWW7K8qZqGKg4GC:b-d0pl28) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/fb802075c6c771b827edfbf6c2d7d0a0ec147ad5/stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs#L123)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I was having hard time to adapt these asserts.
Do you think it is necessary?
</blockquote></details>

I don't think it's necessary

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/37)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @alonh5 and @spapinistarkware)

___
*[`stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs` line 84 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/37#-O3WQsn9EHrSDrzKB1CO:-O3WiAyX8mtGgjHbHFW0:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/cc9ffe8b6e64fda298194a34b79b3cae24382a1c/stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs#L84)):*
> ```XML
> // Given 16 128-bit values, stored as 4 32-bit values, split them into 9-bit values elements.
> fn split_u128(x: [u32x16; 4]) -> [PackedM31; N_VALUES_FELTS] {
>     let mut curr_bit = 0;
> ```

Done.
___
*[`stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs` line 88 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/37#-O3WQwkA0vHY1nIlB50s:-O3WgwYv9dyJChl1cCFP:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/cc9ffe8b6e64fda298194a34b79b3cae24382a1c/stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs#L88)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Why take?
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs` line 89 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/37#-O3Wglo40GTvfqeVYBoG:-O3WxkXEE2J2NyFBaIO5:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/cc9ffe8b6e64fda298194a34b79b3cae24382a1c/stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs#L89)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Consider something like this
```

let mut n_bits_in_word = 32;
let mut word_i = 0;
let mut word = x[0];
for e in res.iter_mut().take(N_VALUES_FELTS) {
	*e = cur;
	// If we word has more bits than needed, chop it.
	if n_bits_in_word > N_BITS_PER_FELT {
		*e = *e & mask;
		word >>= N_BITS_PER_FELT;
		n_bits_in_word -= N_BITS_PER_FELT;
		continue;
	}

	// Fetch next word.
	word_i += 1
	word = x.get(word_i + 1).unwrap_or_default();
	// If we need more bits to fill, take from next word.
	if n_bits_in_word < N_BITS_PER_FELT {
		*e |= (word << n_bits_in_word) & mask;
		word >>= (N_BITS_PER_FELT - n_bits_in_word)
	}

	n_bits_in_word += 32 - N_BITS_PER_FELT;
}

```
</blockquote></details>

Done.

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/37)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @alonh5 and @shaharsamocha7)

___
*[`stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs` line 84 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/37#-O3X0Jip3BhoRi21M_8o:-O3X0Jip3BhoRi21M_8p:b-7s4sqq) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/7437d37ed0a243dbf28b73ab36ae17c098f5892a/stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs#L84)):*
> ```XML
> // Given 16 128-bit values, stored as 4 32-bit values, split them into 9-bit values elements.
> fn split_u128(x: [u32x16; 4]) -> [PackedM31; N_VALUES_FELTS] {
>     let mask: u32x16 = u32x16::splat((1 << N_BITS_PER_FELT) - 1);
> ```

const
___
*[`stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs` line 106 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/37#-O3X0MGcE86bfH-Twb5w:-O3X0MGcE86bfH-Twb5x:b7pifvl) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/7437d37ed0a243dbf28b73ab36ae17c098f5892a/stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs#L106)):*
> ```XML
>         // If we need more bits to fill, take from next word.
>         if n_bits_in_word < N_BITS_PER_FELT {
>             *e += (word << n_bits_in_word as u32) & mask;
> ```

Consider `|=`
___
*[`stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs` line 113 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/37#-O3X17Yf-haYSUNP6URP:-O3X17Yf-haYSUNP6URQ:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/7437d37ed0a243dbf28b73ab36ae17c098f5892a/stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs#L113)):*
> ```XML
>     }
> 
>     unsafe { std::mem::transmute(res) }
> ```





_Suggestion:_
```XML
res.map(|x| unsafe { PackedM31::from... })
```

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/37)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @alonh5 and @spapinistarkware)

___
*[`stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs` line 84 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/37#-O3X0Jip3BhoRi21M_8o:-O3XOeG4DLRQefvBTkZW:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/7437d37ed0a243dbf28b73ab36ae17c098f5892a/stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs#L84)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

const
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs` line 106 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/37#-O3X0MGcE86bfH-Twb5w:-O3XK2QB96gFeg7NvtyU:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/7437d37ed0a243dbf28b73ab36ae17c098f5892a/stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs#L106)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Consider `|=`
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs` line 113 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/37#-O3X17Yf-haYSUNP6URP:-O3XK2g_CoFVXhaBGA8N:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/7437d37ed0a243dbf28b73ab36ae17c098f5892a/stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs#L113)):*
> ```XML
>     }
> 
>     unsafe { std::mem::transmute(res) }
> ```

Done.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:
with 1 comment

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/37#-:-O3Xb9VmEJ-BBkY6lTvA:b-9hxz9t)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @alonh5)

___
*[`stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs` line 113 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/37#-O3X17Yf-haYSUNP6URP:-O3Xb4WRAlQxV_E5s_uC:bb6a6j5) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/7437d37ed0a243dbf28b73ab36ae17c098f5892a/stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs#L113)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Do the from_unchecked variant.

**Review by spapinistarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/37)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Review by spapinistarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/37)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Pull request merged**
