### PR TITLE
Implement Component for RangeCheckUnitComponent.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/12)

### CODE REVIEW

**Comment by alonh5** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/12?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#12** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/12?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#11** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/11?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alonh5 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/12)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @alonh5)

___
*[`stwo_cairo_prover/src/components/range_check_unit.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/12#-O1QYmEn9fNUCcCE6ic6:-O1QYmEo7KWUAuCHsOXR:bixb17v) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/5fe74b3117b1483338a70cbf8d26dd30e7b0833a/stwo_cairo_prover/src/components/range_check_unit.rs#L58)):*
> ```XML
> 
>     fn max_constraint_log_degree_bound(&self) -> u32 {
>         self.log_n_instances
> ```

The step constraint is of degree 2, right?



_Suggestion:_
```XML
self.log_n_instances + 1?
```
___
*[`stwo_cairo_prover/src/components/range_check_unit.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/12#-O1QYxgA0m_x-SPsQDlO:-O1QYxgA0m_x-SPsQDlP:bvpuoh8) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/5fe74b3117b1483338a70cbf8d26dd30e7b0833a/stwo_cairo_prover/src/components/range_check_unit.rs#L94)):*
> ```XML
>             interaction_elements,
>             constraint_zero_domain,
>         );
> ```

Why not adding all the constraints?



_Code quote:_
```XML
        self.evaluate_lookup_boundary_constraints_at_point(
            point,
            mask,
            evaluation_accumulator,
            interaction_elements,
            constraint_zero_domain,
        );
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/12)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7)

___
*[`stwo_cairo_prover/src/components/range_check_unit.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/12#-O1QYmEn9fNUCcCE6ic6:-O1R5bEy03RdvmXkWNqX:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/5fe74b3117b1483338a70cbf8d26dd30e7b0833a/stwo_cairo_prover/src/components/range_check_unit.rs#L58)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

The step constraint is of degree 2, right?
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/src/components/range_check_unit.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/12#-O1QYxgA0m_x-SPsQDlO:-O1R5bwE8XB3Fp-clC4Q:b-65l7p6) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/5fe74b3117b1483338a70cbf8d26dd30e7b0833a/stwo_cairo_prover/src/components/range_check_unit.rs#L94)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Why not adding all the constraints?
</blockquote></details>

All in one PR? It would be harder to review

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/12)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @alonh5)

___
*[`stwo_cairo_prover/src/components/range_check_unit.rs` line 33 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/12#-O1ROuytBtE1sI7Ec-Uw:-O1ROuytBtE1sI7Ec-Ux:bj3gnuh) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e0f48d27b22a81c7157ce6fd3dd89df1d4a14192/stwo_cairo_prover/src/components/range_check_unit.rs#L33)):*
> ```XML
> 
> impl RangeCheckUnitComponent {
>     fn evaluate_lookup_boundary_constraints_at_point(
> ```

Don't you want to update the eval_at_domain function for the prover in the same pr?



_Code quote:_
```XML
fn evaluate_lookup_boundary_constraints_at_point(
```
___
*[`stwo_cairo_prover/src/components/range_check_unit.rs` line 73 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/12#-O1RPB6nE698Z4BQQmQg:-O1RPB6nE698Z4BQQmQh:bdqk8bz) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e0f48d27b22a81c7157ce6fd3dd89df1d4a14192/stwo_cairo_prover/src/components/range_check_unit.rs#L73)):*
> ```XML
>         point: CirclePoint<SecureField>,
>     ) -> TreeVec<ColumnVec<Vec<CirclePoint<SecureField>>>> {
>         TreeVec::new(vec![fixed_mask_points(&vec![vec![0_usize]], point)])
> ```

didn't you have that with ;2?



_Code quote:_
```XML
fixed_mask_points(&vec![vec![0_usize]
```

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/12#-:-O1Rmydj1wy5GhZMi0L6:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

___
*[`stwo_cairo_prover/src/components/range_check_unit.rs` line 33 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/12#-O1ROuytBtE1sI7Ec-Uw:-O1RmwT22YBAwkYwU1Od:b-9vo0u2) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e0f48d27b22a81c7157ce6fd3dd89df1d4a14192/stwo_cairo_prover/src/components/range_check_unit.rs#L33)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

It's in the next PR. I can combine them if you prefer.
</blockquote></details>

your call

**Comment by alonh5** [comment]
### Merge activity

* **Jul 11, 3:20 AM EDT**: @alonh5 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/12).

**Pull request merged**
