### PR TITLE
Add `draw_random_bytes` to the channel

### PR DESCRIPTION
**Pull request by schouhy**
This PR adds a method to the channel to draw 31 random bytes.
The tests are cross validated with stwo's implementation.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/21)

### CODE REVIEW

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/21)* status: all files reviewed, 4 unresolved discussions (waiting on @schouhy)

___
*[`stwo_cairo_verifier/src/channel.cairo` line 127 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/21#-O1vWQNYENIY6hV6iGsT:-O1vWQNZEkhzPfrj2ei7:bb752ax) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/81b3df2157f7759a126b81d9fb28e6997455d2a4/stwo_cairo_verifier/src/channel.cairo#L127)):*
> ```Cairo
> 
>     /// Returns 31 random bytes computed as the first 31 bytes of the representative of 
>     /// `self.draw_felt252()` in little endinan.
> ```

Typo



_Suggestion:_
```Cairo
/// `self.draw_felt252()` in little endian.
```
___
*[`stwo_cairo_verifier/src/channel.cairo` line 128 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/21#-O1vWW_e8As31b8dwzAo:-O1vWW_e8As31b8dwzAp:b-86kxa7) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/81b3df2157f7759a126b81d9fb28e6997455d2a4/stwo_cairo_verifier/src/channel.cairo#L128)):*
> ```Cairo
>     /// Returns 31 random bytes computed as the first 31 bytes of the representative of 
>     /// `self.draw_felt252()` in little endinan.
>     fn draw_random_bytes(ref self: Channel) -> Array<u8> {
> ```

Please add a TODO to check that this distribution is good enough, as it is only close to the uniform distribution.



_Code quote:_
```Cairo
fn draw_random_bytes(ref self: Channel) -> Array<u8> {
```
___
*[`stwo_cairo_verifier/src/channel.cairo` line 141 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/21#-O1vXTv3-UD-0s488xuS:-O1vXTv3-UD-0s488xuT:b-69ckq2) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/81b3df2157f7759a126b81d9fb28e6997455d2a4/stwo_cairo_verifier/src/channel.cairo#L141)):*
> ```Cairo
>             let res_representative: u256 = res.into();
>             cur = next;
>             bytes.append((res_representative & 0xff).try_into().unwrap());
> ```

No need to have felts inside the loop
See extract_m31



_Suggestion:_
```Cairo
let (q, r) = div_rem(cur, 256);
bytes.append(r.try_into().unwrap());
cur = q;
```
___
*[`stwo_cairo_verifier/src/channel.cairo` line 254 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/21#-O1vZ4hI2_SdLYUPH19t:-O1vZ4hI2_SdLYUPH19u:b-c9wdzm) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/81b3df2157f7759a126b81d9fb28e6997455d2a4/stwo_cairo_verifier/src/channel.cairo#L254)):*
> ```Cairo
> 
>     #[test]
>     pub fn test_draw_random_bytes_1() {
> ```

Consider call draw_random_bytes() twice and check that you get different bytes



_Code quote:_
```Cairo
pub fn test_draw_random_bytes_1() 
```

**Review by schouhy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/21)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7)

___
*[`stwo_cairo_verifier/src/channel.cairo` line 128 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/21#-O1vWW_e8As31b8dwzAo:-O1w8tyd3RkxUIhp5XS0:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/81b3df2157f7759a126b81d9fb28e6997455d2a4/stwo_cairo_verifier/src/channel.cairo#L128)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Please add a TODO to check that this distribution is good enough, as it is only close to the uniform distribution.
</blockquote></details>

Done.
___
*[`stwo_cairo_verifier/src/channel.cairo` line 141 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/21#-O1vXTv3-UD-0s488xuS:-O1w8vaC7gVg3QmBuZ7p:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/81b3df2157f7759a126b81d9fb28e6997455d2a4/stwo_cairo_verifier/src/channel.cairo#L141)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

No need to have felts inside the loop
See extract_m31
</blockquote></details>

Done.
___
*[`stwo_cairo_verifier/src/channel.cairo` line 254 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/21#-O1vZ4hI2_SdLYUPH19t:-O1w90m7-Sx7MPq1u7JQ:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/81b3df2157f7759a126b81d9fb28e6997455d2a4/stwo_cairo_verifier/src/channel.cairo#L254)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Consider call draw_random_bytes() twice and check that you get different bytes
</blockquote></details>

Done.

**Review by shaharsamocha7 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/21)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @schouhy)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/21#-:-O1zlIoz6oxPQK0O43r4:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @schouhy)

**Pull request merged**
