### PR TITLE
public memory

### PR DESCRIPTION
**Pull request by ohad-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/168)

### CODE REVIEW

**Comment by ohad-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/168?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#168** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/168?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#167** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/167?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#166** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/166?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#165** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/165?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#161** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/161?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#160** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/160?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ohad-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/168)* status: all files reviewed, 2 unresolved discussions (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs` line 39 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/168#-OBeJ7Q757_4XIfTEWvc:-OBeJ7Q757_4XIfTEWvd:b-lfsyq9) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/02f7b1685e873c60a62a846fc42e8aa361988907/stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs#L39)):*
> ```XML
> pub struct CairoClaim {
>     // Common claim values.
>     pub public_memory: Vec<(u32, u32, [u32; 8])>,
> ```

Document or add typedef



_Code quote:_
```XML
pub public_memory: Vec<(u32, u32, [u32; 8])>,
```
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs` line 346 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/168#-OBeJUcpBs54-cPW9nVF:-OBeJUcpBs54-cPW9nVG:b-1vkonm) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/02f7b1685e873c60a62a846fc42e8aa361988907/stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs#L346)):*
> ```XML
>             let id = input.mem.address_to_id[addr as usize];
>             (addr, id.0, input.mem.get(addr).as_u256())
>         })
> ```

I think we have a get_raw_id function



_Suggestion:_
```XML
        .map(|addr| {
            let id = input.mem.get_raw_id(addr);
            let value = input.mem.get(addr).as_u256()
            (addr, id, value)
        })
```

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/168)* status: all files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs` line 39 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/168#-OBeJ7Q757_4XIfTEWvc:-OBebRX2EWirEZGO5NzA:b-7rl0jd) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/02f7b1685e873c60a62a846fc42e8aa361988907/stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs#L39)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Document or add typedef
</blockquote></details>

done.
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs` line 346 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/168#-OBeJUcpBs54-cPW9nVF:-OBebPTkEosMRrdFZIIb:b32wy2) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/02f7b1685e873c60a62a846fc42e8aa361988907/stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs#L346)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I think we have a get_raw_id function
</blockquote></details>

ty

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/168#-:-OBes-gD4lQspV0oqdJv:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs` line 37 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/168#-OBerYhQ80MvS75F1Kd2:-OBerYhQ80MvS75F1Kd3:b-8orq4h) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/1267d228f10b09b3efacfd56fcdb4b3ac6923a7f/stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs#L37)):*
> ```XML
> 
> // (Address, Id, Value)
> pub type PublicMemory = Vec<(u32, u32, [u32; 8])>;
> ```

I thought more about something like this
pub public_memory: Vec<MemoryEntryWithId>

non-blocking



_Suggestion:_
```XML
// (Address, Id, value)
pub type MemoryEntryWithId = (u32, u32, [u32; 8]);
```

**Comment by ohad-starkware** [comment]
### Merge activity

* **Nov 14, 8:43 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/168).

**Pull request merged**
