### PR TITLE
E2E call ret

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/58)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/58?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#58** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/58?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#57** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/57?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#56** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/56?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#55** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/55?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#54** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/54?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#53** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/53?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#52** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/52?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#51** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/51?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/58)* status: 2 of 16 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs` line 131 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/58#-O4_TgaY7H9pxXaNYQYK:-O4_TgaY7H9pxXaNYQYL:be0jbfo) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/d654312670725b635d1937b70dfa2f715f344522/stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs#L131)):*
> ```XML
> }
> 
> const LOG_MAX_ROWS: u32 = 20;
> ```

Why 20?



_Code quote:_
```XML
const LOG_MAX_ROWS: u32 = 20;
```
___
*[`stwo_cairo_prover/crates/prover/src/components/ret_opcode/component.rs` line 53 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/58#-O4_QndUCMHzMSngCqx7:-O4_QndUCMHzMSngCqx8:b-8y02yl) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/d654312670725b635d1937b70dfa2f715f344522/stwo_cairo_prover/crates/prover/src/components/ret_opcode/component.rs#L53)):*
> ```XML
>             510, 447, 511, 495, 511, 91, 130, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
>             0, 0, 0,
>         ];
> ```

Should we make this a constant? Anyway give it a better name
Also below.



_Code quote:_
```XML
        let a = [
            510, 447, 511, 495, 511, 91, 130, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0,
        ];
```

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/58)* status: 7 of 16 files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_builtin/simd_trace.rs` line 114 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/58#-O4_W48d4Ebv9wLFdg7L:-O4_W48d4Ebv9wLFdg7M:b-jimjls) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/d654312670725b635d1937b70dfa2f715f344522/stwo_cairo_prover/crates/prover/src/components/range_check_builtin/simd_trace.rs#L114)):*
> ```XML
> }
> 
> fn split<const N: usize, const M: usize>(x: [u32x16; N]) -> [PackedM31; M] {
> ```

Document

**Review by alonh5 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/58)* status: 7 of 16 files reviewed, 4 unresolved discussions (waiting on @spapinistarkware)

___
*[`stwo_cairo_prover/crates/prover/src/components/memory/prover.rs` line 37 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/58#-O4igl6CDdanDmulWqSe:-O4igl6CDdanDmulWqSf:bss4962) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/9d876e2bce1d12ecff133abb5874911edd7eb5ce/stwo_cairo_prover/crates/prover/src/components/memory/prover.rs#L37)):*
> ```XML
> 
>         let size = values.len().next_power_of_two().max(MEMORY_ADDRESS_BOUND);
>         println!("size: {}", size);
> ```

Remove? 



_Code quote:_
```XML
println!("size: {}", size);
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/58)* status: 7 of 16 files reviewed, 4 unresolved discussions (waiting on @alonh5)

___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs` line 131 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/58#-O4_TgaY7H9pxXaNYQYK:-O4io_LTEMPd6ImvAOk8:b-rhgadu) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/d654312670725b635d1937b70dfa2f715f344522/stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs#L131)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Why 20?
</blockquote></details>

We need to predetermine some maximum log rows we are willing to have. Then, we should split the components to powers of 2, but of at most this size.
So, in this suggestion, LOG_MAX_ROWS determines the sizes of the components, and not the other way around.

20 seems ok. Especially since we are talking about at most 2^26 steps.
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/prover.rs` line 37 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/58#-O4igl6CDdanDmulWqSe:-O4ip7yuCyIqxEGFSa2-:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/9d876e2bce1d12ecff133abb5874911edd7eb5ce/stwo_cairo_prover/crates/prover/src/components/memory/prover.rs#L37)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Remove?
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_builtin/simd_trace.rs` line 114 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/58#-O4_W48d4Ebv9wLFdg7L:-O4ipUIRDVkq3n1sq9Wl:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/d654312670725b635d1937b70dfa2f715f344522/stwo_cairo_prover/crates/prover/src/components/range_check_builtin/simd_trace.rs#L114)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Document
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/components/ret_opcode/component.rs` line 53 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/58#-O4_QndUCMHzMSngCqx7:-O4ipt6DEJ1FaJdXb-uL:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/d654312670725b635d1937b70dfa2f715f344522/stwo_cairo_prover/crates/prover/src/components/ret_opcode/component.rs#L53)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Should we make this a constant? Anyway give it a better name
Also below.
</blockquote></details>

Done.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 15 files at r1, 1 of 4 files at r2, 3 of 4 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/58)* status: all files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs` line 131 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/58#-O4_TgaY7H9pxXaNYQYK:-O4it94l6V1iM-pVbrpi:bcr5s31) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/d654312670725b635d1937b70dfa2f715f344522/stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs#L131)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

We need to predetermine some maximum log rows we are willing to have. Then, we should split the components to powers of 2, but of at most this size.
So, in this suggestion, LOG_MAX_ROWS determines the sizes of the components, and not the other way around.

20 seems ok. Especially since we are talking about at most 2^26 steps.
</blockquote></details>

Got it, thanks.
___
*[`stwo_cairo_prover/crates/prover/src/components/ret_opcode/prover.rs` line 37 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/58#-O4ivGpVE5oaeI-DBUwq:-O4ivGpVE5oaeI-DBUwr:b29isvu) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/877d49e605156262080b03341f9e95c139a52e26/stwo_cairo_prover/crates/prover/src/components/ret_opcode/prover.rs#L37)):*
> ```XML
>         // TODO(spapini): Split to multiple components.
>         let size = inputs.len().next_power_of_two().max(64);
>         inputs.resize(size, inputs[0].clone());
> ```

This is the padding right?



_Code quote:_
```XML
inputs.resize(size, inputs[0].clone());
```
___
*[`stwo_cairo_prover/crates/prover/src/input/mem.rs` line 223 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/58#-O4iyXch0pKEtFWSASX6:-O4iyXciCJbimfrzBv3D:b3nner1) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/877d49e605156262080b03341f9e95c139a52e26/stwo_cairo_prover/crates/prover/src/input/mem.rs#L223)):*
> ```XML
>     pub fn as_u256(&self) -> [u32; 8] {
>         match self {
>             MemoryValue::Small(x) => {
> ```

Would this work? instead of dereferencing every time?



_Suggestion:_
```XML
MemoryValue::Small(&x)
```
___
*[`stwo_cairo_prover/crates/prover/src/input/mem.rs` line 230 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/58#-O4j-1bL0VEnVdtMdZTe:-O4j-1bL0VEnVdtMdZTf:b48vmvp) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/877d49e605156262080b03341f9e95c139a52e26/stwo_cairo_prover/crates/prover/src/input/mem.rs#L230)):*
> ```XML
>                 } else {
>                     let mut res = P_MIN_2;
>                     res[0] = 0xFFFF_FFFF - (-x - 2) as u32;
> ```

Add unit test?



_Suggestion:_
```XML
(x - 2)
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/58)* status: all files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`stwo_cairo_prover/crates/prover/src/input/mem.rs` line 230 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/58#-O4j-1bL0VEnVdtMdZTe:-O4j-bH2ECMuKk-K7ewH:bbqm3fi) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/877d49e605156262080b03341f9e95c139a52e26/stwo_cairo_prover/crates/prover/src/input/mem.rs#L230)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Add unit test?
</blockquote></details>

I was wrong, but add unit test anyway?

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/58)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`stwo_cairo_prover/crates/prover/src/components/ret_opcode/prover.rs` line 37 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/58#-O4ivGpVE5oaeI-DBUwq:-O4j9wxc46J45o9AS4Le:bb77ufg) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/877d49e605156262080b03341f9e95c139a52e26/stwo_cairo_prover/crates/prover/src/components/ret_opcode/prover.rs#L37)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

This is the padding right?
</blockquote></details>

Yes.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/58)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`stwo_cairo_prover/crates/prover/src/input/mem.rs` line 303 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/58#-O4jAtT64CViOFC-s3gx:-O4jAtT64CViOFC-s3gy:bryrg7m) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/eb765ffca37c28fca6a747743445f1825303107c/stwo_cairo_prover/crates/prover/src/input/mem.rs#L303)):*
> ```XML
>     #[test]
>     fn test_mem_value_casts() {
>         let small = MemoryValue::Small(1);
> ```

Add negative cases.

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/58)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`stwo_cairo_prover/crates/prover/src/input/mem.rs` line 303 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/58#-O4jAtT64CViOFC-s3gx:-O4jGsSzEkyWu_4DP2-y:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/eb765ffca37c28fca6a747743445f1825303107c/stwo_cairo_prover/crates/prover/src/input/mem.rs#L303)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Add negative cases.
</blockquote></details>

Done.

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/58#-:-O4jHRzk3Scv1nG5x45w:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @spapinistarkware)

**Comment by spapinistarkware** [comment]
### Merge activity

* **Aug 20, 6:46 AM EDT**: @spapinistarkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/58).

**Pull request merged**
