### PR TITLE
unify adapter functionality

### PR DESCRIPTION
**Pull request by Stavbe**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/274)

### CODE REVIEW

**Comment by Stavbe** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/274?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#274** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/274?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/274?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#269** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/269?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#268** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/268?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/274)* status: all files reviewed, 4 unresolved discussions (waiting on @shaharsamocha7 and @Stavbe)

___
*[`stwo_cairo_prover/crates/prover/src/input/plain.rs` line 57 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/274#-OF119yd92Nm25b04_Lr:-OF119yd92Nm25b04_Ls:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3ebf7855543298a356a5907bea0f7a48c8736898/stwo_cairo_prover/crates/prover/src/input/plain.rs#L57)):*
> ```XML
> // TODO(yuval): consider returning a result instead of panicking.
> // TODO(Ohad): remove dev_mode after adding the rest of the opcodes.
> /// Translates a CairoRunner into a CairoInput by extracting the relevant input to the adapter.
> ```





_Suggestion:_
```XML
/// Translates a CairoRunner that finished its run into a CairoInput by extracting the relevant input to the adapter.
```
___
*[`stwo_cairo_prover/crates/prover/src/input/plain.rs` line 73 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/274#-OF14wUj8oijEguVK-Tm:-OF14wUj8oijEguVK-Tn:b8lk60g) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3ebf7855543298a356a5907bea0f7a48c8736898/stwo_cairo_prover/crates/prover/src/input/plain.rs#L73)):*
> ```XML
>         });
> 
>     let trace = runner.relocated_trace.clone().unwrap();
> ```

why need the clone here?



_Code quote:_
```XML
clone()
```
___
*[`stwo_cairo_prover/crates/prover/src/input/plain.rs` line 96 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/274#-OF14Ugz9One6zGUMdAk:-OF14Ugz9One6zGUMdAl:b-s1tzx3) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3ebf7855543298a356a5907bea0f7a48c8736898/stwo_cairo_prover/crates/prover/src/input/plain.rs#L96)):*
> ```XML
>         dev_mode,
>     );
>     match cairo_input {
> ```

Can you use unwrap/expect?
___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/274#-OF13SZjEP32w6o2a4gt:-OF13SZjEP32w6o2a4gu:b-r8so2h) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3ebf7855543298a356a5907bea0f7a48c8736898/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L74)):*
> ```XML
> /// - `adapt_vm_output` in the prover.
> /// - `adapt_finished_runner` in the validator.
> pub fn adapter(
> ```

How about `create_stwo_cairo_input`?
I'd also rename `CairoInput` to `StwoCairoInput` or even `StwoInput`/`ProverInput` (but in a separate PR).

Edit:
I see now why you want to call it adapt*, how about `adapt_to_stwo_input`/`adapt_to_stwo_cairo_input`?

**Review by Stavbe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/274)* status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7 and @yuvalsw)

___
*[`stwo_cairo_prover/crates/prover/src/input/plain.rs` line 73 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/274#-OF14wUj8oijEguVK-Tm:-OF2M7Kp5pkoJxQupf3b:bchoy9n) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3ebf7855543298a356a5907bea0f7a48c8736898/stwo_cairo_prover/crates/prover/src/input/plain.rs#L73)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

why need the clone here?
</blockquote></details>

I tried to avoid that but there is a problem with consuming the runner, so one of them (trace/public_input) must be cloned. PublicInput<'a> doesn't implement the clone trait.
___
*[`stwo_cairo_prover/crates/prover/src/input/plain.rs` line 96 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/274#-OF14Ugz9One6zGUMdAk:-OF2RUTVBA9nogFU3f3N:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3ebf7855543298a356a5907bea0f7a48c8736898/stwo_cairo_prover/crates/prover/src/input/plain.rs#L96)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Can you use unwrap/expect?
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/274#-OF13SZjEP32w6o2a4gt:-OF2SGUrDsOra0ijC5J5:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3ebf7855543298a356a5907bea0f7a48c8736898/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L74)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

How about `create_stwo_cairo_input`?
I'd also rename `CairoInput` to `StwoCairoInput` or even `StwoInput`/`ProverInput` (but in a separate PR).

Edit:
I see now why you want to call it adapt*, how about `adapt_to_stwo_input`/`adapt_to_stwo_cairo_input`?
</blockquote></details>

Done.

**Comment by ohad-starkware** [comment]
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/274#-OF13SZjEP32w6o2a4gt:-OFDwmts534RL6_WDlVY:byhvkw8) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3ebf7855543298a356a5907bea0f7a48c8736898/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L74)):*
<details><summary><i>Previously, Stavbe wrote…</i></summary><blockquote>

Done.
</blockquote></details>

the repo is called stwo-cairo, than we say stwo-cairo again in the workspace name, and then prover in the crate name.
`StwoInput` suggests there is a non-Stwo input. suggestions: 
VmTrace, VmOutput, ProverInput

**Review by Stavbe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/274)* status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7 and @yuvalsw)

___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/274#-OF13SZjEP32w6o2a4gt:-OFGh1yn2_5N_i6prbNS:bouht71) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3ebf7855543298a356a5907bea0f7a48c8736898/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L74)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

the repo is called stwo-cairo, than we say stwo-cairo again in the workspace name, and then prover in the crate name.
`StwoInput` suggests there is a non-Stwo input. suggestions: 
VmTrace, VmOutput, ProverInput
</blockquote></details>

@yuvalsw ?

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/274)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7 and @Stavbe)

___
*[`stwo_cairo_prover/crates/prover/src/input/plain.rs` line 73 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/274#-OF14wUj8oijEguVK-Tm:-OFL9aka6EIqZ4DNg4-Z:bdi35zv) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3ebf7855543298a356a5907bea0f7a48c8736898/stwo_cairo_prover/crates/prover/src/input/plain.rs#L73)):*
<details><summary><i>Previously, Stavbe wrote…</i></summary><blockquote>

I tried to avoid that but there is a problem with consuming the runner, so one of them (trace/public_input) must be cloned. PublicInput<'a> doesn't implement the clone trait.
</blockquote></details>

Would be happy to try to figure it out - better avoid cloning the trace
___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/274#-OF13SZjEP32w6o2a4gt:-OFL8RLj1aQIT1OQMryW:b3gdgex) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3ebf7855543298a356a5907bea0f7a48c8736898/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L74)):*
<details><summary><i>Previously, Stavbe wrote…</i></summary><blockquote>

@yuvalsw ?
</blockquote></details>

VmTrace describes the contents rather than the meaning. VmOutput is wrong as it describes the input for the adapter, not its output. ProverInput is completely fine (it was one of my suggestions above).
___
*[`stwo_cairo_prover/crates/prover/src/input/mod.rs` line 19 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/274#-OFL7Ul7A-lSrmP_Qlky:-OFL7Ul7A-lSrmP_Qlkz:b47k3nd) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/5bba2e8aae866e53c36a648c485c5d5226c60bd0/stwo_cairo_prover/crates/prover/src/input/mod.rs#L19)):*
> ```XML
> #[derive(Debug)]
> pub struct CairoInput {
>     pub state_transitions: StateTransitions,
> ```

If already here :)



_Suggestion:_
```XML
// TODO(Stav): rename to StwoInput.
/// Externally provided inputs for the Stwo prover.
#[derive(Debug)]
pub struct CairoInput {
    pub state_transitions: StateTransitions,
```

**Comment by ohad-starkware** [comment]
*[`stwo_cairo_prover/crates/prover/src/input/plain.rs` line 58 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/274#-OFL9wEiCNIpC9L_dXZm:-OFL9wEiCNIpC9L_dXZn:b-4j3wzh) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/5bba2e8aae866e53c36a648c485c5d5226c60bd0/stwo_cairo_prover/crates/prover/src/input/plain.rs#L58)):*
> ```XML
> // TODO(Ohad): remove dev_mode after adding the rest of the opcodes.
> /// Translates a CairoRunner that finished its run into a CairoInput by extracting the relevant
> /// input to the adapter. Assumes memory and trace are already relocated. Otherwise panics.
> ```

use # assumptions or # panics

**Comment by ohad-starkware** [comment]
*[`stwo_cairo_prover/crates/prover/src/input/plain.rs` line 73 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/274#-OF14wUj8oijEguVK-Tm:-OFLA1rg9P88kPIBTm67:b32v57) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3ebf7855543298a356a5907bea0f7a48c8736898/stwo_cairo_prover/crates/prover/src/input/plain.rs#L73)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Would be happy to try to figure it out - better avoid cloning the trace
</blockquote></details>

+1

**Comment by ohad-starkware** [comment]
*[`stwo_cairo_prover/crates/prover/src/input/plain.rs` line 87 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/274#-OFLA6jG1ljIMgdQVZhh:-OFLA6jG1ljIMgdQVZhi:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/5bba2e8aae866e53c36a648c485c5d5226c60bd0/stwo_cairo_prover/crates/prover/src/input/plain.rs#L87)):*
> ```XML
>         .into_iter()
>         .map(|s| s.address as u32)
>         .collect::<Vec<u32>>();
> ```





_Suggestion:_
```XML
collect_vec
```

**Comment by ohad-starkware** [comment]
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 31 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/274#-OFLAJwb0VK2IfWm7Dcz:-OFLAJwb0VK2IfWm7Dd-:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/5bba2e8aae866e53c36a648c485c5d5226c60bd0/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L31)):*
> ```XML
> 
> // TODO(Ohad): remove dev_mode after adding the rest of the instructions.
> /// Adapts the VM's output files to the Cairo input of the prover.
> ```





_Suggestion:_
```XML
/// Adapts the VM's output files to the Cairo input of the prover.
// TODO(Ohad): remove dev_mode after adding the rest of the instructions.
```

**Comment by ohad-starkware** [comment]
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/274#-OF13SZjEP32w6o2a4gt:-OFLAUPS0gGWT520wDoz:bxqpofh) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3ebf7855543298a356a5907bea0f7a48c8736898/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L74)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

VmTrace describes the contents rather than the meaning. VmOutput is wrong as it describes the input for the adapter, not its output. ProverInput is completely fine (it was one of my suggestions above).
</blockquote></details>

yes but I stole it from you after

**Comment by ohad-starkware** [comment]
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 33 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/274#-OFLAgEo92QtdiHGAURg:-OFLAgEo92QtdiHGAURh:b8c2nk8) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/b4ba6e1b650266a59f1e2e252c44607e31e0bb16/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L33)):*
> ```XML
>     public_input_json: &Path,
>     private_input_json: &Path,
>     dev_mode: bool,
> ```

this is a mode and not a mod

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 1 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/274)* status: all files reviewed, 6 unresolved discussions (waiting on @ohad-starkware, @shaharsamocha7, and @Stavbe)

___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/274#-OF13SZjEP32w6o2a4gt:-OFLBOkCCkEBL2Y8saUz:b-ristx1) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3ebf7855543298a356a5907bea0f7a48c8736898/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L74)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

yes but I stole it from you after
</blockquote></details>

It's all yours! :)
___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 33 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/274#-OFLAgEo92QtdiHGAURg:-OFLBmG09N_8NDnPHGOB:b-ntpuzd) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/b4ba6e1b650266a59f1e2e252c44607e31e0bb16/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L33)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

this is a mode and not a mod
</blockquote></details>

It was fixed, needs a rebase.

**Review by ohad-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/274)* status: all files reviewed, 6 unresolved discussions (waiting on @shaharsamocha7 and @Stavbe)

___
*[`-- commits` line 1 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/274#-OFLE2WM0rCSnKAgDjto:-OFLE2WM0rCSnKAgDjtp:b5zwucs):*
blocking until rebase

**Review by Stavbe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/274)* status: 3 of 6 files reviewed, 6 unresolved discussions (waiting on @ohad-starkware, @shaharsamocha7, and @yuvalsw)

___
*[`-- commits` line 1 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/274#-OFLE2WM0rCSnKAgDjto:-OFLxufw9mUIGO0ta55V:b-896fix):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

blocking until rebase
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/input/mod.rs` line 19 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/274#-OFL7Ul7A-lSrmP_Qlky:-OFLxyyb87QoeOxsJgwO:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3379f9ad4c9e62dcb094478e71b9be66be055a3f/stwo_cairo_prover/crates/prover/src/input/mod.rs#L19)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

If already here :)
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/input/plain.rs` line 58 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/274#-OFL9wEiCNIpC9L_dXZm:-OFLy-xv2UdVsxqvH6-R:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3379f9ad4c9e62dcb094478e71b9be66be055a3f/stwo_cairo_prover/crates/prover/src/input/plain.rs#L58)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

use # assumptions or # panics
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 31 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/274#-OFLAJwb0VK2IfWm7Dcz:-OFLvxiBBqyYsMNgrT4X:biptv97) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3379f9ad4c9e62dcb094478e71b9be66be055a3f/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L31)):*
> ```XML
> 
> // TODO(Ohad): remove dev_mode after adding the rest of the instructions.
> /// Adapts the VM's output files to the Cairo input of the prover.
> ```

Todo's are first no ? 
___
*[`stwo_cairo_prover/crates/prover/src/input/plain.rs` line 87 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/274#-OFLA6jG1ljIMgdQVZhh:-OFLy1C7EXOZAi_HuWrW:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3379f9ad4c9e62dcb094478e71b9be66be055a3f/stwo_cairo_prover/crates/prover/src/input/plain.rs#L87)):*
> ```XML
>         .into_iter()
>         .map(|s| s.address as u32)
>         .collect::<Vec<u32>>();
> ```

Done.

**Comment by ohad-starkware** [comment]
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 31 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/274#-OFLAJwb0VK2IfWm7Dcz:-OFM9-zj4-Y2bnvBabyP:b-y2pvz5) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3379f9ad4c9e62dcb094478e71b9be66be055a3f/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L31)):*
<details><summary><i>Previously, Stavbe wrote…</i></summary><blockquote>

Todo's are first no ?
</blockquote></details>

yes? is there a convention?
I always write them after but if there is a convention ok

**Review by ohad-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/274)* status: 3 of 6 files reviewed, 4 unresolved discussions (waiting on @shaharsamocha7, @Stavbe, and @yuvalsw)

___
*[`stwo_cairo_prover/crates/prover/src/input/plain.rs` line 62 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/274#-OFM8rZC1rRPIsS1VODl:-OFM8rZD97uDM7BH_t9o:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/8da963a6f317378b7b63405f637c9039b4a7201b/stwo_cairo_prover/crates/prover/src/input/plain.rs#L62)):*
> ```XML
> /// component only.
> /// # Panics
> /// - Panics if `memory` and 'trace' are not relocated.
> ```





_Suggestion:_
```XML
- if `memory` or 'trace' are not relocated.
```

**Review by Stavbe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/274)* status: 3 of 6 files reviewed, 4 unresolved discussions (waiting on @ohad-starkware, @shaharsamocha7, and @yuvalsw)

___
*[`stwo_cairo_prover/crates/prover/src/input/plain.rs` line 73 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/274#-OF14wUj8oijEguVK-Tm:-OFMYKX34tpmpO9ojyil:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3ebf7855543298a356a5907bea0f7a48c8736898/stwo_cairo_prover/crates/prover/src/input/plain.rs#L73)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/input/plain.rs` line 62 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/274#-OFM8rZC1rRPIsS1VODl:-OFMX9QGDhhPjvD31fY-:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/8da963a6f317378b7b63405f637c9039b4a7201b/stwo_cairo_prover/crates/prover/src/input/plain.rs#L62)):*
> ```XML
> /// component only.
> /// # Panics
> /// - Panics if `memory` and 'trace' are not relocated.
> ```

Done.

**Comment by ohad-starkware** [comment]
*[`stwo_cairo_prover/crates/prover/src/input/plain.rs` line 101 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/274#-OFQrhZ85hGZcK2OcuR8:-OFQrhZ85hGZcK2OcuR9:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/aaabc3a493835e6c0ae64dfd42eea28f4231f636/stwo_cairo_prover/crates/prover/src/input/plain.rs#L101)):*
> ```XML
>         dev_mode,
>     );
>     cairo_input.unwrap()
> ```





_Suggestion:_
```XML
adapt_to_stwo_input(
        trace_iter,
        MemoryBuilder::from_iter(MemoryConfig::default(), memory_iter),
        public_memory_addresses,
        memory_segments,
        dev_mode,
    ).unwrap()
```

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/274#-:-OFQukW60ZPF5ajvxOEY:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @ohad-starkware, @shaharsamocha7, and @Stavbe)

___
*[`stwo_cairo_prover/crates/prover/src/input/plain.rs` line 62 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/274#-OFQu0Os8FcWftu6I4-y:-OFQu0Os8FcWftu6I4-z:bhg7sxv) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/aaabc3a493835e6c0ae64dfd42eea28f4231f636/stwo_cairo_prover/crates/prover/src/input/plain.rs#L62)):*
> ```XML
> /// component only.
> /// # Panics
> /// - if `memory` or 'trace' are not relocated.
> ```

There are no variables named `memory` and `trace`. Either just refer to them (e.g. "if the memory or the trace of the given `runner` are not relocated", or refer to `runner.relocated_memory` etc.



_Code quote:_
```XML
f `memory` or 'trace' are not relocated.
```

**Review by Stavbe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/274)* status: 3 of 6 files reviewed, 3 unresolved discussions (waiting on @ohad-starkware, @shaharsamocha7, and @yuvalsw)

___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 31 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/274#-OFLAJwb0VK2IfWm7Dcz:-OFR2KWc8coNz5wFm72-:b-w1i38i) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3379f9ad4c9e62dcb094478e71b9be66be055a3f/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L31)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

yes? is there a convention?
I always write them after but if there is a convention ok
</blockquote></details>

That's what Yuval taught me
___
*[`stwo_cairo_prover/crates/prover/src/input/plain.rs` line 101 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/274#-OFQrhZ85hGZcK2OcuR8:-OFR34Ig-PDrCcZm7hnT:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/aaabc3a493835e6c0ae64dfd42eea28f4231f636/stwo_cairo_prover/crates/prover/src/input/plain.rs#L101)):*
> ```XML
>         dev_mode,
>     );
>     cairo_input.unwrap()
> ```

Done.

**Comment by ohad-starkware** [comment]
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 31 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/274#-OFLAJwb0VK2IfWm7Dcz:-OFR8UmU3i-ayVjtBpIQ:b-v4zg1p) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3379f9ad4c9e62dcb094478e71b9be66be055a3f/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L31)):*
<details><summary><i>Previously, Stavbe wrote…</i></summary><blockquote>

That's what Yuval taught me
</blockquote></details>

ok your crate your choice

**Review by ohad-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/274#-:-OFR8YS0ABnSrfULrufn:bnfp4nl)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7, @Stavbe, and @yuvalsw)

**Pull request merged**
