### PR TITLE
Add last 2 bit value constraint.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/74)

### CODE REVIEW

**Comment by alonh5** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/74?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#74** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/74?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#71** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/71?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#70** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/70?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#65** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/65?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#64** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/64?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alonh5 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Alon-Ti — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/74)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_builtin/prover.rs` line 126 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/74#-O5lubuM8wCeqMRgOHhO:-O5lubuM8wCeqMRgOHhP:bw320q7) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c37771f3df6fc246fe24b3159f2cf6b9dbc0f474/stwo_cairo_prover/crates/prover/src/components/range_check_builtin/prover.rs#L126)):*
> ```XML
>         }
>         let last_value_felt = split_values[N_VALUES_FELTS - 1];
>         trace[N_VALUES_FELTS + 1].data[vec_row] = last_value_felt
> ```

Consider splitting the values early, you can save a mul here:
`tmp = v(v-1)(v-2); tmp(v-3) = 0` => `tmp = v(v-1); tmp(v-2)(v-3) = 0`

Then you only have to write `v(v-1)` here.

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/74)* status: all files reviewed, 1 unresolved discussion (waiting on @Alon-Ti, @shaharsamocha7, and @spapinistarkware)

___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_builtin/prover.rs` line 126 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/74#-O5lubuM8wCeqMRgOHhO:-O5mQXpo5RblMVkadQZa:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c37771f3df6fc246fe24b3159f2cf6b9dbc0f474/stwo_cairo_prover/crates/prover/src/components/range_check_builtin/prover.rs#L126)):*
<details><summary><i>Previously, Alon-Ti wrote…</i></summary><blockquote>

Consider splitting the values early, you can save a mul here:
`tmp = v(v-1)(v-2); tmp(v-3) = 0` => `tmp = v(v-1); tmp(v-2)(v-3) = 0`

Then you only have to write `v(v-1)` here.
</blockquote></details>

Done.

**Review by shaharsamocha7 — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/74)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @Alon-Ti, @alonh5, and @spapinistarkware)

___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_builtin/component.rs` line 84 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/74#-O5msB_JAwgfy8eAs6SD:-O5msB_JAwgfy8eAs6SE:blir48b) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ab9b2fe422bfd0b54cb42b29de3007a07d9a2685/stwo_cairo_prover/crates/prover/src/components/range_check_builtin/component.rs#L84)):*
> ```XML
>         // Add constraints for the last 2 bit value.
>         let last_value_felt = values[N_ADDRESS_FELTS + N_VALUES_FELTS - 1];
>         let tmp_value = eval.next_trace_mask();
> ```

Consider to give a more meaningful name



_Code quote:_
```XML
let tmp_value = eval.next_trace_mask();
```
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_builtin/prover.rs` line 107 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/74#-O5mseKB9EG3fgY7I__m:-O5mseKB9EG3fgY7I__n:b-hgvmpl) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ab9b2fe422bfd0b54cb42b29de3007a07d9a2685/stwo_cairo_prover/crates/prover/src/components/range_check_builtin/prover.rs#L107)):*
> ```XML
>     let log_size = inputs.len().ilog2() + LOG_N_LANES;
>     let mut interaction_prover = RangeCheckBuiltinInteractionProver::with_capacity(inputs.len());
>     let mut trace = (0..N_ADDRESS_FELTS + N_VALUES_FELTS + 1)
> ```

Can you document or make a constant for this +1?



_Code quote:_
```XML
 + 1
```

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/74)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @Alon-Ti, @alonh5, and @spapinistarkware)

___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_builtin/prover.rs` line 251 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/74#-O5msyS78be9Z_AwgIjs:-O5msyS78be9Z_AwgIjt:b-i273yi) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ab9b2fe422bfd0b54cb42b29de3007a07d9a2685/stwo_cairo_prover/crates/prover/src/components/range_check_builtin/prover.rs#L251)):*
> ```XML
>             let last_value_felts = trace[N_ADDRESS_FELTS + N_VALUES_FELTS - 1].values.clone();
>             let tmp_values = trace[N_ADDRESS_FELTS + N_VALUES_FELTS].values.clone();
>             for (last_value_felt, tmp_value) in zip_eq(last_value_felts.data, tmp_values.data) {
> ```

Add an assert that the `last_value_felt` is in [0,1,2,3]

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/74)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @Alon-Ti, @shaharsamocha7, and @spapinistarkware)

___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_builtin/prover.rs` line 251 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/74#-O5msyS78be9Z_AwgIjs:-O5muIQSDGmAFJTBA8h-:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ab9b2fe422bfd0b54cb42b29de3007a07d9a2685/stwo_cairo_prover/crates/prover/src/components/range_check_builtin/prover.rs#L251)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Add an assert that the `last_value_felt` is in [0,1,2,3]
</blockquote></details>

Done.

**Review by Alon-Ti — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/74)* status: all files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7 and @spapinistarkware)

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r3, 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/74#-:-O5wZbhNAPjXErKT4k6E:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Comment by alonh5** [comment]
### Merge activity

* **Sep 4, 6:39 AM EDT**: @alonh5 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/74).

**Pull request merged**
