### PR TITLE
call

### PR DESCRIPTION
**Pull request by ohad-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/222)

### CODE REVIEW

**Comment by ohad-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/222?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#222** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/222?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/222?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#221** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/221?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#220** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/220?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#219** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/219?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#218** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/218?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#217** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/217?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#216** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/216?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#215** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/215?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#214** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/214?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#209** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/209?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#208** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/208?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#207** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/207?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#206** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/206?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 14 files at r1, 1 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/222)* status: 2 of 14 files reviewed, 4 unresolved discussions (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/air.rs` line 207 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/222#-OD_yTSUEu3EbnZz6JmZ:-OD_yTSUEu3EbnZz6Jm_:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/63b235839f4972031c0e8c8d2326ed479e1d4667/stwo_cairo_prover/crates/prover/src/cairo_air/air.rs#L207)):*
> ```XML
>         tree_builder: &mut TreeBuilder<'_, '_, SimdBackend, Blake2sMerkleChannel>,
>     ) -> (CairoClaim, CairoInteractionClaimGenerator) {
>         let _span = span!(Level::INFO, "opcodes_trace").entered();
> ```





_Suggestion:_
```XML
let span = span!(Level::INFO, "write opcode traces").entered();
```
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/air.rs` line 217 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/222#-OD_yaEG6r1_mPNVOamU:-OD_yaEG6r1_mPNVOamV:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/63b235839f4972031c0e8c8d2326ed479e1d4667/stwo_cairo_prover/crates/prover/src/cairo_air/air.rs#L217)):*
> ```XML
>         );
>         _span.exit();
>         let _span = span!(Level::INFO, "other trace").entered();
> ```





_Suggestion:_
```XML
let span = span!(Level::INFO, "write internal component traces").entered();
```
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/opcodes_air.rs` line 286 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/222#-OD_ytHK-39YI5VkP2Gr:-OD_ytHK-39YI5VkP2Gs:b-a8d21i) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/63b235839f4972031c0e8c8d2326ed479e1d4667/stwo_cairo_prover/crates/prover/src/cairo_air/opcodes_air.rs#L286)):*
> ```XML
>                 input.casm_states_by_opcode.generic_opcode,
>             ));
>         }
> ```

move this below the call* generators



_Code quote:_
```XML
        if !input.casm_states_by_opcode.generic_opcode.is_empty() {
            generic.push(generic_opcode::ClaimGenerator::new(
                input.casm_states_by_opcode.generic_opcode,
            ));
        }
```
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs` line 53 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/222#-OD_yFhb1u2SOKCxeuPz:-OD_yFhb1u2SOKCxeuQ-:b-mugzw2) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/63b235839f4972031c0e8c8d2326ed479e1d4667/stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs#L53)):*
> ```XML
>     // Base trace.
>     let mut tree_builder = commitment_scheme.tree_builder();
>     let _span = span!(Level::INFO, "Base trace").entered();
> ```

you also want to exit no?
Otherwise it is ended only at the function exits



_Code quote:_
```XML
let _span = span!(Level::INFO, "Base trace").entered();
```

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/222)* status: 2 of 14 files reviewed, 4 unresolved discussions (waiting on @ohad-starkware and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs` line 53 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/222#-OD_yFhb1u2SOKCxeuPz:-ODaFeUS3BxvxxbKhqY9:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/63b235839f4972031c0e8c8d2326ed479e1d4667/stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs#L53)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

you also want to exit no?
Otherwise it is ended only at the function exits
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/opcodes_air.rs` line 286 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/222#-OD_ytHK-39YI5VkP2Gr:-ODaFneeCooIMX4ewou1:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/63b235839f4972031c0e8c8d2326ed479e1d4667/stwo_cairo_prover/crates/prover/src/cairo_air/opcodes_air.rs#L286)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

move this below the call* generators
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/air.rs` line 207 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/222#-OD_yTSUEu3EbnZz6JmZ:-ODaFe-v3CJmJjhgz6_c:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/63b235839f4972031c0e8c8d2326ed479e1d4667/stwo_cairo_prover/crates/prover/src/cairo_air/air.rs#L207)):*
> ```XML
>         tree_builder: &mut TreeBuilder<'_, '_, SimdBackend, Blake2sMerkleChannel>,
>     ) -> (CairoClaim, CairoInteractionClaimGenerator) {
>         let _span = span!(Level::INFO, "opcodes_trace").entered();
> ```

Done.
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/air.rs` line 217 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/222#-OD_yaEG6r1_mPNVOamU:-ODa8S5vEv1nLMMuCxcK:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/63b235839f4972031c0e8c8d2326ed479e1d4667/stwo_cairo_prover/crates/prover/src/cairo_air/air.rs#L217)):*
> ```XML
>         );
>         _span.exit();
>         let _span = span!(Level::INFO, "other trace").entered();
> ```

Done.

**Review by shaharsamocha7 — COMMENTED** [review]
> Reviewed 3 of 14 files at r1, 9 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/222)* status: 11 of 14 files reviewed, 4 unresolved discussions (waiting on @ohad-starkware)

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm: one small comment

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/222#-:-ODaabVOD-aAXjynkojk:b-e78ltv)* status: 11 of 14 files reviewed, all discussions resolved (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/air.rs` line 207 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/222#-OD_yTSUEu3EbnZz6JmZ:-ODaaUzE1g6vhUDQn9G4:b5nbccy) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/63b235839f4972031c0e8c8d2326ed479e1d4667/stwo_cairo_prover/crates/prover/src/cairo_air/air.rs#L207)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

you didn't change to "write opcode traces"

**Comment by ohad-starkware** [comment]
### Merge activity

* **Dec 8, 10:20 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/222).

**Pull request merged**
