### PR TITLE
verify and ret

### PR DESCRIPTION
**Pull request by ohad-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/166)

### CODE REVIEW

**Comment by ohad-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/166?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#166** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/166?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#165** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/165?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#161** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/161?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#160** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/160?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ohad-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/166)* status: all files reviewed, 6 unresolved discussions (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/components/ret_opcode/prover.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/166#-OBdiS-I-kVrY4C0rD1J:-OBdiS-I-kVrY4C0rD1K:b-9ydyk6) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/795783363af10dd6c7e3fbf6ddec3441dfc404b4/stwo_cairo_prover/crates/prover/src/components/ret_opcode/prover.rs#L39)):*
> ```XML
>         let cpu_inputs = cpu_inputs
>             .into_iter()
>             .map(|VmState { pc, ap, fp }| CasmState {
> ```

This should be rename to VmState



_Code quote:_
```XML
CasmState
```
___
*[`stwo_cairo_prover/crates/prover/src/components/ret_opcode/prover.rs` line 278 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/166#-OBdilMC8HgD1N3o4bN-:-OBdilMDD6lovsEiYH34:bpvh5lm) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/795783363af10dd6c7e3fbf6ddec3441dfc404b4/stwo_cairo_prover/crates/prover/src/components/ret_opcode/prover.rs#L278)):*
> ```XML
>                 M31_0,
>                 M31_0,
>                 M31_0,
> ```

I thought we got rid of those



_Code quote:_
```XML
                M31_0,
                M31_0,
                M31_0,
                M31_0,
                M31_0,
                M31_0,
                M31_0,
                M31_0,
                M31_0,
                M31_0,
                M31_0,
                M31_0,
                M31_0,
                M31_0,
                M31_0,
                M31_0,
                M31_0,
                M31_0,
                M31_0,
                M31_0,
                M31_0,
                M31_0,
                M31_0,
                M31_0,
                M31_0,
```
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs` line 346 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/166#-OBdh3V4Cx_gAnn0MYnN:-OBdh3V4Cx_gAnn0MYnO:bxj8apq) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/795783363af10dd6c7e3fbf6ddec3441dfc404b4/stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs#L346)):*
> ```XML
>         memory_id_to_value_trace_generator
>             .write_trace(&mut tree_builder, &mut range_check_9_9_trace_generator);
>     let (vi_claim, verify_instruction_interaction_generator) = verify_instruction_trace_generator
> ```

maybe we want to shorten all the names, but let's be consistent for now and rethink in the future.



_Suggestion:_
```XML
verify_instruction_claim
```
___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/166#-OBdhXmfBwYfMqhpy35z:-OBdhXmfBwYfMqhpy36-:bf28dam) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/795783363af10dd6c7e3fbf6ddec3441dfc404b4/stwo_cairo_prover/crates/prover/src/components/mod.rs#L11)):*
> ```XML
> pub mod verifyinstruction;
> 
> pub fn pack_values<T: Pack>(values: &[T]) -> Vec<T::SimdType> {
> ```

Is this Pack trait new?
Are we going to implement it for every type?
I wonder if this function should be near the trait declaration itself



_Code quote:_
```XML
pub fn pack_values<T: Pack>(values: &[T]) -> Vec<T::SimdType> {
```
___
*[`stwo_cairo_prover/crates/prover/src/components/ret_opcode/component.rs` line 75 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/166#-OBdiJ-S8jS1q84sVolt:-OBdiJ-S8jS1q84sVolu:b-xgsw49) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/795783363af10dd6c7e3fbf6ddec3441dfc404b4/stwo_cairo_prover/crates/prover/src/components/ret_opcode/component.rs#L75)):*
> ```XML
> impl InteractionClaim {
>     pub fn mix_into(&self, channel: &mut impl Channel) {
>         // TODO(Ohad): mix claimed_sum.
> ```

Can't you implement this TODO now?



_Code quote:_
```XML
// TODO(Ohad): mix claimed_sum.
```
___
*[`stwo_cairo_prover/crates/prover/src/components/opcodes/mod.rs` line 3 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/166#-OBdhl2x6M0Ee6mYYtI1:-OBdhl2x6M0Ee6mYYtI2:b-zgxfee) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/795783363af10dd6c7e3fbf6ddec3441dfc404b4/stwo_cairo_prover/crates/prover/src/components/opcodes/mod.rs#L3)):*
> ```XML
> use stwo_prover::constraint_framework::logup::LookupElements;
> 
> pub type RelationElements = LookupElements<3>;
> ```

Add a comment that this refers to the VmState? 
Actually, why the VmState isn't defined here?



_Suggestion:_
```XML
pub type VmRelationElements = LookupElements<3>;
```

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/166)* status: all files reviewed, 6 unresolved discussions (waiting on @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs` line 346 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/166#-OBdh3V4Cx_gAnn0MYnN:-OBe2UHE3vVSvaFAV80v:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/795783363af10dd6c7e3fbf6ddec3441dfc404b4/stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs#L346)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

maybe we want to shorten all the names, but let's be consistent for now and rethink in the future.
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/166#-OBdhXmfBwYfMqhpy35z:-OBdzbd06V96NgzYB-NX:bu5zf9r) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/795783363af10dd6c7e3fbf6ddec3441dfc404b4/stwo_cairo_prover/crates/prover/src/components/mod.rs#L11)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Is this Pack trait new?
Are we going to implement it for every type?
I wonder if this function should be near the trait declaration itself
</blockquote></details>

it's a trait in stwo, already implemented recursively for every type that is M31- based (arrays, tupples, array of tupples etc.).
do you think the function also belongs in two? I'm not sure, using this as a utility here. 
___
*[`stwo_cairo_prover/crates/prover/src/components/opcodes/mod.rs` line 3 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/166#-OBdhl2x6M0Ee6mYYtI1:-OBe-6ku7YjE3duVqHBg:b-rmkuoa) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/795783363af10dd6c7e3fbf6ddec3441dfc404b4/stwo_cairo_prover/crates/prover/src/components/opcodes/mod.rs#L3)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Add a comment that this refers to the VmState? 
Actually, why the VmState isn't defined here?
</blockquote></details>

CasmState - defined by the air team as a prover type,
we should kill papini's vmstate and rename CasmState to VmState, but that would take coordinating with the air team
 
___
*[`stwo_cairo_prover/crates/prover/src/components/ret_opcode/component.rs` line 75 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/166#-OBdiJ-S8jS1q84sVolt:-OBe1yuWCr0ffTrzojNW:bb7f2mf) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/795783363af10dd6c7e3fbf6ddec3441dfc404b4/stwo_cairo_prover/crates/prover/src/components/ret_opcode/component.rs#L75)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can't you implement this TODO now?
</blockquote></details>

done
___
*[`stwo_cairo_prover/crates/prover/src/components/ret_opcode/prover.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/166#-OBdiS-I-kVrY4C0rD1J:-OBe-qxs2lra-KgjvyBG:b-j5e57o) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/795783363af10dd6c7e3fbf6ddec3441dfc404b4/stwo_cairo_prover/crates/prover/src/components/ret_opcode/prover.rs#L39)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

This should be rename to VmState
</blockquote></details>

same answer as above
___
*[`stwo_cairo_prover/crates/prover/src/components/ret_opcode/prover.rs` line 278 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/166#-OBdilMC8HgD1N3o4bN-:-OBe-xjw2iIVpAGYQmEv:b-i4nmch) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/795783363af10dd6c7e3fbf6ddec3441dfc404b4/stwo_cairo_prover/crates/prover/src/components/ret_opcode/prover.rs#L278)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I thought we got rid of those
</blockquote></details>

in constraints yes
trace_gen is a bit more tricky, because I'm generating the struct appropriately, and it would mean inlining the arrays in lookup_data
here there's only one call to verify so should be okay, changed manually.

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/166)* status: 7 of 13 files reviewed, 6 unresolved discussions (waiting on @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/components/ret_opcode/prover.rs` line 278 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/166#-OBdilMC8HgD1N3o4bN-:-OBe3P0v-mWRxbZLm2BO:bdb87t1) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/795783363af10dd6c7e3fbf6ddec3441dfc404b4/stwo_cairo_prover/crates/prover/src/components/ret_opcode/prover.rs#L278)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

in constraints yes
trace_gen is a bit more tricky, because I'm generating the struct appropriately, and it would mean inlining the arrays in lookup_data
here there's only one call to verify so should be okay, changed manually.
</blockquote></details>

onecall to memory**

**Review by shaharsamocha7 — APPROVED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/166)* status: all files reviewed, 3 unresolved discussions (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/166#-OBdhXmfBwYfMqhpy35z:-OBeEBKw16U07H3HTCWb:b-n3q9ng) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/795783363af10dd6c7e3fbf6ddec3441dfc404b4/stwo_cairo_prover/crates/prover/src/components/mod.rs#L11)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

it's a trait in stwo, already implemented recursively for every type that is M31- based (arrays, tupples, array of tupples etc.).
do you think the function also belongs in two? I'm not sure, using this as a utility here.
</blockquote></details>

I think this function should be near the trait.
Not sure any of those belong to Stwo TBH
___
*[`stwo_cairo_prover/crates/prover/src/components/opcodes/mod.rs` line 3 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/166#-OBdhl2x6M0Ee6mYYtI1:-OBeETac63d7VP1Jvy5T:buwnprg) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/795783363af10dd6c7e3fbf6ddec3441dfc404b4/stwo_cairo_prover/crates/prover/src/components/opcodes/mod.rs#L3)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

CasmState - defined by the air team as a prover type,
we should kill papini's vmstate and rename CasmState to VmState, but that would take coordinating with the air team
</blockquote></details>

ok, let's send them a message about that
___
*[`stwo_cairo_prover/crates/prover/src/components/verifyinstruction/component.rs` line 93 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/166#-OBeEr0UBaLTb7dEZcrM:-OBeEr0UBaLTb7dEZcrN:btzxp2a) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3890805ecec30d5d93e3b5c51433c559564ec2aa/stwo_cairo_prover/crates/prover/src/components/verifyinstruction/component.rs#L93)):*
> ```XML
> pub struct InteractionClaim {
>     pub total_sum: SecureField,
>     pub claimed_sum: Option<ClaimedPrefixSum>,
> ```

AlonT pr has new type names LogupSums
`pub type LogupSums = (SecureField, Option<ClaimedPrefixSum>);`

We should consider to integrate with that, not for this pr



_Code quote:_
```XML
    pub total_sum: SecureField,
    pub claimed_sum: Option<ClaimedPrefixSum>,
```

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/166)* status: all files reviewed, 4 unresolved discussions (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/components/verifyinstruction/prover.rs` line 310 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/166#-OBeI6CU2nFGZcCUkmeI:-OBeI6CU2nFGZcCUkmeJ:b-pt5bbn) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/795783363af10dd6c7e3fbf6ddec3441dfc404b4/stwo_cairo_prover/crates/prover/src/components/verifyinstruction/prover.rs#L310)):*
> ```XML
>                 M31_0,
>                 M31_0,
>                 M31_0,
> ```

I don't think we want to do this manual changes.
We will probably generate those files again, so we want to track the changes



_Code quote:_
```XML
                    + ((input_col18) * (M31_256))),
                M31_0,
                M31_0,
                M31_0,
                M31_0,
                M31_0,
                M31_0,
                M31_0,
                M31_0,
                M31_0,
                M31_0,
                M31_0,
                M31_0,
                M31_0,
                M31_0,
                M31_0,
                M31_0,
                M31_0,
                M31_0,
                M31_0,
                M31_0,
                M31_0,
```

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/166)* status: 12 of 13 files reviewed, 4 unresolved discussions (waiting on @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/166#-OBdhXmfBwYfMqhpy35z:-OBeKkupDfAW8BTMpnd_:b-e1n121) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/795783363af10dd6c7e3fbf6ddec3441dfc404b4/stwo_cairo_prover/crates/prover/src/components/mod.rs#L11)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I think this function should be near the trait.
Not sure any of those belong to Stwo TBH
</blockquote></details>

they both belong in "stwo_air_utils", but it doesn't exist
___
*[`stwo_cairo_prover/crates/prover/src/components/opcodes/mod.rs` line 3 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/166#-OBdhl2x6M0Ee6mYYtI1:-OBeTQYUD2wVYPbR4gE_:bb7og0t) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/795783363af10dd6c7e3fbf6ddec3441dfc404b4/stwo_cairo_prover/crates/prover/src/components/opcodes/mod.rs#L3)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

ok, let's send them a message about that
</blockquote></details>

sent
___
*[`stwo_cairo_prover/crates/prover/src/components/verifyinstruction/component.rs` line 93 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/166#-OBeEr0UBaLTb7dEZcrM:-OBeTPBy3SdBbRiCvC1H:b-6prmam) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3890805ecec30d5d93e3b5c51433c559564ec2aa/stwo_cairo_prover/crates/prover/src/components/verifyinstruction/component.rs#L93)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

AlonT pr has new type names LogupSums
`pub type LogupSums = (SecureField, Option<ClaimedPrefixSum>);`

We should consider to integrate with that, not for this pr
</blockquote></details>

will consider
___
*[`stwo_cairo_prover/crates/prover/src/components/verifyinstruction/prover.rs` line 310 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/166#-OBeI6CU2nFGZcCUkmeI:-OBeajqd8Yki556nBizT:bvth56w) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/795783363af10dd6c7e3fbf6ddec3441dfc404b4/stwo_cairo_prover/crates/prover/src/components/verifyinstruction/prover.rs#L310)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I don't think we want to do this manual changes.
We will probably generate those files again, so we want to track the changes
</blockquote></details>

reverted

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/166#-:-OBeqv4i0d7CXqXkgaQn:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/166#-OBdhXmfBwYfMqhpy35z:-OBeqTbS6mMrolcn9G3j:b-gmz058) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/795783363af10dd6c7e3fbf6ddec3441dfc404b4/stwo_cairo_prover/crates/prover/src/components/mod.rs#L11)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

they both belong in "stwo_air_utils", but it doesn't exist
</blockquote></details>

so, TODO?

**Comment by ohad-starkware** [comment]
### Merge activity

* **Nov 14, 8:43 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/166).

**Pull request merged**
