### PR TITLE
Move split to utils file.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/62)

### CODE REVIEW

**Comment by alonh5** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/62?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#62** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/62?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#61** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/61?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alonh5 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/62#-:-O4nepdw36a3fQ8sZH6t:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`stwo_cairo_prover/crates/prover/src/lib.rs` line 6 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/62#-O4nejwF1Y2Y6DYIGMe9:-O4nejwF1Y2Y6DYIGMeA:b-j7uofb) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/a53b585199812bc776cf39afbbd48bc016fdd561/stwo_cairo_prover/crates/prover/src/lib.rs#L6)):*
> ```XML
> pub mod input;
> pub mod prover_types;
> pub mod utils;
> ```

utils is a bit generic, don't you think? Consider renaming to `felt`.

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/62)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`stwo_cairo_prover/crates/prover/src/lib.rs` line 6 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/62#-O4nejwF1Y2Y6DYIGMe9:-O4nmL6I5lRHerosRZwX:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/a53b585199812bc776cf39afbbd48bc016fdd561/stwo_cairo_prover/crates/prover/src/lib.rs#L6)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

utils is a bit generic, don't you think? Consider renaming to `felt`.
</blockquote></details>

Done.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 5 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/62#-:-O4oSQhM0CjXsUdi5ixA:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Comment by alonh5** [comment]
### Merge activity

* **Aug 21, 6:24 AM EDT**: @alonh5 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/62).

**Pull request merged**
