### PR TITLE
Reorganize decommitted values in the proof.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/201)

### CODE REVIEW

**Comment by andrewmilson** [comment]
*[`stwo_cairo_verifier/src/fri.cairo` line 474 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/201#-OD2KXZk31iZLp-piNqL:-OD2KXZk31iZLp-piNqM:b45h) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/18462687a39e7919f9abbbfa2417c4a0fbe6446d/stwo_cairo_verifier/src/fri.cairo#L474)):*
> ```Cairo
>         }
> 
>         let mut decommitmented_value = array![];
> ```





_Suggestion:_
```Cairo
decommitmented_values
```

**Review by andrewmilson — COMMENTED** [review]
> Reviewed 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/201)* status: 1 of 6 files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`stwo_cairo_verifier/src/pcs/quotients.cairo` line 134 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/201#-OD2LNX6Dnt5Q7yIthFo:-OD2LNX6Dnt5Q7yIthFp:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/18462687a39e7919f9abbbfa2417c4a0fbe6446d/stwo_cairo_verifier/src/pcs/quotients.cairo#L134)):*
> ```Cairo
>         };
> 
>         let mut n_columns_per_log_size: Array::<usize> = array![];
> ```





_Suggestion:_
```Cairo
let mut n_columns_per_log_size = array![];
```
___
*[`stwo_cairo_verifier/src/pcs/quotients.cairo` line 140 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/201#-OD2LrN-DeDrMVwjnR9E:-OD2LrN-DeDrMVwjnR9F:buzpj1o) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/18462687a39e7919f9abbbfa2417c4a0fbe6446d/stwo_cairo_verifier/src/pcs/quotients.cairo#L140)):*
> ```Cairo
>                 .try_into()
>                 .unwrap();
>         };
> ```

Does Cairo support `..=` ranges?
Can we add a constant for MAX_LOG_SIZE?



_Suggestion:_
```Cairo
        for log_size in (0..=MAX_LOG_SIZE) {
            // Insert in descending order.
            n_columns_per_log_size
                .append(res_dict.get(MAX_LOG_SIZE - log_size.into()).deref_or(0))
                .try_into()
                .unwrap();
        };
```
___
*[`stwo_cairo_verifier/src/pcs/quotients.cairo` line 184 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/201#-OD2MsUJ2nkgsnYkJMGB:-OD2MsUJ2nkgsnYkJMGC:bo09gy9) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/18462687a39e7919f9abbbfa2417c4a0fbe6446d/stwo_cairo_verifier/src/pcs/quotients.cairo#L184)):*
> ```Cairo
>     let mut n_colums0 = n_columns_per_interaction.pop_front().unwrap().span();
>     let mut n_colums1 = n_columns_per_interaction.pop_front().unwrap().span();
>     let mut n_colums2 = n_columns_per_interaction.pop_front().unwrap().span();
> ```

Doesn't this break if there are more than 2 interactions?



_Code quote:_
```Cairo
    let mut n_colums0 = n_columns_per_interaction.pop_front().unwrap().span();
    let mut n_colums1 = n_columns_per_interaction.pop_front().unwrap().span();
    let mut n_colums2 = n_columns_per_interaction.pop_front().unwrap().span();
```
___
*[`stwo_cairo_verifier/tests/verifier/proofs/horizontal_fib_128_column_with_blowup_2.cairo` line 1 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/201#-OD2N5OPCx2EOTpdE2HG:-OD2N5OQ59EUaJtNy03p:b4dde8u) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/18462687a39e7919f9abbbfa2417c4a0fbe6446d/stwo_cairo_verifier/tests/verifier/proofs/horizontal_fib_128_column_with_blowup_2.cairo#L1)):*
> ```Cairo
> use stwo_cairo_verifier::verifier::StarkProof;
> ```

It's a shame the Cairo formatter in VScode ignores .cairofmtignore.
I think having the proof on one line makes the compiler faster and also doesn't muck up github stats

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/201)* status: 1 of 6 files reviewed, 6 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`stwo_cairo_verifier/src/pcs/quotients.cairo` line 182 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/201#-OD2O841BnhfhEPQWnWY:-OD2O841BnhfhEPQWnWZ:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/18462687a39e7919f9abbbfa2417c4a0fbe6446d/stwo_cairo_verifier/src/pcs/quotients.cairo#L182)):*
> ```Cairo
>     let mut log_size = M31_CIRCLE_LOG_ORDER;
> 
>     let mut n_colums0 = n_columns_per_interaction.pop_front().unwrap().span();
> ```





_Suggestion:_
```Cairo
columns
```

**Comment by ilyalesokhin-starkware** [comment]
*[`stwo_cairo_verifier/src/pcs/quotients.cairo` line 140 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/201#-OD2LrN-DeDrMVwjnR9E:-OD5QgyX0S9L1BaV6PaY:bave0s3) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/18462687a39e7919f9abbbfa2417c4a0fbe6446d/stwo_cairo_verifier/src/pcs/quotients.cairo#L140)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

They are of different types.
</blockquote></details>

also it seems that we don't support that syntax for ranges

**Comment by ilyalesokhin-starkware** [comment]
*[`stwo_cairo_verifier/src/pcs/quotients.cairo` line 184 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/201#-OD2MsUJ2nkgsnYkJMGB:-OD5QvOE3c8NOfhpu14K:b-v169bx) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/18462687a39e7919f9abbbfa2417c4a0fbe6446d/stwo_cairo_verifier/src/pcs/quotients.cairo#L184)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Doesn't this break if there are more than 2 interactions?
</blockquote></details>

it does, do we expect AIRs with more interactions?

**Comment by ilyalesokhin-starkware** [comment]
*[`stwo_cairo_verifier/tests/verifier/proofs/horizontal_fib_128_column_with_blowup_2.cairo` line 1 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/201#-OD2N5OPCx2EOTpdE2HG:-OD5RYd5-Wg33wl-NEyT:bogphhz) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/18462687a39e7919f9abbbfa2417c4a0fbe6446d/stwo_cairo_verifier/tests/verifier/proofs/horizontal_fib_128_column_with_blowup_2.cairo#L1)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

It's a shame the Cairo formatter in VScode ignores .cairofmtignore.
I think having the proof on one line makes the compiler faster and also doesn't muck up github stats
</blockquote></details>

How much faster is it?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/201)* status: 1 of 6 files reviewed, 6 unresolved discussions (waiting on @andrewmilson)

___
*[`stwo_cairo_verifier/src/pcs/quotients.cairo` line 182 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/201#-OD2O841BnhfhEPQWnWY:-OD5RAS05qT-HvmRGL8Y:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/18462687a39e7919f9abbbfa2417c4a0fbe6446d/stwo_cairo_verifier/src/pcs/quotients.cairo#L182)):*
> ```Cairo
>     let mut log_size = M31_CIRCLE_LOG_ORDER;
> 
>     let mut n_colums0 = n_columns_per_interaction.pop_front().unwrap().span();
> ```

Done.
___
*[`stwo_cairo_verifier/src/fri.cairo` line 474 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/201#-OD2KXZk31iZLp-piNqL:-OD5PmyJ7iUuUm9hZiPr:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/18462687a39e7919f9abbbfa2417c4a0fbe6446d/stwo_cairo_verifier/src/fri.cairo#L474)):*
> ```Cairo
>         }
> 
>         let mut decommitmented_value = array![];
> ```

Done.

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/201)* status: 1 of 6 files reviewed, 6 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`stwo_cairo_verifier/src/pcs/quotients.cairo` line 184 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/201#-OD2MsUJ2nkgsnYkJMGB:-OD6atlD1gKpRlOz0EvX:b-npfyeo) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/18462687a39e7919f9abbbfa2417c4a0fbe6446d/stwo_cairo_verifier/src/pcs/quotients.cairo#L184)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

it does, do we expect AIRs with more interactions?
</blockquote></details>

Not sure but I don't think we assume this in any other places. Perhaps we can add an assert?

```assert!(n_columns_per_interaction.len() < 4);```
___
*[`stwo_cairo_verifier/tests/verifier/proofs/horizontal_fib_128_column_with_blowup_2.cairo` line 1 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/201#-OD2N5OPCx2EOTpdE2HG:-OD6bsTG-5yp7U59j1OU:b-ddlp5d) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/18462687a39e7919f9abbbfa2417c4a0fbe6446d/stwo_cairo_verifier/tests/verifier/proofs/horizontal_fib_128_column_with_blowup_2.cairo#L1)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

How much faster is it?
</blockquote></details>

Can't exactly remember. Maybe 2x. Non blocker though. 
Thanks for the message in Slack!
___
*[`stwo_cairo_verifier/src/vcs/verifier.cairo` line 320 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/201#-OD6bqFY4vfJR0s71Swl:-OD6bqFY4vfJR0s71Swm:ba3dfna) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/06f367b22316c5642ba44158272856f641cf11ca/stwo_cairo_verifier/src/vcs/verifier.cairo#L320)):*
> ```Cairo
>         queries_per_log_size.insert(4, NullableTrait::new(array![7, 11, 14].span()));
> 
>         //4    array![m31(720125469), m31(997644238), m31(194302184)],
> ```

Remove?
___
*[`stwo_cairo_verifier/src/pcs/quotients.cairo` line 560 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/201#-OD6cXXpC5ogYW8saz4e:-OD6cXXpC5ogYW8saz4f:b-cfvtd8) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/06f367b22316c5642ba44158272856f641cf11ca/stwo_cairo_verifier/src/pcs/quotients.cairo#L560)):*
> ```Cairo
>     //     let col0_log_size = @array![5];
>     //     let col1_log_size = @array![7];
>     //     let log_size_per_column = array![col0_log_size, col1_log_size];
> ```

Is the idea to uncomment these once all merkle PRs are in?



_Code quote:_
```Cairo
    // #[test]
    // fn test_fri_answers() {
    //     let col0_log_size = @array![5];
    //     let col1_log_size = @array![7];
    //     let log_size_per_column = array![col0_log_size, col1_log_size];
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/201)* status: 1 of 60 files reviewed, 6 unresolved discussions (waiting on @andrewmilson)

___
*[`stwo_cairo_verifier/src/pcs/quotients.cairo` line 184 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/201#-OD2MsUJ2nkgsnYkJMGB:-OD6tDDw6u8hMzhSUQn0:b-nht8bk) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/18462687a39e7919f9abbbfa2417c4a0fbe6446d/stwo_cairo_verifier/src/pcs/quotients.cairo#L184)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Not sure but I don't think we assume this in any other places. Perhaps we can add an assert?

```assert!(n_columns_per_interaction.len() < 4);```
</blockquote></details>

Removed the limitation.

**Comment by ilyalesokhin-starkware** [comment]
*[`stwo_cairo_verifier/src/pcs/quotients.cairo` line 184 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/201#-OD2MsUJ2nkgsnYkJMGB:-OD72D-NEmj3c3PQvL3F:bb1uww5) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/18462687a39e7919f9abbbfa2417c4a0fbe6446d/stwo_cairo_verifier/src/pcs/quotients.cairo#L184)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Removed the limitation.
</blockquote></details>

nvm, added an assert

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/201)* status: 0 of 60 files reviewed, 6 unresolved discussions (waiting on @andrewmilson)

___
*[`stwo_cairo_verifier/src/pcs/quotients.cairo` line 560 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/201#-OD6cXXpC5ogYW8saz4e:-OD72C1C4NCRZUosSGku:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/06f367b22316c5642ba44158272856f641cf11ca/stwo_cairo_verifier/src/pcs/quotients.cairo#L560)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Is the idea to uncomment these once all merkle PRs are in?
</blockquote></details>

Done.
___
*[`stwo_cairo_verifier/src/vcs/verifier.cairo` line 320 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/201#-OD6bqFY4vfJR0s71Swl:-OD6xi2V1xGIerp2pWdb:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/06f367b22316c5642ba44158272856f641cf11ca/stwo_cairo_verifier/src/vcs/verifier.cairo#L320)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Remove?
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/201)* status: 0 of 60 files reviewed, 6 unresolved discussions (waiting on @andrewmilson)

___
*[`stwo_cairo_verifier/tests/verifier/proofs/horizontal_fib_128_column_with_blowup_2.cairo` line 1 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/201#-OD2N5OPCx2EOTpdE2HG:-OD72e0h1rt3UCkDL3rf:bxsz9c7) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/18462687a39e7919f9abbbfa2417c4a0fbe6446d/stwo_cairo_verifier/tests/verifier/proofs/horizontal_fib_128_column_with_blowup_2.cairo#L1)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Can't exactly remember. Maybe 2x. Non blocker though. 
Thanks for the message in Slack!
</blockquote></details>

we can use
#\[cairofmt::skip\]

**Review by andrewmilson — APPROVED** [review]
:lgtm: with comment

> Reviewed 1 of 56 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/201#-:-OD7JsnqEMhU9iMkmhG_:b10c0l0)* status: 1 of 60 files reviewed, 7 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`stwo_cairo_verifier/tests/verifier/proofs/horizontal_fib_128_column_with_blowup_2.cairo` line 1 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/201#-OD2N5OPCx2EOTpdE2HG:-OD7Jp42CNcusb-1aH5D:b-hxjyw2) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/18462687a39e7919f9abbbfa2417c4a0fbe6446d/stwo_cairo_verifier/tests/verifier/proofs/horizontal_fib_128_column_with_blowup_2.cairo#L1)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

we can use
#\[cairofmt::skip\]
</blockquote></details>

Awesome
___
*[`stwo_cairo_verifier/src/pcs/quotients.cairo` line 220 at r7](https://reviewable.io/reviews/starkware-libs/stwo-cairo/201#-OD7JeJLDqGF4P9DwMcP:-OD7JeJLDqGF4P9DwMcQ:b-9d881h) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e07792bc4c291f61749e3a80ff3e144facadfa67/stwo_cairo_verifier/src/pcs/quotients.cairo#L220)):*
> ```Cairo
> }
> 
> /// Takes n[i] elements from the i'th `tree` and returns them as a single array.
> ```

[...] is a docstring link



_Suggestion:_
```Cairo
`n[i]`
```

**Pull request merged**
