### PR TITLE
memory small table

### PR DESCRIPTION
**Pull request by ohad-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/165)

### CODE REVIEW

**Comment by ohad-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/165?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#165** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/165?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#161** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/161?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#160** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/160?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ohad-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/165)* status: 9 of 13 files reviewed, 10 unresolved discussions (waiting on @ohad-starkware and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/felt.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/165#-OBZskgq4-6qOxJBn4f_:-OB_rLwGAF6zWv_UBq8A:bcai2jb) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/b13cf942c428d062cc3ce35b9a57d50b96375aaf/stwo_cairo_prover/crates/prover/src/felt.rs#L56)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I think this const does not belong here
move to memory?
</blockquote></details>

not sure it fits there too, 
this is only for rangecheck-builtin purposes.
moved it to memory
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs` line 232 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/165#-OBZtCVYBfbhM6qCVNV1:-OB_raJV7kP-AsNj2jKb:bbyp9g2) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/b13cf942c428d062cc3ce35b9a57d50b96375aaf/stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs#L232)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

rename
</blockquote></details>

what's wrong with Cerebral palsy?
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/id_to_f252/component.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/165#-OB_-C705HrdWfCylDO6:-OB_rusT1-zL8Y96miio:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/b13cf942c428d062cc3ce35b9a57d50b96375aaf/stwo_cairo_prover/crates/prover/src/components/memory/id_to_f252/component.rs#L27)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

can you reorder those so we have 
BIG_*
SMALL_*
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/id_to_f252/component.rs` line 166 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/165#-OB__zOa2hZrMwz79t7z:-OB_s3ZM5IsJ-sJ7pfvb:b-p9poot) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/b13cf942c428d062cc3ce35b9a57d50b96375aaf/stwo_cairo_prover/crates/prover/src/components/memory/id_to_f252/component.rs#L166)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

div_ceil
</blockquote></details>

is it?
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/id_to_f252/component.rs` line 192 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/165#-OB_-kUG9FeuWJ9YpkB2:-OB_sFOV-0SfjI3WH3Zp:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/b13cf942c428d062cc3ce35b9a57d50b96375aaf/stwo_cairo_prover/crates/prover/src/components/memory/id_to_f252/component.rs#L192)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

to be consistent with Claim::mix_into
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/id_to_f252/prover.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/165#-OB_-zfY12YtxFdfy-A-:-OB_sITL2xPt8n6aeAMA:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/b13cf942c428d062cc3ce35b9a57d50b96375aaf/stwo_cairo_prover/crates/prover/src/components/memory/id_to_f252/prover.rs#L40)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I think you can remove this TODO
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/id_to_f252/prover.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/165#-OB_aBWV78FMidr4zoWn:-OB_snJE4P9UqblMw15V:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/b13cf942c428d062cc3ce35b9a57d50b96375aaf/stwo_cairo_prover/crates/prover/src/components/memory/id_to_f252/prover.rs#L52)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can you order it that way?
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/id_to_f252/prover.rs` line 225 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/165#-OB_azmn8mcqcw6ETGwA:-OB_zBSu1SSW7MD4MGzF:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/b13cf942c428d062cc3ce35b9a57d50b96375aaf/stwo_cairo_prover/crates/prover/src/components/memory/id_to_f252/prover.rs#L225)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/id_to_f252/prover.rs` line 307 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/165#-OB_b6Ul7qneuiq4rWkl:-OB_zLkd13ZRW3GrnDz0:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/b13cf942c428d062cc3ce35b9a57d50b96375aaf/stwo_cairo_prover/crates/prover/src/components/memory/id_to_f252/prover.rs#L307)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Also add a comment for big values in the top of the function
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/input/mem.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/165#-OB_bMT3-2Zu-LPLgFMP:-OB_zbnH310ibSM4OAle:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/b13cf942c428d062cc3ce35b9a57d50b96375aaf/stwo_cairo_prover/crates/prover/src/input/mem.rs#L30)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I think this should be removed
</blockquote></details>

Done.

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/165)* status: 5 of 13 files reviewed, 8 unresolved discussions (waiting on @ohad-starkware and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/components/memory/id_to_f252/component.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/165#-OB_-C705HrdWfCylDO6:-OBaHccbDgLOReIVVa4s:bb7f2mf) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/b13cf942c428d062cc3ce35b9a57d50b96375aaf/stwo_cairo_prover/crates/prover/src/components/memory/id_to_f252/component.rs#L27)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

didn't push?
</blockquote></details>

done

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/165)* status: 7 of 13 files reviewed, 1 unresolved discussion (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/components/memory/id_to_f252/component.rs` line 166 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/165#-OB__zOa2hZrMwz79t7z:-OBaIoZU7AltBvABhu6z:bfm9kyk) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/b13cf942c428d062cc3ce35b9a57d50b96375aaf/stwo_cairo_prover/crates/prover/src/components/memory/id_to_f252/component.rs#L166)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

is it?
</blockquote></details>

I think yes
`div_ceil(N_M31_IN_FELT252, 2) + 1

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/165)* status: 6 of 13 files reviewed, 1 unresolved discussion (waiting on @ohad-starkware and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/components/memory/id_to_f252/component.rs` line 166 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/165#-OB__zOa2hZrMwz79t7z:-OBdW9F70MnTGvREnyNW:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/b13cf942c428d062cc3ce35b9a57d50b96375aaf/stwo_cairo_prover/crates/prover/src/components/memory/id_to_f252/component.rs#L166)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I think yes
`div_ceil(N_M31_IN_FELT252, 2) + 1
</blockquote></details>

Done.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 13 files at r1, 4 of 6 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/165)* status: all files reviewed, 5 unresolved discussions (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/input/mem.rs` line 38 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/165#-OBdeaWr75CmhoXXxmpH:-OBdeaWr75CmhoXXxmpI:bf0ulde) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e1fc64b56539e333080dca8fd09386071c128ed6/stwo_cairo_prover/crates/prover/src/input/mem.rs#L38)):*
> ```XML
> impl MemConfig {
>     pub fn new(small_max: u128) -> MemConfig {
>         assert!(small_max <= 1 << (N_M31_IN_SMALL_FELT252 * N_BITS_PER_FELT));
> ```

you can't support 1 << 72



_Suggestion:_
```XML
assert!(small_max < (1 << (N_M31_IN_SMALL_FELT252 * N_BITS_PER_FELT)));
```
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/id_to_f252/prover.rs` line 111 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/165#-OBdd-8t6nqBLQxJWCcF:-OBdd-8t6nqBLQxJWCcG:b-mfknhw) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e1fc64b56539e333080dca8fd09386071c128ed6/stwo_cairo_prover/crates/prover/src/components/memory/id_to_f252/prover.rs#L111)):*
> ```XML
>         tree_builder: &mut TreeBuilder<'_, '_, SimdBackend, Blake2sMerkleChannel>,
>         range_check_9_9_trace_generator: &mut range_check_9_9::ClaimGenerator,
>     ) -> (Claim, InteractionClaimGenerator) {
> ```


maybe this function impl should handle  big_values, and than small_values
Only the extend_evals for the trace should be together at the end.



_Code quote:_
```XML
    pub fn write_trace(
        self,
        tree_builder: &mut TreeBuilder<'_, '_, SimdBackend, Blake2sMerkleChannel>,
        range_check_9_9_trace_generator: &mut range_check_9_9::ClaimGenerator,
    ) -> (Claim, InteractionClaimGenerator) {
```
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/id_to_f252/prover.rs` line 148 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/165#-OBddIZn7ZiefScPU1Mk:-OBddIZn7ZiefScPU1Ml:bf6ygc1) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e1fc64b56539e333080dca8fd09386071c128ed6/stwo_cairo_prover/crates/prover/src/components/memory/id_to_f252/prover.rs#L148)):*
> ```XML
>             big_trace[0].data[i] = unsafe {
>                 PackedM31::from_simd_unchecked(
>                     Simd::splat((i * N_LANES + 0x4000_0000) as u32) + inc,
> ```

This should be a constant in the component file, also you it for the input in mem.rs



_Code quote:_
```XML
0x4000_0000
```
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/id_to_f252/prover.rs` line 272 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/165#-OBde0vA9tOw6_j7RQY_:-OBde0vA9tOw6_j7RQYa:bny8xt) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e1fc64b56539e333080dca8fd09386071c128ed6/stwo_cairo_prover/crates/prover/src/components/memory/id_to_f252/prover.rs#L272)):*
> ```XML
>     ) -> InteractionClaim {
>         let log_size = self.big_ids_and_values[0].len().ilog2() + LOG_N_LANES;
>         let mut logup_gen = LogupTraceGenerator::new(log_size);
> ```

Consider to rename



_Suggestion:_
```XML
let mut big_values_logup = LogupTraceGenerator::new(log_size);
```
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/id_to_f252/prover.rs` line 284 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/165#-OBd_NXu1IDU6cTOMLBB:-OBd_NXu1IDU6cTOMLBC:b-a2nhbn) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e1fc64b56539e333080dca8fd09386071c128ed6/stwo_cairo_prover/crates/prover/src/components/memory/id_to_f252/prover.rs#L284)):*
> ```XML
>         col_gen.finalize_col();
> 
>         for (l, r) in self.big_ids_and_values[MEMORY_ID_SIZE..].iter().tuples() {
> ```

Add a comment that this uses range check9 for the values



_Code quote:_
```XML
for (l, r) in self.big_ids_and_values[MEMORY_ID_SIZE..].iter().tuples() {
```

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/165)* status: all files reviewed, 4 unresolved discussions (waiting on @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/components/memory/id_to_f252/prover.rs` line 111 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/165#-OBdd-8t6nqBLQxJWCcF:-OBdvpQ22XGgg3BYwZZ-:b-7hbpla) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e1fc64b56539e333080dca8fd09386071c128ed6/stwo_cairo_prover/crates/prover/src/components/memory/id_to_f252/prover.rs#L111)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

maybe this function impl should handle  big_values, and than small_values
Only the extend_evals for the trace should be together at the end.
</blockquote></details>

wdyt?
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/id_to_f252/prover.rs` line 148 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/165#-OBddIZn7ZiefScPU1Mk:-OBdwQ_35nH8f3FAK2St:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e1fc64b56539e333080dca8fd09386071c128ed6/stwo_cairo_prover/crates/prover/src/components/memory/id_to_f252/prover.rs#L148)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

This should be a constant in the component file, also you it for the input in mem.rs
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/id_to_f252/prover.rs` line 284 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/165#-OBd_NXu1IDU6cTOMLBB:-OBdygwp-7Go8p_2U-z7:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e1fc64b56539e333080dca8fd09386071c128ed6/stwo_cairo_prover/crates/prover/src/components/memory/id_to_f252/prover.rs#L284)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Add a comment that this uses range check9 for the values
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/input/mem.rs` line 38 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/165#-OBdeaWr75CmhoXXxmpH:-OBdyehN5sDoUiwkvAXi:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e1fc64b56539e333080dca8fd09386071c128ed6/stwo_cairo_prover/crates/prover/src/input/mem.rs#L38)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

you can't support 1 << 72
</blockquote></details>

Done.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/165#-:-OBeDzve2BHIn7sKdBck:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/components/memory/id_to_f252/prover.rs` line 111 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/165#-OBdd-8t6nqBLQxJWCcF:-OBeD_qY1YgzRNAIYPZq:btojbfd) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e1fc64b56539e333080dca8fd09386071c128ed6/stwo_cairo_prover/crates/prover/src/components/memory/id_to_f252/prover.rs#L111)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

wdyt?
</blockquote></details>

Great!
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/id_to_f252/prover.rs` line 272 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/165#-OBde0vA9tOw6_j7RQY_:-OBeDkX04Qci2dsHafT5:b-lwlxxz) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e1fc64b56539e333080dca8fd09386071c128ed6/stwo_cairo_prover/crates/prover/src/components/memory/id_to_f252/prover.rs#L272)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Consider to rename
</blockquote></details>

I thought you will also do make this change for the small_logup_gen :(
non-blocking

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/165)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/components/memory/id_to_f252/prover.rs` line 272 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/165#-OBde0vA9tOw6_j7RQY_:-OBeKIV17k-QAB28kdMw:btm5wpw) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e1fc64b56539e333080dca8fd09386071c128ed6/stwo_cairo_prover/crates/prover/src/components/memory/id_to_f252/prover.rs#L272)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I thought you will also do make this change for the small_logup_gen :(
non-blocking
</blockquote></details>

im  so sorry
done.

**Review by shaharsamocha7 — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/165)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ohad-starkware)

**Pull request merged**
