### PR TITLE
Import Stwo repo Range check unit component with logup

### PR DESCRIPTION
**Pull request by shaharsamocha7**
Range check unit component with logup

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/9)

### CODE REVIEW

**Comment by shaharsamocha7** [comment]
* **#9** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/9?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @shaharsamocha7 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/9)* status: all files reviewed, 3 unresolved discussions (waiting on @ohad-starkware and @shaharsamocha7)

___
*[`stwo_cairo_prover/Cargo.toml` line 10 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/9#-O0JqhbY1AWeDhVC9utZ:-O0JqhbZCgnzOi37YElX:b-24ddqf) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/5becafd9a9c5f9f96d91834f07e426bc86391c04/stwo_cairo_prover/Cargo.toml#L10)):*
> ```TOML
> num-traits = "0.2.17"
> # TODO(ShaharS): take stwo version from the source repository.
> stwo-prover = { git = "https://github.com/starkware-libs/stwo", branch = "dev" }
> ```

Add blank line below.
___
*[`stwo_cairo_prover/src/components/range_check_unit.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/9#-O0Jr_mR8jJTkCvnt4kQ:-O0Jr_mS0EWLc5HJ0JFM:b-wjjz7a) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/5becafd9a9c5f9f96d91834f07e426bc86391c04/stwo_cairo_prover/src/components/range_check_unit.rs#L41)):*
> ```XML
>         for input in inputs {
>             let input = input.0 as usize;
>             if input < self.max_value {
> ```

If the input is too big you want to ignore it? Or panic/return an error?



_Code quote:_
```XML
if input < self.max_value {
```
___
*[`stwo_cairo_prover/src/components/range_check_unit.rs` line 86 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/9#-O0JtlHl6lUB-mqCVicp:-O0JtlHl6lUB-mqCVicq:b-emhvor) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/5becafd9a9c5f9f96d91834f07e426bc86391c04/stwo_cairo_prover/src/components/range_check_unit.rs#L86)):*
> ```XML
>                         acc.push(last + (value - z).inverse() * *multiplicity);
>                     } else {
>                         acc.push((value - z).inverse() * *multiplicity);
> ```

Maybe better to define `last` outside as 0 and update it every iteration? instead of this edge case `if`.



_Code quote:_
```XML
                    if let Some(&last) = acc.last() {
                        acc.push(last + (value - z).inverse() * *multiplicity);
                    } else {
                        acc.push((value - z).inverse() * *multiplicity);
```

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/9)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5 and @ohad-starkware)

___
*[`stwo_cairo_prover/Cargo.toml` line 10 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/9#-O0JqhbY1AWeDhVC9utZ:-O0K9D6R0rESOIQDfUQg:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/5becafd9a9c5f9f96d91834f07e426bc86391c04/stwo_cairo_prover/Cargo.toml#L10)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Add blank line below.
</blockquote></details>

Done.

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/9)* status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @alonh5 and @ohad-starkware)

___
*[`stwo_cairo_prover/src/components/range_check_unit.rs` line 86 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/9#-O0JtlHl6lUB-mqCVicp:-O0NFNUM7Wo_BIqcCDJK:b15b4ox) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/5becafd9a9c5f9f96d91834f07e426bc86391c04/stwo_cairo_prover/src/components/range_check_unit.rs#L86)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Maybe better to define `last` outside as 0 and update it every iteration? instead of this edge case `if`.
</blockquote></details>

I changed to a match statement?
Do you think I should implement it with vec(BaseField::zero()) at the start?
Doesn't the compiler optimize that anyway?
___
*[`stwo_cairo_prover/src/components/range_check_unit.rs` line 191 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/9#-O0NFvCS6fASUvDsaQiE:-O0NFvCS6fASUvDsaQiF:b-dyp50p) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/00c2700a624b01f5412e46a2236f4cdaf33cda79/stwo_cairo_prover/src/components/range_check_unit.rs#L191)):*
> ```XML
>         let interaction_trace = registry
>             .get_generator::<RangeCheckUnitTraceGenerator>(RC_COMPONENT_ID)
>             .write_interaction_trace(&trace.iter().collect(), &interaction_elements);
> ```

Is this actually a copy?



_Code quote:_
```XML
&trace.iter().collect()
```

**Review by ohad-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/9)* status: 2 of 5 files reviewed, 5 unresolved discussions (waiting on @alonh5 and @shaharsamocha7)

___
*[`stwo_cairo_prover/src/components/range_check_unit.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/9#-O0JkCq29z5MrZkrKUHS:-O0JkCq29z5MrZkrKUHT:bx8qsf6) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/5becafd9a9c5f9f96d91834f07e426bc86391c04/stwo_cairo_prover/src/components/range_check_unit.rs#L36)):*
> ```XML
> 
> impl TraceGenerator<CpuBackend> for RangeCheckUnitComponent {
>     type ComponentInputs = Vec<BaseField>;
> ```

Basefield does not exist in trace filling terminology right?
perhaps a mod level typdef?
 typedef Felt = stwo::M31
___
*[`stwo_cairo_prover/src/components/range_check_unit.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/9#-O0Jl5zSCDKHAoF_Oyyz:-O0Jl5zSCDKHAoF_Oyz-:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/5becafd9a9c5f9f96d91834f07e426bc86391c04/stwo_cairo_prover/src/components/range_check_unit.rs#L71)):*
> ```XML
>         &self,
>         trace: &ColumnVec<&CircleEvaluation<CpuBackend, BaseField, BitReversedOrder>>,
>         elements: &InteractionElements,
> ```





_Suggestion:_
```XML
interaction_elements
```

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/9)* status: 2 of 5 files reviewed, 5 unresolved discussions (waiting on @alonh5 and @ohad-starkware)

___
*[`stwo_cairo_prover/src/components/range_check_unit.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/9#-O0JkCq29z5MrZkrKUHS:-O0NZzq0Dq8Phi5nAauK:b-evmj7r) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/5becafd9a9c5f9f96d91834f07e426bc86391c04/stwo_cairo_prover/src/components/range_check_unit.rs#L36)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

Basefield does not exist in trace filling terminology right?
perhaps a mod level typdef?
 typedef Felt = stwo::M31
</blockquote></details>

I thought we said that they changed Felt to our BaseField, no?
Maybe they will send here a type of Uint16? I'm not sure yet
___
*[`stwo_cairo_prover/src/components/range_check_unit.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/9#-O0Jl5zSCDKHAoF_Oyyz:-O0NZvio-fNbhqqbW7u-:br8tdo7) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/5becafd9a9c5f9f96d91834f07e426bc86391c04/stwo_cairo_prover/src/components/range_check_unit.rs#L71)):*
> ```XML
>         &self,
>         trace: &ColumnVec<&CircleEvaluation<CpuBackend, BaseField, BitReversedOrder>>,
>         elements: &InteractionElements,
> ```

This is an interface change in stwo. @alonh5 WDYT?

**Review by alonh5 — COMMENTED** [review]
> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/9)* status: all files reviewed, 7 unresolved discussions (waiting on @ohad-starkware and @shaharsamocha7)

___
*[`stwo_cairo_prover/src/components/range_check_unit.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/9#-O0Jl5zSCDKHAoF_Oyyz:-O0NaAu74tHRYLLsfvwf:bhndpi9) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/5becafd9a9c5f9f96d91834f07e426bc86391c04/stwo_cairo_prover/src/components/range_check_unit.rs#L71)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

This is an interface change in stwo. @alonh5 WDYT?
</blockquote></details>

I think it's clear they're interaction elements, but both are fine.
___
*[`stwo_cairo_prover/src/components/range_check_unit.rs` line 86 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/9#-O0JtlHl6lUB-mqCVicp:-O0NcnwB76Z31x4CFh-r:b8mda4n) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/5becafd9a9c5f9f96d91834f07e426bc86391c04/stwo_cairo_prover/src/components/range_check_unit.rs#L86)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I changed to a match statement?
Do you think I should implement it with vec(BaseField::zero()) at the start?
Doesn't the compiler optimize that anyway?
</blockquote></details>

I'm not sure if the compiler optimizes this. what I was thinking is something like this:
```
let mut last = BaseField::zero();
let interaction_values = zip_eq(&trace[0].values, &trace[1].values).fold(
    Vec::new(),
    |mut acc, (trace_value, multiplicity)| {
        interaction_value = last + (z - trace_value).inverse() * multiplicity;
        acc.push(interaction_value);
        last = interaction_value;
        acc
    },
);
```
but it's not very important, just another option.
___
*[`stwo_cairo_prover/src/components/range_check_unit.rs` line 191 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/9#-O0NFvCS6fASUvDsaQiE:-O0NdzfK3vosLKTEkMeS:b-py40ot) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/00c2700a624b01f5412e46a2236f4cdaf33cda79/stwo_cairo_prover/src/components/range_check_unit.rs#L191)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Is this actually a copy?
</blockquote></details>

I don't think so, just turning the evaluations into references.
___
*[`stwo_cairo_prover/src/components/range_check_unit.rs` line 89 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/9#-O0N_U9P881elbt_ZtDq:-O0N_U9P881elbt_ZtDr:bvzk25s) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e6c7baee4a9f046fba514a091dc4850afe52a78e/stwo_cairo_prover/src/components/range_check_unit.rs#L89)):*
> ```XML
>         for input in inputs {
>             let input = input.0 as usize;
>             debug_assert!(input < self.max_value, "Input out of range");
> ```

Why debug_assert?



_Code quote:_
```XML
debug_assert!
```
___
*[`stwo_cairo_prover/src/components/range_check_unit.rs` line 104 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/9#-O0N_lwP9MmP0FP0jjMa:-O0N_lwP9MmP0FP0jjMb:bcg272n) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e6c7baee4a9f046fba514a091dc4850afe52a78e/stwo_cairo_prover/src/components/range_check_unit.rs#L104)):*
> ```XML
>         let mut trace = vec![vec![BaseField::zero(); rc_max_value]; 2];
>         for (i, multiplicity) in rc_unit_trace_generator.multiplicities.iter().enumerate() {
>             trace[0][i] = BaseField::from_u32_unchecked(i as u32);
> ```

Do we need this column?



_Code quote:_
```XML
trace[0][i] = BaseField::from_u32_unchecked(i as u32);
```
___
*[`stwo_cairo_prover/src/components/range_check_unit.rs` line 195 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/9#-O0NfCru67OjZEMgb743:-O0NfCrv82yEb_cJueR6:b-uxepwn) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e6c7baee4a9f046fba514a091dc4850afe52a78e/stwo_cairo_prover/src/components/range_check_unit.rs#L195)):*
> ```XML
>             assert_eq!(trace[0].values[i], BaseField::from_u32_unchecked(i as u32));
>             trace_sum += trace.last().unwrap().values[i]
>                 / BaseField::from_u32_unchecked((random_seed - i) as u32);
> ```

Can you explain this calculation?



_Code quote:_
```XML
            trace_sum += trace.last().unwrap().values[i]
                / BaseField::from_u32_unchecked((random_seed - i) as u32);
```

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/9)* status: 4 of 5 files reviewed, 6 unresolved discussions (waiting on @alonh5 and @ohad-starkware)

___
*[`stwo_cairo_prover/src/components/range_check_unit.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/9#-O0Jl5zSCDKHAoF_Oyyz:-O0NzoDMC-pxx_cLMUuk:bnt9hn7) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/5becafd9a9c5f9f96d91834f07e426bc86391c04/stwo_cairo_prover/src/components/range_check_unit.rs#L71)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

I think it's clear they're interaction elements, but both are fine.
</blockquote></details>

Yeah I agree that it is okay as is
___
*[`stwo_cairo_prover/src/components/range_check_unit.rs` line 86 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/9#-O0JtlHl6lUB-mqCVicp:-O0Nzz-27iOdMTOhFzVL:bp2j46s) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/5becafd9a9c5f9f96d91834f07e426bc86391c04/stwo_cairo_prover/src/components/range_check_unit.rs#L86)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

I'm not sure if the compiler optimizes this. what I was thinking is something like this:
```
let mut last = BaseField::zero();
let interaction_values = zip_eq(&trace[0].values, &trace[1].values).fold(
    Vec::new(),
    |mut acc, (trace_value, multiplicity)| {
        interaction_value = last + (z - trace_value).inverse() * multiplicity;
        acc.push(interaction_value);
        last = interaction_value;
        acc
    },
);
```
but it's not very important, just another option.
</blockquote></details>

This code is more clear, I'll go with your impl
Thanks
___
*[`stwo_cairo_prover/src/components/range_check_unit.rs` line 89 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/9#-O0N_U9P881elbt_ZtDq:-O0NzKlTERavj0WvBpPB:bajf0i4) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e6c7baee4a9f046fba514a091dc4850afe52a78e/stwo_cairo_prover/src/components/range_check_unit.rs#L89)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Why debug_assert?
</blockquote></details>

I thought that this assert is a bit defensive, we don't expect the prover to send incorrect code here.
Do you think I should revert it to `assert!`?
___
*[`stwo_cairo_prover/src/components/range_check_unit.rs` line 104 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/9#-O0N_lwP9MmP0FP0jjMa:-O0NzZXe4kxCQ3meUkv6:b-nxrm0l) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e6c7baee4a9f046fba514a091dc4850afe52a78e/stwo_cairo_prover/src/components/range_check_unit.rs#L104)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Do we need this column?
</blockquote></details>

I wasn't sure so I said I'll add it and we'll remove that in case it is not needed.
I intend that the implementation to use the traditional lookups, so we'll see after that.
___
*[`stwo_cairo_prover/src/components/range_check_unit.rs` line 195 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/9#-O0NfCru67OjZEMgb743:-O0Nums-5Ld3jLK1-M2U:b8pqhkx) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e6c7baee4a9f046fba514a091dc4850afe52a78e/stwo_cairo_prover/src/components/range_check_unit.rs#L195)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Can you explain this calculation?
</blockquote></details>

This is the logup calculations, you essentially summing the the shifted inverses (by multiplying the multiplicity).

For each (value, multiplicities) you compute `'sum_{m_i / (z - v_i)}` where z is drawn from the channel.
* The values are 0..n so I used enumerator for that

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/9)* status: 4 of 5 files reviewed, 4 unresolved discussions (waiting on @ohad-starkware and @shaharsamocha7)

___
*[`stwo_cairo_prover/src/components/range_check_unit.rs` line 89 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/9#-O0N_U9P881elbt_ZtDq:-O0OEOar98_CqOo7JaKX:brslffo) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e6c7baee4a9f046fba514a091dc4850afe52a78e/stwo_cairo_prover/src/components/range_check_unit.rs#L89)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I thought that this assert is a bit defensive, we don't expect the prover to send incorrect code here.
Do you think I should revert it to `assert!`?
</blockquote></details>

Shouldn't it be an error? This can be caused by a faulty Air.
___
*[`stwo_cairo_prover/src/components/range_check_unit.rs` line 195 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/9#-O0NfCru67OjZEMgb743:-O0OEpyxEva7GewExLa3:bt8rbt9) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e6c7baee4a9f046fba514a091dc4850afe52a78e/stwo_cairo_prover/src/components/range_check_unit.rs#L195)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

This is the logup calculations, you essentially summing the the shifted inverses (by multiplying the multiplicity).

For each (value, multiplicities) you compute `'sum_{m_i / (z - v_i)}` where z is drawn from the channel.
* The values are 0..n so I used enumerator for that
</blockquote></details>

got it, thanks.

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/9)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @alonh5 and @ohad-starkware)

___
*[`stwo_cairo_prover/src/components/range_check_unit.rs` line 89 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/9#-O0N_U9P881elbt_ZtDq:-O0cfd_L6dFsJoRwo1Qz:bvv4foo) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e6c7baee4a9f046fba514a091dc4850afe52a78e/stwo_cairo_prover/src/components/range_check_unit.rs#L89)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Shouldn't it be an error? This can be caused by a faulty Air.
</blockquote></details>

Added a TODO to change that

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/9#-:-O0chJt_5eiweSQWscvB:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ohad-starkware)

**Review by ohad-starkware — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/9#-:-O0d8YaQ2HNWzRPuFm-b:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5 and @shaharsamocha7)

___
*[`stwo_cairo_prover/src/components/range_check_unit.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/9#-O0JkCq29z5MrZkrKUHS:-O0d8C5Q6ED_qyn_CZow:bhad2ds) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/5becafd9a9c5f9f96d91834f07e426bc86391c04/stwo_cairo_prover/src/components/range_check_unit.rs#L36)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I thought we said that they changed Felt to our BaseField, no?
Maybe they will send here a type of Uint16? I'm not sure yet
</blockquote></details>

copy of the slack msg:
Basefield, stwo's M31, and air-infra's are all typdefes of each other.  
When filling airs, you don't care about your field being Basefield, it's just a field.  
That's why I think writing Vec<Felt> makes more sense.  
In the prover code context, Basefield is more correct, because there is a notion of another field.  
Maybe this is just nit-picking, non-blocking.
___
*[`stwo_cairo_prover/src/components/range_check_unit.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/9#-O0Jl5zSCDKHAoF_Oyyz:-O0d8MaOEhfqcoqGH5OY:b-f3196c) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/5becafd9a9c5f9f96d91834f07e426bc86391c04/stwo_cairo_prover/src/components/range_check_unit.rs#L71)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Yeah I agree that it is okay as is
</blockquote></details>

you can decide the name without changing the interface, resolving.

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/9)* status: all files reviewed, 2 unresolved discussions (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/src/components/range_check_unit.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/9#-O0JkCq29z5MrZkrKUHS:-O0dFD740N7qWQueO0yZ:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/5becafd9a9c5f9f96d91834f07e426bc86391c04/stwo_cairo_prover/src/components/range_check_unit.rs#L36)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

copy of the slack msg:
Basefield, stwo's M31, and air-infra's are all typdefes of each other.  
When filling airs, you don't care about your field being Basefield, it's just a field.  
That's why I think writing Vec<Felt> makes more sense.  
In the prover code context, Basefield is more correct, because there is a notion of another field.  
Maybe this is just nit-picking, non-blocking.
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/src/components/range_check_unit.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/9#-O0Jl5zSCDKHAoF_Oyyz:-O0dFDlj1EwuY3fwHTjR:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/5becafd9a9c5f9f96d91834f07e426bc86391c04/stwo_cairo_prover/src/components/range_check_unit.rs#L71)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

you can decide the name without changing the interface, resolving.
</blockquote></details>

Done.

**Review by ohad-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/9)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Pull request merged**
