### PR TITLE
Added `run_and_prove` binary

### PR DESCRIPTION
**Pull request by yuvalsw**
(and refactorred binaries to share code)

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/227)

### CODE REVIEW

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/227)* status: all files reviewed, 3 unresolved discussions (waiting on @yuvalsw)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo-cairo/227#-ODkZce36FXSY7owo-_T:-ODkZce36FXSY7owo-_U:bhh8rf) (no related file):*
Why we need to create another crate and not create two binaries from the same one?
___
*[`stwo_cairo_prover/crates/vm_runner/src/main.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/227#-ODkiQIDBlGchXYTnmE0:-ODkiQIDBlGchXYTnmE1:b3h0jnw) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e9f06e8cdaed94e9d8457d643ac7de81fbb98527/stwo_cairo_prover/crates/vm_runner/src/main.rs#L24)):*
> ```XML
>     vm_args: VmArgs,
>     #[structopt(long = "output_path")]
>     output_path: PathBuf,
> ```

What is special about this attribute?



_Code quote:_
```XML
    #[structopt(long = "output_path")]
    output_path: PathBuf,
```
___
*[`stwo_cairo_prover/crates/vm_runner/src/main.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/227#-ODkiYV15ePJhUzxfqHp:-ODkiYV15ePJhUzxfqHq:b26qjbn) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e9f06e8cdaed94e9d8457d643ac7de81fbb98527/stwo_cairo_prover/crates/vm_runner/src/main.rs#L34)):*
> ```XML
>     IO(#[from] std::io::Error),
>     #[error("VM run failed: {0}")]
>     Vm(#[from] VmError),
> ```

This means that now we will get Error::VM::IO
Is this the resulted behaviour? (should we test those things?)



_Code quote:_
```XML
Vm(#[from] VmError),
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/227)* status: 10 of 13 files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo-cairo/227#-ODkZce36FXSY7owo-_T:-OEwkTgT-DPHxIYgRElv:b-iflscq) (no related file):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Why we need to create another crate and not create two binaries from the same one?
</blockquote></details>

I didn't try to do it. This is how we've done this in the cairo repo (although it doesn't mean it's the right way)
___
*[`stwo_cairo_prover/crates/vm_runner/src/main.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/227#-ODkiQIDBlGchXYTnmE0:-OEwjeAqCRUN9D4mXXfY:bsk1c7j) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e9f06e8cdaed94e9d8457d643ac7de81fbb98527/stwo_cairo_prover/crates/vm_runner/src/main.rs#L24)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

What is special about this attribute?
</blockquote></details>

Just that it's not part of the VM args, if that's what you meant.
___
*[`stwo_cairo_prover/crates/vm_runner/src/main.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/227#-ODkiYV15ePJhUzxfqHp:-OEwjuNk9gytkzd7GXNQ:bi4o1ly) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e9f06e8cdaed94e9d8457d643ac7de81fbb98527/stwo_cairo_prover/crates/vm_runner/src/main.rs#L34)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

This means that now we will get Error::VM::IO
Is this the resulted behaviour? (should we test those things?)
</blockquote></details>

Hmm I guess that's right, and it seems ok to me (if the IO error is in the VM). Not sure if we need unit tests for making sure what exact error we get. Of course we can, but not sure it's worth it. If it comes up that something doesn't make sense we can fix. LMK if you think differently. Anyway - this is similar to other binaries so far, so if we want to fix it can be done separately.

**Review by shaharsamocha7 — APPROVED** [review]
> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/227)* status: all files reviewed, 3 unresolved discussions (waiting on @yuvalsw)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo-cairo/227#-ODkZce36FXSY7owo-_T:-OExAZ7F892h6S0qWHIS:b-t59399) (no related file):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I didn't try to do it. This is how we've done this in the cairo repo (although it doesn't mean it's the right way)
</blockquote></details>

If we merge it as is, we got the decision and each binary will have its own crate.
Is this what we want?
unblocking
___
*[`stwo_cairo_prover/crates/vm_runner/src/main.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/227#-ODkiQIDBlGchXYTnmE0:-OExBM7c-_w0O6oWF3XX:b9gsbla) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e9f06e8cdaed94e9d8457d643ac7de81fbb98527/stwo_cairo_prover/crates/vm_runner/src/main.rs#L24)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Just that it's not part of the VM args, if that's what you meant.
</blockquote></details>

Document what it is?
___
*[`stwo_cairo_prover/crates/vm_runner/src/main.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/227#-ODkiYV15ePJhUzxfqHp:-OExB_DvBHm4OIdkG6tz:b-1atiey) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e9f06e8cdaed94e9d8457d643ac7de81fbb98527/stwo_cairo_prover/crates/vm_runner/src/main.rs#L34)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Hmm I guess that's right, and it seems ok to me (if the IO error is in the VM). Not sure if we need unit tests for making sure what exact error we get. Of course we can, but not sure it's worth it. If it comes up that something doesn't make sense we can fix. LMK if you think differently. Anyway - this is similar to other binaries so far, so if we want to fix it can be done separately.
</blockquote></details>

I think that code should be tested in general.
If you don't want to do it now, I would add a TODO rather to wait for it to fail

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/227#-:-OExZTQr-rtxLe0wI-ag:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

**Pull request merged**
