### PR TITLE
Deduplicate memory values

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/55)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/55?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#55** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/55?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#54** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/54?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#53** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/53?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#52** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/52?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#51** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/51?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/55)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`stwo_cairo_prover/crates/prover/src/input/mem.rs` line 150 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/55#-O4L8oLe845sIEI03Bex:-O4L8oLe845sIEI03Bey:b2f6sgx) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/b0ba9f182a4883a16bccab1f43982a27374d85e1/stwo_cairo_prover/crates/prover/src/input/mem.rs#L150)):*
> ```XML
>                 };
>                 MemoryValueId::F252(id)
>             }
> ```

Only this changed



_Code quote:_
```XML
            MemoryValue::U64(val) => {
                let len = self.u64_values.len();
                let id = *self.u64_id_cache.entry(val).or_insert(len);
                if id == len {
                    self.u64_values.push(val);
                };
                MemoryValueId::U64(id)
            }
            MemoryValue::F252(val) => {
                let len = self.f252_values.len();
                let id = *self.felt252_id_cache.entry(val).or_insert(len);
                if id == len {
                    self.f252_values.push(val);
                };
                MemoryValueId::F252(id)
            }
```

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/55)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`stwo_cairo_prover/crates/prover/src/input/mem.rs` line 106 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/55#-O4LR9xnCvk_tZYxVBVf:-O4LR9xnCvk_tZYxVBVg:b-1ogw45) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/b0ba9f182a4883a16bccab1f43982a27374d85e1/stwo_cairo_prover/crates/prover/src/input/mem.rs#L106)):*
> ```XML
>     felt252_id_cache: HashMap<[u32; 8], usize>,
> }
> impl MemoryBuilder {
> ```

Add a unit test for duplicates?

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/55)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5)

___
*[`stwo_cairo_prover/crates/prover/src/input/mem.rs` line 106 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/55#-O4LR9xnCvk_tZYxVBVf:-O4Z6nbHDhpyy3mKYGfO:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/b0ba9f182a4883a16bccab1f43982a27374d85e1/stwo_cairo_prover/crates/prover/src/input/mem.rs#L106)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Add a unit test for duplicates?
</blockquote></details>

Done.

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/55#-:-O4ZXm6z6E9wYI4G9nvm:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`stwo_cairo_prover/crates/prover/src/input/mem.rs` line 258 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/55#-O4ZXUhWBDjZNfadLVGu:-O4ZXUhWBDjZNfadLVGv:bxebrlz) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ce3ce8b9aa1cd0024044ce2c5335210991e3544a/stwo_cairo_prover/crates/prover/src/input/mem.rs#L258)):*
> ```XML
>             MemEntry {
>                 addr: 100,
>                 val: [1; 8],
> ```

Extract into variable for both addresses. Same with the next value.



_Code quote:_
```XML
[1; 8]
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/55)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5)

___
*[`stwo_cairo_prover/crates/prover/src/input/mem.rs` line 258 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/55#-O4ZXUhWBDjZNfadLVGu:-O4ZwOts7SSpOoIeJzDK:b27r2rd) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ce3ce8b9aa1cd0024044ce2c5335210991e3544a/stwo_cairo_prover/crates/prover/src/input/mem.rs#L258)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Extract into variable for both addresses. Same with the next value.
</blockquote></details>

I think this is less indirections, and easier to read

**Review by alonh5 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/55)* status: all files reviewed, 1 unresolved discussion

**Comment by spapinistarkware** [comment]
### Merge activity

* **Aug 18, 7:48 AM EDT**: @spapinistarkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/55).

**Pull request merged**
