### PR TITLE
Refactor FriVerifier::decommit_inner_layers

### PR DESCRIPTION
**Pull request by andrewmilson**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/134)

### CODE REVIEW

**Comment by andrewmilson** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/134?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#135** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/135?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#134** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/134?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#133** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/133?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#127** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/127?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#118** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/118?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/117?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#116** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/116?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#115** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/115?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#114** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/114?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#113** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/113?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#112** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/112?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @andrewmilson and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by ilyalesokhin-starkware** [comment]
*[`stwo_cairo_verifier/src/fri.cairo` line 213 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/134#-OB4ZRCk0FTcsi0i0f0L:-OB4ZRCk0FTcsi0i0f0M:bl4m1r4) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/728621e44a6830cc924a8f7a7a7106838749bb58/stwo_cairo_verifier/src/fri.cairo#L213)):*
> ```Cairo
> #[derive(Drop)]
> pub struct FriProof {
>     pub inner_layers: Array<FriLayerProof>,
> ```

Is there ar reason for this not to be a span?



_Suggestion:_
```Cairo
Span<FriLayerProof>
```

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/134)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @Alon-Ti, @ilyalesokhin-starkware, and @shaharsamocha7)

___
*[`stwo_cairo_verifier/src/fri.cairo` line 213 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/134#-OB4ZRCk0FTcsi0i0f0L:-OBYeY5iD9rOUsCJODFp:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/728621e44a6830cc924a8f7a7a7106838749bb58/stwo_cairo_verifier/src/fri.cairo#L213)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Is there ar reason for this not to be a span?
</blockquote></details>

Done.

**Comment by ilyalesokhin-starkware** [comment]
*[`stwo_cairo_verifier/src/fri.cairo` line 358 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/134#-OBZzhJ078q8CxpfBUhv:-OBZzhJ078q8CxpfBUhw:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/579d886c9200269ab9e66911d20b20cf1b562a9f/stwo_cairo_verifier/src/fri.cairo#L358)):*
> ```Cairo
>                     };
>                 layer_query_evals = next_layer_query_evals;
>             };
> ```





_Suggestion:_
```Cairo
                let mut next_layer_query_evals = array![];
                while let Some(layer_eval) = layer_query_evals.pop_front() {
                        let folded_eval = folded_evals.pop_front().unwrap();
                        next_layer_query_evals
                            .append(layer_eval * circle_poly_alpha_sq + folded_eval);
                };
                assert!(folded_evals.is_empty());
                layer_query_evals = next_layer_query_evals;
            };
```

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/134)* status: 9 of 11 files reviewed, 2 unresolved discussions (waiting on @Alon-Ti, @ilyalesokhin-starkware, and @shaharsamocha7)

___
*[`stwo_cairo_verifier/src/fri.cairo` line 395 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/134#-OB_SiFa1eATlXI08vOw:-OBbLzG27GnihlNX0bPb:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/579d886c9200269ab9e66911d20b20cf1b562a9f/stwo_cairo_verifier/src/fri.cairo#L395)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

can you use pop_front
</blockquote></details>

Done.
___
*[`stwo_cairo_verifier/src/fri.cairo` line 358 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/134#-OBZzhJ078q8CxpfBUhv:-OBbLypA3mjiRQLVrqwS:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/579d886c9200269ab9e66911d20b20cf1b562a9f/stwo_cairo_verifier/src/fri.cairo#L358)):*
> ```Cairo
>                     };
>                 layer_query_evals = next_layer_query_evals;
>             };
> ```

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 10 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/134#-:-OBdLc_18r4qRIBCHYQP:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Alon-Ti and @shaharsamocha7)

**Pull request merged**
