### PR TITLE
Switched RC unit to eval framework.

### PR DESCRIPTION
**Pull request by Alon-Ti**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/59)

### CODE REVIEW

**Comment by Alon-Ti** [comment]
* **#59** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/59?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Alon-Ti and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/59)* status: all files reviewed, 2 unresolved discussions (waiting on @Alon-Ti)

___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_unit/component_prover.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/59#-O4f3nq21JJtUQVxdzBV:-O4f3nq21JJtUQVxdzBW:bccezuz) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/609d9225cb4d114e905a88dd45f7bbc948a727c7/stwo_cairo_prover/crates/prover/src/components/range_check_unit/component_prover.rs#L59)):*
> ```XML
> 
>         // Extend trace.
>         let domain = CanonicCoset::new(RC_TRACE_LEN.ilog2()).circle_domain();
> ```

This might not be a power of 2 right? Should we assert for now?



_Code quote:_
```XML
RC_TRACE_LEN.ilog2()
```
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_unit/mod.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/59#-O4f4zPI0yS7TQljjagM:-O4f4zPI0yS7TQljjagN:b-a32vkx) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/5ddd8acf07d1c3c73dc5bfc217011ae329728043/stwo_cairo_prover/crates/prover/src/components/range_check_unit/mod.rs#L9)):*
> ```XML
> 
> #[cfg(test)]
> pub mod tests {
> ```

Can we test this with the memory? Can do it in the next PR.

**Review by Alon-Ti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/59)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @alonh5)

___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_unit/component_prover.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/59#-O4f3nq21JJtUQVxdzBV:-O591C6aCPuaeDSbhT3s:b-artt29) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/609d9225cb4d114e905a88dd45f7bbc948a727c7/stwo_cairo_prover/crates/prover/src/components/range_check_unit/component_prover.rs#L59)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

This might not be a power of 2 right? Should we assert for now?
</blockquote></details>

Done; becomes unnecessary in the next PR.
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_unit/mod.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/59#-O4f4zPI0yS7TQljjagM:-O5919GI66GsrS8Tm1DU:b522opr) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/5ddd8acf07d1c3c73dc5bfc217011ae329728043/stwo_cairo_prover/crates/prover/src/components/range_check_unit/mod.rs#L9)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Can we test this with the memory? Can do it in the next PR.
</blockquote></details>

Tested in the next PR.

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/59#-:-O5C_ew83uPZCjXZJT9O:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @Alon-Ti)

___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_builtin/simd_trace.rs` line 18 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/59#-O5C_bTp8CrbXHWXcVc6:-O5C_bTp8CrbXHWXcVc7:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3b44f11402abd6930ab384348cf58429dc09b091/stwo_cairo_prover/crates/prover/src/components/range_check_builtin/simd_trace.rs#L18)):*
> ```XML
> 
> use super::component::{LAST_VALUE_OFFSET, N_VALUES_FELTS};
> use crate::components::memory::{MemoryLookupElements, N_ADDRESS_FELTS, N_BITS_PER_FELT};
> ```


___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_builtin/simd_trace.rs` line 19 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/59#-O5C_Ycn5il95pCG9105:-O5C_Yco2JJOVryOG2Nr:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3b44f11402abd6930ab384348cf58429dc09b091/stwo_cairo_prover/crates/prover/src/components/range_check_builtin/simd_trace.rs#L19)):*
> ```XML
> use super::component::{LAST_VALUE_OFFSET, N_VALUES_FELTS};
> use crate::components::memory::{MemoryLookupElements, N_ADDRESS_FELTS, N_BITS_PER_FELT};
> use crate::components::range_check_unit::RangeElements;
> ```





_Suggestion:_
```XML
RangeCheckElements
```

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, 1 of 1 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/59)* status: all files reviewed, 7 unresolved discussions (waiting on @Alon-Ti)

*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo-cairo/59#-O5IA8CQ7rxy9DXvMuia:-O5IA8CQ7rxy9DXvMuib:b2jq87s) (no related file):*
I think we should have a naming convention for the air files, I suggest:
gen.rs
constraints/component.rs

WDYT?

___
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_unit/component_prover.rs` line 47 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/59#-O5I7qfVACLI1XG1bdeE:-O5I7qfVACLI1XG1bdeF:b45h) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/4c6c7306bb4d0b73363f2be16882043f9c6c6b89/stwo_cairo_prover/crates/prover/src/components/range_check_unit/component_prover.rs#L47)):*
> ```XML
> 
>         let mut trace = (0..2)
>             .map(|_| Col::<SimdBackend, BaseField>::zeros(RC_TRACE_LEN / N_LANES))
> ```





_Suggestion:_
```XML
.map(|_| Col::<SimdBackend, BaseField>::uninitialized(RC_TRACE_LEN / N_LANES))
```
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_unit/component_prover.rs` line 54 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/59#-O5I87jEBBXSHMB37NM9:-O5I87jEBBXSHMB37NMA:b-l2935h) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/4c6c7306bb4d0b73363f2be16882043f9c6c6b89/stwo_cairo_prover/crates/prover/src/components/range_check_unit/component_prover.rs#L54)):*
> ```XML
>                 PackedBaseField::from_array(std::array::from_fn(|i| {
>                     M31::from_u32_unchecked(((vec_row << LOG_N_LANES) + i) as u32)
>                 }));
> ```

Are you going to replace it with constant column?



_Code quote:_
```XML
            trace[TRACE_INDICES_OFFSET].data[vec_row] =
                PackedBaseField::from_array(std::array::from_fn(|i| {
                    M31::from_u32_unchecked(((vec_row << LOG_N_LANES) + i) as u32)
                }));
```
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_unit/component_prover.rs` line 58 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/59#-O5I8jQFCImTOwOkGJcQ:-O5I8jQG5MlO0WIXdnR7:bhwvv0z) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/4c6c7306bb4d0b73363f2be16882043f9c6c6b89/stwo_cairo_prover/crates/prover/src/components/range_check_unit/component_prover.rs#L58)):*
> ```XML
>         }
> 
>         let multiplicities = trace[TRACE_MULTIPLICITIES_OFFSET].data.clone();
> ```

Do we really need that clone? can it be removed?



_Code quote:_
```XML
        let multiplicities = trace[TRACE_MULTIPLICITIES_OFFSET].data.clone();
```
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_unit/component_prover.rs` line 81 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/59#-O5I9xpL6-m3WLVQVzn1:-O5I9xpL6-m3WLVQVzn2:byp18fd) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/4c6c7306bb4d0b73363f2be16882043f9c6c6b89/stwo_cairo_prover/crates/prover/src/components/range_check_unit/component_prover.rs#L81)):*
> ```XML
>         Self::new()
>     }
> }
> ```

Remove



_Code quote:_
```XML
impl<const RC_TRACE_LEN: usize> Default for RangeCheckClaimProver<RC_TRACE_LEN> {
    fn default() -> Self {
        Self::new()
    }
}
```

**Review by Alon-Ti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/59)* status: all files reviewed, 5 unresolved discussions (waiting on @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_unit/component_prover.rs` line 47 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/59#-O5I7qfVACLI1XG1bdeE:-O5PKrKeEJUefkzFcUQw:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/4c6c7306bb4d0b73363f2be16882043f9c6c6b89/stwo_cairo_prover/crates/prover/src/components/range_check_unit/component_prover.rs#L47)):*
> ```XML
> 
>         let mut trace = (0..2)
>             .map(|_| Col::<SimdBackend, BaseField>::zeros(RC_TRACE_LEN / N_LANES))
> ```

Done.
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_unit/component_prover.rs` line 54 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/59#-O5I87jEBBXSHMB37NM9:-O5ITG4T5d4IKzcmF-3G:bivrv5k) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/4c6c7306bb4d0b73363f2be16882043f9c6c6b89/stwo_cairo_prover/crates/prover/src/components/range_check_unit/component_prover.rs#L54)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Are you going to replace it with constant column?
</blockquote></details>

No, this component assumes that the constant column is sequential so it doesn't have to refer to load values from it from memory when generating the trace.
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_unit/component_prover.rs` line 58 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/59#-O5I8jQFCImTOwOkGJcQ:-O5PT7gTEFhgAe2dCnUy:b-jg1ddt) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/4c6c7306bb4d0b73363f2be16882043f9c6c6b89/stwo_cairo_prover/crates/prover/src/components/range_check_unit/component_prover.rs#L58)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Do we really need that clone? can it be removed?
</blockquote></details>

Looks a little difficult to remove (the other classes have to take a reference and then a lot of lifetime propagation), adding a TODO.
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_unit/component_prover.rs` line 81 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/59#-O5I9xpL6-m3WLVQVzn1:-O5PTqTcDf_dLYxjz_no:b-ktdmw8) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/4c6c7306bb4d0b73363f2be16882043f9c6c6b89/stwo_cairo_prover/crates/prover/src/components/range_check_unit/component_prover.rs#L81)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Remove
</blockquote></details>

Done (my linter will now complain forever :()

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/59)* status: all files reviewed, 5 unresolved discussions (waiting on @Alon-Ti)

___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_unit/component_prover.rs` line 54 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/59#-O5I87jEBBXSHMB37NM9:-O5Rr9WXEnROsBqUf7Hu:b-lophaa) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/4c6c7306bb4d0b73363f2be16882043f9c6c6b89/stwo_cairo_prover/crates/prover/src/components/range_check_unit/component_prover.rs#L54)):*
<details><summary><i>Previously, Alon-Ti wrote…</i></summary><blockquote>

No, this component assumes that the constant column is sequential so it doesn't have to refer to load values from it from memory when generating the trace.
</blockquote></details>

I don't understand that.
If this column is in the trace then we should have constraints that it has the correct values.
If you want to assume this column is seqeuntial (without constraint it), then it should be in the constant trace. Am I missing something?

**Review by shaharsamocha7 — COMMENTED** [review]
> Reviewed 1 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/59)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @Alon-Ti and @alonh5)

___
*[`stwo_cairo_prover/crates/prover/src/input/range_check9.rs` line 1 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/59#-O5S9eiFEVtu6Fm802X0:-O5S9eiFEVtu6Fm802X1:b354jbh) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/0f7b91ef1c877403af3c6ef1ece69a34fde0af5e/stwo_cairo_prover/crates/prover/src/input/range_check9.rs#L1)):*
> ```XML
> 
> ```

what's that?

**Review by Alon-Ti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/59)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_unit/component_prover.rs` line 54 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/59#-O5I87jEBBXSHMB37NM9:-O5SEAj-ExX18OVU5Clz:b-jzk1c4) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/4c6c7306bb4d0b73363f2be16882043f9c6c6b89/stwo_cairo_prover/crates/prover/src/components/range_check_unit/component_prover.rs#L54)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I don't understand that.
If this column is in the trace then we should have constraints that it has the correct values.
If you want to assume this column is seqeuntial (without constraint it), then it should be in the constant trace. Am I missing something?
</blockquote></details>

It's currently an unconstrained column in the trace, once we support constant columns it'll be a constant column (which is also unconstrained), this reflects what these constraints will end up looking like so we can benchmark etc.
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_unit/component_prover.rs` line 81 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/59#-O5I9xpL6-m3WLVQVzn1:-O5SGBDbAnow48DN3pRy:blhtey6) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/4c6c7306bb4d0b73363f2be16882043f9c6c6b89/stwo_cairo_prover/crates/prover/src/components/range_check_unit/component_prover.rs#L81)):*
<details><summary><i>Previously, Alon-Ti wrote…</i></summary><blockquote>

Done (my linter will now complain forever :()
</blockquote></details>

Turns out removing this makes clippy sad

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/59)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @Alon-Ti)

___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_unit/component_prover.rs` line 73 at r7](https://reviewable.io/reviews/starkware-libs/stwo-cairo/59#-O5SsfaYBY3fxa3wSta_:-O5SsfaYBY3fxa3wStaa:b-mj4pj5) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/9c3c2fc1bc7eb2a5af27a298a0530d07a55eded1/stwo_cairo_prover/crates/prover/src/components/range_check_unit/component_prover.rs#L73)):*
> ```XML
>         (
>             RangeCheckClaim {
>                 log_rc_max: RC_TRACE_LEN.ilog2() - LOG_N_LANES,
> ```

I'm confused.
It's weird to me that the claim is affected by the LOG_N_LANES which is specific to SIMD impl.
What RangeCheckClaim really is?



_Suggestion:_
```XML
RC_TRACE_LEN.ilog2(),
```

**Review by Alon-Ti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/59)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_unit/component_prover.rs` line 81 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/59#-O5I9xpL6-m3WLVQVzn1:-O5Sy_Y4Cwt9arfxZbdJ:b9fgcyi) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/4c6c7306bb4d0b73363f2be16882043f9c6c6b89/stwo_cairo_prover/crates/prover/src/components/range_check_unit/component_prover.rs#L81)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I wonder why, we don't use that at all, no?
</blockquote></details>

No, it compiles fine without it. Maybe it doesn't like the `new()` convention?
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_unit/component_prover.rs` line 73 at r7](https://reviewable.io/reviews/starkware-libs/stwo-cairo/59#-O5SsfaYBY3fxa3wSta_:-O5SxfG_-rWL19Z7vUsx:bjxprv3) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/9c3c2fc1bc7eb2a5af27a298a0530d07a55eded1/stwo_cairo_prover/crates/prover/src/components/range_check_unit/component_prover.rs#L73)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I'm confused.
It's weird to me that the claim is affected by the LOG_N_LANES which is specific to SIMD impl.
What RangeCheckClaim really is?
</blockquote></details>

It's not specific to SIMD, `RC_TRACE_LEN` is, this is canceling it out. (This should actually be `+`, but the next PR, which also introduces the test, changes this semantic to log height).
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_unit/component_prover.rs` line 88 at r7](https://reviewable.io/reviews/starkware-libs/stwo-cairo/59#-O5SVXdA26BZ02Ec4KxP:-O5T3FDS4gm7dFGUY6R9:b6xde1l) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/9c3c2fc1bc7eb2a5af27a298a0530d07a55eded1/stwo_cairo_prover/crates/prover/src/components/range_check_unit/component_prover.rs#L88)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Why here is with PackedElement and not PackedU32?
I think it should be consistent
</blockquote></details>

Changed this in the next PR (where they types change anyway because of reps)

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/59#-:-O5TMoxm2oyTvHVmcNpv:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @Alon-Ti)

**Pull request merged**
