### PR TITLE
better verify add inputs

### PR DESCRIPTION
**Pull request by ohad-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/285)

### CODE REVIEW

**Comment by ohad-starkware** [comment]
* **#285** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/285?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/285?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Comment by ohad-starkware** [comment]
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 181 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/285#-OFLL-D-3Ij0BbMmhFE6:-OFLL-D-3Ij0BbMmhFE7:bu7lex8) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/965215e92060451c5f190dc65fabd006cbe4dd97/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L181)):*
> ```XML
>     /// Iterates over the casm states and splits them into the appropriate opcode components.
>     /// # Returns
>     /// A tuple of the state transitions and the maximum observed pc value.
> ```

@Stavbe

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/285)* status: 0 of 8 files reviewed, 3 unresolved discussions (waiting on @ohad-starkware and @Stavbe)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo-cairo/285#-OFLjv05BaV_CCkQdkza:-OFLjv066nk9Iiva1CDm:b-ky8pdg) (no related file):*
Is it worth the bother?
___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 204 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/285#-OFLkG6rEumtQAcvwdmy:-OFLkG6s9A6y86Bf-fYN:b98vzkv) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/965215e92060451c5f190dc65fabd006cbe4dd97/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L204)):*
> ```XML
>             };
>             res.push_instr(mem, entry.into(), dev_mode);
>             max_pc = std::cmp::max(max_pc, entry.pc);
> ```

I think that max_pc could be taken directly from the program memory segment



_Code quote:_
```XML
max_pc = std::cmp::max(max_pc, entry.pc);
```

**Comment by ohad-starkware** [comment]
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 204 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/285#-OFLkG6rEumtQAcvwdmy:-OFLpY220mSsjtr05sRm:b-l3fu1i) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/965215e92060451c5f190dc65fabd006cbe4dd97/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L204)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I think that max_pc could be taken directly from the program memory segment
</blockquote></details>

program_len?

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/285)* status: 0 of 8 files reviewed, 3 unresolved discussions (waiting on @ohad-starkware and @Stavbe)

___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 204 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/285#-OFLkG6rEumtQAcvwdmy:-OFLtQQGDSRf7APlFjxW:bas8uxa) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/965215e92060451c5f190dc65fabd006cbe4dd97/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L204)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

program_len?
</blockquote></details>

there is program_segment IIRC

**Pull request closed without merging**
