### PR TITLE
Added proof serialization to adapted-Stwo

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/94)

### CODE REVIEW

**Comment by yuvalsw** [comment]
change target branch

**Review by Alon-Ti — APPROVED** [review]
:lgtm:, but is there anything on top of this? (If you just serialize the proof but also say that you want to decide what the correct serialization is later, maybe it's better not to do this now).

> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/94#-:-O81ayMtEnKFZ_mzvmQ3:b-pn4y41)* status: all files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

**Review by yuvalsw — COMMENTED** [review]
Nothing on top of it right now. But I wanted to have the extra arg, and the generated file, which I could also manually skim through.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/94#-:-O8Wa4keAf0r-7bHfjwe:bicljk6)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @Alon-Ti and @shaharsamocha7)

**Review by Alon-Ti — APPROVED** [review]
:thumbsup: 

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/94#-:-O8WfC3TEOBRZrhrvI6o:b4c9lyr)* status: all files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

**Pull request merged**
