### PR TITLE
change CairoInput to ProverInput

### PR DESCRIPTION
**Pull request by Stavbe**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/280)

### CODE REVIEW

**Review by ohad-starkware — COMMENTED** [review]
I hate that name very much, please explain the reason

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/280#-:-OF2w9Av4k1SOXaX84r5:bbi6o8t)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by ohad-starkware — COMMENTED** [review]
wrote suggestions in #274  

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/280#-:-OFDy7pS7bVfOeeuweXi:bgf4fva)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by yuvalsw — APPROVED** [review]
:lgtm:
LGTM for either StwoInput or ProverInput (but Ohad seems to prefer ProverInput, so let's go with it).

> Reviewed 1 of 7 files at r1, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/280#-:-OFLA67Y3X1IpAyjLRkz:bmfyt3z)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Stavbe)

**Review by Stavbe — COMMENTED** [review]
DONE

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/280#-:-OFLyv2M3i1z85d97vIf:bb6tyiv)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by yuvalsw — APPROVED** [review]
nit: Please fix the commit message (commit --amend) and the title of the PR (through github)

> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/280#-:-OFQv2hp9RrZ2eB3weTF:bpa94bm)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Stavbe)

**Review by yuvalsw — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/280)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Stavbe)

**Review by ohad-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/280#-:-OFRJUnrCDNwt0pXtfcY:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @Stavbe)

**Pull request merged**
