### PR TITLE
Add memory component.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/19)

### CODE REVIEW

**Comment by alonh5** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/19?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#19** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/19?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#18** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/18?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#17** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/17?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#16** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/16?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#13** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/13?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#12** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/12?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#11** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/11?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#14** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/14?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alonh5 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/19)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @spapinistarkware)

___
*[`stwo_cairo_prover/src/components/memory/component.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/19#-O1vdPcAAXT768SqjUVf:-O1vdPcB-nwpk6NNSrvR:b-bslk7q) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/9e404a77a5327c1059eb7661931ea8bf27c8e53b/stwo_cairo_prover/src/components/memory/component.rs#L65)):*
> ```XML
>     }
> 
>     fn write_trace(
> ```

Can you add a unit test that this function works?
maybe we should initialize the memory with non_zero values?



_Code quote:_
```XML
 fn write_trace(
```

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/19#-:-O1zjS8v279wtoP5ykd2:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5)

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/19)* status: all files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

___
*[`stwo_cairo_prover/src/components/memory/component.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/19#-O1vdPcAAXT768SqjUVf:-O2-Bez67xc43zT2UBbS:blo197g) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/09c5c7d46146d0cfd5781a003d897438126ad23d/stwo_cairo_prover/src/components/memory/component.rs#L65)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can you add a unit test that this function works?
maybe we should initialize the memory with non_zero values?
</blockquote></details>

Added a test in PR 27.

**Comment by alonh5** [comment]
### Merge activity

* **Jul 17, 6:36 AM EDT**: @alonh5 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/19).

**Pull request merged**
