### PR TITLE
derive subcomponentinput

### PR DESCRIPTION
**Pull request by ohad-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/260)

### CODE REVIEW

**Comment by ohad-starkware** [comment]
* **#260** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/260?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/260?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Comment by ilyalesokhin-starkware** [comment]
*[`stwo_cairo_prover/crates/air_structs_derive/src/lib.rs` line 99 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/260#-OEJj5hL3800bgJDVpB7:-OEJj5hM1MnYGCij3PB9:bh9ha30) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/baffd30020a9fd3f57eaf8ac1136b59a0126c488/stwo_cairo_prover/crates/air_structs_derive/src/lib.rs#L99)):*
> ```XML
> 
>             quote! {
>                 #field_name: [(); #array_length].map(|_| Vec::with_capacity(capacity))
> ```

Merge loops.



_Suggestion:_
```XML
let v = Vec::with_capacity(capacity);
v.set_len(capacity);
v
```

**Comment by ilyalesokhin-starkware** [comment]
*[`stwo_cairo_prover/crates/air_structs_derive/src/lib.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/260#-OEJkLePC5qnm8QXtpt4:-OEJkLePC5qnm8QXtpt5:b-r9y7gl) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/baffd30020a9fd3f57eaf8ac1136b59a0126c488/stwo_cairo_prover/crates/air_structs_derive/src/lib.rs#L36)):*
> ```XML
>     let mut vec_array_fields = Vec::new();
> 
>     if let Data::Struct(data_struct) = &input.data {
> ```

in the compiler repo we are using
https://docs.rs/syn/latest/syn/

https://github.com/starkware-libs/cairo/blob/932767340c4b8a762140bf9eba305f437587ac1b/crates/cairo-lang-proc-macros/src/rewriter.rs#L10



_Code quote:_
```XML
if let Data::Struct(data_struct) = &input.data {
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 35 of 38 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/260)* status: 35 of 38 files reviewed, 2 unresolved discussions (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/crates/air_structs_derive/src/lib.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/260#-OEJkLePC5qnm8QXtpt4:-OEJqca60ICG5yTwREXA:bqx9siv) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/baffd30020a9fd3f57eaf8ac1136b59a0126c488/stwo_cairo_prover/crates/air_structs_derive/src/lib.rs#L36)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

in the compiler repo we are using
https://docs.rs/syn/latest/syn/

https://github.com/starkware-libs/cairo/blob/932767340c4b8a762140bf9eba305f437587ac1b/crates/cairo-lang-proc-macros/src/rewriter.rs#L10
</blockquote></details>

my main worry is that you have silent parsing errors here.

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/260)* status: 35 of 38 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`stwo_cairo_prover/crates/air_structs_derive/src/lib.rs` line 99 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/260#-OEJj5hL3800bgJDVpB7:-OEJqPAA5vGLayNjnutr:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/baffd30020a9fd3f57eaf8ac1136b59a0126c488/stwo_cairo_prover/crates/air_structs_derive/src/lib.rs#L99)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Merge loops.
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/260)* status: 33 of 38 files reviewed, 1 unresolved discussion (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/crates/air_structs_derive/src/lib.rs` line 99 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/260#-OEJj5hL3800bgJDVpB7:-OEJu2vHAIZgCrGAzWi6:b-vr4p06) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/baffd30020a9fd3f57eaf8ac1136b59a0126c488/stwo_cairo_prover/crates/air_structs_derive/src/lib.rs#L99)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see it.

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/260)* status: 33 of 38 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @ohad-starkware)

___
*[`stwo_cairo_prover/crates/air_structs_derive/src/lib.rs` line 99 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/260#-OEJj5hL3800bgJDVpB7:-OEJuxMP-JKI5Am6uuga:brz320a) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/baffd30020a9fd3f57eaf8ac1136b59a0126c488/stwo_cairo_prover/crates/air_structs_derive/src/lib.rs#L99)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I don't see it.
</blockquote></details>

oh the expanded function right

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 38 files at r1, 2 of 3 files at r2, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/260#-:-OEJzJg2B6l2CHjsFHZK:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @ohad-starkware)

**Review by ohad-starkware — COMMENTED** [review]
@Alon-Ti  ptal

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/260#-:-OEK1vVW9PHjb8FwWupn:b-r3wo38)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @ohad-starkware)

**Review by Alon-Ti — APPROVED** [review]
:lgtm:

> Reviewed 35 of 38 files at r1, 2 of 3 files at r2, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/260#-:-OEK4LvB5MM6w1_ndN5a:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ohad-starkware)

**Pull request merged**
