### PR TITLE
Test memory trace.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/27)

### CODE REVIEW

**Comment by alonh5** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/27?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#27** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/27?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#25** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/25?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#24** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/24?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#23** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/23?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#19** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/19?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#18** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/18?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#17** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/17?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#16** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/16?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#13** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/13?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#12** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/12?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#11** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/11?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#14** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/14?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alonh5 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/27)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`stwo_cairo_prover/src/components/memory/component.rs` line 256 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/27#-O23aTRR9Tf2WdrV0o2_:-O23aTRS6co3V82TC4fC:b-l6mkjh) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/573d1c456fe331f0822d0ae8a2a3aeb0e975de71/stwo_cairo_prover/src/components/memory/component.rs#L256)):*
> ```XML
>             .write_interaction_trace(&trace.iter().collect(), &interaction_elements);
> 
>         let mut trace_sum = SecureField::zero();
> ```

rename



_Suggestion:_
```XML
expected_logup_sum
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/27)* status: all files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

___
*[`stwo_cairo_prover/src/components/memory/component.rs` line 256 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/27#-O23aTRR9Tf2WdrV0o2_:-O23iaiv-nBTAUYksmC7:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f2c1802f4479440a17e20a9cedb05a0d17195c9f/stwo_cairo_prover/src/components/memory/component.rs#L256)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

rename
</blockquote></details>

Done.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/27#-:-O23yg9z-kywufRGYX0D:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Pull request merged**
