### PR TITLE
vm constraint

### PR DESCRIPTION
**Pull request by ohad-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/188)

### CODE REVIEW

**Comment by ohad-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/188?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#188** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/188?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/188?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#187** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/187?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#180** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/180?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#182](https://github.com/starkware-libs/stwo-cairo/pull/182) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/182?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#179** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/179?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#177** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/177?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#178** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/178?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#176** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/176?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 9 of 10 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/188)* status: all files reviewed, 4 unresolved discussions (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/lib.rs` line 13 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/188#-OC9AqRVBhzyBdhHb_SC:-OC9AqRVBhzyBdhHb_SD:bqaoh0p) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/2610be005b7916a447002dfd1b267030acf56208/stwo_cairo_prover/crates/prover/src/lib.rs#L13)):*
> ```XML
>     use crate::input::plain::input_from_plain_casm;
> 
>     // TODO(yuval): un-ignore ,implement and test opcode filter.
> ```

Why is it on Yuval?
Can we just fix the test and add a TODO to support more instructions?



_Code quote:_
```XML
// TODO(yuval): un-ignore ,implement and test opcode filter.
```
___
*[`stwo_cairo_prover/crates/prover_types/src/simd.rs` line 447 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/188#-OC9ByGc6fcvL3YHZiQB:-OC9ByGc6fcvL3YHZiQC:bhzhjlz) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/9bc3880fce85864df8ab087268fcc16a1454f976/stwo_cairo_prover/crates/prover_types/src/simd.rs#L447)):*
> ```XML
>     }
> }
> ```

revert change
___
*[`stwo_cairo_prover/crates/prover/src/input/instructions.rs` line 7 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/188#-OC9Bn27C4GA0EaQIsNN:-OC9Bn27C4GA0EaQIsNO:b-lwb46v) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/2610be005b7916a447002dfd1b267030acf56208/stwo_cairo_prover/crates/prover/src/input/instructions.rs#L7)):*
> ```XML
> use super::mem::MemoryBuilder;
> use super::vm_import::TraceEntry;
> ```

What's going on with the changes in this file?
I don't understand
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/air.rs` line 397 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/188#-OC9BGew6bnj3TtKd57Q:-OC9BGew6bnj3TtKd57R:b-30yalu) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/2610be005b7916a447002dfd1b267030acf56208/stwo_cairo_prover/crates/prover/src/cairo_air/air.rs#L397)):*
> ```XML
>         .opcodes
>         .combine::<M31, QM31>(&claim.public_data.initial_state.values())
>         .inverse();
> ```

comments and change order



_Suggestion:_
```XML
    // Use first State.
    sum -= elements
        .opcodes
        .combine::<M31, QM31>(&claim.public_data.initial_state.values())
        .inverse();
    // Yield last state.
    sum += elements
        .opcodes
        .combine::<M31, QM31>(&claim.public_data.final_state.values())
        .inverse();
```

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/188)* status: all files reviewed, 6 unresolved discussions (waiting on @ohad-starkware and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/lib.rs` line 13 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/188#-OC9AqRVBhzyBdhHb_SC:-OCCH_EDCO6rEt71LmxD:b-wa2yd5) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/2610be005b7916a447002dfd1b267030acf56208/stwo_cairo_prover/crates/prover/src/lib.rs#L13)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Why is it on Yuval?
Can we just fix the test and add a TODO to support more instructions?
</blockquote></details>

we can't fix the test and have the vmconstraint before the jmp_abs air is in
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/air.rs` line 397 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/188#-OC9BGew6bnj3TtKd57Q:-OCCIjYq7MlMOPDKbasY:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/2610be005b7916a447002dfd1b267030acf56208/stwo_cairo_prover/crates/prover/src/cairo_air/air.rs#L397)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

comments and change order
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/input/instructions.rs` line 7 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/188#-OC9Bn27C4GA0EaQIsNN:-OCCJPzxDO3uuqckCQOs:bd8tn4k) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/2610be005b7916a447002dfd1b267030acf56208/stwo_cairo_prover/crates/prover/src/input/instructions.rs#L7)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

What's going on with the changes in this file?
I don't understand
</blockquote></details>

wrote stuff
___
*[`stwo_cairo_prover/crates/prover_types/src/simd.rs` line 447 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/188#-OC9ByGc6fcvL3YHZiQB:-OCCJNX76jFCB5ZDUD9K:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/9bc3880fce85864df8ab087268fcc16a1454f976/stwo_cairo_prover/crates/prover_types/src/simd.rs#L447)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

revert change
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/input/instructions.rs` line 16 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/188#-OCCIn7s5x-acHY5PDx-:-OCCIn7s5x-acHY5PDx0:bvcyw9e) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/2610be005b7916a447002dfd1b267030acf56208/stwo_cairo_prover/crates/prover/src/input/instructions.rs#L16)):*
> ```XML
> }
> impl VmState {
>     pub fn values(&self) -> [M31; 3] {
> ```

convenience
___
*[`stwo_cairo_prover/crates/prover/src/input/instructions.rs` line 89 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/188#-OCCIrZFCrkiZm404xcx:-OCCIrZFCrkiZm404xcy:b3v6hdp) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/2610be005b7916a447002dfd1b267030acf56208/stwo_cairo_prover/crates/prover/src/input/instructions.rs#L89)):*
> ```XML
>         res.push_instr(mem, first.into());
> 
>         while let Some(entry) = iter.next() {
> ```

there should be n-1 state transitions for n states
currently we are counting the last one

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/188)* status: all files reviewed, 5 unresolved discussions (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/lib.rs` line 13 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/188#-OC9AqRVBhzyBdhHb_SC:-OCTOKQ74w2OAmP95Iri:bi071jr) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/2610be005b7916a447002dfd1b267030acf56208/stwo_cairo_prover/crates/prover/src/lib.rs#L13)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

we can't fix the test and have the vmconstraint before the jmp_abs air is in
</blockquote></details>

so let's put this TODO on ourselves and remove it once we add jmp inst
___
*[`stwo_cairo_prover/crates/prover/src/input/instructions.rs` line 89 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/188#-OCCIrZFCrkiZm404xcx:-OCTPDTu-DvLlD8MxKeO:b434a4m) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/2610be005b7916a447002dfd1b267030acf56208/stwo_cairo_prover/crates/prover/src/input/instructions.rs#L89)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

there should be n-1 state transitions for n states
currently we are counting the last one
</blockquote></details>

Change to "Check if the adapter output the final state"
___
*[`stwo_cairo_prover/crates/prover/src/input/instructions.rs` line 104 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/188#-OCTH_1z0sBheVuAhSJP:-OCTH_1z0sBheVuAhSJQ:bso7fcm) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/0190fc3f02ffaa8847211d1fde58215304a7b169/stwo_cairo_prover/crates/prover/src/input/instructions.rs#L104)):*
> ```XML
>     }
> 
>     // TODO(Ohad): uncomment when adding the rest of the instructions.
> ```

fix todo



_Suggestion:_
```XML
remove dev_mode when adding the rest of the instructions.
```
___
*[`stwo_cairo_prover/crates/prover/src/input/instructions.rs` line 131 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/188#-OCTHfMIAEH3jqX8UCSg:-OCTHfMIAEH3jqX8UCSh:bb7pwfd) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/0190fc3f02ffaa8847211d1fde58215304a7b169/stwo_cairo_prover/crates/prover/src/input/instructions.rs#L131)):*
> ```XML
>                 opcode_assert_eq: false,
>             } => self.ret.push(state),
>             // // ap += imm.
> ```

undo



_Code quote:_
```XML
// // ap += imm.
```

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/188)* status: 14 of 16 files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/lib.rs` line 13 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/188#-OC9AqRVBhzyBdhHb_SC:-OCTV_V8BXx3I_-4D-DG:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/2610be005b7916a447002dfd1b267030acf56208/stwo_cairo_prover/crates/prover/src/lib.rs#L13)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

so let's put this TODO on ourselves and remove it once we add jmp inst
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/input/instructions.rs` line 104 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/188#-OCTH_1z0sBheVuAhSJP:-OCTTeb8D6ET9EwLulCZ:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/0190fc3f02ffaa8847211d1fde58215304a7b169/stwo_cairo_prover/crates/prover/src/input/instructions.rs#L104)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

fix todo
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/input/instructions.rs` line 131 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/188#-OCTHfMIAEH3jqX8UCSg:-OCTTkzU9cxFNKvYlqfU:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/0190fc3f02ffaa8847211d1fde58215304a7b169/stwo_cairo_prover/crates/prover/src/input/instructions.rs#L131)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

undo
</blockquote></details>

Done.

**Pull request merged**
