### PR TITLE
mul

### PR DESCRIPTION
**Pull request by ohad-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/219)

### CODE REVIEW

**Comment by ohad-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/219?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#219** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/219?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/219?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#218** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/218?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#217** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/217?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#216** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/216?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#215** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/215?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#209** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/209?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#214](https://github.com/starkware-libs/stwo-cairo/pull/214) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/214?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#208** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/208?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#207** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/207?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#206** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/206?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/219)* status: 1 of 12 files reviewed, 2 unresolved discussions (waiting on @ohad-starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo-cairo/219#-ODFl08x453rZLEeDBvm:-ODFl08y66yFqG05OJAI:b-awki53) (no related file):*
Here you only add large muls, right?
Don't we have the small mul yet?
___
*[`stwo_cairo_prover/crates/prover/src/lib.rs` line 198 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/219#-ODFjfyv04WA3wZtzAmn:-ODFjfyv04WA3wZtzAmo:b-n224rr) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/1af7f7c2e742d37eb8be990bde722663ba16ac1b/stwo_cairo_prover/crates/prover/src/lib.rs#L198)):*
> ```XML
> 
>     // TODO(Ohad): un-ignore.
>     #[ignore = "mul small opcode is not implemented yet"]
> ```

When will we unignore this?



_Code quote:_
```XML
    // TODO(Ohad): un-ignore.
    #[ignore = "mul small opcode is not implemented yet"]
```

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/219)* status: 1 of 12 files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/lib.rs` line 198 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/219#-ODFjfyv04WA3wZtzAmn:-ODG5C9t1a-Jhq24ZGoe:b-vltphr) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/1af7f7c2e742d37eb8be990bde722663ba16ac1b/stwo_cairo_prover/crates/prover/src/lib.rs#L198)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

When will we unignore this?
</blockquote></details>

it's stated in the ignore reason

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 10 of 12 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/219)* status: 11 of 12 files reviewed, 4 unresolved discussions (waiting on @ohad-starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo-cairo/219#-ODGcEZi0Vp_k0fzN0H7:-ODGcEZi0Vp_k0fzN0H8:bjhhez7) (no related file):*
I think Stav should check the changes in state_transitions.rs file
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_vector/mod.rs` line 78 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/219#-ODGbwoS2od3YDrmLwST:-ODGbwoS2od3YDrmLwSU:bj98euw) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ab85e9e2c25046c8b967bcf3c4ff0a3c4e7bbf8f/stwo_cairo_prover/crates/prover/src/components/range_check_vector/mod.rs#L78)):*
> ```XML
> generate_range_check_code!([4, 3]);
> generate_range_check_code!([6]);
> generate_range_check_code!([3]);
> ```

Does this work with current impl? (the N_LANES problem)



_Code quote:_
```XML
generate_range_check_code!([3]);
```
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/opcodes_air.rs` line 243 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/219#-ODGa4YU4XPAT77NLTtn:-ODGa4YU4XPAT77NLTto:b-strgtp) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/502d05bdf1d3dbf7bd960c20bcd8544a3bc956ff/stwo_cairo_prover/crates/prover/src/cairo_air/opcodes_air.rs#L243)):*
> ```XML
>                 input.casm_states_by_opcode.mul_opcode_is_small_t_is_imm_f,
>             ));
>         }
> ```

You also need to push here the big muls right?
Currently this only handles the small ones



_Code quote:_
```XML
        if !input
            .casm_states_by_opcode
            .mul_opcode_is_small_t_is_imm_f
            .is_empty()
        {
            mul_f_f.push(mul_opcode_is_small_f_is_imm_f::ClaimGenerator::new(
                input.casm_states_by_opcode.mul_opcode_is_small_t_is_imm_f,
            ));
        }
```
___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 26 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/219#-ODGbhmC7BMF0B98VVLQ:-ODGbhmC7BMF0B98VVLR:b4fr5ak) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ab85e9e2c25046c8b967bcf3c4ff0a3c4e7bbf8f/stwo_cairo_prover/crates/prover/src/components/mod.rs#L26)):*
> ```XML
> pub use memory::{memory_address_to_id, memory_id_to_big};
> pub use range_check_vector::{
>     range_check_19, range_check_3, range_check_4_3, range_check_6, range_check_7_2_5,
> ```

I thought we don't want to use that 



_Code quote:_
```XML
range_check_3,
```

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/219)* status: 11 of 12 files reviewed, 4 unresolved discussions (waiting on @shaharsamocha7 and @Stavbe)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo-cairo/219#-ODFl08x453rZLEeDBvm:-ODGZOL10YsiI_VSI_Ia:bmtnbi8) (no related file):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Here you only add large muls, right?
Don't we have the small mul yet?
</blockquote></details>

the air has rc3 in it and wer'e not supporting that yet
___
*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo-cairo/219#-ODGcEZi0Vp_k0fzN0H7:-ODGfsZU5Qa_cQFvysDi:bu7lex8) (no related file):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I think Stav should check the changes in state_transitions.rs file
</blockquote></details>

@Stavbe

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/219)* status: 11 of 12 files reviewed, 4 unresolved discussions (waiting on @shaharsamocha7 and @Stavbe)

___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/opcodes_air.rs` line 243 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/219#-ODGa4YU4XPAT77NLTtn:-ODH6ehr9AGBQeU05nri:b4zu289) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/502d05bdf1d3dbf7bd960c20bcd8544a3bc956ff/stwo_cairo_prover/crates/prover/src/cairo_air/opcodes_air.rs#L243)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

You also need to push here the big muls right?
Currently this only handles the small ones
</blockquote></details>

bug, done.

**Review by Stavbe — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/219)* status: 11 of 12 files reviewed, 4 unresolved discussions (waiting on @ohad-starkware, @shaharsamocha7, and @Stavbe)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo-cairo/219#-ODGcEZi0Vp_k0fzN0H7:-ODL6pwD8Yhtq4bvmTXB:bb7k0qh) (no related file):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

@Stavbe
</blockquote></details>

lgtm

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/219)* status: all files reviewed, 3 unresolved discussions (waiting on @ohad-starkware and @Stavbe)

___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 619 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/219#-ODLht9n9l1L5qGxWiwM:-ODLht9n9l1L5qGxWiwN:bxg7kb3) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/282d46c76184ba2abc56da7fbec553182748d6c0/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L619)):*
> ```XML
> // Returns 'true' if the a memory value is within the range of [-2^27, 2^27 - 1].
> fn is_small(val: MemoryValue) -> bool {
>     matches!(val, MemoryValue::Small(val) if (val as i128>= SMALL_MIN_VALUE as i128) && (val as i128 <= SMALL_MAX_VALUE as i128))
> ```

currently small values are in the range [0, 2**72),
Do we really support small negative values or should we drop it for now?



_Code quote:_
```XML
MemoryValue::Small(val) if (val as i128>= SMALL_MIN_VALUE as i128)
```
___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 619 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/219#-ODLi3XX9njPPUWCSWGW:-ODLi3XX9njPPUWCSWGX:b-k5dlaw) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/282d46c76184ba2abc56da7fbec553182748d6c0/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L619)):*
> ```XML
> // Returns 'true' if the a memory value is within the range of [-2^27, 2^27 - 1].
> fn is_small(val: MemoryValue) -> bool {
>     matches!(val, MemoryValue::Small(val) if (val as i128>= SMALL_MIN_VALUE as i128) && (val as i128 <= SMALL_MAX_VALUE as i128))
> ```

Can we test those functions?



_Code quote:_
```XML
// Returns 'true' if all the operands are within the range of [-2^27, 2^27 - 1].
fn are_small_operands(dst: MemoryValue, op0: MemoryValue, op1: MemoryValue) -> bool {
    is_small(dst) && is_small(op0) && is_small(op1)
}

// Returns 'true' if the a memory value is within the range of [-2^27, 2^27 - 1].
fn is_small(val: MemoryValue) -> bool {
    matches!(val, MemoryValue::Small(val) if (val as i128>= SMALL_MIN_VALUE as i128) && (val as i128 <= SMALL_MAX_VALUE as i128))
```
___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 216 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/219#-ODLiFu-3qgGKxKWtWdT:-ODLiFu-3qgGKxKWtWdU:b-2bihk7) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/282d46c76184ba2abc56da7fbec553182748d6c0/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L216)):*
> ```XML
>     }
> 
>     // When not ignored, the test passes only with dev_mod = false.
> ```

Why do we have this comment?
Either un-ignore it and use dev_mod=false
or just remove the ignore when it is supported.



_Code quote:_
```XML
// When not ignored, the test passes only with dev_mod = false.
```

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/219)* status: all files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7 and @Stavbe)

___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 619 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/219#-ODLht9n9l1L5qGxWiwM:-ODLjOpmEXAvrpF3KINi:b-ngdr72) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/282d46c76184ba2abc56da7fbec553182748d6c0/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L619)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

currently small values are in the range [0, 2**72),
Do we really support small negative values or should we drop it for now?
</blockquote></details>

its a different small, thats changes from stavs pr
___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 619 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/219#-ODLi3XX9njPPUWCSWGW:-ODLjT-a2w-4TmvrcQGC:bn5tqnq) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/282d46c76184ba2abc56da7fbec553182748d6c0/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L619)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can we test those functions?
</blockquote></details>

stavs pr 
___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 216 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/219#-ODLiFu-3qgGKxKWtWdT:-ODLjU2i8tdE_dz70EBV:b-d00ziu) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/282d46c76184ba2abc56da7fbec553182748d6c0/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L216)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Why do we have this comment?
Either un-ignore it and use dev_mod=false
or just remove the ignore when it is supported.
</blockquote></details>

stavs pr

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/219#-:-ODM60noBE1SK_Lpit9T:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ohad-starkware and @Stavbe)

___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 216 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/219#-ODLiFu-3qgGKxKWtWdT:-ODM5wCxCm601kYKAmH3:b-nvh9b) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/282d46c76184ba2abc56da7fbec553182748d6c0/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L216)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

stavs pr
</blockquote></details>

This should be removed from there as well
unblocking

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/219)* status: 12 of 13 files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7 and @Stavbe)

___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 216 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/219#-ODLiFu-3qgGKxKWtWdT:-ODMWgVHDA-H-41PFPmP:bjot0az) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/282d46c76184ba2abc56da7fbec553182748d6c0/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L216)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

This should be removed from there as well
unblocking
</blockquote></details>

will be removed with all the dev mode stuff soon enough

**Comment by ohad-starkware** [comment]
### Merge activity

* **Dec 5, 10:57 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/219).

**Pull request merged**
