### PR TITLE
Use BoundedInt to implement m31.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/204)

### CODE REVIEW

**Review by andrewmilson — CHANGES_REQUESTED** [review]
> Reviewed 4 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/204)* status: 4 of 10 files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`stwo_cairo_verifier/src/fields/m31.cairo` line 10 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/204#-OCn7oTt2Mz0rlbyyQ8A:-OCn7oTt2Mz0rlbyyQ8B:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c434888d8afd7556fe507c8d0a6d0186edd60b3b/stwo_cairo_verifier/src/fields/m31.cairo#L10)):*
> ```Cairo
> 
> type M31InnerT = BoundedInt<0, { P - 1 }>;
> #[derive(Copy, Drop, Debug, PartialEq, Serde)]
> ```





_Suggestion:_
```Cairo
type M31InnerT = BoundedInt<0, { P - 1 }>;

#[derive(Copy, Drop, Debug, PartialEq, Serde)]
```
___
*[`stwo_cairo_verifier/src/fields/m31.cairo` line 206 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/204#-OCnB6Uo2W4RucVxBuG-:-OCnB6Uo2W4RucVxBuG0:b-ygcuy) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c434888d8afd7556fe507c8d0a6d0186edd60b3b/stwo_cairo_verifier/src/fields/m31.cairo#L206)):*
> ```Cairo
> const M31_P: ConstValue<0x7fffffff> = 0x7fffffff;
> 
> impl DivRemU32ByP of DivRemHelper<u32, ConstValue<0x7fffffff>> {
> ```

Const declared for this?



_Code quote:_
```Cairo
0x7fffffff
```
___
*[`stwo_cairo_verifier/src/fields/m31.cairo` line 212 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/204#-OCnB949Euie6rijQALT:-OCnB949Euie6rijQALU:b-m73pba) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c434888d8afd7556fe507c8d0a6d0186edd60b3b/stwo_cairo_verifier/src/fields/m31.cairo#L212)):*
> ```Cairo
> 
> impl DivRemU64ByP of DivRemHelper<u64, ConstValue<0x7fffffff>> {
>     type DivT = BoundedInt<0, 0x200000004>;
> ```

Comment explaining what the number is?



_Code quote:_
```Cairo
0x200000004
```
___
*[`stwo_cairo_verifier/src/fields/m31.cairo` line 217 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/204#-OCnB9pt52B7cfFWPiau:-OCnAwNlBbe3iADt0Oi8:brhun0a) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c434888d8afd7556fe507c8d0a6d0186edd60b3b/stwo_cairo_verifier/src/fields/m31.cairo#L217)):*
> ```Cairo
> 
> impl DivRemU128ByP of DivRemHelper<u128, ConstValue<0x7fffffff>> {
>     type DivT = BoundedInt<0, 0x2000000040000000800000010>;
> ```

Same here?
___
*[`stwo_cairo_verifier/bounded_int/src/lib.cairo` line 1 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/204#-OCn7PY19fxKuNda1tU4:-OCn7PY19fxKuNda1tU5:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c434888d8afd7556fe507c8d0a6d0186edd60b3b/stwo_cairo_verifier/bounded_int/src/lib.cairo#L1)):*
> ```Cairo
> // An helper crate that exposes internal corelib function.
> ```





_Suggestion:_
```Cairo
A
```

**Review by andrewmilson — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/204#-:-OCnFAra3vzM2HMEBsQq:bnfp4nl)* status: 4 of 10 files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/204)* status: 3 of 10 files reviewed, 5 unresolved discussions (waiting on @andrewmilson)

___
*[`stwo_cairo_verifier/src/fields/m31.cairo` line 206 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/204#-OCnB6Uo2W4RucVxBuG-:-OCnLkEo0OSNtJ-8tAVN:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c434888d8afd7556fe507c8d0a6d0186edd60b3b/stwo_cairo_verifier/src/fields/m31.cairo#L206)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Const declared for this?
</blockquote></details>

Done.
___
*[`stwo_cairo_verifier/src/fields/m31.cairo` line 212 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/204#-OCnB949Euie6rijQALT:-OCnLkda6ap30rzK84MN:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c434888d8afd7556fe507c8d0a6d0186edd60b3b/stwo_cairo_verifier/src/fields/m31.cairo#L212)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Comment explaining what the number is?
</blockquote></details>

Done.
___
*[`stwo_cairo_verifier/src/fields/m31.cairo` line 217 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/204#-OCnB9pt52B7cfFWPiau:-OCnLl5g4VYZTremKpS3:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c434888d8afd7556fe507c8d0a6d0186edd60b3b/stwo_cairo_verifier/src/fields/m31.cairo#L217)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Same here?
</blockquote></details>

Done.
___
*[`stwo_cairo_verifier/src/fields/m31.cairo` line 10 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/204#-OCn7oTt2Mz0rlbyyQ8A:-OCnKVvCABOC0Nv7kDOT:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c434888d8afd7556fe507c8d0a6d0186edd60b3b/stwo_cairo_verifier/src/fields/m31.cairo#L10)):*
> ```Cairo
> 
> type M31InnerT = BoundedInt<0, { P - 1 }>;
> #[derive(Copy, Drop, Debug, PartialEq, Serde)]
> ```

Done.

**Comment by maciektr** [comment]
*[`stwo_cairo_verifier/bounded_int/Scarb.lock` line 0 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/204#-OCnYxPd9zwxPeD9Ipdy:-OCnYxPd9zwxPeD9Ipdz:b5zss3) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/b7c8ea0a8c44b76cae6393d202837cf97cd64c3f/stwo_cairo_verifier/bounded_int/Scarb.lock#L0)):*
I don't think you need this - there should only be one  `Scarb.lock` file for a workspace.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/204)* status: 3 of 10 files reviewed, 6 unresolved discussions (waiting on @andrewmilson and @maciektr)

___
*[`stwo_cairo_verifier/bounded_int/Scarb.lock` line  at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/204#-OCnYxPd9zwxPeD9Ipdy:-OCnaYk34vUUn6380niJ:b-9m7u8a) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/b7c8ea0a8c44b76cae6393d202837cf97cd64c3f/stwo_cairo_verifier/bounded_int/Scarb.lock#L)):*
<details><summary><i>Previously, maciektr (maciektr) wrote…</i></summary><blockquote>

I don't think you need this - there should only be one  `Scarb.lock` file for a workspace.
</blockquote></details>

removed, thanks.
___
*[`stwo_cairo_verifier/bounded_int/src/lib.cairo` line 1 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/204#-OCn7PY19fxKuNda1tU4:-OCnaXF24ihwXPcP1pXe:b-no9x65) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c434888d8afd7556fe507c8d0a6d0186edd60b3b/stwo_cairo_verifier/bounded_int/src/lib.cairo#L1)):*
> ```Cairo
> // An helper crate that exposes internal corelib function.
> ```

rephrased

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 10 files at r1, 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/204)* status: 9 of 10 files reviewed, 8 unresolved discussions (waiting on @andrewmilson, @ilyalesokhin-starkware, and @maciektr)

___
*[`stwo_cairo_verifier/src/fields/m31.cairo` line 155 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/204#-OCrTewK8phYPXVLF7qm:-OCrTewK8phYPXVLF7qn:be7neq5) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/fb29bb771a0048858e1716e2d3eddf2ca8a1ccd6/stwo_cairo_verifier/src/fields/m31.cairo#L155)):*
> ```Cairo
>     fn ge(lhs: M31, rhs: M31) -> bool {
>         upcast::<_, u32>(lhs.inner) >= upcast(rhs.inner)
>     }
> ```

i believe you can remove this.
___
*[`stwo_cairo_verifier/bounded_int/src/lib.cairo` line 2 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/204#-OCrQgCQ-BMLjAo4f_uF:-OCrQgCR-WAXrwSXqcCl:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/fb29bb771a0048858e1716e2d3eddf2ca8a1ccd6/stwo_cairo_verifier/bounded_int/src/lib.cairo#L2)):*
> ```Cairo
> // Utility crate that exposes internal corelib function.
> // This crate is compiled with an older edition that does not enforce visibity rules.
> ```





_Suggestion:_
```Cairo
///! Utility crate that exposes internal corelib function.
///! This crate is compiled with an older edition that does not enforce visibity rules.
```

**Comment by ilyalesokhin-starkware** [comment]
*[`stwo_cairo_verifier/src/fields/m31.cairo` line 155 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/204#-OCrTewK8phYPXVLF7qm:-OD07EBh8_2EmTbR5w0P:b45h) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/fb29bb771a0048858e1716e2d3eddf2ca8a1ccd6/stwo_cairo_verifier/src/fields/m31.cairo#L155)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i believe you can remove this.
</blockquote></details>





_Code snippet:_
```Cairo
error: Trait has no implementation in context: core::traits::PartialOrd::<core::internal::bounded_int::BoundedInt::<0, 2147483646>>.
 --> /home/ilya/workspaces/stwo-cairo/stwo_cairo_verifier/src/fields/m31.cairo:158:9
        lhs.inner < rhs.inner
        ^*******************^
```

**Comment by ilyalesokhin-starkware** [comment]
*[`stwo_cairo_verifier/src/fields/m31.cairo` line 155 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/204#-OCrTewK8phYPXVLF7qm:-OD507OOEL_xc6ApIiv7:b46ss4) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/fb29bb771a0048858e1716e2d3eddf2ca8a1ccd6/stwo_cairo_verifier/src/fields/m31.cairo#L155)):*
> ```Cairo
>     fn ge(lhs: M31, rhs: M31) -> bool {
>         upcast::<_, u32>(lhs.inner) >= upcast(rhs.inner)
>     }
> ```

I'd rather keep it like other places.

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/204)* status: 9 of 10 files reviewed, 6 unresolved discussions (waiting on @andrewmilson and @maciektr)

___
*[`stwo_cairo_verifier/bounded_int/src/lib.cairo` line 2 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/204#-OCrQgCQ-BMLjAo4f_uF:-OD52nON8G_eS3pZy_K7:b-u33adk) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/fb29bb771a0048858e1716e2d3eddf2ca8a1ccd6/stwo_cairo_verifier/bounded_int/src/lib.cairo#L2)):*
> ```Cairo
> // Utility crate that exposes internal corelib function.
> // This crate is compiled with an older edition that does not enforce visibity rules.
> ```

! Not an additional /

**Comment by ilyalesokhin-starkware** [comment]
*[`stwo_cairo_verifier/bounded_int/src/lib.cairo` line 2 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/204#-OCrQgCQ-BMLjAo4f_uF:-OD5i_Q21e0mRkZ8izFi:b-7jck7c) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/fb29bb771a0048858e1716e2d3eddf2ca8a1ccd6/stwo_cairo_verifier/bounded_int/src/lib.cairo#L2)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

! Not an additional /
</blockquote></details>

how many `/` do I need?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/204)* status: 9 of 10 files reviewed, 6 unresolved discussions (waiting on @andrewmilson and @maciektr)

___
*[`stwo_cairo_verifier/bounded_int/src/lib.cairo` line 2 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/204#-OCrQgCQ-BMLjAo4f_uF:-OD5lvCw-SsuXlZcCc0Y:b-7uyedi) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/fb29bb771a0048858e1716e2d3eddf2ca8a1ccd6/stwo_cairo_verifier/bounded_int/src/lib.cairo#L2)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

how many `/` do I need?
</blockquote></details>

`//!`

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/204)* status: all files reviewed (commit messages unreviewed), 6 unresolved discussions (waiting on @andrewmilson and @maciektr)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/204)* status: 8 of 10 files reviewed, 6 unresolved discussions (waiting on @andrewmilson, @maciektr, and @orizi)

___
*[`stwo_cairo_verifier/bounded_int/src/lib.cairo` line 2 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/204#-OCrQgCQ-BMLjAo4f_uF:-OD6KU4N93rQT77tUSCO:bb7f2mf) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/fb29bb771a0048858e1716e2d3eddf2ca8a1ccd6/stwo_cairo_verifier/bounded_int/src/lib.cairo#L2)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

`//!`
</blockquote></details>

done

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/204#-:-OD6XF2z2zV8t1I-_mWn:bnfp4nl)* status: 9 of 10 files reviewed, 6 unresolved discussions (waiting on @andrewmilson and @maciektr)

**Pull request merged**
