### PR TITLE
Add LinePoly

### PR DESCRIPTION
**Pull request by ajgara**
Add the implementation of `LinePoly` and `eval_at_point`, as needed for the Fri Verifier.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/26)

### CODE REVIEW

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/26)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @ajgara)

___
*[`stwo_cairo_verifier/src/poly/line.cairo` line 6 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/26#-O2PVPqFE6inTZ7OojiW:-O2PVPqFE6inTZ7OojiX:bh44hcv) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/0d6d3a9bd042b9889ecd683fbd0d8a5a7f9fec43/stwo_cairo_verifier/src/poly/line.cairo#L6)):*
> ```Cairo
> #[derive(Drop, Clone)]
> pub struct LinePoly {
>     pub coeffs: Array<SecureField>,
> ```

Those are in bit-reverse order, right?
Please add documentation



_Code quote:_
```Cairo
pub coeffs: Array<SecureField>,
```
___
*[`stwo_cairo_verifier/src/poly/line.cairo` line 16 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/26#-O2PT-xSAmm2xVd59l7z:-O2PT-xSAmm2xVd59l8-:b-jzhqvq) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/0d6d3a9bd042b9889ecd683fbd0d8a5a7f9fec43/stwo_cairo_verifier/src/poly/line.cairo#L16)):*
> ```Cairo
>     }
> 
>     fn eval_at_point(self: @LinePoly, mut x: SecureField) -> SecureField {
> ```

Add a TODO to consider replacing the eval_at_point with fft



_Code quote:_
```Cairo
 fn eval_at_point(self: @LinePoly, mut x: SecureField) -> SecureField {
```
___
*[`stwo_cairo_verifier/src/poly/line.cairo` line 21 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/26#-O2PTTcb4oW7M4kQfWq6:-O2PTTcb4oW7M4kQfWq7:b-j4wxph) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/0d6d3a9bd042b9889ecd683fbd0d8a5a7f9fec43/stwo_cairo_verifier/src/poly/line.cairo#L21)):*
> ```Cairo
>         while i < *self.log_size {
>             mappings.append(x);
>             x = m31(2).into() * x * x - m31(1).into();
> ```

more efficient



_Suggestion:_
```Cairo
let x_square = x * x; 
x = x_square + x_square - m31(1).into();
```
___
*[`stwo_cairo_verifier/src/poly/line.cairo` line 40 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/26#-O2PWAakA2w1BdSFrRYb:-O2PWAakA2w1BdSFrRYc:b8ly36i) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/0d6d3a9bd042b9889ecd683fbd0d8a5a7f9fec43/stwo_cairo_verifier/src/poly/line.cairo#L40)):*
> ```Cairo
>         };
> 
>         *level[0]
> ```

Add an assert that level is of length 1.



_Code quote:_
```Cairo
        *level[0]
```

**Review by shaharsamocha7 — COMMENTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/26)* status: all files reviewed, 4 unresolved discussions (waiting on @ajgara)

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/26)* status: all files reviewed, 1 unresolved discussion (waiting on @ajgara)

___
*[`stwo_cairo_verifier/src/poly/line.cairo` line 13 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/26#-O2sA5t26HyqmyFtkROQ:-O2sA5t26HyqmyFtkROR:bh0dl7l) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/5def40ecef99c1c3f2d2c7cb6890ae4dfe4be66c/stwo_cairo_verifier/src/poly/line.cairo#L13)):*
> ```Cairo
> /// reversed order is {b₀, b₄, b₂, b₆}.
> /// Then, the polynomial p represented by coeffs = [a₀, a₁, a₂, a₃] and log_size = 2 is
> /// p = a₀ * b₀ + a₁ * b₄ + a₂ * b₂ + a₃ * b₆.
> ```

Please avoid of using unicode chars.
I think that the first line is enough for this doc.



_Suggestion:_
```Cairo
/// A univariate polynomial represented by its coefficients in the line part of the FFT-basis
/// in bit reversed order.
```

**Comment by schouhy** [comment]
Sure! done.

**Review by andrewmilson — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/26)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @ajgara and @shaharsamocha7)

___
*[`stwo_cairo_verifier/src/poly/line.cairo` line 42 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/26#-O4TC2kS5qYzrzuEipr-:-O4TC2kS5qYzrzuEipr0:bunv4e1) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/7890432676bf003f739bfed3b3bfe8a264ade7c0/stwo_cairo_verifier/src/poly/line.cairo#L42)):*
> ```Cairo
>             };
>             level = new_level;
>         };
> ```

Can this be done recursively to reflect the code in the Rust implementation https://github.com/starkware-libs/stwo/blob/e4014820ee79ab32025d9bcb80d1bfe8d277d61b/src/core/poly/line.rs#L106



_Code quote:_
```Cairo
        let mappings = @mappings;
        let mut i = mappings.len();
        while i > 0 {
            i -= 1;
            let mut new_level = array![];
            let mut j = 0;
            while j < level.len() {
                new_level.append(*level[j] + *mappings[i] * *level[j + 1]);
                j += 2;
            };
            level = new_level;
        };
```
___
*[`stwo_cairo_verifier/src/poly/line.cairo` line 65 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/26#-O4TDGlD1OdFW3UznizW:-O4TDGlD1OdFW3UznizX:byqkfjh) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/7890432676bf003f739bfed3b3bfe8a264ade7c0/stwo_cairo_verifier/src/poly/line.cairo#L65)):*
> ```Cairo
>         };
>         let x = m31(590768354);
>         let result = line_poly.eval_at_point(x.into());
> ```

Arrange Act Assert



_Suggestion:_
```Cairo
   
   let result = line_poly.eval_at_point(x.into());
   
```
___
*[`stwo_cairo_verifier/src/poly/line.cairo` line 76 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/26#-O4TDCV73YYGSgCQEIKQ:-O4TDCV73YYGSgCQEIKR:byqkfjh) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/7890432676bf003f739bfed3b3bfe8a264ade7c0/stwo_cairo_verifier/src/poly/line.cairo#L76)):*
> ```Cairo
>         };
>         let x = m31(10);
>         let result = line_poly.eval_at_point(x.into());
> ```

Arrange Act Assert



_Suggestion:_
```Cairo
        
        let result = line_poly.eval_at_point(x.into());
        
```

**Review by ajgara — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/26)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

___
*[`stwo_cairo_verifier/src/poly/line.cairo` line 13 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/26#-O2sA5t26HyqmyFtkROQ:-O3IgIbK5eDV7rHjgdoS:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/5def40ecef99c1c3f2d2c7cb6890ae4dfe4be66c/stwo_cairo_verifier/src/poly/line.cairo#L13)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Please avoid of using unicode chars.
I think that the first line is enough for this doc.
</blockquote></details>

Done.
___
*[`stwo_cairo_verifier/src/poly/line.cairo` line 42 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/26#-O4TC2kS5qYzrzuEipr-:-O5FGTsRDi9KZHq0LOgZ:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/7890432676bf003f739bfed3b3bfe8a264ade7c0/stwo_cairo_verifier/src/poly/line.cairo#L42)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Can this be done recursively to reflect the code in the Rust implementation https://github.com/starkware-libs/stwo/blob/e4014820ee79ab32025d9bcb80d1bfe8d277d61b/src/core/poly/line.rs#L106
</blockquote></details>

Done.
___
*[`stwo_cairo_verifier/src/poly/line.cairo` line 65 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/26#-O4TDGlD1OdFW3UznizW:-O5FGF8-2m9CHwl50UBF:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/7890432676bf003f739bfed3b3bfe8a264ade7c0/stwo_cairo_verifier/src/poly/line.cairo#L65)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Arrange Act Assert
</blockquote></details>

Done.
___
*[`stwo_cairo_verifier/src/poly/line.cairo` line 76 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/26#-O4TDCV73YYGSgCQEIKQ:-O5FGE5B89iR-fiBwbyK:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/7890432676bf003f739bfed3b3bfe8a264ade7c0/stwo_cairo_verifier/src/poly/line.cairo#L76)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Arrange Act Assert
</blockquote></details>

Done.

**Review by ajgara — COMMENTED** [review]
Let us know if there's anything else to improve! I'm not used to this tool haha.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/26#-:-O5OAZmH5MA9uT5N1Dno:b4xz0jp)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

**Review by andrewmilson — APPROVED** [review]
:lgtm: with comments

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/26#-:-O6oMreq46VA8f4sdLT2:bvaci67)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @ajgara and @shaharsamocha7)

___
*[`stwo_cairo_verifier/src/poly/line.cairo` line 1 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/26#-O6Zf3kU35xZ3t7mXeTy:-O6Zf3kU35xZ3t7mXeTz:bwhauqh) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/532e33fb18f6e8e158158277d0ed4c89a76b68b8/stwo_cairo_verifier/src/poly/line.cairo#L1)):*
> ```Cairo
> use core::array::ArrayTrait;
> ```

Is this needed?
___
*[`stwo_cairo_verifier/src/poly/line.cairo` line 20 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/26#-O6Zem1V-akhIvn_jW9X:-O6Zem1V-akhIvn_jW9Y:b-8pw7lf) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/532e33fb18f6e8e158158277d0ed4c89a76b68b8/stwo_cairo_verifier/src/poly/line.cairo#L20)):*
> ```Cairo
>     }
> 
>     // TODO: Consider replacing with FFT.
> ```

I don't think "replacing with FFT" is necessary. The protocol only uses LinePoly to evaluate at a single point.
___
*[`stwo_cairo_verifier/src/poly/utils.cairo` line 4 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/26#-O6oMnlJ4jE6VLtwdNPP:-O6Zf7xHA7t8APBR_sfA:b-7yjtq1) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/532e33fb18f6e8e158158277d0ed4c89a76b68b8/stwo_cairo_verifier/src/poly/utils.cairo#L4)):*
> ```Cairo
> 
> 
> pub fn fold(
> ```

Please copy over docs from rust.

**Review by carlogf — COMMENTED** [review]
Hi! I addressed the comments and rebased with the last commit in main

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/26#-:-O7-UwmrD1ZgzSI97NFr:bpbyzm1)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @ajgara, @andrewmilson, and @shaharsamocha7)

___
*[`stwo_cairo_verifier/src/poly/line.cairo` line 1 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/26#-O6Zf3kU35xZ3t7mXeTy:-O7-U6Yg419D1gsVi63q:byjnu5i) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/532e33fb18f6e8e158158277d0ed4c89a76b68b8/stwo_cairo_verifier/src/poly/line.cairo#L1)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Is this needed?
</blockquote></details>

Not needed, removed it
___
*[`stwo_cairo_verifier/src/poly/line.cairo` line 20 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/26#-O6Zem1V-akhIvn_jW9X:-O7-UQzz41T6oTMHfAaE:b-codgm7) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/532e33fb18f6e8e158158277d0ed4c89a76b68b8/stwo_cairo_verifier/src/poly/line.cairo#L20)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

I don't think "replacing with FFT" is necessary. The protocol only uses LinePoly to evaluate at a single point.
</blockquote></details>

makes sense :)

**Review by shaharsamocha7 — COMMENTED** [review]
> Reviewed 2 of 4 files at r5, 1 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/26)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @ajgara, @andrewmilson, and @carlogf)

**Review by shaharsamocha7 — APPROVED** [review]
> Reviewed 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/26)* status: all files reviewed, 4 unresolved discussions (waiting on @ajgara and @andrewmilson)

**Pull request merged**
