### PR TITLE
Write memory interaction trace.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/23)

### CODE REVIEW

**Comment by alonh5** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/23?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#23** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/23?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#19** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/19?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#18** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/18?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#17** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/17?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#16** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/16?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#13** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/13?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#12** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/12?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#11** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/11?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#14** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/14?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alonh5 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/23)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @alonh5 and @spapinistarkware)

___
*[`stwo_cairo_prover/src/components/memory/component.rs` line 102 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/23#-O1vgAHJ4u6g2idImwaI:-O1vgAHJ4u6g2idImwaJ:brqlu9m) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/d107cac7cdab00346383806ba9c1f8b319dd1b8e/stwo_cairo_prover/src/components/memory/component.rs#L102)):*
> ```XML
>     }
> 
>     fn write_interaction_trace(
> ```

Add a test that the interaction trace is correct



_Code quote:_
```XML
fn write_interaction_trace(
```
___
*[`stwo_cairo_prover/src/components/memory/component.rs` line 120 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/23#-O1vfIxP12ovyKnETZyA:-O1vfIxQBsbjmKkfXak8:b1l435f) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/d107cac7cdab00346383806ba9c1f8b319dd1b8e/stwo_cairo_prover/src/components/memory/component.rs#L120)):*
> ```XML
>         let mut denom_inverses = vec![SecureField::zero(); denoms.len()];
>         SecureField::batch_inverse(&denoms, &mut denom_inverses);
>         let mut logup_values = vec![SecureField::zero(); trace[MULTIPLICITY_COLUMN].values.len()];
> ```

consider storing the length only once at the start and use it in all places.



_Code quote:_
```XML
trace[MULTIPLICITY_COLUMN].values.len()
```
___
*[`stwo_cairo_prover/src/components/memory/component.rs` line 123 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/23#-O1vg-Y44tO_UGirfYau:-O1vg-Y44tO_UGirfYav:by6emtv) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/d107cac7cdab00346383806ba9c1f8b319dd1b8e/stwo_cairo_prover/src/components/memory/component.rs#L123)):*
> ```XML
>         let mut last = SecureField::zero();
>         let log_size = interaction_trace_domain.log_size();
>         for i in 0..trace[MULTIPLICITY_COLUMN].values.len() {
> ```

consider to change



_Suggestion:_
```XML
for (index, multiplicity) in trace[MULTIPLICITY_COLUMN].values.enumerate() {
```
___
*[`stwo_cairo_prover/src/components/memory/component.rs` line 125 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/23#-O1vfY0uB0edsB-Ju2y_:-O1vfY0vEVVrRnhL169u:by6emtv) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/d107cac7cdab00346383806ba9c1f8b319dd1b8e/stwo_cairo_prover/src/components/memory/component.rs#L125)):*
> ```XML
>         for i in 0..trace[MULTIPLICITY_COLUMN].values.len() {
>             let index = coset_order_to_circle_domain_order_index(i, log_size);
>             let index = bit_reverse_index(index, log_size);
> ```

consider to change



_Suggestion:_
```XML
            let next_index = bit_reverse_index(coset_order_to_circle_domain_order_index(i, log_size), log_size);
        
```

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/23#-:-O1zjZeM73xp4fdDAGYc:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @alonh5)

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/23)* status: all files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7)

___
*[`stwo_cairo_prover/src/components/memory/component.rs` line 120 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/23#-O1vfIxP12ovyKnETZyA:-O1zqieHCuG6XKWmZri0:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/9bd984f3ccc298856610622380a738886f717f78/stwo_cairo_prover/src/components/memory/component.rs#L120)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

consider storing the length only once at the start and use it in all places.
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/src/components/memory/component.rs` line 123 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/23#-O1vg-Y44tO_UGirfYau:-O1zrStt-rm6TE9UrjeH:b-sju0ny) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/9bd984f3ccc298856610622380a738886f717f78/stwo_cairo_prover/src/components/memory/component.rs#L123)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

consider to change
</blockquote></details>

I'm indexing multiple vectors so I find it more readable and cleaner as a regular for loop over i.

**Review by shaharsamocha7 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/23)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/23)* status: all files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

___
*[`stwo_cairo_prover/src/components/memory/component.rs` line 102 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/23#-O1vgAHJ4u6g2idImwaI:-O2-BagH3XupfEcVfKga:blo197g) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/9bd984f3ccc298856610622380a738886f717f78/stwo_cairo_prover/src/components/memory/component.rs#L102)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Add a test that the interaction trace is correct
</blockquote></details>

Added a test in PR 27.

**Review by shaharsamocha7 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/23)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Comment by alonh5** [comment]
### Merge activity

* **Jul 17, 6:36 AM EDT**: @alonh5 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/23).

**Pull request merged**
