### PR TITLE
Example fibonacci

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/51)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
* **#51** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/51?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 28 of 30 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/51)* status: all files reviewed, 3 unresolved discussions (waiting on @Alon-Ti, @andrewmilson, @ohad-starkware, and @spapinistarkware)

___
*[`stwo_cairo_prover/crates/runner/examples/fibonacci.rs` line 5 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/51#-O4Ki-nPBwcJDVRPIg9X:-O4Ki-nPBwcJDVRPIg9Y:b-lak7s3) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/aa98f8a40b8069e2446d51dcd1a79f4f457f575f/stwo_cairo_prover/crates/runner/examples/fibonacci.rs#L5)):*
> ```XML
> use stwo_cairo_runner::input_from_plain_casm;
> 
> fn main() {
> ```

Is this tested?



_Code quote:_
```XML
main()
```
___
*[`stwo_cairo_prover/crates/runner/src/lib.rs` line 16 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/51#-O4KiJbl54O9zCSOItDt:-O4KiJbl54O9zCSOItDu:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/aa98f8a40b8069e2446d51dcd1a79f4f457f575f/stwo_cairo_prover/crates/runner/src/lib.rs#L16)):*
> ```XML
>     let felt_code = casm
>         .into_iter()
>         .flat_map(|i| i.assemble().encode())
> ```





_Suggestion:_
```XML
instruction
```
___
*[`stwo_cairo_prover/crates/runner/src/lib.rs` line 17 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/51#-O4KiNcfCDd2rsJds_k4:-O4KiNcfCDd2rsJds_k5:bb7g558) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/aa98f8a40b8069e2446d51dcd1a79f4f457f575f/stwo_cairo_prover/crates/runner/src/lib.rs#L17)):*
> ```XML
>         .into_iter()
>         .flat_map(|i| i.assemble().encode())
>         .map(|i| MaybeRelocatable::Int(i.into()))
> ```

felt



_Code quote:_
```XML
i
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/51)* status: all files reviewed, 1 unresolved discussion (waiting on @Alon-Ti, @alonh5, @andrewmilson, and @ohad-starkware)

___
*[`stwo_cairo_prover/crates/runner/examples/fibonacci.rs` line 5 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/51#-O4Ki-nPBwcJDVRPIg9X:-O4Kku7_1QslY3yeKKcl:b7xc1u1) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/aa98f8a40b8069e2446d51dcd1a79f4f457f575f/stwo_cairo_prover/crates/runner/examples/fibonacci.rs#L5)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Is this tested?
</blockquote></details>

Can't test an example apparently

**Review by alonh5 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/51#-:-O4Km1ttEQ-PYwByzL5I:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Alon-Ti, @andrewmilson, and @ohad-starkware)

**Comment by spapinistarkware** [comment]
### Merge activity

* **Aug 15, 7:30 AM EDT**: @spapinistarkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/51).

**Pull request merged**
