### PR TITLE
tracking relations

### PR DESCRIPTION
**Pull request by ohad-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/229)

### CODE REVIEW

**Comment by ohad-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/229?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#229** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/229?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/229?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#222** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/222?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#228** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/228?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#221** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/221?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#220** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/220?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#219** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/219?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#218** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/218?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#217** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/217?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#216** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/216?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#215** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/215?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#214** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/214?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#209** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/209?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#208** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/208?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#207** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/207?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#206** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/206?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by Alon-Ti — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/229)* status: all files reviewed, 2 unresolved discussions (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/debug.rs` line 46 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/229#-ODL8y2SBylo0jqj_WYJ:-ODL8y2SBylo0jqj_WYK:b-o81vq5) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/279e0f1f6d422a23fa6a4d1d8882ed3126afdc1a/stwo_cairo_prover/crates/prover/src/cairo_air/debug.rs#L46)):*
> ```XML
>     });
>     let evals = &evals.as_ref();
>     let trace = &(evals).into();
> ```

Check if there's a less confusing way to write this (`(&evals)`?)
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/debug.rs` line 67 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/229#-ODL9cLnCVpA1ngQbIBL:-ODL9cLnCVpA1ngQbIBM:b-om9iq) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/279e0f1f6d422a23fa6a4d1d8882ed3126afdc1a/stwo_cairo_prover/crates/prover/src/cairo_air/debug.rs#L67)):*
> ```XML
>         );
>     }
>     for claim in claim.opcodes.add_f_t.clone() {
> ```

Macro these out?

Maybe even possible with regular code if `Eval`s had some sort of common trait.

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/229)* status: all files reviewed, 2 unresolved discussions (waiting on @Alon-Ti)

___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/debug.rs` line 46 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/229#-ODL8y2SBylo0jqj_WYJ:-ODLdxWm86QMxxbnMOo5:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e631f0a6093dde7c195304233d51f1664d0d0cf3/stwo_cairo_prover/crates/prover/src/cairo_air/debug.rs#L46)):*
<details><summary><i>Previously, Alon-Ti wrote…</i></summary><blockquote>

Check if there's a less confusing way to write this (`(&evals)`?)
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/debug.rs` line 67 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/229#-ODL9cLnCVpA1ngQbIBL:-ODLdbjBDOHH-SxiWWOl:bsouvzd) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e631f0a6093dde7c195304233d51f1664d0d0cf3/stwo_cairo_prover/crates/prover/src/cairo_air/debug.rs#L67)):*
<details><summary><i>Previously, Alon-Ti wrote…</i></summary><blockquote>

Macro these out?

Maybe even possible with regular code if `Eval`s had some sort of common trait.
</blockquote></details>

evals need to expose n_calls for that
I think we would have that eventually, and I don't want to write a macro for this (different attributes). added a TODO stating I'm not happy about it.

**Review by Alon-Ti — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/229#-:-ODLgQzb0YeWlQyvCAuT:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/debug.rs` line 67 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/229#-ODL9cLnCVpA1ngQbIBL:-ODLgKxH3Efy-t24ZTsn:b-dxcbts) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e631f0a6093dde7c195304233d51f1664d0d0cf3/stwo_cairo_prover/crates/prover/src/cairo_air/debug.rs#L67)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

evals need to expose n_calls for that
I think we would have that eventually, and I don't want to write a macro for this (different attributes). added a TODO stating I'm not happy about it.
</blockquote></details>

Makes sense.

**Review by Alon-Ti — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/229#-:-ODM5z7nBOs3uBtoD5ZN:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ohad-starkware)

**Review by Alon-Ti — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/229)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ohad-starkware)

**Comment by ohad-starkware** [comment]
### Merge activity

* **Dec 8, 10:20 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/229).

**Pull request merged**
