### PR TITLE
allow biguint to output 12 bit children

### PR DESCRIPTION
**Pull request by ohad-nir-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/195)

### CODE REVIEW

**Review by anatgstarkware — CHANGES_REQUESTED** [review]
Where do you use this?
Please remove the content of pr 183 from here
Please add @DavidLevitGurevich as a reviewer

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/195#-:-OCYCjMS9o2Tz-50ioB6:bfkc1t9)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @az-starkware)

**Review by DavidLevitGurevich — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/195)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @az-starkware and @ohad-nir-starkware)

___
*[`stwo_cairo_prover/crates/prover_types/src/cpu.rs` line 606 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/195#-OCc6-bc58xK8Up5ar7R:-OCc6-bd5Siul5pblZS3:bebd9cd) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/1ef5bf5e91ff7491c462b2696d041f4d78968e74/stwo_cairo_prover/crates/prover_types/src/cpu.rs#L606)):*
> ```XML
>     pub fn get_m31(&self, index: usize) -> M31 {
>         let mask = (1u64 << CHILD_BITS) - 1;
>         let shift = CHILD_BITS * index;
> ```

what should the function do? (there is nontrivial logic here and I don't fully understand the goal so I find it hard to check)

**Review by anatgstarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/195)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @az-starkware, @DavidLevitGurevich, and @ohad-nir-starkware)

___
*[`stwo_cairo_prover/crates/prover_types/src/cpu.rs` line 559 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/195#-OD_uHpY7C-ZASGobqq9:-OD_uHpZ6jMlnuw7383E:b-5bfynj) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/486465d8710545280c414991d449d7b99e9cee68/stwo_cairo_prover/crates/prover_types/src/cpu.rs#L559)):*
> ```XML
> 
> #[derive(Copy, Clone, Debug, Eq, PartialEq, Hash)]
> pub struct BigUInt<const B: usize, const L: usize> {
> ```

please add another const to biguint `const F: usize`
and add documentation that explains that B is the total num of bits, L is num of 64-bit UInt64 limbs and F is num of 12-bit M31 limbs
___
*[`stwo_cairo_prover/crates/prover_types/src/cpu.rs` line 603 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/195#-OD_tCOj2t6hILJb0LmG:-OD_tCOj2t6hILJb0LmH:b-oo1iks) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/486465d8710545280c414991d449d7b99e9cee68/stwo_cairo_prover/crates/prover_types/src/cpu.rs#L603)):*
> ```XML
> // Length of each modulo builtin word in bits.
> pub const MOD_BUILTIN_WORD_BIT_LEN: usize = 96;
> const CHILD_BITS: usize = 12;
> ```

let's call it `BIGUINT_BITS_PER_M31` or something like that (`CHILD` is not clear)
let's make it pub
also, can you please move these consts to the top of biguint?

**Review by ohad-nir-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/195)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @anatgstarkware, @az-starkware, and @DavidLevitGurevich)

___
*[`stwo_cairo_prover/crates/prover_types/src/cpu.rs` line 559 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/195#-OD_uHpY7C-ZASGobqq9:-ODa082k7PcB5vZGnZhT:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/486465d8710545280c414991d449d7b99e9cee68/stwo_cairo_prover/crates/prover_types/src/cpu.rs#L559)):*
<details><summary><i>Previously, anatgstarkware (anatg) wrote…</i></summary><blockquote>

please add another const to biguint `const F: usize`
and add documentation that explains that B is the total num of bits, L is num of 64-bit UInt64 limbs and F is num of 12-bit M31 limbs
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover_types/src/cpu.rs` line 603 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/195#-OD_tCOj2t6hILJb0LmG:-ODa-S6T2H7ugXcS4zqz:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/486465d8710545280c414991d449d7b99e9cee68/stwo_cairo_prover/crates/prover_types/src/cpu.rs#L603)):*
<details><summary><i>Previously, anatgstarkware (anatg) wrote…</i></summary><blockquote>

let's call it `BIGUINT_BITS_PER_M31` or something like that (`CHILD` is not clear)
let's make it pub
also, can you please move these consts to the top of biguint?
</blockquote></details>

Done.

**Review by anatgstarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/195)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @az-starkware, @DavidLevitGurevich, and @ohad-nir-starkware)

___
*[`stwo_cairo_prover/crates/prover_types/src/cpu.rs` line 564 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/195#-ODa2tAx1cT3Aol1lQhz:-ODa2tAx1cT3Aol1lQi-:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/41e36bb33d404ae431c46be2918242f42f38c9f0/stwo_cairo_prover/crates/prover_types/src/cpu.rs#L564)):*
> ```XML
> 
> #[derive(Copy, Clone, Debug, Eq, PartialEq, Hash)]
> // B is the numver of bits in the BigUInt.
> ```





_Suggestion:_
```XML
number
```

**Review by anatgstarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/195)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @az-starkware, @DavidLevitGurevich, and @ohad-nir-starkware)

___
*[`stwo_cairo_prover/crates/prover_types/src/cpu.rs` line 606 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/195#-OCc6-bc58xK8Up5ar7R:-ODaASk246URBcZ3H59w:bd6ogwb) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/1ef5bf5e91ff7491c462b2696d041f4d78968e74/stwo_cairo_prover/crates/prover_types/src/cpu.rs#L606)):*
<details><summary><i>Previously, ohad-nir-starkware (Ohad Nir) wrote…</i></summary><blockquote>

add documentation and changed `shift` into `child_start`
</blockquote></details>

After talking to David, shift is probably better
___
*[`stwo_cairo_prover/crates/prover_types/src/cpu.rs` line 561 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/195#-ODaA1bXDWxkuTTWmN09:-ODaA1bXDWxkuTTWmN0A:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/41e36bb33d404ae431c46be2918242f42f38c9f0/stwo_cairo_prover/crates/prover_types/src/cpu.rs#L561)):*
> ```XML
> pub const MOD_BUILTIN_WORD_BIT_LEN: usize = 96;
> // Length of each infra side limb in bits.
> pub const BIGUINT_BITS_PER_M31: usize = 12;
> ```





_Suggestion:_
```XML
// Length of each biguint word in bits.
pub const BIGUINT_BITS_PER_WORD: usize = 12;
```
___
*[`stwo_cairo_prover/crates/prover_types/src/cpu.rs` line 644 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/195#-ODaACM24_fI3CmLZb43:-ODaACM3DqirCrI8JoT5:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/41e36bb33d404ae431c46be2918242f42f38c9f0/stwo_cairo_prover/crates/prover_types/src/cpu.rs#L644)):*
> ```XML
> 
>     // Given an index, returns the child of index `index` of the partition into limbs of
>     // BIGUINT_BITS_PER_M31 bits as a M31 felt.
> ```





_Suggestion:_
```XML
    // Returns the BIGUINT_BITS_PER_WORD-bits word at the given index.
```
___
*[`stwo_cairo_prover/crates/prover_types/src/cpu.rs` line 650 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/195#-ODaAsNu-jnIFDRs_WS0:-ODaAsNu-jnIFDRs_WS1:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/41e36bb33d404ae431c46be2918242f42f38c9f0/stwo_cairo_prover/crates/prover_types/src/cpu.rs#L650)):*
> ```XML
>         let low_limb = child_start / 64;
>         let shift_low = child_start & 0x3F;
>         let high_limb = min((child_start + BIGUINT_BITS_PER_M31 - 1) / 64, L - 1);
> ```





_Suggestion:_
```XML
(shift + BIGUINT_BITS_PER_WORD - 1) / 64;
```
___
*[`stwo_cairo_prover/crates/prover_types/src/cpu.rs` line 660 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/195#-ODaBFPv8aWBZfWm-KHe:-ODaBFPv8aWBZfWm-KHf:b-17fnu3) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/41e36bb33d404ae431c46be2918242f42f38c9f0/stwo_cairo_prover/crates/prover_types/src/cpu.rs#L660)):*
> ```XML
>     }
> 
>     pub fn from_limbs(limbs: Vec<UInt64>) -> Self {
> ```

Please erase this function as well (it's confusing, we don't need the u64 limbs/words, only 12-bit felts)



_Code quote:_
```XML
pub fn from_limbs(limbs: Vec<UInt64>) -> Self
```

**Comment by anatgstarkware** [comment]
*[`stwo_cairo_prover/crates/prover_types/src/cpu.rs` line 644 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/195#-ODaACM24_fI3CmLZb43:-ODaCalQ71tZICQGrdxr:b-4dyhiq) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/41e36bb33d404ae431c46be2918242f42f38c9f0/stwo_cairo_prover/crates/prover_types/src/cpu.rs#L644)):*
> ```XML
> 
>     // Given an index, returns the child of index `index` of the partition into limbs of
>     // BIGUINT_BITS_PER_M31 bits as a M31 felt.
> ```

actually `BIGUINT_BITS_PER_WORD-bit`, not `BIGUINT_BITS_PER_WORD-bits`

**Comment by anatgstarkware** [comment]
*[`stwo_cairo_prover/crates/prover_types/src/cpu.rs` line 566 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/195#-ODaCkrQBPZHe5e-VtqR:-ODaCkrQBPZHe5e-VtqS:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/41e36bb33d404ae431c46be2918242f42f38c9f0/stwo_cairo_prover/crates/prover_types/src/cpu.rs#L566)):*
> ```XML
> // B is the numver of bits in the BigUInt.
> // L is the number of 64 bit UInt64 limbs in the BigUInt.
> // F is the number of BIGUINT_BITS_PER_M31 bit M31 limbs in the BigUInt.
> ```





_Suggestion:_
```XML
// L is the number of 64-bit limbs in the BigUInt.
// F is the number of BIGUINT_BITS_PER_M31-bit limbs in the BigUInt.
```

**Review by ohad-nir-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/195)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @anatgstarkware, @az-starkware, and @DavidLevitGurevich)

___
*[`stwo_cairo_prover/crates/prover_types/src/cpu.rs` line 606 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/195#-OCc6-bc58xK8Up5ar7R:-ODaN5PX1mq4eCNvqJGP:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/1ef5bf5e91ff7491c462b2696d041f4d78968e74/stwo_cairo_prover/crates/prover_types/src/cpu.rs#L606)):*
<details><summary><i>Previously, anatgstarkware (anatg) wrote…</i></summary><blockquote>

After talking to David, shift is probably better
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover_types/src/cpu.rs` line 644 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/195#-ODaACM24_fI3CmLZb43:-ODaMxcm5l1I0kkJSlz0:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/41e36bb33d404ae431c46be2918242f42f38c9f0/stwo_cairo_prover/crates/prover_types/src/cpu.rs#L644)):*
<details><summary><i>Previously, anatgstarkware (anatg) wrote…</i></summary><blockquote>

actually `BIGUINT_BITS_PER_WORD-bit`, not `BIGUINT_BITS_PER_WORD-bits`
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover_types/src/cpu.rs` line 660 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/195#-ODaBFPv8aWBZfWm-KHe:-ODaNwaf-1hc3Y_3x2Sl:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/41e36bb33d404ae431c46be2918242f42f38c9f0/stwo_cairo_prover/crates/prover_types/src/cpu.rs#L660)):*
<details><summary><i>Previously, anatgstarkware (anatg) wrote…</i></summary><blockquote>

Please erase this function as well (it's confusing, we don't need the u64 limbs/words, only 12-bit felts)
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover_types/src/cpu.rs` line 561 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/195#-ODaA1bXDWxkuTTWmN09:-ODaMIuL-cKntcp3bly5:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/41e36bb33d404ae431c46be2918242f42f38c9f0/stwo_cairo_prover/crates/prover_types/src/cpu.rs#L561)):*
> ```XML
> pub const MOD_BUILTIN_WORD_BIT_LEN: usize = 96;
> // Length of each infra side limb in bits.
> pub const BIGUINT_BITS_PER_M31: usize = 12;
> ```

Done.
___
*[`stwo_cairo_prover/crates/prover_types/src/cpu.rs` line 564 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/195#-ODa2tAx1cT3Aol1lQhz:-ODaLT6e6zz8JHwGcww2:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/41e36bb33d404ae431c46be2918242f42f38c9f0/stwo_cairo_prover/crates/prover_types/src/cpu.rs#L564)):*
> ```XML
> 
> #[derive(Copy, Clone, Debug, Eq, PartialEq, Hash)]
> // B is the numver of bits in the BigUInt.
> ```

Done.
___
*[`stwo_cairo_prover/crates/prover_types/src/cpu.rs` line 566 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/195#-ODaCkrQBPZHe5e-VtqR:-ODaMYZp2o_9Wgc1asm9:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/41e36bb33d404ae431c46be2918242f42f38c9f0/stwo_cairo_prover/crates/prover_types/src/cpu.rs#L566)):*
> ```XML
> // B is the numver of bits in the BigUInt.
> // L is the number of 64 bit UInt64 limbs in the BigUInt.
> // F is the number of BIGUINT_BITS_PER_M31 bit M31 limbs in the BigUInt.
> ```

Done.
___
*[`stwo_cairo_prover/crates/prover_types/src/cpu.rs` line 650 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/195#-ODaAsNu-jnIFDRs_WS0:-ODaNQEJ-eq5uKmVQTa_:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/41e36bb33d404ae431c46be2918242f42f38c9f0/stwo_cairo_prover/crates/prover_types/src/cpu.rs#L650)):*
> ```XML
>         let low_limb = child_start / 64;
>         let shift_low = child_start & 0x3F;
>         let high_limb = min((child_start + BIGUINT_BITS_PER_M31 - 1) / 64, L - 1);
> ```

Done.

**Review by anatgstarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/195#-:-ODaUnif7CXrDeiwgDrF:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @az-starkware)

**Review by DavidLevitGurevich — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/195#-:-ODbn8VS40sNCMlz65wS:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @az-starkware)

**Pull request merged**
