### PR TITLE
Update Stwo Version

### PR DESCRIPTION
**Pull request by Gali-StarkWare**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/283)

### CODE REVIEW

**Comment by Gali-StarkWare** [comment]
* **#283** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/283?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/283?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by ohad-starkware — COMMENTED** [review]
what is the reason?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/283#-:-OFL7iAgA8Unvjh0s1Cg:bw8cpe5)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Review by shaharsamocha7 — APPROVED** [review]
I guess to have the Seq preprocessed column

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/283#-:-OFLkjsD2Ie8ScyqDiS-:bnl8thf)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Gali-StarkWare)

**Review by ohad-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/283#-:-OFM9LFi8oSb71n5YOoU:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Gali-StarkWare)

**Pull request merged**
