### PR TITLE
packed types for generic opcode

### PR DESCRIPTION
**Pull request by ohad-starkware**
range check small table

packed types for generic opcode

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/176)

### CODE REVIEW

**Comment by ohad-starkware** [comment]
* **#176** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/176?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/176?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/176)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover_types/src/cpu.rs` line 436 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/176#-OBz3vBXAIbcUNS47K8u:-OBz3vBXAIbcUNS47K8v:b-sluuqb) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/32c2f420cdaea57ad7dda6fa371a4cc7d07a47c0/stwo_cairo_prover/crates/prover_types/src/cpu.rs#L436)):*
> ```XML
>     }
> 
>     pub fn from_limbs(felts: &[M31; FELT252_N_WORDS]) -> Self {
> ```

Why did you change that?
Now you can't get felt from less limbs?



_Code quote:_
```XML
    pub fn from_limbs(felts: &[M31; FELT252_N_WORDS]) -> Self {
```
___
*[`stwo_cairo_prover/crates/prover_types/src/simd.rs` line 377 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/176#-OBz4IDmEdMdXswJsb4v:-OBz4IDnEDOqaPCTAsdG:b7e777d) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/2ca5223ff01d456cfeba283ba87e56004babf55b/stwo_cairo_prover/crates/prover_types/src/simd.rs#L377)):*
> ```XML
>             value: std::array::from_fn(|i| if i == 0 { val } else { PackedM31::zero() }),
>         }
>     }
> ```

don't you need to split it to 9 bits?
Alternatively if you assume that these values are 9 bits write in the doc



_Code quote:_
```XML
    pub fn from_m31(val: PackedM31) -> Self {
        Self {
            value: std::array::from_fn(|i| if i == 0 { val } else { PackedM31::zero() }),
        }
    }
```

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/176)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @ohad-starkware and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover_types/src/cpu.rs` line 436 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/176#-OBz3vBXAIbcUNS47K8u:-OBz90CaB_zKFlzQo3C0:b-t5pnte) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/32c2f420cdaea57ad7dda6fa371a4cc7d07a47c0/stwo_cairo_prover/crates/prover_types/src/cpu.rs#L436)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Why did you change that?
Now you can't get felt from less limbs?
</blockquote></details>

sorry, I thought the assert was the opposite
___
*[`stwo_cairo_prover/crates/prover_types/src/simd.rs` line 377 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/176#-OBz4IDmEdMdXswJsb4v:-OBz9wW33XB6m_aJieTm:b-na8l62) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/2ca5223ff01d456cfeba283ba87e56004babf55b/stwo_cairo_prover/crates/prover_types/src/simd.rs#L377)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

don't you need to split it to 9 bits?
Alternatively if you assume that these values are 9 bits write in the doc
</blockquote></details>

my bad

**Review by shaharsamocha7 — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/176)* status: all files reviewed, 2 unresolved discussions (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover_types/src/simd.rs` line 376 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/176#-OC3q4igCayiIbO8M0G-:-OC3q4ih5w_fIS6_t51e:b2wa2kx) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ebe3c1a0c45d0e1a701c9ccd0555b7927a714437/stwo_cairo_prover/crates/prover_types/src/simd.rs#L376)):*
> ```XML
>     }
> 
>     pub fn to_array(&self) -> [Felt252; N_LANES] {
> ```

can you also test these functions?
also from_m31



_Code quote:_
```XML
pub fn to_array(&self) -> [Felt252; N_LANES] {
```
___
*[`stwo_cairo_prover/crates/prover_types/src/simd.rs` line 447 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/176#-OC3qAT5Bl_urQwwF-yE:-OC3qAT5Bl_urQwwF-yF:bfpv4wx) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ebe3c1a0c45d0e1a701c9ccd0555b7927a714437/stwo_cairo_prover/crates/prover_types/src/simd.rs#L447)):*
> ```XML
> pub trait DivExtend {
>     fn div(&self, other: Self) -> Self;
> }
> ```

also test that



_Code quote:_
```XML
pub trait DivExtend {
    fn div(&self, other: Self) -> Self;
}
```

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/176)* status: all files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover_types/src/simd.rs` line 376 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/176#-OC3q4igCayiIbO8M0G-:-OC42Iz60Wjiy1UlGIeJ:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/17c2794975e01f6d6c7d4f292801917cfcb216c3/stwo_cairo_prover/crates/prover_types/src/simd.rs#L376)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

can you also test these functions?
also from_m31
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover_types/src/simd.rs` line 447 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/176#-OC3qAT5Bl_urQwwF-yE:-OC42uVD50XDS1P9D7Lz:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/17c2794975e01f6d6c7d4f292801917cfcb216c3/stwo_cairo_prover/crates/prover_types/src/simd.rs#L447)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

also test that
</blockquote></details>

Done.

**Pull request merged**
