### PR TITLE
rangecheck macro adjustments

### PR DESCRIPTION
**Pull request by ohad-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/147)

### CODE REVIEW

**Comment by ohad-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/147?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#147** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/147?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#146** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/146?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ohad-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/147#-:-OAWLA-E40n4EeI0PoJq:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_vector/mod.rs` line 75 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/147#-OAWLBUS04UnkO4lqoHO:-OAWLBUS04UnkO4lqoHP:bb7onj7) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/5f247fd6a252d28e631527f5a82e3a42b22ff6fb/stwo_cairo_prover/crates/prover/src/components/range_check_vector/mod.rs#L75)):*
> ```XML
>                 use stwo_prover::core::vcs::blake2_merkle::Blake2sMerkleChannel;
>                 use $crate::components::range_check_vector::component_prover::
>                                                         RangeCheckInteractionClaimGenerator;
> ```

sort



_Code quote:_
```XML
                use stwo_prover::constraint_framework::FrameworkComponent;
                use $crate::components::range_check_vector::RangeCheckVectorEval;
                use $crate::components::range_check_vector::component::{RangeCheckClaim,
                                                                    RangeCheckInteractionClaim};
                use $crate::components::range_check_vector::component_prover::RangeCheckClaimGenerator;
                use stwo_prover::constraint_framework::logup::LookupElements;
                use stwo_prover::core::fields::qm31::QM31;
                use stwo_prover::constraint_framework::FrameworkEval;
                use stwo_prover::constraint_framework::EvalAtRow;
                use serde::{Serialize, Deserialize};
                use std::ops::{Deref, DerefMut};
                use stwo_prover::core::pcs::TreeBuilder;
                use stwo_prover::core::backend::simd::SimdBackend;
                use stwo_prover::core::vcs::blake2_merkle::Blake2sMerkleChannel;
                use $crate::components::range_check_vector::component_prover::
                                                        RangeCheckInteractionClaimGenerator;
```

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/147)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_vector/mod.rs` line 75 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/147#-OAWLBUS04UnkO4lqoHO:-OAWRiPAAOk3_Vg7Sqan:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/5f247fd6a252d28e631527f5a82e3a42b22ff6fb/stwo_cairo_prover/crates/prover/src/components/range_check_vector/mod.rs#L75)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

sort
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/147)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ohad-starkware)

**Comment by ohad-starkware** [comment]
### Merge activity

* **Oct 31, 3:41 AM EDT**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/147).

**Pull request merged**
