### PR TITLE
rangecheck vector in memory

### PR DESCRIPTION
**Pull request by ohad-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/144)

### CODE REVIEW

**Comment by ohad-starkware** [comment]
* **#144** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/144?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ohad-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by ilyalesokhin-starkware** [comment]
*[`stwo_cairo_prover/crates/prover/src/components/memory/id_to_f252/prover.rs` line 168 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/144#-OASAVTc3xKs1inLFpqt:-OASAVTd8P1ciqyNZMSt:b-oal5lc) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/45119bd649b168dd4242b700387500f8d60654ac/stwo_cairo_prover/crates/prover/src/components/memory/id_to_f252/prover.rs#L168)):*
> ```XML
>         col_gen.finalize_col();
> 
>         for columumn_pair in self.ids_and_values[MEMORY_ID_SIZE..].chunks_exact(2) {
> ```

can you try using
https://docs.rs/itertools/0.10.0/itertools/trait.Itertools.html#method.tuples



_Code quote:_
```XML
.chunks_exact(2
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/144)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_vector/component_prover.rs` line 189 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/144#-OASBbp56QNu0J_Z6BB1:-OASBbp56QNu0J_Z6BB2:bso3b97) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/45119bd649b168dd4242b700387500f8d60654ac/stwo_cairo_prover/crates/prover/src/components/range_check_vector/component_prover.rs#L189)):*
> ```XML
>         });
> 
>         let mut claim_prover = RangeCheckClaimGenerator::new(log_ranges);
> ```

fix name

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/144)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_vector/component_prover.rs` line 189 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/144#-OASBbp56QNu0J_Z6BB1:-OASCPhW1mexSHeApXfz:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/45119bd649b168dd4242b700387500f8d60654ac/stwo_cairo_prover/crates/prover/src/components/range_check_vector/component_prover.rs#L189)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

fix name
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/144#-:-OASDtZXChlrcnCH77Fb:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ohad-starkware)

**Comment by ohad-starkware** [comment]
### Merge activity

* **Oct 30, 8:12 AM EDT**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/144).

**Pull request merged**
