### PR TITLE
update stwo

### PR DESCRIPTION
**Pull request by ohad-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/197)

### CODE REVIEW

**Comment by ohad-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/197?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#197** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/197?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/197?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#196** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/196?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#193** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/193?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#194](https://github.com/starkware-libs/stwo-cairo/pull/194) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/194?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#190** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/190?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#189** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/189?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#188** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/188?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#187** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/187?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#180** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/180?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#182](https://github.com/starkware-libs/stwo-cairo/pull/182) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/182?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#179** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/179?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#177** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/177?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#178** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/178?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#176** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/176?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/197)* status: all files reviewed, 1 unresolved discussion (waiting on @Alon-Ti)

___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_vector/mod.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/197#-OCYTrgh4_DRXykhvuK9:-OCYmL3MCTK8u5T-ek44:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e741515d85a4970b7d077255a4a3b1a0d1618531/stwo_cairo_prover/crates/prover/src/components/range_check_vector/mod.rs#L65)):*
<details><summary><i>Previously, Alon-Ti wrote…</i></summary><blockquote>

Export relations to a global module and give them distinct names.
</blockquote></details>

Done.

**Review by Alon-Ti — CHANGES_REQUESTED** [review]
> Reviewed 19 of 19 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/197)* status: all files reviewed, 2 unresolved discussions (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/components/genericopcode/prover.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/197#-OCbaf2h9ekSbUme-ErL:-OCbaf2h9ekSbUme-ErM:b-php0a2) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/6285973b4f7afb20058c45de46a20cab656db7ad/stwo_cairo_prover/crates/prover/src/components/genericopcode/prover.rs#L27)):*
> ```XML
> use super::component::{Claim, InteractionClaim, RelationElements};
> use crate::components::memory::{addr_to_id, id_to_f252};
> use crate::relations::*;
> ```

Remove (or have everything import all relations and remove the specific imports below).
___
*[`stwo_cairo_prover/crates/prover/src/relations/mod.rs` line 4 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/197#-OCbeIes1VNiCBLa8H80:-OCbeIes1VNiCBLa8H81:b-bvrzd) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3e6dadd3f4614b4f75685ca4e54a6e5cecafcbd4/stwo_cairo_prover/crates/prover/src/relations/mod.rs#L4)):*
> ```XML
> use stwo_prover::relation;
> 
> relation!(AddrToIdRelation, 2);
> ```

Consider Removing the `Relation` suffix and importing them as `relation::{}`.

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/197)* status: all files reviewed, 1 unresolved discussion (waiting on @Alon-Ti)

___
*[`stwo_cairo_prover/crates/prover/src/components/genericopcode/prover.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/197#-OCbaf2h9ekSbUme-ErL:-OCbm3Je7QXkfj2oITUI:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/6285973b4f7afb20058c45de46a20cab656db7ad/stwo_cairo_prover/crates/prover/src/components/genericopcode/prover.rs#L27)):*
<details><summary><i>Previously, Alon-Ti wrote…</i></summary><blockquote>

Remove (or have everything import all relations and remove the specific imports below).
</blockquote></details>

Done.

**Review by Alon-Ti — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/197#-:-OCbmrhKENb7d2k1Oe5K:bnfp4nl)* status: 11 of 25 files reviewed, all discussions resolved (waiting on @ohad-starkware)

**Pull request merged**
