### PR TITLE
cairo air 

### PR DESCRIPTION
**Pull request by ohad-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/41)

### CODE REVIEW

**Comment by ohad-starkware** [comment]
* **#41** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/41?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ohad-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 18 files at r1, 5 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/41)* status: 8 of 19 files reviewed, 8 unresolved discussions (waiting on @alonh5 and @ohad-starkware)

___
*[`stwo_cairo_prover/src/cairo_air/mod.rs` line 56 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/41#-O3ksUI9Auh9Wa0H6WB2:-O3ksUI9Auh9Wa0H6WB3:bjputgi) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ede00106e76e98921b49952b293b6bdc5019d41c/stwo_cairo_prover/src/cairo_air/mod.rs#L56)):*
> ```XML
>         self.ret.iter().for_each(|c| c.mix_into(_channel));
>     }
>     pub fn log_sizes(&self) -> Vec<u32> {
> ```

I could be mistaken, but I think we actually want this to return the sizes for all interactions.
CairoInteractionClaim doesn't (shouldnt) hold the log_sizes, since we already committed on them. No sense to add them to the channel again.



_Suggestion:_
```XML
pub fn log_sizes(&self) -> TreeVec<Vec<u32>> {
```
___
*[`stwo_cairo_prover/src/cairo_air/mod.rs` line 115 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/41#-O3ktPk9CREHiTB1ijpB:-O3ktPkA3gsWBuwcsKtL:b-izzokm) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ede00106e76e98921b49952b293b6bdc5019d41c/stwo_cairo_prover/src/cairo_air/mod.rs#L115)):*
> ```XML
> 
>     // Draw interaction elements.
>     let memory_lookup_elements = LookupElements::draw(channel);
> ```

Add a TODO to use a type for MemoryElements.
e.g. define pub type MemoryElements = LookupElements::<ADDR_FELTS+VAL_FELTS>



_Code quote:_
```XML
let memory_lookup_elements = LookupElements::draw(channel);
```
___
*[`stwo_cairo_prover/src/cairo_air/mod.rs` line 126 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/41#-O3ktimqELY3cgr4c_L_:-O3ktimqELY3cgr4c_La:b-drs7vx) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ede00106e76e98921b49952b293b6bdc5019d41c/stwo_cairo_prover/src/cairo_air/mod.rs#L126)):*
> ```XML
>         memory_interaction_claim.claimed_sum,
>         ret_interaction_claim.memory_claimed_sum
>     );
> ```

This will become false very very fast.
We actually want to verify that the sum of all claimed_sums is zero.
Also, make sure that the "use" and "yield" lookups appear with different signs in the numerator, so that will actually hold.



_Code quote:_
```XML
    debug_assert_eq!(
        memory_interaction_claim.claimed_sum,
        ret_interaction_claim.memory_claimed_sum
    );
```
___
*[`stwo_cairo_prover/src/cairo_air/mod.rs` line 139 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/41#-O3ku7B025d8_48Zj0vx:-O3ku7B025d8_48Zj0vy:b-q6lzb4) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ede00106e76e98921b49952b293b6bdc5019d41c/stwo_cairo_prover/src/cairo_air/mod.rs#L139)):*
> ```XML
>         claimed_sum: cairo_interaction_claim.ret[0].memory_claimed_sum,
>         lookup_elements: memory_lookup_elements.clone(),
>     };
> ```

I tihnk it'll be clearner if component creation only needs the component claims



_Suggestion:_
```XML
    let ret_component = RetOpcodeComponent::new {
        cairo_claim.ret[0],
        memory_lookup_elements.clone(),
        cairo_interaction_claim.ret[0],
    };
```
___
*[`stwo_cairo_prover/src/cairo_air/mod.rs` line 146 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/41#-O3kuNATEkxddPRDiZSK:-O3kuNATEkxddPRDiZSL:b6i93pp) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ede00106e76e98921b49952b293b6bdc5019d41c/stwo_cairo_prover/src/cairo_air/mod.rs#L146)):*
> ```XML
>     };
>     let components: Vec<&dyn ComponentProver<SimdBackend>> =
>         vec![&ret_component, &memory_component];
> ```

Consider (somehow) extracting a function that creates components from CairoClaim and CairoInteractionClaim, to be used by both the prover and thheh verifier.
Probably will require some generic magic here, see if you can make it work.



_Code quote:_
```XML
    let components: Vec<&dyn ComponentProver<SimdBackend>> =
        vec![&ret_component, &memory_component];
```
___
*[`stwo_cairo_prover/src/components/memory/simd_trace.rs` line 92 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/41#-O3kv48H4HODvEwGWv1Z:-O3kv48IBtGMv8MYCyUI:bvh3geg) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ede00106e76e98921b49952b293b6bdc5019d41c/stwo_cairo_prover/src/components/memory/simd_trace.rs#L92)):*
> ```XML
>             }
>             assert!(multiplicity.in_m31_range());
>             trace[MULTIPLICITY_COLUMN_OFFSET].data[i] = multiplicity.as_m31_unchecked();
> ```

Consider making these multiplicities negative
___
*[`stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs` line 248 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/41#-O3kvAt_0J7nrbUqdUws:-O3kvAt_0J7nrbUqdUwt:by359xv) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ede00106e76e98921b49952b293b6bdc5019d41c/stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs#L248)):*
> ```XML
> 
>         let channel = &mut Blake2sChannel::new(Blake2sHasher::hash(BaseField::into_slice(&[])));
>         let memory_lookup_elements = MemoryLookupElements::draw(channel);
> ```

I see you already have this defined. Can you use it in the air?



_Code quote:_
```XML
MemoryLookupElements
```
___
*[`stwo_cairo_prover/src/prover_types/mod.rs` line 12 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/41#-O3kvRcz-3xNGnXZlk9k:-O3kvRcz-3xNGnXZlk9l:bhghdw0) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ede00106e76e98921b49952b293b6bdc5019d41c/stwo_cairo_prover/src/prover_types/mod.rs#L12)):*
> ```XML
> 
> #[derive(Copy, Clone, Debug, Default)]
> pub struct PackedUInt32 {
> ```

Do you really need this wrapper? Why not use u32x16 directly, or even just make a type alias instead:
```
pub type PackedUIint32 = u32x16;
```
?

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/41)* status: 7 of 19 files reviewed, 8 unresolved discussions (waiting on @alonh5 and @spapinistarkware)

___
*[`stwo_cairo_prover/src/cairo_air/mod.rs` line 56 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/41#-O3ksUI9Auh9Wa0H6WB2:-O3l38V_3YdtzpTX_cp-:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ede00106e76e98921b49952b293b6bdc5019d41c/stwo_cairo_prover/src/cairo_air/mod.rs#L56)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I could be mistaken, but I think we actually want this to return the sizes for all interactions.
CairoInteractionClaim doesn't (shouldnt) hold the log_sizes, since we already committed on them. No sense to add them to the channel again.
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/src/cairo_air/mod.rs` line 115 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/41#-O3ktPk9CREHiTB1ijpB:-O3l3A2U2_lSy19ehaUZ:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ede00106e76e98921b49952b293b6bdc5019d41c/stwo_cairo_prover/src/cairo_air/mod.rs#L115)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Add a TODO to use a type for MemoryElements.
e.g. define pub type MemoryElements = LookupElements::<ADDR_FELTS+VAL_FELTS>
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/src/cairo_air/mod.rs` line 126 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/41#-O3ktimqELY3cgr4c_L_:-O3l3jLM70QAjSb2N1ad:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ede00106e76e98921b49952b293b6bdc5019d41c/stwo_cairo_prover/src/cairo_air/mod.rs#L126)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

This will become false very very fast.
We actually want to verify that the sum of all claimed_sums is zero.
Also, make sure that the "use" and "yield" lookups appear with different signs in the numerator, so that will actually hold.
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/src/cairo_air/mod.rs` line 139 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/41#-O3ku7B025d8_48Zj0vx:-O3lQspo3sCrDwjzW-kb:bb7f2mf) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ede00106e76e98921b49952b293b6bdc5019d41c/stwo_cairo_prover/src/cairo_air/mod.rs#L139)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I tihnk it'll be clearner if component creation only needs the component claims
</blockquote></details>

done
___
*[`stwo_cairo_prover/src/cairo_air/mod.rs` line 146 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/41#-O3kuNATEkxddPRDiZSK:-O3l_vnb1wiLh-wA_JRF:b-7hbpla) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ede00106e76e98921b49952b293b6bdc5019d41c/stwo_cairo_prover/src/cairo_air/mod.rs#L146)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Consider (somehow) extracting a function that creates components from CairoClaim and CairoInteractionClaim, to be used by both the prover and thheh verifier.
Probably will require some generic magic here, see if you can make it work.
</blockquote></details>

wdyt?
___
*[`stwo_cairo_prover/src/components/memory/simd_trace.rs` line 92 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/41#-O3kv48H4HODvEwGWv1Z:-O3l3m5d7xVvABaW5phO:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ede00106e76e98921b49952b293b6bdc5019d41c/stwo_cairo_prover/src/components/memory/simd_trace.rs#L92)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Consider making these multiplicities negative
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs` line 248 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/41#-O3kvAt_0J7nrbUqdUws:-O3l7BlJ9luzlunQ1ocP:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ede00106e76e98921b49952b293b6bdc5019d41c/stwo_cairo_prover/src/components/range_check_builtin/simd_trace.rs#L248)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I see you already have this defined. Can you use it in the air?
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/src/prover_types/mod.rs` line 12 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/41#-O3kvRcz-3xNGnXZlk9k:-O3kyh3dBHQa-q0Y16zE:bv5pk3v) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ede00106e76e98921b49952b293b6bdc5019d41c/stwo_cairo_prover/src/prover_types/mod.rs#L12)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Do you really need this wrapper? Why not use u32x16 directly, or even just make a type alias instead:
```
pub type PackedUIint32 = u32x16;
```
?
</blockquote></details>

we are going to have multiple Packed prover types
some of them need  a non-trivial `as_m31()`, and trait operations that might not be the default simd ones (packed felt252 for instance).
it is true that uint32 is trivial (other than as_m31() but were doing unchecked in this pr.
also I'm using it in the code-generation, with the assumption that every packed type is the prover type with the string 'Packed' attached to it.

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/41)* status: 7 of 19 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @ohad-starkware)

___
*[`stwo_cairo_prover/src/cairo_air/mod.rs` line 126 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/41#-O3ktimqELY3cgr4c_L_:-O3laYoN1fYfOsmD0J9-:btj0rxc) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ede00106e76e98921b49952b293b6bdc5019d41c/stwo_cairo_prover/src/cairo_air/mod.rs#L126)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This assert should appear in the verifier, not just for debug.
___
*[`stwo_cairo_prover/src/cairo_air/mod.rs` line 101 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/41#-O3latwk3cQzVMt3-fky:-O3latwk3cQzVMt3-fkz:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/da67b2cf04245b5bb485dc023292230c29523800/stwo_cairo_prover/src/cairo_air/mod.rs#L101)):*
> ```XML
> }
> 
> pub struct OpCodeComponentGenerator {
> ```





_Suggestion:_
```XML
CairoComponentGenerator
```

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/41)* status: 7 of 19 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @spapinistarkware)

___
*[`stwo_cairo_prover/src/cairo_air/mod.rs` line 126 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/41#-O3ktimqELY3cgr4c_L_:-O3lbK601AnnmpB5jehv:b2nign6) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ede00106e76e98921b49952b293b6bdc5019d41c/stwo_cairo_prover/src/cairo_air/mod.rs#L126)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

This assert should appear in the verifier, not just for debug.
</blockquote></details>

yes
___
*[`stwo_cairo_prover/src/cairo_air/mod.rs` line 101 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/41#-O3latwk3cQzVMt3-fky:-O3lbroK7eARufQkTvlS:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/da67b2cf04245b5bb485dc023292230c29523800/stwo_cairo_prover/src/cairo_air/mod.rs#L101)):*
> ```XML
> }
> 
> pub struct OpCodeComponentGenerator {
> ```

Done.

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 18 files at r1, 2 of 12 files at r2, 1 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/41)* status: 12 of 19 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @ohad-starkware)

___
*[`stwo_cairo_prover/src/components/memory/mod.rs` line 14 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/41#-O3lcLEBEwQcctyo4Rwk:-O3lcLEBEwQcctyo4Rwl:b-ijdf8o) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e712076114315b25f106d58cd677dfa22bb6cdb8/stwo_cairo_prover/src/components/memory/mod.rs#L14)):*
> ```XML
> 
> pub struct MemoryValues {
>     pub values: Vec<[PackedM31; N_M31_IN_FELT252]>,
> ```

Note: I plan to split this according to sizes in my PR.
___
*[`stwo_cairo_prover/src/components/ret_opcode/simd_trace.rs` line 20 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/41#-O3lccIT6E9ZmxrWKe2T:-O3lccIT6E9ZmxrWKe2U:bi8xk1m) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e712076114315b25f106d58cd677dfa22bb6cdb8/stwo_cairo_prover/src/components/ret_opcode/simd_trace.rs#L20)):*
> ```XML
> use crate::prover_types::{LOG_N_LANES, N_LANES};
> 
> pub struct RetOpcodeInteractionProver {
> ```

I wonder about the inputs format here. Why do we have memory_outputs in the prover?
Consider doing something similar to RetInput from my PR

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/41)* status: 12 of 19 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @spapinistarkware)

___
*[`stwo_cairo_prover/src/components/memory/mod.rs` line 14 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/41#-O3lcLEBEwQcctyo4Rwk:-O3lgNMH-Ku-NpNqE9og:b-7m2y43) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e712076114315b25f106d58cd677dfa22bb6cdb8/stwo_cairo_prover/src/components/memory/mod.rs#L14)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Note: I plan to split this according to sizes in my PR.
</blockquote></details>

noted
___
*[`stwo_cairo_prover/src/components/ret_opcode/simd_trace.rs` line 20 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/41#-O3lccIT6E9ZmxrWKe2T:-O3lfLDk0czp2pHdxhsH:bdiic9h) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e712076114315b25f106d58cd677dfa22bb6cdb8/stwo_cairo_prover/src/components/ret_opcode/simd_trace.rs#L20)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I wonder about the inputs format here. Why do we have memory_outputs in the prover?
Consider doing something similar to RetInput from my PR
</blockquote></details>

1. memory_outputs is for writing the interaction trace
2. The 3 down below refers  to the number of `memory` function calls, and those are pc, fp-1, fp-2,

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 18 files at r1, 2 of 12 files at r2, 2 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/41)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5 and @ohad-starkware)

___
*[`stwo_cairo_prover/src/components/ret_opcode/simd_trace.rs` line 20 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/41#-O3lt03KAhRhxYKAxBkL:-O3lt03KAhRhxYKAxBkM:br46uhl) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e712076114315b25f106d58cd677dfa22bb6cdb8/stwo_cairo_prover/src/components/ret_opcode/simd_trace.rs#L20)):*
> ```XML
> use crate::prover_types::{LOG_N_LANES, N_LANES};
> 
> pub struct RetOpcodeInteractionProver {
> ```

Put this after the trace generator
___
*[`stwo_cairo_prover/src/components/ret_opcode/simd_trace.rs` line 77 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/41#-O3lt3E3EhXk4f6ae9Hv:-O3lt3E3EhXk4f6ae9Hw:b-9b96pp) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e712076114315b25f106d58cd677dfa22bb6cdb8/stwo_cairo_prover/src/components/ret_opcode/simd_trace.rs#L77)):*
> ```XML
> }
> 
> pub struct RetOpcodeSimdTraceGenerator {
> ```

Consider renaming to RetOpcodeProver

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/41)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5 and @spapinistarkware)

___
*[`stwo_cairo_prover/src/components/ret_opcode/simd_trace.rs` line 20 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/41#-O3lt03KAhRhxYKAxBkL:-O3lyFs0DFW98eZKe0-U:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e712076114315b25f106d58cd677dfa22bb6cdb8/stwo_cairo_prover/src/components/ret_opcode/simd_trace.rs#L20)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Put this after the trace generator
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/src/components/ret_opcode/simd_trace.rs` line 77 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/41#-O3lt3E3EhXk4f6ae9Hv:-O3lweW_-4RLtixS4UVw:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e712076114315b25f106d58cd677dfa22bb6cdb8/stwo_cairo_prover/src/components/ret_opcode/simd_trace.rs#L77)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Consider renaming to RetOpcodeProver
</blockquote></details>

Done.

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 2 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/41)* status: 16 of 19 files reviewed, all discussions resolved (waiting on @alonh5)

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 19 of 19 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/41)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @ohad-starkware)

___
*[`stwo_cairo_prover/Cargo.toml` line 15 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/41#-O44Lb5-2HW1kFK-Bt7P:-O44Lb5-2HW1kFK-Bt7Q:br5lmdb) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/376fa65e98b217fd2fc967073d1347364065012f/stwo_cairo_prover/Cargo.toml#L15)):*
> ```TOML
> 
> [dev-dependencies]
> rand = "0.8.5"
> ```

What happened to the new line?

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/41)* status: 19 of 20 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @ohad-starkware)

___
*[`stwo_cairo_prover/src/cairo_air/mod.rs` line 32 at r7](https://reviewable.io/reviews/starkware-libs/stwo-cairo/41#-O44VLAw69ja5RiIf5HB:-O44VLAw69ja5RiIf5HC:b-fmoygk) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/a51055071847de0d72d5741fb97891074ac804b8/stwo_cairo_prover/src/cairo_air/mod.rs#L32)):*
> ```XML
> pub struct CairoInput {
>     // Opcodes.
>     pub ret: Vec<[PackedM31; 3]>,
> ```

Struct with meaningful names.
This is the interface to the prover, it should be human readable



_Code quote:_
```XML
[PackedM31; 3]
```

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/41)* status: 19 of 20 files reviewed, 3 unresolved discussions (waiting on @alonh5 and @ohad-starkware)

___
*[`stwo_cairo_prover/src/cairo_air/mod.rs` line 56 at r7](https://reviewable.io/reviews/starkware-libs/stwo-cairo/41#-O44awkP8DSrPFuciJ-S:-O44awkP8DSrPFuciJ-T:b-z9xs55) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/a51055071847de0d72d5741fb97891074ac804b8/stwo_cairo_prover/src/cairo_air/mod.rs#L56)):*
> ```XML
>     }
>     pub fn log_sizes(&self) -> TreeVec<Vec<u32>> {
>         // Interaction 0.
> ```

Consider using TreeVec::concat_cols at https://reviewable.io/reviews/starkware-libs/stwo/787

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/41)* status: 17 of 20 files reviewed, 4 unresolved discussions (waiting on @alonh5 and @ohad-starkware)

___
*[`stwo_cairo_prover/src/components/ret_opcode/prover.rs` line 26 at r8](https://reviewable.io/reviews/starkware-libs/stwo-cairo/41#-O44egUqC4NGAiFrX4PY:-O44egUqC4NGAiFrX4PZ:bq6j81r) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/58580f95f360d4eb5f8c44e71c4ba7200aad34fb/stwo_cairo_prover/src/components/ret_opcode/prover.rs#L26)):*
> ```XML
>     pub ap: PackedM31,
>     pub fp: PackedM31,
>     // pub new_pc: PackedM31,
> ```

You can removed these 2

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/41)* status: 17 of 20 files reviewed, 4 unresolved discussions (waiting on @alonh5 and @spapinistarkware)

___
*[`stwo_cairo_prover/src/cairo_air/mod.rs` line 32 at r7](https://reviewable.io/reviews/starkware-libs/stwo-cairo/41#-O44VLAw69ja5RiIf5HB:-O44a7Es1IVy_8FV_kwL:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/a51055071847de0d72d5741fb97891074ac804b8/stwo_cairo_prover/src/cairo_air/mod.rs#L32)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Struct with meaningful names.
This is the interface to the prover, it should be human readable
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/src/cairo_air/mod.rs` line 56 at r7](https://reviewable.io/reviews/starkware-libs/stwo-cairo/41#-O44awkP8DSrPFuciJ-S:-O44f_d1-4zU2PW3w80Q:b93n6om) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/a51055071847de0d72d5741fb97891074ac804b8/stwo_cairo_prover/src/cairo_air/mod.rs#L56)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Consider using TreeVec::concat_cols at https://reviewable.io/reviews/starkware-libs/stwo/787
</blockquote></details>

added a todo for now to avoid multiple cargo updates,
will do when its merged
___
*[`stwo_cairo_prover/Cargo.toml` line 15 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/41#-O44Lb5-2HW1kFK-Bt7P:-O44MdMqBs1omymi2QHb:b-7ql1td) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/376fa65e98b217fd2fc967073d1347364065012f/stwo_cairo_prover/Cargo.toml#L15)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

What happened to the new line?
</blockquote></details>

fixed
___
*[`stwo_cairo_prover/src/components/ret_opcode/prover.rs` line 26 at r8](https://reviewable.io/reviews/starkware-libs/stwo-cairo/41#-O44egUqC4NGAiFrX4PY:-O44floA0d7nm9CBOe7F:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/58580f95f360d4eb5f8c44e71c4ba7200aad34fb/stwo_cairo_prover/src/components/ret_opcode/prover.rs#L26)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

You can removed these 2
</blockquote></details>

Done.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7, 1 of 2 files at r8, 1 of 1 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/41#-:-O44jEotANcFoXh4V0TK:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Pull request merged**
