### PR TITLE
Cairo Memory

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/42)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/42?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#43** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/43?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#42** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/42?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#39** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/39?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/42)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/src/input/io.rs` line 68 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/42#-O3knR-LA7EE952NBqHi:-O3knR-LA7EE952NBqHj:b9olzpl) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/6563fbb9950b107ba0ecde27372533d6b600ea95/stwo_cairo_prover/src/input/io.rs#L68)):*
> ```XML
>     fn test_read_from_files() {
>         let _input = cairo_input_from_files(
>             Path::new("/home/spapini/Downloads/trace_file_sn"),
> ```

Not sure what to do here. Please help. These are 1GB files.
I probably want:
1. A smaller test with small files.
2. A more comprehensive test / benchmark with large files somehow, that may or may not run in CI

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/42)* status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/src/input/instructions.rs` line 18 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/42#-O3knoIfAVp_SzJzm8Wt:-O3knoIfAVp_SzJzm8Wu:b-45bikd) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/6563fbb9950b107ba0ecde27372533d6b600ea95/stwo_cairo_prover/src/input/instructions.rs#L18)):*
> ```XML
>         for TraceEntry { ap, fp, pc } in iter {
>             let instruction = mem.get(pc).as_64();
>             let instruction = decode_instruction(instruction).unwrap();
> ```

This is the only reason for my dependency on the cairo-vm crate. its a ~100 lines function. Not sure it justifies the dependency.



_Code quote:_
```XML
decode_instruction
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/42)* status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @ohad-starkware and @spapinistarkware)

___
*[`stwo_cairo_prover/src/input/io.rs` line 68 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/42#-O3knR-LA7EE952NBqHi:-O3ko0O14LbkkMe5X8eY:b-qrajag) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/6563fbb9950b107ba0ecde27372533d6b600ea95/stwo_cairo_prover/src/input/io.rs#L68)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Not sure what to do here. Please help. These are 1GB files.
I probably want:
1. A smaller test with small files.
2. A more comprehensive test / benchmark with large files somehow, that may or may not run in CI
</blockquote></details>

It's very compressible. 200MB for a PIE with a 2GB memory file. Not sure if it's not too much anyway, though

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/42)* status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @alonh5, @ohad-starkware, and @yuvalsw)

___
*[`stwo_cairo_prover/src/input/io.rs` line 68 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/42#-O3knR-LA7EE952NBqHi:-O3kpF0fESlQLrCZNSVu:b3dtc6d) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/6563fbb9950b107ba0ecde27372533d6b600ea95/stwo_cairo_prover/src/input/io.rs#L68)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

It's very compressible. 200MB for a PIE with a 2GB memory file. Not sure if it's not too much anyway, though
</blockquote></details>

That's good news, but still too large to commit in git

**Review by ohad-starkware — CHANGES_REQUESTED** [review]
> Reviewed 8 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/42)* status: 8 of 10 files reviewed, 3 unresolved discussions (waiting on @alonh5, @spapinistarkware, and @yuvalsw)

___
*[`stwo_cairo_prover/src/input/mem.rs` line 54 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/42#-O3ktarx2L_0otBQyRLL:-O3ktarx2L_0otBQyRLM:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/6563fbb9950b107ba0ecde27372533d6b600ea95/stwo_cairo_prover/src/input/mem.rs#L54)):*
> ```XML
> 
> #[derive(Copy, Clone, Default)]
> pub struct PackedMemoryValueId(u32);
> ```


___
*[`stwo_cairo_prover/src/input/mem.rs` line 54 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/42#-O3ktgdB2HHldUDLdXX_:-O3ktgdB2HHldUDLdXXa:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/6563fbb9950b107ba0ecde27372533d6b600ea95/stwo_cairo_prover/src/input/mem.rs#L54)):*
> ```XML
> 
> #[derive(Copy, Clone, Default)]
> pub struct PackedMemoryValueId(u32);
> ```





_Suggestion:_
```XML
EncodedMemoryValueId
```
___
*[`stwo_cairo_prover/src/input/io.rs` line 21 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/42#-O3ksQOs0cZFWJM669DT:-O3ksQOs0cZFWJM669DU:b8jy3ei) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/6563fbb9950b107ba0ecde27372533d6b600ea95/stwo_cairo_prover/src/input/io.rs#L21)):*
> ```XML
> #[repr(C)]
> #[derive(Copy, Clone, Default, Pod, Zeroable)]
> pub struct TraceEntry {
> ```

either put in a cairo-vm folder or rename



_Code quote:_
```XML
TraceEntry
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/42)* status: 8 of 10 files reviewed, 3 unresolved discussions (waiting on @alonh5 and @spapinistarkware)

___
*[`stwo_cairo_prover/src/input/instructions.rs` line 18 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/42#-O3knoIfAVp_SzJzm8Wt:-O3kwtS33hyr6ojassJz:b-3jgn0z) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/6563fbb9950b107ba0ecde27372533d6b600ea95/stwo_cairo_prover/src/input/instructions.rs#L18)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

This is the only reason for my dependency on the cairo-vm crate. its a ~100 lines function. Not sure it justifies the dependency.
</blockquote></details>

We can consider outputing this from the cairo-vm run (alongside the values per instruction, if helpful). This is still only CASM-dependent (and AIR-agnostic) IIUC. But it makes the output a larger, not sure if for a good reason.
it makes any u64 an `Instruction`, which is of size 32B on 64b machines (4X).

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/42)* status: 8 of 10 files reviewed, 3 unresolved discussions (waiting on @alonh5, @ohad-starkware, and @yuvalsw)

___
*[`stwo_cairo_prover/src/input/instructions.rs` line 18 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/42#-O3knoIfAVp_SzJzm8Wt:-O3kzvwU3rtI1N-I1P6V:bhnarm3) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/6563fbb9950b107ba0ecde27372533d6b600ea95/stwo_cairo_prover/src/input/instructions.rs#L18)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

We can consider outputing this from the cairo-vm run (alongside the values per instruction, if helpful). This is still only CASM-dependent (and AIR-agnostic) IIUC. But it makes the output a larger, not sure if for a good reason.
it makes any u64 an `Instruction`, which is of size 32B on 64b machines (4X).
</blockquote></details>

Most likely disk read speed will be the bottleneck, so if we stay with files, I don't think it's worth it.
If we move to an in-memory solution using api from the vm
___
*[`stwo_cairo_prover/src/input/io.rs` line 21 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/42#-O3ksQOs0cZFWJM669DT:-O3lYRLR0ocpeO5oiHmf:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/6563fbb9950b107ba0ecde27372533d6b600ea95/stwo_cairo_prover/src/input/io.rs#L21)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

either put in a cairo-vm folder or rename
</blockquote></details>

Done.

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/42)* status: 0 of 11 files reviewed, 3 unresolved discussions (waiting on @alonh5, @ohad-starkware, and @yuvalsw)

___
*[`stwo_cairo_prover/src/input/instructions.rs` line 18 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/42#-O3knoIfAVp_SzJzm8Wt:-O3lbL3lCJ33Nqik06n6:b3f833) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/6563fbb9950b107ba0ecde27372533d6b600ea95/stwo_cairo_prover/src/input/instructions.rs#L18)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Most likely disk read speed will be the bottleneck, so if we stay with files, I don't think it's worth it.
If we move to an in-memory solution using api from the vm
</blockquote></details>

Then maybe it'll pay off.
Don't think it's necessary right now

**Comment by yuvalsw** [comment]
*[`stwo_cairo_prover/src/input/instructions.rs` line 18 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/42#-O3knoIfAVp_SzJzm8Wt:-O3ll3bVBAh95PZ-4xiS:b-bhv7al) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/6563fbb9950b107ba0ecde27372533d6b600ea95/stwo_cairo_prover/src/input/instructions.rs#L18)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Then maybe it'll pay off.
Don't think it's necessary right now
</blockquote></details>

One main advantage to do so is separation of concerns. But the actual run-time is not less important. If we decide to separate, your in-memory suggestion sounds right.

**Review by ohad-starkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 11 files at r4, 4 of 8 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/42)* status: 5 of 13 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @spapinistarkware)

___
*[`stwo_cairo_prover/src/input/vm_import.rs` line 22 at r7](https://reviewable.io/reviews/starkware-libs/stwo-cairo/42#-O3m4q2b-4psOVRJ3bAK:-O3m4q2b-4psOVRJ3bAL:b-co5kf6) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/958a7c5d93ab4d2b5053fd72dd4d8854d6d9a1f4/stwo_cairo_prover/src/input/vm_import.rs#L22)):*
> ```XML
> #[derive(Copy, Clone, Default, Pod, Zeroable)]
> pub struct TraceEntry {
>     pub ap: u64,
> ```

u32 here?

**Review by ohad-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 11 files at r4, 4 of 8 files at r5, 2 of 2 files at r6, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/42#-:-O3m5C5q3c_eLffxBjgn:bnfp4nl)* status: 12 of 13 files reviewed, all discussions resolved (waiting on @alonh5)

**Pull request merged**
