### PR TITLE
add adapter tests

### PR DESCRIPTION
**Pull request by Stavbe**
Add a unit test to ensure instructions are correctly mapped with the adapter.
The only components that can’t be tested using casm! are:

jmp rel [ap/fp + offset]
jump abs [[ap/fp + offset1] + offset2]
[ap/fp + offset0] = [[ap/fp + offset1] + offset

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/245)

### CODE REVIEW

**Review by ohad-starkware — COMMENTED** [review]
so double derefs? doc that somewhere

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/245#-:-OE8hVSAE7nHzZ98ndkf:b-cqc9po)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @Stavbe)

**Review by ohad-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/245)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @Stavbe)

___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 641 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/245#-OEEZ4mq8i5whpKSYSI3:-OEEZ4mq8i5whpKSYSI4:bzc1vnh) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/7ac2ebbaeba1a2ddbf6706b7537481bb57d0d2fc/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L641)):*
> ```XML
> 
> // Ensures that instructions are correctly mapped with the adapter.
> // All components were checked except:
> ```

this needs to be a TODO
___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 1030 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/245#-OEEZ8Se-P5VyQXywhmf:-OEEZ8Se-P5VyQXywhmg:b-l6mwxj) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/7ac2ebbaeba1a2ddbf6706b7537481bb57d0d2fc/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L1030)):*
> ```XML
>         let input = input_from_plain_casm(instructions, false);
>         let casm_states_by_opcode = input.state_transitions.casm_states_by_opcode;
>         println!("{:?}", casm_states_by_opcode.counts());
> ```

remove

**Review by Stavbe — COMMENTED** [review]
Added

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/245#-:-OEEUEi-DZB0d3z3iluB:b-8b11j9)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ohad-starkware and @Stavbe)

___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 641 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/245#-OEEZ4mq8i5whpKSYSI3:-OEF0xxx8OD8gBS7kD5u:b-n8bsxu) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/7ac2ebbaeba1a2ddbf6706b7537481bb57d0d2fc/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L641)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

this needs to be a TODO
</blockquote></details>

We won't be able to test those using the same terminology because the casm macro does not support it, and according to Ori Ziv, it will not be expanded to support it.
___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 1030 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/245#-OEEZ8Se-P5VyQXywhmf:-OEF27UF5aNoaTFtI4ZM:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/7ac2ebbaeba1a2ddbf6706b7537481bb57d0d2fc/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L1030)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.

**Review by ohad-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/245)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Stavbe)

___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 641 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/245#-OEEZ4mq8i5whpKSYSI3:-OEIsR3T5ThN1ysJYNKV:bbvenxe) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/7ac2ebbaeba1a2ddbf6706b7537481bb57d0d2fc/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L641)):*
<details><summary><i>Previously, Stavbe wrote…</i></summary><blockquote>

We won't be able to test those using the same terminology because the casm macro does not support it, and according to Ori Ziv, it will not be expanded to support it.
</blockquote></details>

still a todo

**Review by Stavbe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/245)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Stavbe)

___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 641 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/245#-OEEZ4mq8i5whpKSYSI3:-OEPTQ6j6cOib2W28-dK:bzes9g8) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/7ac2ebbaeba1a2ddbf6706b7537481bb57d0d2fc/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L641)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

still a todo
</blockquote></details>

todo what ?

**Review by Stavbe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/245)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ohad-starkware and @Stavbe)

___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 641 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/245#-OEEZ4mq8i5whpKSYSI3:-OEU9X8e1Jykzo6VQ59V:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/7ac2ebbaeba1a2ddbf6706b7537481bb57d0d2fc/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L641)):*
<details><summary><i>Previously, Stavbe wrote…</i></summary><blockquote>

todo what ?
</blockquote></details>

Done.

**Review by ohad-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/245)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @Stavbe)

___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 644 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/245#-OEUDrLx-07ldveSWaa3:-OEUDrLx-07ldveSWaa4:b45h) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3892105524d8f8f533fa9c683cf2be053b6da035/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L644)):*
> ```XML
> }
> 
> // Ensures that instructions are correctly mapped with the adapter.
> ```





_Suggestion:_
```XML
/// Tests instructions mapping.
```
___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 645 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/245#-OEUEjdE1tUqWF3HT1pd:-OEUEjdE1tUqWF3HT1pe:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3892105524d8f8f533fa9c683cf2be053b6da035/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L645)):*
> ```XML
> 
> // Ensures that instructions are correctly mapped with the adapter.
> // All components were checked except:
> ```





_Suggestion:_
```XML
/// Every opcode is tested except:
```
___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 650 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/245#-OEUEFPQ5sT5UDZb9ztX:-OEUEFPQ5sT5UDZb9ztY:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3892105524d8f8f533fa9c683cf2be053b6da035/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L650)):*
> ```XML
> // TODO(Stav): Find a way to check those without the casm macro.
> #[cfg(test)]
> mod tests {
> ```





_Suggestion:_
```XML
mod mappings_tests
```

**Review by Stavbe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/245)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ohad-starkware and @Stavbe)

___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 644 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/245#-OEUDrLx-07ldveSWaa3:-OEUIAD31t9HjdmInpPc:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3892105524d8f8f533fa9c683cf2be053b6da035/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L644)):*
> ```XML
> }
> 
> // Ensures that instructions are correctly mapped with the adapter.
> ```

Done.
___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 645 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/245#-OEUEjdE1tUqWF3HT1pd:-OEUIBwC1MRNE2uZGFiU:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3892105524d8f8f533fa9c683cf2be053b6da035/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L645)):*
> ```XML
> 
> // Ensures that instructions are correctly mapped with the adapter.
> // All components were checked except:
> ```

Done.

**Review by ohad-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/245)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @Stavbe)

___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 215 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/245#-OEURU3M6UXkPSYdOHp9:-OEURU3M6UXkPSYdOHpA:b9shmhs) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/cca282b955954b5446f2dcd35ec4d015c0a799f7/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L215)):*
> ```XML
>         // TODO(Ohad): update counts after adding mull small.
>         assert_eq!(components.mul_opcode_is_small_t_is_imm_t.len(), 0);
>         assert_eq!(components.mul_opcode_is_small_t_is_imm_f.len(), 0);
> ```

can dev mode be turned off here and revert that?

**Review by Stavbe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/245)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @ohad-starkware and @Stavbe)

___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 215 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/245#-OEURU3M6UXkPSYdOHp9:-OEUfhp1Af-2cbsYY7FM:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/cca282b955954b5446f2dcd35ec4d015c0a799f7/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L215)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

can dev mode be turned off here and revert that?
</blockquote></details>

Done.

**Comment by ohad-starkware** [comment]
*[`stwo_cairo_prover/crates/adapted_prover/src/main.rs` line 68 at r7](https://reviewable.io/reviews/starkware-libs/stwo-cairo/245#-OEhKMre7g6RHZGeOrha:-OEhKMre7g6RHZGeOrhb:b-l6mwxj) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/6eb8bed4be3976c6ba4d7876b37bb0663ee6ce74/stwo_cairo_prover/crates/adapted_prover/src/main.rs#L68)):*
> ```XML
>     let args = Args::try_parse_from(args)?;
> 
>     // dev_mode = true
> ```

remove

**Comment by ohad-starkware** [comment]
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 648 at r7](https://reviewable.io/reviews/starkware-libs/stwo-cairo/245#-OEhKSM53JdtvHQZH9ot:-OEhKSM53JdtvHQZH9ou:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/6eb8bed4be3976c6ba4d7876b37bb0663ee6ce74/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L648)):*
> ```XML
> // - `jmp rel [ap/fp + offset]`
> // - `jmp abs [[ap/fp + offset1] + offset2]`
> // TODO(Stav): Find a way to check those without the casm macro.
> ```





_Suggestion:_
```XML
/// Every opcode is tested except:
/// - `jmp rel [ap/fp + offset]`
/// - `jmp abs [[ap/fp + offset1] + offset2]`
// TODO(Stav): Find a way to check those without the casm macro.
```

**Review by Stavbe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/245)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @ohad-starkware and @Stavbe)

___
*[`stwo_cairo_prover/crates/adapted_prover/src/main.rs` line 68 at r7](https://reviewable.io/reviews/starkware-libs/stwo-cairo/245#-OEhKMre7g6RHZGeOrha:-OEhU8GV-NEHiL1cmHXr:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/6eb8bed4be3976c6ba4d7876b37bb0663ee6ce74/stwo_cairo_prover/crates/adapted_prover/src/main.rs#L68)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 648 at r7](https://reviewable.io/reviews/starkware-libs/stwo-cairo/245#-OEhKSM53JdtvHQZH9ot:-OEhU7cpDrexCVEz30Co:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/6eb8bed4be3976c6ba4d7876b37bb0663ee6ce74/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L648)):*
> ```XML
> // - `jmp rel [ap/fp + offset]`
> // - `jmp abs [[ap/fp + offset1] + offset2]`
> // TODO(Stav): Find a way to check those without the casm macro.
> ```

Done.

**Pull request merged**
