### PR TITLE
addr_to_id fixes

### PR DESCRIPTION
**Pull request by ohad-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/161)

### CODE REVIEW

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/161)* status: all files reviewed, 4 unresolved discussions (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/components/memory/addr_to_id/prover.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/161#-OBZmb014U0pY9l0t5bC:-OBZmb014U0pY9l0t5bD:brl5oe2) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/d1632030ffab9d9aef5e0f459f120fdf69786b6b/stwo_cairo_prover/crates/prover/src/components/memory/addr_to_id/prover.rs#L50)):*
> ```XML
>     pub fn deduce_output_cpu(&self, input: BaseField) -> M31 {
>         M31(self.ids[input.0 as usize])
>     }
> ```

How would the autogen components use this function?



_Code quote:_
```XML
    pub fn deduce_output_cpu(&self, input: BaseField) -> M31 {
        M31(self.ids[input.0 as usize])
    }
```
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/addr_to_id/prover.rs` line 87 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/161#-OBZmzn062MnU8CADbFm:-OBZmzn1D1ZGOeWDu19Y:b-l6mkjh) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/d1632030ffab9d9aef5e0f459f120fdf69786b6b/stwo_cairo_prover/crates/prover/src/components/memory/addr_to_id/prover.rs#L87)):*
> ```XML
>             .ids
>             .array_chunks::<N_LANES>()
>             .map(|c| PackedM31::from_array(std::array::from_fn(|i| M31::from_u32_unchecked(c[i]))))
> ```

rename



_Suggestion:_
```XML
.map(|chunk| PackedM31::from_array(std::array::from_fn(|i| M31::from_u32_unchecked(chunk[i]))))
```
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/addr_to_id/prover.rs` line 92 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/161#-OBZn7jvDUe_vFRijQIi:-OBZn7jw93VyuOvxFY-m:b-tq20t3) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/d1632030ffab9d9aef5e0f459f120fdf69786b6b/stwo_cairo_prover/crates/prover/src/components/memory/addr_to_id/prover.rs#L92)):*
> ```XML
>         for (i, id) in packed_ids.iter().enumerate() {
>             trace[0].data[i] =
>                 PackedM31::broadcast(BaseField::from_u32_unchecked((i * N_LANES) as u32)) + inc;
> ```

Can you add a TODO that this should be replaced with constant "seq" column?
or do we already have it somewhere else?



_Code quote:_
```XML
            trace[0].data[i] =
                PackedM31::broadcast(BaseField::from_u32_unchecked((i * N_LANES) as u32)) + inc;
```
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/addr_to_id/component.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/161#-OBZmWI65OCYecMPMq_m:-OBZmWI73Jfaf7zpxLC5:b-p6zsxm) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/d1632030ffab9d9aef5e0f459f120fdf69786b6b/stwo_cairo_prover/crates/prover/src/components/memory/addr_to_id/component.rs#L29)):*
> ```XML
>         &self.0
>     }
> }
> ```

why is this change?



_Code quote:_
```XML
#[derive(Clone)]
pub struct RelationElements(LookupElements<2>);
impl RelationElements {
    pub fn draw(channel: &mut impl Channel) -> Self {
        Self(LookupElements::<2>::draw(channel))
    }
}
impl Deref for RelationElements {
    type Target = LookupElements<2>;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
```

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/161)* status: all files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/components/memory/addr_to_id/component.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/161#-OBZmWI65OCYecMPMq_m:-OBZvjTz84V9C-CGfWDV:b-enk620) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/d1632030ffab9d9aef5e0f459f120fdf69786b6b/stwo_cairo_prover/crates/prover/src/components/memory/addr_to_id/component.rs#L29)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

why is this change?
</blockquote></details>

this is what relations should look like, after alon finishes with the macro it will get replaced
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/addr_to_id/prover.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/161#-OBZmb014U0pY9l0t5bC:-OBZtlXnCWq8OUP_1mhk:bngaowh) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/d1632030ffab9d9aef5e0f459f120fdf69786b6b/stwo_cairo_prover/crates/prover/src/components/memory/addr_to_id/prover.rs#L50)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

How would the autogen components use this function?
</blockquote></details>

they do not
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/addr_to_id/prover.rs` line 87 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/161#-OBZmzn062MnU8CADbFm:-OB_0Nlu9M6R6mZxTsVy:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/d1632030ffab9d9aef5e0f459f120fdf69786b6b/stwo_cairo_prover/crates/prover/src/components/memory/addr_to_id/prover.rs#L87)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

rename
</blockquote></details>

Done.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/161#-:-OB_mQou6tQb_DLIMpCX:bnfp4nl)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/components/memory/addr_to_id/prover.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/161#-OBZmb014U0pY9l0t5bC:-OB_mO9h5uT5hyH1GvLj:bf8z9av) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/d1632030ffab9d9aef5e0f459f120fdf69786b6b/stwo_cairo_prover/crates/prover/src/components/memory/addr_to_id/prover.rs#L50)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

they do not
</blockquote></details>

remove pub then

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/161)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/components/memory/addr_to_id/prover.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/161#-OBZmb014U0pY9l0t5bC:-OB_mogM0h8vKtc_BVdr:b-7rl0jd) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/d1632030ffab9d9aef5e0f459f120fdf69786b6b/stwo_cairo_prover/crates/prover/src/components/memory/addr_to_id/prover.rs#L50)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

remove pub then
</blockquote></details>

done.

**Pull request merged**
