### PR TITLE
Add range check builtin to cairo air.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/70)

### CODE REVIEW

**Comment by alonh5** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/70?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#70** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/70?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#65** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/65?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#64** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/64?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alonh5 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/70)* status: all files reviewed, 7 unresolved discussions (waiting on @Alon-Ti, @shaharsamocha7, and @spapinistarkware)

___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs` line 59 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/70#-O5m_Kfs7S7HxsYWPwZi:-O5mkvaS4HspInJ0s-Px:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/a3a3e9c1bb0706f450dd8e82706551fea97e8983/stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs#L59)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Put range check and memory always in the same order (both struct and calls)
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs` line 353 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/70#-O5max7i18YaUr_hPgxv:-O5mlYnQ6OWotad6-RwQ:b-3fsjq0) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/a3a3e9c1bb0706f450dd8e82706551fea97e8983/stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs#L353)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Try to undersand how the runner accepts the range check segment
</blockquote></details>

Added A TODO, will do in a seperate PR.
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/prover.rs` line 145 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/70#-O5mbEiBBQJsRXu7E_tZ:-O5mi3s25DLrqwrHUPol:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/a3a3e9c1bb0706f450dd8e82706551fea97e8983/stwo_cairo_prover/crates/prover/src/components/memory/prover.rs#L145)):*
> ```XML
>         lookup_elements: &MemoryLookupElements,
>     ) -> MemoryInteractionClaim {
>         let log_size = self.adresses_and_values[0].len().ilog2() + LOG_N_LANES;
> ```

Done.
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_builtin/component.rs` line 71 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/70#-O5mc7LuEKW7uLTB_0Ob:-O5miI3e-fj0Y_Ztlfvw:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/a3a3e9c1bb0706f450dd8e82706551fea97e8983/stwo_cairo_prover/crates/prover/src/components/range_check_builtin/component.rs#L71)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Add a TODO to constrain the 2 bits
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_builtin/component.rs` line 74 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/70#-O5mbd6v4EugzFlQNImO:-O5miIYjDR2Li9io8uBl:b-hxv02d) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/a3a3e9c1bb0706f450dd8e82706551fea97e8983/stwo_cairo_prover/crates/prover/src/components/range_check_builtin/component.rs#L74)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Why not 2?
</blockquote></details>

There's only one column anyways, no?
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_builtin/prover.rs` line 47 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/70#-O5mcTMiBLDjLtkSxvQW:-O5miZjT-ByQ6c_YB8Sg:b-3pq2dl) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/a3a3e9c1bb0706f450dd8e82706551fea97e8983/stwo_cairo_prover/crates/prover/src/components/range_check_builtin/prover.rs#L47)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

addresses should be increasing
</blockquote></details>

Addede a TODO (we don't have a quick fix do we?)
___
*[`stwo_cairo_prover/crates/prover/src/input/plain.rs` line 78 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/70#-O5maFY2DuODXWxwNsjL:-O5mlb_M6r6h8uHBb7h1:b-70pz2e) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/a3a3e9c1bb0706f450dd8e82706551fea97e8983/stwo_cairo_prover/crates/prover/src/input/plain.rs#L78)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

This shouldn't be hardcoded. This is dynamic.
I think the runner has api for range check and memory segment.
For example, at `import\_from\_vm\_output` we construct `CairoInput` using the json. Here you don't have a json, but you should find out how to get it from the runner.
</blockquote></details>

Same TODO as above.

**Review by shaharsamocha7 — COMMENTED** [review]
> Reviewed 1 of 8 files at r1, 1 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/70)* status: 4 of 9 files reviewed, 7 unresolved discussions (waiting on @Alon-Ti and @spapinistarkware)

___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_builtin/component.rs` line 74 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/70#-O5mbd6v4EugzFlQNImO:-O5qh7H84R3gIKvuS36O:b-obtrkh) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/a3a3e9c1bb0706f450dd8e82706551fea97e8983/stwo_cairo_prover/crates/prover/src/components/range_check_builtin/component.rs#L74)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

There's only one column anyways, no?
</blockquote></details>

I think that this is the same in the case that you have 1 column (so you could also leave this value with 2)
but this is also ok

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/70)* status: 4 of 9 files reviewed, 7 unresolved discussions (waiting on @Alon-Ti and @spapinistarkware)

___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_builtin/component.rs` line 74 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/70#-O5mbd6v4EugzFlQNImO:-O5qlME39oyKxjIzk3qB:bcm3oik) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/a3a3e9c1bb0706f450dd8e82706551fea97e8983/stwo_cairo_prover/crates/prover/src/components/range_check_builtin/component.rs#L74)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I think that this is the same in the case that you have 1 column (so you could also leave this value with 2)
but this is also ok
</blockquote></details>

Yes, it's just more explicit this way. I'll leave it like this

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/70#-:-O5waPri6GtwUDrkQaB2:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @Alon-Ti, @alonh5, and @spapinistarkware)

___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 130 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/70#-O5wa7TcCyWZofELc-D5:-O5wa7Td1bDdeR673awQ:bq39uj6) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/4c051ebfd3d20fa098c8ca68565b72889a46835c/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L130)):*
> ```XML
>     }
> 
>     // Slow test. Run only in release.
> ```

Either remove the comment or add 
`#[cfg_attr(not(feature = "slow-tests"), ignore)]`



_Code quote:_
```XML
// Slow test. Run only in release.
```

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/70#-:-O5wb0RE6FIcI_YcjK6O:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Alon-Ti and @alonh5)

**Comment by alonh5** [comment]
### Merge activity

* **Sep 4, 6:39 AM EDT**: @alonh5 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/70).

**Pull request merged**
