### PR TITLE
add generic_opcode

### PR DESCRIPTION
**Pull request by ohad-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/187)

### CODE REVIEW

**Comment by ohad-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/187?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#188** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/188?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#187** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/187?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/187?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#180** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/180?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#182](https://github.com/starkware-libs/stwo-cairo/pull/182) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/182?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#179** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/179?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#177** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/177?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#178** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/178?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#176** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/176?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/187)* status: all files reviewed, 4 unresolved discussions (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/air.rs` line 94 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/187#-OC946mBBdeLcrzlRl48:-OC946mBBdeLcrzlRl49:b419lqo) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/9bc3880fce85864df8ab087268fcc16a1454f976/stwo_cairo_prover/crates/prover/src/cairo_air/air.rs#L94)):*
> ```XML
>     // Opcodes
>     ret_trace_generator: ret_opcode::ClaimGenerator,
>     generic_opcode_trace_generator: genericopcode::ClaimGenerator,
> ```

move above ret,
I think that also here it should be alphabetically ordered.



_Code quote:_
```XML
generic_opcode_trace_generator: genericopcode::ClaimGenerator,
```
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/air.rs` line 393 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/187#-OC9568IC7424uZPqC0A:-OC9568IC7424uZPqC0B:b-petyhq) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/9bc3880fce85864df8ab087268fcc16a1454f976/stwo_cairo_prover/crates/prover/src/cairo_air/air.rs#L393)):*
> ```XML
>     } else {
>         interaction_claim.generic.total_sum
>     };
> ```

Please add a comment about that logic,
I would maybe refactor such that 
claimed_sum = claimed_sum if not None else total_sum..



_Code quote:_
```XML
    sum += if let Some((claimed_sum, ..)) = interaction_claim.generic.claimed_sum {
        claimed_sum
    } else {
        interaction_claim.generic.total_sum
    };
```
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/187#-OC99dKG06ZbEky632Q6:-OC99dKG06ZbEky632Q7:b387m8x) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/9bc3880fce85864df8ab087268fcc16a1454f976/stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs#L20)):*
> ```XML
> const LOG_MAX_ROWS: u32 = 20;
> 
> const IS_FIRST_LOG_SIZES: [u32; 7] = [18, 4, 14, 19, 7, 6, 5];
> ```

can you now order it in descending order?



_Code quote:_
```XML
const IS_FIRST_LOG_SIZES: [u32; 7] = [18, 4, 14, 19, 7, 6, 5];
```
___
*[`stwo_cairo_prover/crates/prover_types/src/simd.rs` line 28 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/187#-OC99kPo29HC4es-oXHI:-OC99kPo29HC4es-oXHJ:bb7hquh) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/9bc3880fce85864df8ab087268fcc16a1454f976/stwo_cairo_prover/crates/prover_types/src/simd.rs#L28)):*
> ```XML
> #[derive(Clone, Copy, Debug)]
> pub struct PackedBool {
>     pub(crate) value: Simd<i32, N_LANES>,
> ```

huh?



_Code quote:_
```XML
    pub(crate) value: Simd<i32, N_LANES>,
```

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/187)* status: all files reviewed, 4 unresolved discussions (waiting on @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/air.rs` line 94 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/187#-OC946mBBdeLcrzlRl48:-OCCETG_E_mxCdLmRsES:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/9bc3880fce85864df8ab087268fcc16a1454f976/stwo_cairo_prover/crates/prover/src/cairo_air/air.rs#L94)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

move above ret,
I think that also here it should be alphabetically ordered.
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/air.rs` line 393 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/187#-OC9568IC7424uZPqC0A:-OCCESRkBugcccrM76vG:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/9bc3880fce85864df8ab087268fcc16a1454f976/stwo_cairo_prover/crates/prover/src/cairo_air/air.rs#L393)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Please add a comment about that logic,
I would maybe refactor such that 
claimed_sum = claimed_sum if not None else total_sum..
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/187#-OC99dKG06ZbEky632Q6:-OCCETxw-CWvwB5Vcg3E:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/9bc3880fce85864df8ab087268fcc16a1454f976/stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs#L20)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

can you now order it in descending order?
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover_types/src/simd.rs` line 28 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/187#-OC99kPo29HC4es-oXHI:-OCCGGwBEiIBUyJJ0iya:bpa6wy7) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/9bc3880fce85864df8ab087268fcc16a1454f976/stwo_cairo_prover/crates/prover_types/src/simd.rs#L28)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

huh?
</blockquote></details>

SimdEq is weird
the instruction returns -1 for true, and we want 1
I found something better

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/187)* status: 4 of 7 files reviewed, 2 unresolved discussions (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/air.rs` line 390 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/187#-OCSO6A79LJqNIpBsaAr:-OCSO6A79LJqNIpBsaAs:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/09ed086d89037210f81459b4be1e2b8ea39175cc/stwo_cairo_prover/crates/prover/src/cairo_air/air.rs#L390)):*
> ```XML
>         .sum::<SecureField>();
> 
>     // If the table is padded, take the sum of the 'real' values.
> ```





_Suggestion:_
```XML
    // If the table is padded, take the sum of the non-padded values.
    // Otherwise, the claimed_sum is the total_sum.
```

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/187)* status: 4 of 7 files reviewed, 2 unresolved discussions (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover_types/src/simd.rs` line 28 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/187#-OC99kPo29HC4es-oXHI:-OCSOrQe3MB16yr1LZyU:b6j07g5) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/9bc3880fce85864df8ab087268fcc16a1454f976/stwo_cairo_prover/crates/prover_types/src/simd.rs#L28)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

SimdEq is weird
the instruction returns -1 for true, and we want 1
I found something better
</blockquote></details>

can't we just multiply by -1?

how u8 returns -1?

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/187)* status: 4 of 7 files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover_types/src/simd.rs` line 28 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/187#-OC99kPo29HC4es-oXHI:-OCSsB1_7fmn9ghfHoVI:bs6hoga) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/9bc3880fce85864df8ab087268fcc16a1454f976/stwo_cairo_prover/crates/prover_types/src/simd.rs#L28)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

can't we just multiply by -1?

how u8 returns -1?
</blockquote></details>

it returns a Mask type (not u8), so it makes sense because 0xFFFFFF... its -1 and that's the mask you want if you're doing comparisons

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/187)* status: 4 of 7 files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/air.rs` line 390 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/187#-OCSO6A79LJqNIpBsaAr:-OCStO3c8CvB6AG9uFR9:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/caa3be929fa6b57fdccd84430de68f4b2858867d/stwo_cairo_prover/crates/prover/src/cairo_air/air.rs#L390)):*
> ```XML
>         .sum::<SecureField>();
> 
>     // If the table is padded, take the sum of the 'real' values.
> ```

Done.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/187)* status: 4 of 7 files reviewed, 1 unresolved discussion (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/air.rs` line 390 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/187#-OCSO6A79LJqNIpBsaAr:-OCStvPK7fc06EIl01uI:b-oz1lh6) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/caa3be929fa6b57fdccd84430de68f4b2858867d/stwo_cairo_prover/crates/prover/src/cairo_air/air.rs#L390)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

didn't push?

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/187)* status: 4 of 7 files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/air.rs` line 390 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/187#-OCSO6A79LJqNIpBsaAr:-OCSvLUYDoH4ihnIP54G:bb7s9zc) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/caa3be929fa6b57fdccd84430de68f4b2858867d/stwo_cairo_prover/crates/prover/src/cairo_air/air.rs#L390)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

didn't push?
</blockquote></details>

yes

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/187#-:-OCTDkBvAxL_-4p46dlU:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ohad-starkware)

**Pull request merged**
