### PR TITLE
Add rust crate for stwo cairo prover

### PR DESCRIPTION
**Pull request by shaharsamocha7**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/7)

### CODE REVIEW

**Comment by shaharsamocha7** [comment]
* **#7** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/7?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @shaharsamocha7 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/7#-:-O-pqLv0CgvHZ4azL9y4:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

___
*[`.gitignore` line 1 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/7#-O-pq66m6-8Xm9I7Q4Px:-O-pq66m6-8Xm9I7Q4Py:bspcfb) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ea5fc39bebd16a8bbca27b3c52ea1668db9ae421/.gitignore#L1)):*
> ```ignore
> /target
> ```

Is this the default gitignore we get with cargo init / cargo new?

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/7)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`.gitignore` line 1 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/7#-O-pq66m6-8Xm9I7Q4Px:-O-pr_djAgkyrG6XsLDs:b2nhswy) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ea5fc39bebd16a8bbca27b3c52ea1668db9ae421/.gitignore#L1)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Is this the default gitignore we get with cargo init / cargo new?
</blockquote></details>

Yes

**Comment by shaharsamocha7** [comment]
### Merge activity

* **Jun 25, 3:00 AM EDT**: @shaharsamocha7 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/7).

**Pull request merged**
