### PR TITLE
Optimize hash_node

### PR DESCRIPTION
**Pull request by andrewmilson**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/163)

### CODE REVIEW

**Comment by andrewmilson** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/163?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#164** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/164?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#163** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/163?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#162** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/162?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#137** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/137?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#138](https://github.com/starkware-libs/stwo-cairo/pull/138) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/138?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#135** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/135?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#134** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/134?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#153** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/153?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#133** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/133?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#152](https://github.com/starkware-libs/stwo-cairo/pull/152) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/152?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#127** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/127?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#118** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/118?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/117?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#116** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/116?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#115** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/115?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#114** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/114?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#113** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/113?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#112** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/112?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @andrewmilson and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by ilyalesokhin-starkware** [comment]
*[`stwo_cairo_verifier/src/vcs/hasher.cairo` line 46 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/163#-OBZu2SrAsI87nK19Fz7:-OBZu2SrAsI87nK19Fz8:b-u0qmb3) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/b6dda2ab78f0fcba4b45c5d6b6d6e89c0acdd357/stwo_cairo_verifier/src/vcs/hasher.cairo#L46)):*
> ```Cairo
>                 let (s0, s1, s2) = hades_permutation(x, y, 0);
>                 let hash_state = HashState { s0, s1, s2, odd: false };
>                 return hash_state.finalize();
> ```

Add a todo to consider using:
Posiedon2 here { == hades_permutation(x, y, 2); }



_Code quote:_
```Cairo
                // Inlined and simplified `poseidon_hash_span(...)` for better performance.
                let (s0, s1, s2) = hades_permutation(x, y, 0);
                let hash_state = HashState { s0, s1, s2, odd: false };
                return hash_state.finalize();
```

**Comment by ilyalesokhin-starkware** [comment]
*[`stwo_cairo_verifier/src/vcs/hasher.cairo` line 71 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/163#-OBZv9176tvQSiiLa5HI:-OBZv9176tvQSiiLa5HJ:b45h) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/b6dda2ab78f0fcba4b45c5d6b6d6e89c0acdd357/stwo_cairo_verifier/src/vcs/hasher.cairo#L71)):*
> ```Cairo
>             column_values.append(core::num::traits::Zero::zero());
>             pad_len -= 1;
>         };
> ```





_Suggestion:_
```Cairo
        let padding = core::num::traits::Zero::zero();
        for 0..pad_len {
            column_values.append(padding);
        };
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/163)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

___
*[`stwo_cairo_verifier/src/vcs/hasher.cairo` line 51 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/163#-OBZu_lh9lZ4oiBaOHYK:-OBZu_lh9lZ4oiBaOHYL:b-gin7c5) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/b6dda2ab78f0fcba4b45c5d6b6d6e89c0acdd357/stwo_cairo_verifier/src/vcs/hasher.cairo#L51)):*
> ```Cairo
>             hash_array.append(y);
>         } else {
>             // Most offten a single QM31 column commitment due to FRI.
> ```

Maybe we can use a dedeciated de-commit function for FRI?



_Code quote:_
```Cairo
 // Most offten a single QM31 column commitment due to FRI.
```

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/163#-:-OBdQPb01ho9lfBQwA2y:bnfp4nl)* status: 1 of 4 files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Pull request merged**
