### PR TITLE
Public memory addresses

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/54)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/54?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#54** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/54?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#53** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/53?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#52** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/52?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#51** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/51?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 15 files at r1, 13 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/54#-:-O4LPGDo7kb5SApqP1Dp:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`stwo_cairo_prover/crates/prover/src/input/mod.rs` line 15 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/54#-O4LPHKG3ks1awwrBExg:-O4LPHKHAe7_843ZOZb1:b-7vy127) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/30231c7cccc1c167bd172a3211fe9b887dbe95ab/stwo_cairo_prover/crates/prover/src/input/mod.rs#L15)):*
> ```XML
>     pub instructions: Instructions,
>     pub mem: Memory,
>     pub public_mem_addresses: Vec<u32>,
> ```

What are public memory addresses used for? Location of builtins?

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/54)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`stwo_cairo_prover/crates/prover/src/input/mod.rs` line 15 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/54#-O4LPHKG3ks1awwrBExg:-O4ZvvKu9t9pMs40Km-M:bojy90t) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/30231c7cccc1c167bd172a3211fe9b887dbe95ab/stwo_cairo_prover/crates/prover/src/input/mod.rs#L15)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

What are public memory addresses used for? Location of builtins?
</blockquote></details>

Memory exposed to verifier.

**Review by alonh5 — COMMENTED** [review]
> Reviewed 1 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/54)* status: 11 of 15 files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by alonh5 — APPROVED** [review]
> Reviewed 4 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/54)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Comment by spapinistarkware** [comment]
### Merge activity

* **Aug 18, 7:48 AM EDT**: @spapinistarkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/54).

**Pull request merged**
