### PR TITLE
Move memory id to value AIR

### PR DESCRIPTION
**Pull request by shaharsamocha7**
Move memory id to value AIR

Adjust memory to id_to_f252 component

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/129)

### CODE REVIEW

**Comment by shaharsamocha7** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/129?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#130** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/130?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#129** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/129?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#128** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/128?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @shaharsamocha7 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Alon-Ti — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/129)* status: all files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/components/memory/id_to_f252/mod.rs` line 7 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/129#-OAHzTNh8y7NT8JS-YFo:-OAHzTNh8y7NT8JS-YFp:b-cw8fas) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/56496153286f4684920873772f5d5a576d790d70/stwo_cairo_prover/crates/prover/src/components/memory/id_to_f252/mod.rs#L7)):*
> ```XML
> pub mod prover;
> 
> const N_LOGUP_POWERS: usize = N_ID_TO_VALUE_COLUMNS - 1;
> ```

`MEMORY_ID_SIZE + N_M31_IN_FELT252` or `N_ID_TO_VALUE_COLUMNS - N_MULTIPLICITY_COLUMNS` if you add it.
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/id_to_f252/component.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/129#-OAHz1tg--C42BopMVH0:-OAHz1tg--C42BopMVH1:bg3fd33) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/56496153286f4684920873772f5d5a576d790d70/stwo_cairo_prover/crates/prover/src/components/memory/id_to_f252/component.rs#L16)):*
> ```XML
> pub const MEMORY_ID_SIZE: usize = 1;
> pub const N_M31_IN_FELT252: usize = 28;
> pub const MULTIPLICITY_COLUMN_OFFSET: usize = N_M31_IN_FELT252 + 1;
> ```

` + MEMORY_ID_SIZE`



_Code quote:_
```XML
 + 1
```
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/id_to_f252/component.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/129#-OAHz83G6fKhdWkr1Ysj:-OAHz83G6fKhdWkr1Ysk:b9i8rug) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/56496153286f4684920873772f5d5a576d790d70/stwo_cairo_prover/crates/prover/src/components/memory/id_to_f252/component.rs#L18)):*
> ```XML
> pub const MULTIPLICITY_COLUMN_OFFSET: usize = N_M31_IN_FELT252 + 1;
> // TODO(AlonH): Make memory size configurable.
> pub const N_ID_TO_VALUE_COLUMNS: usize = MEMORY_ID_SIZE + N_M31_IN_FELT252 + 1;
> ```

Maybe `N_MULTIPLICITY_COLUMNS` given everything else is constants?



_Code quote:_
```XML
1
```

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/129)* status: all files reviewed, 2 unresolved discussions (waiting on @Alon-Ti)

___
*[`stwo_cairo_prover/crates/prover/src/components/memory/id_to_f252/mod.rs` line 7 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/129#-OAHzTNh8y7NT8JS-YFo:-OAMNem37X4a8H5MJHQv:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/56496153286f4684920873772f5d5a576d790d70/stwo_cairo_prover/crates/prover/src/components/memory/id_to_f252/mod.rs#L7)):*
<details><summary><i>Previously, Alon-Ti wrote…</i></summary><blockquote>

`MEMORY_ID_SIZE + N_M31_IN_FELT252` or `N_ID_TO_VALUE_COLUMNS - N_MULTIPLICITY_COLUMNS` if you add it.
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/id_to_f252/component.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/129#-OAHz1tg--C42BopMVH0:-OAMN0Nv2suVxixiqWhD:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/56496153286f4684920873772f5d5a576d790d70/stwo_cairo_prover/crates/prover/src/components/memory/id_to_f252/component.rs#L16)):*
<details><summary><i>Previously, Alon-Ti wrote…</i></summary><blockquote>

` + MEMORY_ID_SIZE`
</blockquote></details>

Done.

**Comment by shaharsamocha7** [comment]
### Merge activity

* **Oct 29, 4:51 AM EDT**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/129).

**Pull request merged**
