### PR TITLE
parralelize ret

### PR DESCRIPTION
**Pull request by ohad-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/234)

### CODE REVIEW

**Comment by ohad-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/234?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#234** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/234?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/234?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#233** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/233?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#229** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/229?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#231](https://github.com/starkware-libs/stwo-cairo/pull/231) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/231?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#222** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/222?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#228** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/228?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#221** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/221?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#220** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/220?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#219** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/219?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#218** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/218?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#217** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/217?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#216** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/216?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#215** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/215?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#214** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/214?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#209** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/209?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#208** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/208?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#207** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/207?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#206** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/206?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by Alon-Ti — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/234)* status: all files reviewed, 2 unresolved discussions (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/components/ret_opcode/prover.rs` line 205 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/234#-ODapKCm4MrrtVjkkYRL:-ODapKCm4MrrtVjkkYRM:bhe57or) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e493cd153aa3770553201887ecde529c260f3ec7/stwo_cairo_prover/crates/prover/src/components/ret_opcode/prover.rs#L205)):*
> ```XML
>     unsafe {
>         inputs
>             .par_iter()
> ```

@shaharsamocha7 Do we want a `feature` on this so we can test single-threaded performance? 
___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 66 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/234#-ODaovEDEKVwNobPdWJb:-ODaovEDEKVwNobPdWJc:bgwmeni) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e493cd153aa3770553201887ecde529c260f3ec7/stwo_cairo_prover/crates/prover/src/components/mod.rs#L66)):*
> ```XML
>     fn new(rows: usize) -> Self {
>         Self {
>             data: array::from_fn(|_| UnsafeCell::new(BaseColumn::zeros(rows))),
> ```

use `BaseColumn::uninitialized`

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/234)* status: all files reviewed, 2 unresolved discussions (waiting on @Alon-Ti)

___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 66 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/234#-ODaovEDEKVwNobPdWJb:-ODar_gx9abjkyxhcK2f:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e493cd153aa3770553201887ecde529c260f3ec7/stwo_cairo_prover/crates/prover/src/components/mod.rs#L66)):*
<details><summary><i>Previously, Alon-Ti wrote…</i></summary><blockquote>

use `BaseColumn::uninitialized`
</blockquote></details>

Done.

**Review by Alon-Ti — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/234#-:-ODatI6U1g7uy4iwgKt4:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ohad-starkware)

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/234)* status: all files reviewed, 6 unresolved discussions (waiting on @Alon-Ti and @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/components/ret_opcode/prover.rs` line 205 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/234#-ODapKCm4MrrtVjkkYRL:-ODbZ-pg4vpf9aewFok1:b2nign6) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e493cd153aa3770553201887ecde529c260f3ec7/stwo_cairo_prover/crates/prover/src/components/ret_opcode/prover.rs#L205)):*
<details><summary><i>Previously, Alon-Ti wrote…</i></summary><blockquote>

@shaharsamocha7 Do we want a `feature` on this so we can test single-threaded performance?
</blockquote></details>

yes
___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 56 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/234#-ODbYcoP7In0Utcjb_ww:-ODbYcoP7In0Utcjb_wx:bv43tod) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/14c230d4057b98ef6971fc80ba743414939b4c8f/stwo_cairo_prover/crates/prover/src/components/mod.rs#L56)):*
> ```XML
> }
> 
> struct ThreadSafeTrace<const N: usize> {
> ```

Add a TODO to move to another file



_Code quote:_
```XML
struct ThreadSafeTrace<const N: usize> {
```
___
*[`stwo_cairo_prover/crates/prover/Cargo.toml` line 21 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/234#-ODbY7nJAhr2-Iaqwb8N:-ODbY7nJAhr2-Iaqwb8O:b-9tpqlx) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/14c230d4057b98ef6971fc80ba743414939b4c8f/stwo_cairo_prover/crates/prover/Cargo.toml#L21)):*
> ```TOML
> prover_types = { path = "../prover_types" }
> rayon.workspace = true
> [dev-dependencies]
> ```

add empty line
___
*[`stwo_cairo_prover/crates/prover/src/components/ret_opcode/prover.rs` line 10 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/234#-ODbYLSVAlC3gH9Pl6Zx:-ODbYLSVAlC3gH9Pl6Zy:b-aq66t0) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/14c230d4057b98ef6971fc80ba743414939b4c8f/stwo_cairo_prover/crates/prover/src/components/ret_opcode/prover.rs#L10)):*
> ```XML
> use prover_types::cpu::*;
> use prover_types::simd::*;
> use rayon::prelude::*;
> ```

Do we want to put it under a flag? 
(or add a TODO?)



_Code quote:_
```XML
use rayon::prelude::*;
```
___
*[`stwo_cairo_prover/crates/prover/src/components/ret_opcode/prover.rs` line 146 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/234#-ODbZG4r9c9g2zCcbQXr:-ODbZG4sA_hbV3aAGdBH:b-7qjpeo) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/14c230d4057b98ef6971fc80ba743414939b4c8f/stwo_cairo_prover/crates/prover/src/components/ret_opcode/prover.rs#L146)):*
> ```XML
>     }
> 
>     unsafe fn set_len(&self, len: usize) {
> ```

Is this code autogen?



_Code quote:_
```XML
unsafe fn set_len(&self, len: usize) {
```
___
*[`stwo_cairo_prover/Cargo.toml` line 43 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/234#-ODbY3Zt4R5BgF7DZ8JH:-ODbY3ZuAisnf10huHkR:bh3o6fy) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/14c230d4057b98ef6971fc80ba743414939b4c8f/stwo_cairo_prover/Cargo.toml#L43)):*
> ```TOML
> rayon = "1.10.0"
> ruint = "1.12.3"
> ```

remove empty line

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/234)* status: 2 of 6 files reviewed, 5 unresolved discussions (waiting on @Alon-Ti and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/Cargo.toml` line 21 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/234#-ODbY7nJAhr2-Iaqwb8N:-ODepGVVCefAxRCW7suc:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/14c230d4057b98ef6971fc80ba743414939b4c8f/stwo_cairo_prover/crates/prover/Cargo.toml#L21)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

add empty line
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 56 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/234#-ODbYcoP7In0Utcjb_ww:-ODepOcI4-dHZhw29vsc:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/14c230d4057b98ef6971fc80ba743414939b4c8f/stwo_cairo_prover/crates/prover/src/components/mod.rs#L56)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Add a TODO to move to another file
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/components/ret_opcode/prover.rs` line 10 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/234#-ODbYLSVAlC3gH9Pl6Zx:-ODfePqc9oxJvu1Dmuez:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/14c230d4057b98ef6971fc80ba743414939b4c8f/stwo_cairo_prover/crates/prover/src/components/ret_opcode/prover.rs#L10)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Do we want to put it under a flag? 
(or add a TODO?)
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/components/ret_opcode/prover.rs` line 146 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/234#-ODbZG4r9c9g2zCcbQXr:-ODepPiA9iRmolJhKh1v:b-btirmq) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/14c230d4057b98ef6971fc80ba743414939b4c8f/stwo_cairo_prover/crates/prover/src/components/ret_opcode/prover.rs#L146)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Is this code autogen?
</blockquote></details>

it should be yes
I replace for uninitialized
___
*[`stwo_cairo_prover/Cargo.toml` line 43 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/234#-ODbY3Zt4R5BgF7DZ8JH:-ODepDRKE26SDJhvw6EH:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/14c230d4057b98ef6971fc80ba743414939b4c8f/stwo_cairo_prover/Cargo.toml#L43)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

remove empty line
</blockquote></details>

Done.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/234)* status: all files reviewed, 1 unresolved discussion (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/components/ret_opcode/prover.rs` line 131 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/234#-ODgA__p9t39cjSlz5dc:-ODgA__p9t39cjSlz5dd:b-c8fxbl) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/948ace84d88ab3a1e2b650f614a6901d5c02ed47/stwo_cairo_prover/crates/prover/src/components/ret_opcode/prover.rs#L131)):*
> ```XML
>     #[allow(unused_variables)]
>     unsafe fn uninitialized(len: usize) -> Self {
>         let s = Self {
> ```

can we not call it `s`?



_Code quote:_
```XML
let s = Self {
```

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/234)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/components/ret_opcode/prover.rs` line 131 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/234#-ODgA__p9t39cjSlz5dc:-ODjLS334iLyzAvRmuGX:bvyb82y) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/948ace84d88ab3a1e2b650f614a6901d5c02ed47/stwo_cairo_prover/crates/prover/src/components/ret_opcode/prover.rs#L131)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

can we not call it `s`?
</blockquote></details>

better?

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/234#-:-ODjOBbz4Vh-gK1ej1Of:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ohad-starkware)

**Pull request merged**
