### PR TITLE
fmt for cairo

### PR DESCRIPTION
**Pull request by ohad-starkware**
fmt for cairo

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/237)

### CODE REVIEW

**Comment by ohad-starkware** [comment]
* **#237** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/237?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/237?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/237)* status: 1 of 5 files reviewed, 3 unresolved discussions (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/237#-ODjsD5-4frc7RI0yV-C:-ODjsD5-4frc7RI0yV-D:b-gpzpkd) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/775f81c5ae7ea09a742c92262deb8b939207b7a7/stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs#L30)):*
> ```XML
>     input: CairoInput,
>     track_relations: bool,
>     display_components: bool,
> ```

Do we want this with 2 different bools?
Why not create a log_level param or something?



_Code quote:_
```XML
    track_relations: bool,
    display_components: bool,
```
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/debug.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/237#-ODjs1NE8jcYQTKvy3W7:-ODjs1NFEEhcgrjrK72l:bhcje8j) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/775f81c5ae7ea09a742c92262deb8b939207b7a7/stwo_cairo_prover/crates/prover/src/cairo_air/debug.rs#L1)):*
> ```XML
> use itertools::Itertools;
> ```

Is this file only compiles in debug mode?



_Code quote:_
```XML
use itertools::Itertools;
```
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/debug.rs` line 589 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/237#-ODjsUhs1_ZDecD2eR_j:-ODjsUhs1_ZDecD2eR_k:b-qpqpay) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/775f81c5ae7ea09a742c92262deb8b939207b7a7/stwo_cairo_prover/crates/prover/src/cairo_air/debug.rs#L589)):*
> ```XML
> }
> 
> pub(super) fn indent_component_display<E: FrameworkEval>(
> ```

Rename, and also:
why do you need the indented format only here?
For the Opcode components you just printed them regularly.

Do we really need those two functions?



_Suggestion:_
```XML
pub(super) fn indented_component_display<E: FrameworkEval>(
```

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/237)* status: 1 of 5 files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/debug.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/237#-ODjs1NE8jcYQTKvy3W7:-ODjtSrC-uHwwOZJz17s:b32wsm) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/775f81c5ae7ea09a742c92262deb8b939207b7a7/stwo_cairo_prover/crates/prover/src/cairo_air/debug.rs#L1)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Is this file only compiles in debug mode?
</blockquote></details>

no
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/237#-ODjsD5-4frc7RI0yV-C:-ODjtUr2ByvQ-u_5v_3K:bii3yj3) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/775f81c5ae7ea09a742c92262deb8b939207b7a7/stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs#L30)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Do we want this with 2 different bools?
Why not create a log_level param or something?
</blockquote></details>

with track relations it needs to be a bool because the operation is very slow
wdym by log_level_param? can give an example?
I do think that these two and some other stuff needs to sit in a Cfg struct of sorts, which the CLI will construct.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/237)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/debug.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/237#-ODjs1NE8jcYQTKvy3W7:-ODkLbrT1hqww5kI51Wb:b604o7j) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/775f81c5ae7ea09a742c92262deb8b939207b7a7/stwo_cairo_prover/crates/prover/src/cairo_air/debug.rs#L1)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

no
</blockquote></details>

but should it?
If so, we should probably need to consider if we want to add dependencies to this file
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/237#-ODjsD5-4frc7RI0yV-C:-ODkLzB7-gwV0BLQcNEG:b9pv778) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/775f81c5ae7ea09a742c92262deb8b939207b7a7/stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs#L30)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

with track relations it needs to be a bool because the operation is very slow
wdym by log_level_param? can give an example?
I do think that these two and some other stuff needs to sit in a Cfg struct of sorts, which the CLI will construct.
</blockquote></details>

I see, but maybe we want a DebugParams?
Good First Issue?

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/237)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @ohad-starkware and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/debug.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/237#-ODjs1NE8jcYQTKvy3W7:-ODkheM7A_yoVWH59TzV:b-13btsa) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/775f81c5ae7ea09a742c92262deb8b939207b7a7/stwo_cairo_prover/crates/prover/src/cairo_air/debug.rs#L1)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

but should it?
If so, we should probably need to consider if we want to add dependencies to this file
</blockquote></details>

it's used in real runs to expose debug prints for the CLI, maybe rename the file?
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/debug.rs` line 589 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/237#-ODjsUhs1_ZDecD2eR_j:-ODkhre23JsHH0kDm5Uq:b-o0rakj) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/775f81c5ae7ea09a742c92262deb8b939207b7a7/stwo_cairo_prover/crates/prover/src/cairo_air/debug.rs#L589)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Rename, and also:
why do you need the indented format only here?
For the Opcode components you just printed them regularly.

Do we really need those two functions?
</blockquote></details>

I did indent them
yes, it's unreadable without indents
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/237#-ODjsD5-4frc7RI0yV-C:-ODkhueACFSnl8cAEYXJ:b-361pvq) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/775f81c5ae7ea09a742c92262deb8b939207b7a7/stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs#L30)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I see, but maybe we want a DebugParams?
Good First Issue?
</blockquote></details>

we need to expose some API for the CLI to use,  the needs are/will dictated by Maya I hope?
from our end, yes good first issue

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/237)* status: all files reviewed, 3 unresolved discussions (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/debug.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/237#-ODjs1NE8jcYQTKvy3W7:-ODlO28x0wzkd0OeAWAD:buq2eea) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/775f81c5ae7ea09a742c92262deb8b939207b7a7/stwo_cairo_prover/crates/prover/src/cairo_air/debug.rs#L1)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

it's used in real runs to expose debug prints for the CLI, maybe rename the file?
</blockquote></details>

debugging_tools.rs
not sure
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/237#-ODjsD5-4frc7RI0yV-C:-ODlOpj57dAkpXL-1C1K:bvvh7cq) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/775f81c5ae7ea09a742c92262deb8b939207b7a7/stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs#L30)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

we need to expose some API for the CLI to use,  the needs are/will dictated by Maya I hope?
from our end, yes good first issue
</blockquote></details>

Can you add a TODO here to wrap them with a struct?
___
*[`stwo_cairo_prover/crates/adapted_prover/src/main.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/237#-ODlPEGg5NKXQzYFhtNb:-ODlPEGg5NKXQzYFhtNc:b-3h0zqh) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/775f81c5ae7ea09a742c92262deb8b939207b7a7/stwo_cairo_prover/crates/adapted_prover/src/main.rs#L32)):*
> ```XML
>     debug_lookup: bool,
>     #[structopt(long = "display_components")]
>     display_components: bool,
> ```

We should consult with maya what should be the params in the CLI



_Code quote:_
```XML
    #[structopt(long = "debug_lookup")]
    debug_lookup: bool,
    #[structopt(long = "display_components")]
    display_components: bool,
```

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/237)* status: all files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/debug.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/237#-ODjs1NE8jcYQTKvy3W7:-OE8gfi9A5iiDzBJc0ZY:b8t41e5) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/775f81c5ae7ea09a742c92262deb8b939207b7a7/stwo_cairo_prover/crates/prover/src/cairo_air/debug.rs#L1)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

debugging_tools.rs
not sure
</blockquote></details>

better than debug
done
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/237#-ODjsD5-4frc7RI0yV-C:-OE8h2ryBGlG387BONSR:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/775f81c5ae7ea09a742c92262deb8b939207b7a7/stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs#L30)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can you add a TODO here to wrap them with a struct?
</blockquote></details>

Done.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/237#-:-OE9-xRR8xlo8plfMSFw:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ohad-starkware)

**Pull request merged**
