### PR TITLE
updated toolchain

### PR DESCRIPTION
**Pull request by ohad-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/264)

### CODE REVIEW

**Comment by ohad-starkware** [comment]
* **#264** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/264?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/264?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by shaharsamocha7 — APPROVED** [review]
> Reviewed 10 of 12 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/264)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @ohad-starkware)

___
*[`stwo_cairo_prover/scripts/rust_fmt.sh` line 3 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/264#-OESr2KhDGJv7ra1FOlE:-OESr2KhDGJv7ra1FOlF:bb7od0r) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/163adab88e5de942af15bb8256b3034df1b30035/stwo_cairo_prover/scripts/rust_fmt.sh#L3)):*
> ```Shell
> #!/bin/bash
> 
> cargo fmt --all -- "$@"
> ```

same



_Code quote:_
```Shell
cargo fmt --all -- "$@"
```
___
*[`stwo_cairo_prover/scripts/clippy.sh` line 4 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/264#-OESqwSX-YeoDru7ADJ-:-OESqwSX-YeoDru7ADJ0:b-bvxioy) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/163adab88e5de942af15bb8256b3034df1b30035/stwo_cairo_prover/scripts/clippy.sh#L4)):*
> ```Shell
> 
> cargo clippy "$@" --all-targets --all-features -- -D warnings \
>     -D future-incompatible -D nonstandard-style -D rust-2018-idioms -D unused
> ```

Write the version explicitly



_Suggestion:_
```Shell
cargo +nightly-2024-12-16 clippy "$@" --all-targets --all-features -- -D warnings \
    -D future-incompatible -D nonstandard-style -D rust-2018-idioms -D unused
```

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/264)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @shaharsamocha7)

___
*[`stwo_cairo_prover/scripts/clippy.sh` line 4 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/264#-OESqwSX-YeoDru7ADJ-:-OESvUeR6v4etFpcXHgA:b-3mfcrm) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/163adab88e5de942af15bb8256b3034df1b30035/stwo_cairo_prover/scripts/clippy.sh#L4)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Write the version explicitly
</blockquote></details>

it's derived from the version stated in rust-toolchain
I think it is more stable to not re mention it here again

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/264#-:-OET567j3TohhyTPZVwZ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
